/* ===== HARD MATHS BANK — tough JEE Main level MCQs (chapters 8-14), merged by chapter name in app.js ===== */
/* Schema matches app.js: {type:"hard", q, options[4], answer(index 0-3), steps[], ans, tip} */
const HARD_MATHS = {
"8. Integral Calculus": [
{type:"hard",q:"The value of ∫₀^π dx/(1 + 3^cos x) is:",options:["π/2","π","π/4","2π"],answer:0,steps:["Using the king property, replace x by π − x: cos(π − x) = −cos x, so I = ∫₀^π 3^cos x/(1 + 3^cos x) dx.","Add the two forms: 2I = ∫₀^π (1 + 3^cos x)/(1 + 3^cos x) dx = ∫₀^π dx = π.","Therefore I = π/2."],ans:"π/2 (option A)",tip:"If the integrand has the shape g(x)/(g(x) + g(a − x)) over 0 to a, the answer is always a/2. Spot the pattern and skip all working."},
{type:"hard",q:"The value of ∫₀^(π/2) sin²x cos²x dx is:",options:["π/16","π/8","π/4","π/32"],answer:0,steps:["sin²x cos²x = (1/4)(2 sin x cos x)² = (1/4) sin²(2x).","∫₀^(π/2) sin²(2x) dx = (1/2)∫₀^π sin²t dt = (1/2)(π/2) = π/4.","So I = (1/4)(π/4) = π/16."],ans:"π/16 (option A)",tip:"Every symmetric power integral reduces to sin²2x form plus the standard ∫₀^(π/2) sin²(2x)dx = π/4. Do NOT expand into multiple angles term by term."},
{type:"hard",q:"∫₀¹ x eˣ dx equals:",options:["1","e","e − 1","e − 2"],answer:0,steps:["By parts (LIATE, take x as the first function): ∫x eˣ dx = x eˣ − eˣ.","At x = 1: e − e = 0. At x = 0: 0 − 1 = −1.","I = 0 − (−1) = 1."],ans:"1 (option A)",tip:"The antiderivative of x eˣ is always eˣ(x − 1). Memorise it and the definite integral takes one substitution line."},
{type:"hard",q:"The value of ∫₁^e (ln x)/x² dx is:",options:["1 − 2/e","2/e − 1","1 + 2/e","1/e"],answer:0,steps:["By parts with u = ln x and dv = x⁻²dx → v = −1/x.","I = [−ln x/x]₁^e + ∫₁^e (1/x)(1/x) dx = [−ln x/x − 1/x]₁^e.","At e: −1/e − 1/e = −2/e; at 1: 0 − 1 = −1. So I = −2/e + 1 = 1 − 2/e."],ans:"1 − 2/e (option A)",tip:"For (ln x)/xⁿ always differentiate ln x and integrate x⁻ⁿ; the lower limit 1 contributes the clean term 1/(n−1)."},
{type:"hard",q:"∫₀^(π/2) ln(sin x) dx equals:",options:["−(π/2)ln 2","(π/2)ln 2","−π ln 2","0"],answer:0,steps:["Let I = ∫₀^(π/2) ln(sin x)dx. Substituting x → π/2 − x gives I = ∫₀^(π/2) ln(cos x)dx.","Adding: 2I = ∫₀^(π/2) ln(sin x cos x)dx = ∫₀^(π/2) ln(sin 2x)dx − (π/2)ln 2.","With t = 2x and the symmetry of ln(sin t) on (0, π), ∫₀^(π/2) ln(sin 2x)dx = I, so 2I = I − (π/2)ln 2 → I = −(π/2)ln 2."],ans:"−(π/2)ln 2 (option A)",tip:"Known pair to memorise: ∫₀^(π/2) ln(sin x)dx = ∫₀^(π/2) ln(cos x)dx = −(π/2)ln 2 and ∫₀^(π/2) ln(tan x)dx = 0."},
{type:"hard",q:"The area (in sq units) of the region enclosed between the parabola y² = 4x and the line x = 1 is:",options:["8/3","4/3","16/3","2"],answer:0,steps:["y = ±2√x, so the region is symmetric about the x-axis: total area = 2∫₀¹ 2√x dx.","= 4 ∫₀¹ x^(1/2) dx = 4 × (2/3).","= 8/3 sq units."],ans:"8/3 (option A)",tip:"For y² = 4ax cut by x = k the area is (8/3)√a · k^(3/2) = 8/3 here — use symmetry so you integrate only the upper branch and double it."},
{type:"hard",q:"∫₋₁¹ (x³ + |x|) dx equals:",options:["1","0","2","1/2"],answer:0,steps:["x³ is odd and the limits are symmetric → its integral is 0.","|x| is even → ∫₋₁¹|x|dx = 2∫₀¹ x dx = 1.","Total = 0 + 1 = 1."],ans:"1 (option A)",tip:"Split into even and odd parts first: odd dies on symmetric limits, even doubles. This turns a two-term integral into one line."},
{type:"hard",q:"The value of ∫₀^∞ (x² + 1)/(x⁴ + 1) dx is:",options:["π/√2","π/2","π/(2√2)","π"],answer:0,steps:["Divide numerator and denominator by x²: integrand = (1 + 1/x²)/(x² + 1/x²).","Put t = x − 1/x → dt = (1 + 1/x²)dx and x² + 1/x² = t² + 2.","Limits: x → 0⁺ gives t → −∞, x → ∞ gives t → ∞, so I = ∫₋∞^∞ dt/(t² + 2) = π/√2."],ans:"π/√2 (option A)",tip:"The classic 1/x²-division trick: any integral of (x² ± 1)/(x⁴ + kx² + 1) collapses to ∫dt/(t² + c) with t = x ± 1/x."},
{type:"hard",q:"∫₀¹ tan⁻¹x dx equals:",options:["π/4 − (1/2)ln 2","π/4 + (1/2)ln 2","π/4","(1/2)ln 2"],answer:0,steps:["By parts with u = tan⁻¹x, dv = dx: I = [x tan⁻¹x]₀¹ − ∫₀¹ x/(1 + x²) dx.","[x tan⁻¹x]₀¹ = π/4.","∫₀¹ x/(1 + x²)dx = (1/2)ln(1 + x²)|₀¹ = (1/2)ln 2.","I = π/4 − (1/2)ln 2."],ans:"π/4 − (1/2)ln 2 (option A)",tip:"For inverse-trig integrands integrate by parts with the inverse function as u; the leftover is a log derivative ln(1 + x²)/2."}
],
"9. Differential Equations": [
{type:"hard",q:"The order and degree of d²y/dx² + (dy/dx)³ + y = 0 are respectively:",options:["2 and 1","2 and 3","1 and 3","3 and 2"],answer:0,steps:["Order = order of the highest derivative present = 2.","Degree = the power of that highest-order derivative in the polynomial form = 1 (the cube sits on dy/dx, a lower derivative).","So order 2, degree 1."],ans:"2 and 1 (option A)",tip:"The degree looks ONLY at the highest-order derivative. Here d²y/dx² has power 1, so the (dy/dx)³ is a decoy."},
{type:"hard",q:"The general solution of dy/dx = e^(x + y) is:",options:["eˣ + e^(−y) = c","eˣ − e^y = c","e^(x+y) = c","e^(−x) + e^y = c"],answer:0,steps:["e^(x+y) = eˣ · e^y, so the equation is separable: e^(−y) dy = eˣ dx.","Integrating: −e^(−y) = eˣ + C.","Rearranged: eˣ + e^(−y) = c."],ans:"eˣ + e^(−y) = c (option A)",tip:"Split the exponential into a product FIRST — e^(x+y) is not directly integrable, but eˣ·e^y is separable. Check the sign of e^(−y) when rearranging."},
{type:"hard",q:"The integrating factor of dy/dx + y/x = x² is:",options:["x","1/x","x²","eˣ"],answer:0,steps:["The equation is linear with P = 1/x, Q = x².","IF = e^(∫P dx) = e^(∫(1/x)dx) = e^(ln x) = x.","Multiplying by x gives d(yx)/dx = x³ → yx = x⁴/4 + c."],ans:"x (option A)",tip:"IF = e^(∫P dx) where P is the coefficient of y after writing dy/dx + Py = Q. If P = 1/x, the IF is always x, never 1/x."},
{type:"hard",q:"The solution of dy/dx = (x + y)/x is:",options:["y = x ln|x| + cx","y = ln|x| + cx","y = x ln|x| + c","y = x²/2 + cx"],answer:0,steps:["(x + y)/x = 1 + y/x, a homogeneous equation → put y = vx.","v + x(dv/dx) = 1 + v → x(dv/dx) = 1 → dv = dx/x.","v = ln|x| + c → y = x(ln|x| + c) = x ln|x| + cx."],ans:"y = x ln|x| + cx (option A)",tip:"Whenever the right side is a function of y/x, substitute y = vx. Remember to convert BACK (y = vx), and keep the constant multiplied by x — option C drops it."},
{type:"hard",q:"The differential equation of the family of circles x² + (y − k)² = 9 (k arbitrary) is:",options:["(x² − 9)y'² + x² = 0","(x² + 9)y'² + x² = 0","x²y'² + x² = 9","x² + y² = 9"],answer:0,steps:["One arbitrary constant ⇒ first-order equation. Differentiate: 2x + 2(y − k)y' = 0 → (y − k) = −x/y'.","Substitute back into the original: x² + (−x/y')² = 9.","Multiply by y'²: x²y'² + x² = 9y'² → (x² − 9)y'² + x² = 0."],ans:"(x² − 9)y'² + x² = 0 (option A)",tip:"Number of arbitrary constants = order of the equation. Differentiate ONCE, then eliminate the constant instead of differentiating again (option D is the original family, not its ODE)."},
{type:"hard",q:"The general solution of y = x(dy/dx) + (dy/dx)² is:",options:["y = cx + c²","y = cx − c²","y = cx² + c","xy = c"],answer:0,steps:["This is Clairaut form y = px + f(p) with p = dy/dx and f(p) = p².","Its general solution is y = cx + f(c).","So y = cx + c² (the singular solution is y = −x²/4)."],ans:"y = cx + c² (option A)",tip:"In Clairaut form, replace p by the arbitrary constant c: y = cx + f(c). Never integrate it by parts or try separation of variables."},
{type:"hard",q:"The solution of dy/dx = (x² + y²)/(2xy) is:",options:["x² − y² = cx","x² + y² = cx","y² − x² = cx","x²y = c"],answer:0,steps:["Homogeneous equation: put y = vx, then dy/dx = v + x(dv/dx).","v + x(dv/dx) = (1 + v²)/(2v) → x(dv/dx) = (1 − v²)/(2v) → 2v dv/(1 − v²) = dx/x.","Integrating: −ln|1 − v²| = ln|x| + const → x(1 − v²) = c → x² − y² = cx."],ans:"x² − y² = cx (option A)",tip:"The substitution y = vx converts it to a separable equation whose integral is a logarithm; note the minus sign that produces 1 − v² in the bracket."},
{type:"hard",q:"The orthogonal trajectories of the family of hyperbolas xy = c are:",options:["x² − y² = k","x² + y² = k","y = kx","xy = k"],answer:0,steps:["Differentiate xy = c: y + x(dy/dx) = 0 → dy/dx = −y/x.","For orthogonal trajectories replace dy/dx by −dx/dy: −dx/dy = −y/x, which gives x dx = y dy (i.e. dy/dx = x/y).","Integrating: y²/2 = x²/2 + c → x² − y² = k."],ans:"x² − y² = k (option A)",tip:"Orthogonal ⇒ replace dy/dx with −dx/dy. The rectangular hyperbola xy = c and x² − y² = k are the standard orthogonal pair to memorise."},
{type:"hard",q:"The order and degree of the differential equation dy/dx + sin(dy/dx) = 0 are:",options:["1 and 1","1 and not defined","0 and 1","2 and 1"],answer:1,steps:["The highest (in fact the only) derivative is dy/dx, so the order is 1.","The equation is NOT a polynomial in dy/dx because sin(dy/dx) is transcendental in that derivative.","Hence the degree is not defined."],ans:"Order 1, degree not defined (option B)",tip:"Degree exists only for equations polynomial in the derivatives. Any sin, cos, log, e^(dy/dx) or fractional power of a derivative ⇒ degree undefined."},
{type:"hard",q:"The differential equation representing the family of parabolas y² = 4ax (a arbitrary) is:",options:["2xy' − y = 0","xy' − 2y = 0","yy' = 2x","2xy' + y = 0"],answer:0,steps:["y² = 4ax → differentiate: 2y y' = 4a → a = y y'/2.","Substitute the value of a back: y² = 4x(y y'/2) = 2xy y'.","Cancel y (y ≠ 0): y = 2xy' → 2xy' − y = 0."],ans:"2xy' − y = 0 (option A)",tip:"One arbitrary constant ⇒ first-order ODE. Differentiate once, solve for the constant, then substitute it back — do not differentiate twice."}
],
"10. Coordinate Geometry": [
{type:"hard",q:"The distance between the parallel lines 3x + 4y = 9 and 6x + 8y = 15 is:",options:["0.3","0.6","3","1.5"],answer:0,steps:["Make the coefficients identical: 3x + 4y = 9 → 6x + 8y = 18.","For parallel lines ax + by = c₁ and ax + by = c₂, d = |c₁ − c₂|/√(a² + b²).","d = |18 − 15|/√(36 + 64) = 3/10 = 0.3."],ans:"0.3 (option A)",tip:"Equalise the coefficients FIRST, then divide by √(a²+b²). Skipping that step gives 0.6 — exactly the trap option."},
{type:"hard",q:"The image of the point (1, 2) in the line x + y = 0 is:",options:["(−2, −1)","(−1, −2)","(2, 1)","(−2, 1)"],answer:0,steps:["The reflection of (x, y) in the line x + y = 0 is (−y, −x).","Applying to (1, 2): (−2, −1).","Check: the midpoint (−1/2, 1/2) lies on x + y = 0, and the segment joining the two points is perpendicular to the line (slope 1 × −1 = −1)."],ans:"(−2, −1) (option A)",tip:"Standard reflections: in x + y = 0 → (−y, −x); in x = y → (y, x); in y = 0 → (x, −y); in x = 0 → (−x, y). Learn the four."},
{type:"hard",q:"The length of the tangent drawn from the point (5, 4) to the circle x² + y² − 2x − 4y − 4 = 0 is:",options:["√11","11","√5","5"],answer:0,steps:["Tangent length from an external point = √(S₁), where S₁ is the circle expression evaluated at the point.","S₁ = 25 + 16 − 10 − 16 − 4 = 11.","Length = √11."],ans:"√11 (option A)",tip:"Tangent length = √(power of the point). Do not solve for the point of contact — one substitution gives the answer."},
{type:"hard",q:"The two circles x² + y² + 2gx + 2fy + c = 0 and x² + y² + 2g'x + 2f'y + c' = 0 cut each other orthogonally if:",options:["2gg' + 2ff' = c + c'","2gg' + 2ff' = c − c'","gg' + ff' = c + c'","g + g' = c + c'"],answer:0,steps:["Orthogonality of two circles in general form requires 2g₁g₂ + 2f₁f₂ = c₁ + c₂.","Substituting the coefficients: 2gg' + 2ff' = c + c'.","(Equivalently, the distance between centres satisfies d² = r₁² + r₂².)"],ans:"2gg' + 2ff' = c + c' (option A)",tip:"Memorise the exact pattern 2gg' + 2ff' = c + c' (equivalent to d² = r₁² + r₂², where d is the distance between centres). The minus variant is only a distractor."},
{type:"hard",q:"The length of the latus rectum of the parabola y² = 4ax whose focus is (3, 0) is:",options:["12","3","6","24"],answer:0,steps:["For y² = 4ax the focus is (a, 0), so a = 3.","Latus rectum = 4a.","= 12."],ans:"12 (option A)",tip:"Parabola latus rectum = 4a; ellipse = 2b²/a; hyperbola = 2b²/a. Only the parabola's is independent of b, so read the focus/directrix to get a instantly."},
{type:"hard",q:"The eccentricity of the ellipse 9x² + 25y² = 225 is:",options:["4/5","3/5","5/4","16/25"],answer:0,steps:["Divide by 225: x²/25 + y²/9 = 1 → a² = 25, b² = 9.","c = √(a² − b²) = √16 = 4.","e = c/a = 4/5."],ans:"4/5 (option A)",tip:"Always normalise to x²/a² + y²/b² = 1 with a² > b² first. Here 9x² + 25y² = 225 gives a² = 25 under the x-term — picking a² = 9 is the trap (and e must always be < 1 for an ellipse)."},
{type:"hard",q:"The equation of the circle passing through the points (0, 0), (a, 0) and (0, b) is:",options:["x² + y² − ax − by = 0","x² + y² + ax + by = 0","x² + y² = a² + b²","x² + y² − ax − by + ab = 0"],answer:0,steps:["Take x² + y² + 2gx + 2fy + c = 0.","Through (0,0): c = 0. Through (a,0): a² + 2ga = 0 → g = −a/2. Through (0,b): b² + 2fb = 0 → f = −b/2.","The circle is x² + y² − ax − by = 0."],ans:"x² + y² − ax − by = 0 (option A)",tip:"The origin always kills c (c = 0) for a circle through it, and each axis-intercept pins one coefficient. This circle has AB as diameter when a, b > 0."},
{type:"hard",q:"The line y = mx + c is a tangent to the circle x² + y² = a² if:",options:["c² = a²(1 + m²)","c² = a²m²","c = am","c² = a²(1 − m²)"],answer:0,steps:["Tangency means the perpendicular distance from the centre (0, 0) to the line equals the radius a.","|c|/√(1 + m²) = a.","Squaring: c² = a²(1 + m²)."],ans:"c² = a²(1 + m²) (option A)",tip:"Distance-from-centre is the master method. The four standard tangency conditions: circle c² = a²(1+m²), parabola c = a/m, ellipse c² = a²m² + b², hyperbola c² = a²m² − b²."},
{type:"hard",q:"The eccentricity of the hyperbola 16x² − 9y² = 144 is:",options:["5/3","4/3","5/4","3/5"],answer:0,steps:["Divide by 144: x²/9 − y²/16 = 1 → a² = 9, b² = 16.","e = √(1 + b²/a²) = √(1 + 16/9).","= √(25/9) = 5/3."],ans:"5/3 (option A)",tip:"Hyperbola: e = √(1 + b²/a²) > 1 (PLUS). Ellipse: e = √(1 − b²/a²) < 1 (MINUS). Any option below 1 for a hyperbola is instantly wrong."}
],
"11. 3D Geometry": [
{type:"hard",q:"The direction cosines of the line joining the points (2, −1, 3) and (4, 3, 1) are:",options:["1/√6, 2/√6, −1/√6","1/√24, 2/√24, 1/√24","2, 4, −2","1/3, 2/3, −1/3"],answer:0,steps:["Direction ratios = (4 − 2, 3 + 1, 1 − 3) = (2, 4, −2).","|r| = √(4 + 16 + 4) = √24 = 2√6.","Direction cosines = (2, 4, −2)/(2√6) = (1/√6, 2/√6, −1/√6)."],ans:"1/√6, 2/√6, −1/√6 (option A)",tip:"Simplify the ratios by their common factor BEFORE normalising — here divide (2, 4, −2) by 2 to get (1, 2, −1), whose magnitude is √6, not √24. Option B is that un-simplified trap."},
{type:"hard",q:"The angle between the lines whose direction ratios are (1, 2, 2) and (2, −2, 1) is:",options:["90°","45°","60°","0°"],answer:0,steps:["cos θ = (a₁a₂ + b₁b₂ + c₁c₂)/(√(Σa₁²)·√(Σa₂²)).","Dot product = 1(2) + 2(−2) + 2(1) = 2 − 4 + 2 = 0.","Dot = 0 ⇒ cos θ = 0 ⇒ θ = 90°; the lines are perpendicular."],ans:"90° (option A)",tip:"Check the dot product FIRST: if it vanishes, the answer is 90° and you never need the magnitudes. Both magnitudes happen to be 3 here (a deliberately symmetric trap)."},
{type:"hard",q:"The shortest distance between the lines r = (i + j) + λ(2i − j + k) and r = (2i + j − k) + μ(3i − 5j + 2k) is:",options:["10/√59","10/59","√59/10","5/√59"],answer:0,steps:["a₂ − a₁ = (2 − 1, 1 − 1, −1 − 0) = (1, 0, −1); b₁ = (2, −1, 1), b₂ = (3, −5, 2).","b₁ × b₂ = (3, −1, −7), so |b₁ × b₂| = √(9 + 1 + 49) = √59.","SD = |(a₂ − a₁)·(b₁ × b₂)|/|b₁ × b₂| = |3 + 0 + 7|/√59 = 10/√59."],ans:"10/√59 (option A)",tip:"SD formula: |(a₂ − a₁)·(b₁ × b₂)|/|b₁ × b₂|. Compute the cross product first, then the dot — and note the dot here is 3 + 7, both terms positive."},
{type:"hard",q:"The image of the point (1, 2, 3) in the plane x + y + z = 1 is:",options:["(−7/3, −4/3, −1/3)","(7/3, 4/3, 1/3)","(−1, −2, −3)","(1/3, 2/3, 1/3)"],answer:0,steps:["Plane: x + y + z − 1 = 0 → n = (1, 1, 1), |n|² = 3 and S₁ = 1 + 2 + 3 − 1 = 5.","Image = P − 2(S₁/|n|²)·n = (1, 2, 3) − (10/3)(1, 1, 1).","= (1 − 10/3, 2 − 10/3, 3 − 10/3) = (−7/3, −4/3, −1/3)."],ans:"(−7/3, −4/3, −1/3) (option A)",tip:"Foot of perpendicular = P − (S₁/Σn²)n, IMAGE = P − 2(S₁/Σn²)n. The factor 2 is the only difference between the two formulas — mixing them up is the standard error."},
{type:"hard",q:"The distance of the point (1, −2, 3) from the plane x − 2y + 2z + 7 = 0 is:",options:["6","18","2","3"],answer:0,steps:["d = |ax₁ + by₁ + cz₁ + k|/√(a² + b² + c²).","Numerator = |1 − 2(−2) + 2(3) + 7| = |1 + 4 + 6 + 7| = 18.","Denominator = √(1 + 4 + 4) = 3 → d = 18/3 = 6."],ans:"6 (option A)",tip:"Watch the sign: −2y with y = −2 contributes +4. Take the modulus at the end and remember the denominator is the magnitude of the normal (1, −2, 2)."},
{type:"hard",q:"The angle between the planes 2x − y + z = 6 and x + y + 2z = 7 is:",options:["60°","30°","90°","45°"],answer:0,steps:["Normals: n₁ = (2, −1, 1), n₂ = (1, 1, 2).","cos θ = |n₁·n₂|/(|n₁||n₂|) = |2 − 1 + 2|/(√6 × √6) = 3/6 = 1/2.","θ = 60°."],ans:"60° (option A)",tip:"Angle between planes = angle between their normals, and the dot product must be taken with a modulus (an obtuse answer would be wrong). 3/6 = 0.5 flags 60° immediately."},
{type:"hard",q:"The lines r = a₁ + λb₁ and r = a₂ + μb₂ are coplanar if and only if:",options:["(a₂ − a₁)·(b₁ × b₂) = 0","(a₂ − a₁)·(b₁ + b₂) = 0","b₁ × b₂ = 0","(a₂ − a₁)·b₁ = 0"],answer:0,steps:["The vector joining the two points must lie in the plane spanned by b₁ and b₂.","That happens exactly when the three vectors a₂ − a₁, b₁ and b₂ are coplanar.","Coplanarity of three vectors ⇔ their scalar triple product is zero: (a₂ − a₁)·(b₁ × b₂) = 0."],ans:"(a₂ − a₁)·(b₁ × b₂) = 0 (option A)",tip:"Coplanar ⇔ STP = 0. Note b₁ × b₂ = 0 (parallel directions) also means coplanar, but that is a special case — the general condition is the triple product."},
{type:"hard",q:"The perpendicular distance from the origin to the plane 3x + 4y + 12z = 13 is:",options:["1","13","1/13","5"],answer:0,steps:["For ax + by + cz = d, the distance from the origin is |d|/√(a² + b² + c²).","= 13/√(9 + 16 + 144).","= 13/√169 = 13/13 = 1."],ans:"1 (option A)",tip:"3-4-12 forms a Pythagorean quadruple with 13, so the denominator collapses to 13 exactly. Recognising such triples saves the whole calculation."},
{type:"hard",q:"The equation of the plane through the point (1, 2, 3) and parallel to the plane 2x − y + 4z = 5 is:",options:["2x − y + 4z = 12","2x − y + 4z = 5","2x + y + 4z = 12","x − 2y + 4z = 3"],answer:0,steps:["Parallel planes share the same normal, so the plane is 2x − y + 4z = k.","Substitute the point (1, 2, 3): k = 2(1) − 2 + 4(3).","k = 2 − 2 + 12 = 12 → 2x − y + 4z = 12."],ans:"2x − y + 4z = 12 (option A)",tip:"Parallel ⇒ only the constant changes. Substitute the given point into the LEFT side without touching the coefficients — the fastest plane question in the syllabus."},
{type:"hard",q:"The volume of the tetrahedron with vertices (0, 0, 0), (1, 0, 0), (0, 2, 0) and (0, 0, 3) is:",options:["1","6","3","1/6"],answer:0,steps:["Volume = (1/6)|a·(b × c)| with a = (1, 0, 0), b = (0, 2, 0), c = (0, 0, 3).","The scalar triple product is the determinant of the diagonal matrix = 1 × 2 × 3 = 6.","V = (1/6)(6) = 1 cubic unit."],ans:"1 (option A)",tip:"For an axis-aligned tetrahedron with intercepts a, b, c the volume is abc/6. Option 6 is the parallelepiped (box) volume — forgetting the 1/6 is the classic error."}
],
/* @@END_HARD_MATHS@@ */
};
