/* ===== EXTRA MATHS BANK — tough JEE Main level MCQs (chapters 1-7), merged by chapter name in app.js ===== */
/* Schema matches app.js: {type:"hard", q, options[4], answer(index 0-3), steps[], ans, tip} */
const EXTRA_MATHS = {
"1. Sets, Relations & Functions": [
{type:"hard",q:"Let A = {1, 2, 3, 4}. The number of functions f: A → A that are one-one but NOT onto is:",options:["0","24","255","256"],answer:0,steps:["A one-one function from A to A is injective on a finite set of the same size.","Pigeonhole principle forces it to cover every element → it must be onto.","Hence one-one-and-not-onto functions do not exist: the count is 0."],ans:"0 (option A)",tip:"For finite sets of EQUAL size, injective ⇔ surjective (both equal n!). So any option other than 0 is a trap."},
{type:"hard",q:"If f(x) = (3x + 2)/(5x − 3), then f(f(x)) equals:",options:["x","(x + 1)/x","1/x","−x"],answer:0,steps:["Numerator of f(f(x)) = 3(3x+2)/(5x−3) + 2 = (9x + 6 + 10x − 6)/(5x−3) = 19x/(5x−3).","Denominator = 5(3x+2)/(5x−3) − 3 = (15x + 10 − 15x + 9)/(5x−3) = 19/(5x−3).","Ratio = 19x/19 = x."],ans:"x (option A)",tip:"Whenever a fractional-linear function returns x on composing with itself, f is its own inverse (f = f⁻¹) — a single substitution proves it."},
{type:"hard",q:"The range of the function f(x) = x/(1 + x²) for x ∈ R is:",options:["[−1/2, 1/2]","(−1, 1)","[−1, 1]","(0, 1/2]"],answer:0,steps:["Set y = x/(1 + x²) → yx² − x + y = 0.","x real ⇒ discriminant ≥ 0: 1 − 4y² ≥ 0 → y² ≤ 1/4.","So −1/2 ≤ y ≤ 1/2, and both ends are attained at x = 1 and x = −1."],ans:"[−1/2, 1/2] (option A)",tip:"Discriminant method for range: make the equation quadratic in x and demand D ≥ 0. AM-GM gives the same bound in one line: 1 + x² ≥ 2|x|."},
{type:"hard",q:"A has 3 elements and B has 4 elements. The number of NON-EMPTY relations from A to B is:",options:["4095","4096","64","12"],answer:0,steps:["A relation is any subset of A × B, and n(A × B) = 3 × 4 = 12.","Total subsets = 2¹² = 4096.","Exclude the empty relation: 4096 − 1 = 4095."],ans:"4095 (option A)",tip:"Relations = subsets of A × B = 2^(mn). For non-empty subtract 1; for reflexive/symmetric relations use fixed-diagonal counting instead."},
{type:"hard",q:"The domain of f(x) = 1/√(log₀.₅ x) is:",options:["(0, 1)","(1, ∞)","(0, ∞)","(1/2, 1)"],answer:0,steps:["Two conditions: x > 0 (log defined) and log₀.₅x > 0 (inside the square root, and not zero since it is in the denominator).","For base 0.5 (< 1) the logarithm is decreasing, so log₀.₅x > 0 requires x < 1.","Intersection: 0 < x < 1."],ans:"(0, 1) (option A)",tip:"Base < 1 flips the inequality: log₀.₅ x > 0 ⇒ x < 1. Also remember the strict inequality because √0 would make the denominator 0."},
{type:"hard",q:"The number of equivalence relations on the set {1, 2, 3} that CONTAIN the ordered pair (1, 2) is:",options:["2","3","4","5"],answer:0,steps:["Equivalence relations on a 3-element set correspond one-to-one with its partitions (5 partitions total).","List them: {123}, {12}{3}, {13}{2}, {1}{23}, {1}{2}{3}.","(1,2) belongs to a relation only if 1 and 2 lie in the same block: {123} and {12}{3} → 2 relations."],ans:"2 (option A)",tip:"Never count relations pair by pair — count the partitions (Bell number B₃ = 5) and then filter by the block condition."},
{type:"hard",q:"|A| = 4 and |B| = 3. The number of onto (surjective) functions from A to B is:",options:["36","24","81","45"],answer:0,steps:["By inclusion-exclusion: onto = 3⁴ − C(3,1)·2⁴ + C(3,2)·1⁴.","= 81 − 3(16) + 3(1).","= 81 − 48 + 3 = 36."],ans:"36 (option A)",tip:"Onto count = Σ(−1)^k C(n,k)(n−k)^m for m elements → n. Total functions 3⁴ = 81 over-counts the cases where some element is missed."},
{type:"hard",q:"f(x) = 2x + 1 and g(x) = x². If (g ∘ f)(a) = 25, then a equals:",options:["2 or −3","2 only","−3 only","3 or −2"],answer:0,steps:["(g ∘ f)(a) = g(f(a)) = (2a + 1)².","(2a + 1)² = 25 → 2a + 1 = ±5.","2a = 4 or 2a = −6 → a = 2 or a = −3."],ans:"a = 2 or a = −3 (option A)",tip:"Squaring always yields two branches — dropping the negative branch is the single most common error in composition questions."},
{type:"hard",q:"Number of relations on A = {1, 2} that are BOTH reflexive and symmetric:",options:["2","4","8","16"],answer:0,steps:["Reflexive forces (1,1) and (2,2) to be present — no freedom there.","Symmetric forces the pair (1,2), (2,1) either both present or both absent.","So only 2 choices remain: the relation {(1,1),(2,2)} or the universal relation A × A."],ans:"2 (option A)",tip:"Fix the forced pairs first, then count the free 2-element blocks; each off-diagonal symmetric pair behaves as a single coin toss."},
{type:"hard",q:"The number of one-one functions from a 3-element set to a 5-element set is:",options:["60","125","10","243"],answer:0,steps:["First element has 5 image choices, second has 4 left, third has 3 left (no repetition allowed).","Count = 5 × 4 × 3.","= 60 = ⁵P₃."],ans:"60 (option A)",tip:"One-one functions = permutations of the codomain taken |domain| at a time: n^P_m; if m > n the answer is 0."}
],
"2. Complex Numbers & Quadratic Equations": [
{type:"hard",q:"If z = (1 + i)/(1 − i), then z⁴ equals:",options:["−1","1","i","−i"],answer:1,steps:["Multiply numerator and denominator by the conjugate: z = (1 + i)²/((1)² + (1)²) = 2i/2.","So z = i.","z⁴ = i⁴ = 1."],ans:"1 (option B)",tip:"recognise the standard pair instantly: (1 + i)/(1 − i) = i and (1 − i)/(1 + i) = −i. Then powers cycle with period 4."},
{type:"hard",q:"The number of real roots of x² − 4|x| + 3 = 0 is:",options:["2","3","4","6"],answer:2,steps:["Put t = |x| ≥ 0 → t² − 4t + 3 = 0.","(t − 1)(t − 3) = 0 → t = 1 or t = 3 (both acceptable since t ≥ 0 is satisfied).","Each positive t gives two values of x: x = ±1 and x = ±3 → 4 real roots."],ans:"4 (option C)",tip:"Substitute t = |x|, solve for t, then double the count of the positive t values. Never reject t = 1 or t = 3 — only NEGATIVE t values are rejected."},
{type:"hard",q:"If α, β are the roots of x² − 2x + 4 = 0, then α² + β² equals:",options:["4","8","−4","−8"],answer:2,steps:["Sum S = α + β = 2 and product P = αβ = 4.","α² + β² = S² − 2P.","= 4 − 8 = −4 (the roots are complex, so a negative value is perfectly fine)."],ans:"−4 (option C)",tip:"Identities to keep ready: α² + β² = S² − 2P, α³ + β³ = S³ − 3PS, (α − β)² = S² − 4P. Never solve the quadratic itself."},
{type:"hard",q:"The least value of |z| for a complex number z satisfying |z − 3 − 4i| = 2 is:",options:["2","5","7","3"],answer:3,steps:["|z − (3 + 4i)| = 2 is a circle of centre (3, 4) and radius 2.","|z| is the distance of z from the origin, and |centre| = √(9 + 16) = 5.","Minimum |z| = 5 − 2 = 3 (maximum would be 5 + 2 = 7)."],ans:"3 (option D)",tip:"For a circle |z − c| = r: min |z| = |c| − r and max |z| = |c| + r. Also note the maximum is the value the minimum-question traps you into choosing."},
{type:"hard",q:"If z + 1/z = 2cos θ (z ≠ 0), then zⁿ + 1/zⁿ equals:",options:["cos nθ","2i sin nθ","2cos nθ","2ⁿ cos θ"],answer:2,steps:["Solving gives z = cos θ ± i sin θ (the two roots are reciprocal).","By De Moivre zⁿ = cos nθ ± i sin nθ, and 1/zⁿ = conjugate = cos nθ ∓ i sin nθ.","Adding the two conjugates: zⁿ + 1/zⁿ = 2cos nθ."],ans:"2cos nθ (option C)",tip:"The pair zⁿ − 1/zⁿ = 2i sin nθ is the companion result — every trigonometric-sum problem uses exactly these two."},
{type:"hard",q:"If α and β are the roots of x² + 2x + 3 = 0, the equation whose roots are 1/α and 1/β is:",options:["3x² − 2x + 1 = 0","3x² + 2x + 1 = 0","x² + 2x + 3 = 0","9x² + 6x + 1 = 0"],answer:1,steps:["S = α + β = −2 and P = αβ = 3.","New sum = 1/α + 1/β = S/P = −2/3; new product = 1/P = 1/3.","Equation: x² − (−2/3)x + 1/3 = 0 → 3x² + 2x + 1 = 0."],ans:"3x² + 2x + 1 = 0 (option B)",tip:"For reciprocal roots, reverse the coefficients (x² + 2x + 3 → 3x² + 2x + 1). It is a 5-second answer once you spot it."},
{type:"hard",q:"If ω is a non-real cube root of unity, then (1 + ω − ω²)³ equals:",options:["8","−8","0","−8ω"],answer:1,steps:["Use 1 + ω + ω² = 0 → ω² = −1 − ω.","1 + ω − ω² = 1 + ω − (−1 − ω) = 2 + 2ω = 2(1 + ω) = 2(−ω²) = −2ω².","Cube it: (−2ω²)³ = −8ω⁶ = −8(ω³)² = −8."],ans:"−8 (option B)",tip:"Always reduce ω-expressions with 1 + ω + ω² = 0 and ω³ = 1 BEFORE raising to a power. Here ω⁶ = (ω³)² = 1 kills the ω entirely."},
{type:"hard",q:"If both roots of x² − 2kx + (k² − 1) = 0 are positive, then:",options:["k > 1","k ≥ 1","0 < k < 1","k < −1"],answer:0,steps:["Discriminant = 4k² − 4(k² − 1) = 4 > 0, so the roots are real for every k; indeed they are k + 1 and k − 1.","For both roots positive we need sum > 0 and product > 0: sum = 2k > 0 → k > 0.","Product = k² − 1 > 0 → k > 1 or k < −1. Combining with k > 0 gives k > 1."],ans:"k > 1 (option A)",tip:"Both-roots-positive needs ALL THREE conditions: D ≥ 0, sum > 0, product > 0. Using the sum alone (k > 0) is the standard trap."},
{type:"hard",q:"If z is a complex number with |z| = 1 (z ≠ −1), then (z − 1)/(z + 1) is:",options:["Purely real","Unimodular","Purely imaginary","Equal to z"],answer:2,steps:["Write z = cos θ + i sin θ = e^(iθ).","(z − 1)/(z + 1) = (e^(iθ/2) − e^(−iθ/2))/(e^(iθ/2) + e^(−iθ/2)) after factoring e^(iθ/2).","= 2i sin(θ/2) / 2cos(θ/2) = i tan(θ/2), which is purely imaginary."],ans:"Purely imaginary (option C)",tip:"The half-angle factorisation is the fastest route. Equivalent check: for |z| = 1, (z − 1)/(z + 1) lies on the imaginary axis because the argument is (arg z)/2 shifted by 90°."}
],
"3. Matrices & Determinants": [
{type:"hard",q:"If A is a 3 × 3 matrix with |A| = 2, then |2A| equals:",options:["4","8","16","2"],answer:2,steps:["For an n × n matrix, det(kA) = kⁿ det(A).","Here n = 3 and k = 2: det(2A) = 2³ × 2.","= 8 × 2 = 16."],ans:"16 (option C)",tip:"det(kA) = kⁿ det A — the exponent is the ORDER of the matrix. Option A (multiplying by 2 only) is the standard error."},
{type:"hard",q:"If A is a skew-symmetric matrix of odd order, then |A| equals:",options:["0","1","−1","Cannot be determined from the data"],answer:0,steps:["Skew-symmetric means Aᵀ = −A.","Taking determinants: |Aᵀ| = |A| = |−A| = (−1)ⁿ|A| = −|A| (since n is odd).","So |A| = −|A| → 2|A| = 0 → |A| = 0."],ans:"0 (option A)",tip:"Odd-order skew-symmetric ⇒ det = 0, always. (For even order det need not vanish — the classic counterexample is the 2×2 rotation-like block.)"},
{type:"hard",q:"If A is a 3 × 3 matrix with |A| = 5, then |adj A| equals:",options:["5","25","125","1"],answer:1,steps:["For an n × n matrix, |adj A| = |A|^(n−1).","= 5^(3−1) = 5².","= 25."],ans:"25 (option B)",tip:"|adj A| = |A|^(n−1) and A·adj A = |A|I. Related favourites: |adj(adj A)| = |A|^((n−1)²) and adj(adj A) = |A|^(n−2)A."},
{type:"hard",q:"The system of homogeneous equations x + 2y + 3z = 0, 3x + 4y + 4z = 0, 7x + 10y + 12z = 0 has:",options:["Only the trivial solution x = y = z = 0","Infinitely many solutions","No solution","Exactly one non-trivial solution"],answer:0,steps:["Coefficient determinant = 1(48 − 40) − 2(36 − 28) + 3(30 − 28).","= 8 − 16 + 6 = −2 ≠ 0.","For a homogeneous system, det ≠ 0 forces the trivial solution only."],ans:"Only the trivial solution (option A)",tip:"Homogeneous systems are never inconsistent: det ≠ 0 ⇒ unique (trivial) solution; det = 0 ⇒ infinitely many non-trivial solutions. Here det = −2 decides it."},
{type:"hard",q:"If A = [[1, 1], [1, 1]], then A⁵ equals:",options:["[[32, 32], [32, 32]]","[[16, 16], [16, 16]]","[[1, 1], [1, 1]]","[[8, 8], [8, 8]]"],answer:1,steps:["A² = [[2, 2], [2, 2]] = 2A.","By induction Aⁿ = 2^(n−1)A (rank-1 matrices with trace 2 satisfy Aⁿ = 2^(n−1)A).","A⁵ = 2⁴A = 16A = [[16, 16], [16, 16]]."],ans:"[[16, 16], [16, 16]] (option B)",tip:"For a rank-1 matrix A = uvᵀ with trace t, Aⁿ = t^(n−1)A. Here trace = 2, so A⁵ = 2⁴A — no need to multiply matrices five times."},
{type:"hard",q:"If A = [[2, 3], [3, 5]], then A⁻¹ equals:",options:["[[5, 3], [3, 2]]","[[5, −3], [−3, 2]]","[[2, −3], [−3, 5]]","[[−5, 3], [3, −2]]"],answer:1,steps:["|A| = (2)(5) − (3)(3) = 10 − 9 = 1.","adj A = [[5, −3], [−3, 2]] (swap the diagonal, negate the off-diagonal).","A⁻¹ = adj A/|A| = [[5, −3], [−3, 2]]."],ans:"[[5, −3], [−3, 2]] (option B)",tip:"2×2 inverse recipe: swap a and d, change the signs of b and c, divide by (ad − bc). Since |A| = 1 here, the inverse IS the adjoint."},
{type:"hard",q:"If A and B are square matrices of the same order satisfying AB = A and BA = B, then which relation must hold?",options:["A² = A","A² = I","AB = BA = I","A = B⁻¹"],answer:0,steps:["Start from A² = A·A and use A = AB.","A² = A·A = (AB)A = A(BA) = A·B = AB.","Since AB = A, we get A² = A (similarly B² = B)."],ans:"A² = A (option A)",tip:"Chain the given identities: replace A by AB and regroup to expose BA. Both A and B turn out to be idempotent — a favourite JEE Main trap."},
{type:"hard",q:"If A is a 2 × 2 matrix with |A| = 3, then |3A⁻¹| equals:",options:["9","1/3","3","27"],answer:2,steps:["det(kA⁻¹) = kⁿ det(A⁻¹) for an n × n matrix, and det(A⁻¹) = 1/|A|.","= 3² × (1/3).","= 9/3 = 3."],ans:"3 (option C)",tip:"Combine the two rules: det(kA⁻¹) = kⁿ/|A|. Remember the power n applies to the scalar k, not to the inverse."},
{type:"hard",q:"If A is a 3 × 3 matrix such that A(adj A) = 5I, then |A| equals:",options:["125","25","5","15"],answer:2,steps:["Master identity: A(adj A) = (adj A)A = |A| I.","Comparing with the given 5I.","|A| = 5."],ans:"5 (option C)",tip:"A(adj A) = |A|I immediately reads off the determinant — the order of the matrix is irrelevant. Do not confuse this with |adj A| = |A|^(n−1) = 25."},
{type:"hard",q:"The number of symmetric matrices of order 3 × 3 with each entry equal to 0 or 1 is:",options:["512","64","36","32"],answer:1,steps:["A symmetric matrix is fixed by its 3 diagonal entries and its 3 entries above the diagonal.","Free entries = 3 + 3 = 6, and each can be 0 or 1 independently.","Count = 2⁶ = 64."],ans:"64 (option B)",tip:"Independent entries of a symmetric n × n matrix = n(n+1)/2 = 6 here, giving 2⁶. Options like 512 come from using all 9 entries (2⁹) — that counts all matrices, not symmetric ones."}
],
"4. Permutations & Combinations": [
{type:"hard",q:"The number of distinct arrangements of the letters of the word MISSISSIPPI is:",options:["11550","34650","69300","2520"],answer:1,steps:["11 letters with M×1, I×4, S×4, P×2.","Number of arrangements = 11!/(4!·4!·2!).","= 39916800/(24 × 24 × 2) = 39916800/1152 = 34650."],ans:"34650 (option B)",tip:"Divide the factorial of the length by the factorial of each repeated letter count. Forgetting the P (2) gives 69300 — exactly the trap option."},
{type:"hard",q:"In how many ways can 5 boys and 5 girls be seated in a row so that no two girls sit together?",options:["86400","14400","120","72200"],answer:0,steps:["Arrange the 5 boys first: 5! = 120 ways, creating 6 gaps (before, between, after).","Choose and arrange 5 of these 6 gaps for the girls: ⁶P₅ = 720 ways.","Total = 120 × 720 = 86400."],ans:"86400 (option A)",tip:"Missing-object method: arrange the majority group, then place the minority in the gaps (n + 1 of them). If the girls may also stand together, the answer is simply 10! — read the condition carefully."},
{type:"hard",q:"The number of ways in which 5 identical balls can be distributed among 3 children so that every child gets at least one ball is:",options:["6","10","15","21"],answer:0,steps:["Give 1 ball to each child first (forced), leaving 2 balls to distribute freely among 3 children.","Number of solutions of x₁ + x₂ + x₃ = 2 with xᵢ ≥ 0 is C(2 + 3 − 1, 3 − 1).","= C(4,2) = 6."],ans:"6 (option A)",tip:"Stars and bars: identical objects → C(n + r − 1, r − 1). For at-least-one conditions, hand out the minimum first and redistribute the rest."},
{type:"hard",q:"How many 4-digit numbers with distinct digits can be formed using the digits 0, 1, 2, 3, 4, 5?",options:["360","300","156","144"],answer:1,steps:["Choose an ordered 4-tuple of distinct digits: ⁶P₄ = 6 × 5 × 4 × 3 = 360.","Subtract the cases with a leading zero: ⁵P₃ = 5 × 4 × 3 = 60.","360 − 60 = 300."],ans:"300 (option B)",tip:"Whenever 0 is in the digit set, count all arrangements and subtract the leading-zero ones. The leading-zero count is always ⁽ⁿ⁻¹⁾P₍ᵣ₋₁₎."},
{type:"hard",q:"Four letters are to be placed in four addressed envelopes, one letter per envelope. The number of ways in which NO letter goes into its own correct envelope is:",options:["15","24","9","23"],answer:2,steps:["This is the derangement count D₄.","Dₙ = n![1 − 1/1! + 1/2! − 1/3! + 1/4! ...].","D₄ = 24[1 − 1 + 1/2 − 1/6 + 1/24] = 24(3/8) = 9."],ans:"9 (option C)",tip:"Memorise D₄ = 9, D₅ = 44, D₆ = 265. Option 23 is the complement (at least one correct) — the classic decoy."},
{type:"hard",q:"If C(n, 4) = C(n, 8), then C(n, 2) equals:",options:["66","55","78","198"],answer:0,steps:["C(n, r) = C(n, s) implies r = s or r + s = n.","Here 4 ≠ 8, so n = 4 + 8 = 12.","C(12, 2) = (12 × 11)/2 = 66."],ans:"66 (option A)",tip:"Use C(n,r) = C(n, n−r) to convert the given equation into a sum: the two arguments add to n. Never expand factorials here."},
{type:"hard",q:"The number of subsets of the set {1, 2, 3, ..., 10} that contain at least one odd number is:",options:["1024","992","32","512"],answer:1,steps:["Total subsets = 2¹⁰ = 1024.","Subsets with NO odd number use only the 5 even numbers: 2⁵ = 32.","Required = 1024 − 32 = 992."],ans:"992 (option B)",tip:"At-least-one ⇒ total minus none. The complement set (all-even subsets) is the only case to exclude — direct casework over 1, 3, 5 odd numbers is far slower."},
{type:"hard",q:"A committee of 4 is to be formed from 6 men and 4 women. The number of committees containing at least one woman is:",options:["210","180","195","205"],answer:2,steps:["Total committees = C(10, 4) = 210.","All-men committees = C(6, 4) = 15.","At least one woman = 210 − 15 = 195."],ans:"195 (option C)",tip:"Complement counting again: at least one of a kind = total − none of that kind. Option 210 is the total, the most common wrong choice."},
{type:"hard",q:"The number of arrangements of the letters of the word EXAMINATION is:",options:["4989600","39916800","1247400","831600"],answer:0,steps:["EXAMINATION has 11 letters, with A, I and N each appearing twice (E, X, M, T, O once).","Count = 11!/(2!·2!·2!).","= 39916800/8 = 4989600."],ans:"4989600 (option A)",tip:"First list the repeated letters. Dividing by 2! three times means dividing by 8; missing one of the repeats gives 1247400 — the decoy."},
{type:"hard",q:"A committee of 2 men and 3 women is to be chosen from 5 men and 6 women. If one particular man must always be included, the number of committees is:",options:["80","120","20","100"],answer:0,steps:["The particular man occupies one of the 2 male seats, so choose the remaining man from the other 4: 4 ways.","Choose 3 women from 6: C(6,3) = 20.","Total = 4 × 20 = 80."],ans:"80 (option A)",tip:"Fix the forced member FIRST and then count the remaining selections — never multiply by arrangements of the fixed member (that gives the wrong 120)."}
],
/* @@END_EXTRA_MATHS@@ */
};
