/* ===== BULK BANK P — 50 hard JEE Main PYQ-pattern MCQs per chapter ===== */
const BULK_PH = {
"1. Physics & Measurement": [
{type:"hard",q:"The dimensional formula of Planck's constant h is the same as that of:",options:["angular momentum","force","linear momentum","energy"],answer:0,steps:["E = hν → h = E/ν, so [h] = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹].","Angular momentum = mvr → [M][LT⁻¹][L] = [ML²T⁻¹].","Same dimensions → h and angular momentum are the same kind of quantity."],ans:"angular momentum (option A)",tip:"E = hν gives [h] = [ML²T⁻¹] in one step; action, angular momentum and h always share dimensions."},
{type:"hard",q:"If force (F), velocity (V) and time (T) are taken as fundamental quantities, the dimensional formula of MASS is:",options:["F V T","F V⁻¹ T","F V⁻¹ T⁻¹","F² V⁻² T²"],answer:1,steps:["From F = ma: mass = F/acceleration.","Acceleration = velocity/time → [A] = [V T⁻¹].","m = F/A → [F]/[V T⁻¹] = [F V⁻¹ T]."],ans:"[F V⁻¹ T] (option B)",tip:"Always start from F = ma and express acceleration via the given fundamentals. Never memorise — derive in 5 seconds."},
{type:"hard",q:"In an experiment R = V/I with V = (100 ± 1) V and I = (2 ± 0.05) A. The percentage error in R is:",options:["3%","2.5%","3.5%","4%"],answer:2,steps:["ΔR/R = ΔV/V + ΔI/I (division → errors ADD).","= 1/100 + 0.05/2 = 0.01 + 0.025 = 0.035.","Percentage error = 3.5%."],ans:"3.5% (option C)",tip:"For ×/÷ add RELATIVE errors; for +/− add ABSOLUTE errors. The 0.05 A on 2 A (2.5%) dominates here, not the 1 V."},
{type:"hard",q:"The number of significant figures in the measurement 0.004080 is:",options:["3","5","2","4"],answer:3,steps:["Leading zeros are never significant.","Interior and trailing zeros after the decimal ARE significant: 4, 0, 8, 0.","Total = 4 significant figures."],ans:"4 (option D)",tip:"Leading zeros never count; every zero AFTER the first non-zero digit counts. 0.004080 → strip 00 → 4080 → 4 figures."},
{type:"hard",q:"The side of a cube is measured as (1.20 ± 0.02) cm and its mass is exact. The percentage error in its density is:",options:["5%","1.67%","15%","3.3%"],answer:0,steps:["ρ = m/a³ → Δρ/ρ = 3(Δa/a).","Δa/a = 0.02/1.20 = 1/60.","Δρ/ρ = 3/60 = 1/20 = 5%."],ans:"5% (option A)",tip:"Power n in the denominator multiplies the relative error by n. Cubed side → triple the 1.67% error to 5%."},
{type:"hard",q:"The value of G = 6.67 × 10⁻¹¹ N·m²/kg² in CGS units is:",options:["6.67 × 10⁻⁷ dyne·cm²/g²","6.67 × 10⁻⁸ dyne·cm²/g²","6.67 × 10⁻⁵ dyne·cm²/g²","6.67 × 10⁻¹¹ dyne·cm²/g²"],answer:1,steps:["1 N = 10⁵ dyne, 1 m = 10² cm, 1 kg = 10³ g.","N·m²/kg² → dyne·cm²/g² factor = 10⁵ × (10²)²/(10³)² = 10⁵ × 10⁴/10⁶ = 10³.","G = 6.67 × 10⁻¹¹ × 10³ = 6.67 × 10⁻⁸."],ans:"6.67 × 10⁻⁸ dyne·cm²/g² (option B)",tip:"Chain the conversion factors as one multiplier (10³ here) instead of three separate steps; the powers of ten add."},
{type:"hard",q:"Which of the following relations is dimensionally INCORRECT?",options:["v² − u² = 2as","P = Fv","E = mc³","T = 2π√(l/g)"],answer:2,steps:["LHS of each: [LT⁻¹]², [ML²T⁻³], [ML²T⁻²], [T].","E = mc³ gives [M][LT⁻¹]³ = [ML³T⁻³] ≠ [ML²T⁻²].","The other three balance correctly."],ans:"E = mc³ (option C)",tip:"Dimensional analysis catches the missing power instantly: E must be ML²T⁻² (energy), so an extra c (LT⁻¹) breaks it."},
{type:"hard",q:"In a vernier calliper, 20 vernier divisions coincide with 19 main-scale divisions (1 MSD = 1 mm). Its least count is:",options:["0.1 mm","0.5 mm","0.01 mm","0.05 mm"],answer:3,steps:["1 VSD = 19/20 MSD = 0.95 mm.","Least count = 1 MSD − 1 VSD.","LC = 1 − 0.95 = 0.05 mm."],ans:"0.05 mm (option D)",tip:"LC = (value of 1 MSD) × (1 − VSD/MSD in the coincidence). n VSD = (n−1) MSD always gives LC = MSD/n."},
{type:"hard",q:"The dimensional formula of Young's modulus of elasticity is:",options:["[ML⁻¹T⁻²]","[ML⁻²T⁻²]","[ML²T⁻²]","[MLT⁻²]"],answer:0,steps:["Y = stress/strain and strain is dimensionless.","So [Y] = [stress] = force/area = [MLT⁻²]/[L²].","[Y] = [ML⁻¹T⁻²], same as pressure."],ans:"[ML⁻¹T⁻²] (option A)",tip:"All elastic moduli, pressure, stress and energy density share [ML⁻¹T⁻²]. One dimension covers four quantities."},
{type:"hard",q:"For Q = A²B/(C√D) the measured percentage errors are A ± 2%, B ± 1%, C ± 3%, D ± 4%. The percentage error in Q is:",options:["7%","10%","9%","12%"],answer:1,steps:["ΔQ/Q = 2(ΔA/A) + ΔB/B + ΔC/C + ½(ΔD/D).","= 2(2%) + 1% + 3% + ½(4%) = 4 + 1 + 3 + 2.","= 10%."],ans:"10% (option B)",tip:"Multiply each error by its exponent (halve for square roots), then add. Errors in a SQUARED quantity double — that is the question's core."},
{type:"hard",q:"A screw gauge has a pitch of 1 mm and 100 divisions on the circular scale. Its least count is:",options:["1 mm","0.1 mm","0.001 mm","0.01 mm"],answer:3,steps:["Least count = pitch / number of circular divisions.","= 1/100 = 0.01 mm.","One full rotation advances the screw by exactly one pitch."],ans:"0.01 mm (option D)",tip:"LC = pitch/N — for the standard 1 mm/100-division gauge the answer is always 0.01 mm; read the given numbers, don't recite memory."},
{type:"hard",q:"In a simple-pendulum experiment l = (100 ± 1) cm and T = (2.00 ± 0.02) s. The percentage error in g is:",options:["1%","3%","2%","4%"],answer:1,steps:["g = 4π²l/T² → Δg/g = Δl/l + 2(ΔT/T).","= 1/100 + 2(0.02/2.00) = 0.01 + 0.02 = 0.03.","Percentage error = 3%."],ans:"3% (option B)",tip:"Time error DOUBLES (T is squared); length error counts once. In every g-pendulum error question, hunt the T term first."},
{type:"hard",q:"The dimensional formula of the product RC (resistance × capacitance) is:",options:["[T]","[ML²T⁻³A⁻²]","[M⁻¹L⁻²T⁴A²]","[AT]"],answer:0,steps:["Charging equation q = q₀(1 − e^(−t/RC)) forces the exponent to be dimensionless.","So RC must have the dimensions of time.","Options B and C are the dimensions of R and C separately — the classic split-trap."],ans:"[T] (option A)",tip:"Any exponent must be dimensionless: [RC] = [t] = T. Same logic gives [L/R] = T and [√(LC)] = T instantly."},
{type:"hard",q:"The Stefan-Boltzmann constant σ (E = σT⁴) has the dimensional formula:",options:["[MLT⁻³Θ⁻⁴]","[ML²T⁻³Θ⁻⁴]","[MT⁻²Θ⁻⁴]","[ML⁰T⁻³Θ⁻⁴]"],answer:3,steps:["σ = energy/(area × time × T⁴).","[σ] = [ML²T⁻²]/([L²][T][Θ⁴]).","= [ML⁰T⁻³Θ⁻⁴]."],ans:"[ML⁰T⁻³Θ⁻⁴] (option D)",tip:"Divide out L² from the area and ML² from energy — one power of M and zero powers of L survive; options with L are eliminable at sight."},
{type:"hard",q:"Which of the following equations of motion is dimensionally correct?",options:["s = ut² + ½at","s = u²t + ½a²t²","s = ut + ½at²","s = ut − ½a²t"],answer:2,steps:["Every term must have the dimensions of length [L].","ut → [LT⁻¹][T] = L; at² → [LT⁻²][T²] = L.","Only option C has all terms equal to [L]."],ans:"s = ut + ½at² (option C)",tip:"Term-by-term dimension audit takes 10 seconds and never fails; any term with t³ or a² is dimensionally dead on arrival."},
{type:"hard",q:"The dimensional formula of the coefficient of viscosity η is:",options:["[ML⁻¹T⁻¹]","[ML⁻¹T⁻²]","[ML⁻²T⁻¹]","[MT⁻²]"],answer:0,steps:["From F = ηA(dv/dx): η = F/(A × velocity gradient).","[η] = [MLT⁻²]/([L²] × [T⁻¹]).","= [ML⁻¹T⁻¹]."],ans:"[ML⁻¹T⁻¹] (option A)",tip:"Velocity gradient (1/T) supplies the single T⁻¹; option B forgets it. Poise (CGS) = g·cm⁻¹·s⁻¹ matches this exactly."},
{type:"hard",q:"One light year is approximately equal to:",options:["9.46 × 10¹² m","3.0 × 10⁸ m","1.5 × 10¹¹ m","9.46 × 10¹⁵ m"],answer:3,steps:["1 ly = speed of light × 1 year = 3 × 10⁸ × 365 × 24 × 3600.","= 3 × 10⁸ × 3.15 × 10⁷ ≈ 9.46 × 10¹⁵ m.","Option B is one light-SECOND, option C is one AU."],ans:"9.46 × 10¹⁵ m (option D)",tip:"One year ≈ π × 10⁷ s (≈3.15 × 10⁷ s) — multiply by 3 × 10⁸ to get 9.46 × 10¹⁵ m without a calculator."},
{type:"hard",q:"The ratio of the radius of an atom (~10⁻¹⁰ m) to the radius of its nucleus (~10⁻¹⁵ m) is of the order of:",options:["10⁻⁵","10⁵","10¹⁰","10¹⁵"],answer:1,steps:["Ratio = 10⁻¹⁰/10⁻¹⁵.","Subtract exponents: −10 − (−15) = +5.","Ratio ≈ 10⁵ — the atom is mostly empty space."],ans:"10⁵ (option B)",tip:"Order-of-magnitude ratios are pure exponent subtraction; the atom-to-nucleus gap (10⁵) also explains Rutherford's scattering result."},
{type:"hard",q:"The Rydberg constant R_H (in the formula 1/λ = R_H(1/n₁² − 1/n₂²)) has dimensions of:",options:["[L]","[T⁻¹]","[ML²T⁻²]","[L⁻¹]"],answer:3,steps:["1/λ has dimensions [L⁻¹]; the bracket is dimensionless.","So R_H must carry [L⁻¹] to balance both sides.","Its SI unit is m⁻¹, consistent with [L⁻¹]."],ans:"[L⁻¹] (option D)",tip:"Isolate the constant on one side mentally: whatever dimensions the other side has, the constant inherits. Brackets of pure numbers never contribute."},
{type:"hard",q:"Surface tension has the same dimensions as:",options:["pressure","force","surface energy per unit area","impulse"],answer:2,steps:["Surface tension = force/length → [MLT⁻²]/[L] = [MT⁻²].","Surface energy/area = [ML²T⁻²]/[L²] = [MT⁻²].","Pressure ([ML⁻¹T⁻²]) and force differ — only option C matches."],ans:"surface energy per unit area (option C)",tip:"Energy/area = force × distance/area = force/length — the two definitions of surface tension are dimensionally identical, so this answer is forced."},
{type:"hard",q:"Which of the following pairs has the SAME dimensions?",options:["force and pressure","torque and work","momentum and energy","power and energy"],answer:1,steps:["Torque = force × distance → [MLT⁻²][L] = [ML²T⁻²].","Work = force × displacement → [ML²T⁻²].","All other pairs differ by at least one power of L or T."],ans:"torque and work (option B)",tip:"Torque vs work is the textbook same-dimension-different-nature pair; pressure (per area) vs force (total) is its mirror-image trap."},
{type:"hard",q:"Magnetic flux (φ = BA) has the dimensional formula:",options:["[MLT⁻²A]","[ML²T⁻¹A⁻¹]","[ML⁰T⁻²A⁻¹]","[ML²T⁻²A⁻¹]"],answer:3,steps:["F = qvB gives B = F/(qv) → [B] = [MLT⁻²]/([AT][LT⁻¹]) = [MT⁻²A⁻¹].","Flux = B × area → [MT⁻²A⁻¹][L²].","= [ML²T⁻²A⁻¹] (weber = T·m²)."],ans:"[ML²T⁻²A⁻¹] (option D)",tip:"Derive B first from F = qvB, then multiply by L² for flux; option B is the dimension of B itself, not of flux."},
{type:"hard",q:"The dimensional formula of self-inductance L is:",options:["[ML²T⁻²A⁻¹]","[MLT⁻²A⁻²]","[ML²T⁻²A⁻²]","[ML²T⁻³A⁻¹]"],answer:2,steps:["Induced emf ε = −L(dI/dt) → L = ε/(dI/dt).","[L] = [ML²T⁻³]/([A]/[T]) = [ML²T⁻²A⁻²].","Equivalently, energy ½LI² gives the same result."],ans:"[ML²T⁻²A⁻²] (option C)",tip:"ε = L(dI/dt) is the one-line derivation; the A⁻² (not A⁻¹) distinguishes inductance from flux — read the current power carefully."},
{type:"hard",q:"The permittivity of free space ε₀ has the dimensional formula:",options:["[M⁻¹L⁻³T⁴A²]","[ML³T⁻⁴A⁻²]","[M⁻¹L⁻³T⁴A⁻²]","[ML⁻³T⁴A²]"],answer:0,steps:["From Coulomb's law F = q₁q₂/(4πε₀r²): ε₀ = q²/(F r²).","[ε₀] = [AT]²/([MLT⁻²][L²]).","= [M⁻¹L⁻³T⁴A²]."],ans:"[M⁻¹L⁻³T⁴A²] (option A)",tip:"Solve Coulomb's law for ε₀ and count exponents mechanically; T⁴A² is the signature — only option A has both with the right signs."},
{type:"hard",q:"The value of 1 eV in SI units is:",options:["1.6 × 10⁻¹⁹ erg","1.6 × 10⁻¹⁹ J","9.1 × 10⁻³¹ J","3 × 10⁸ J"],answer:1,steps:["1 eV = charge of electron × 1 volt.","= 1.602 × 10⁻¹⁹ C × 1 V = 1.6 × 10⁻¹⁹ J.","Option A confuses joule with erg (1 J = 10⁷ erg)."],ans:"1.6 × 10⁻¹⁹ J (option B)",tip:"eV = e × V by definition, so the number 1.6 × 10⁻¹⁹ is just the electron charge; only the UNIT (joule vs erg) decides the option."},
{type:"hard",q:"If A = (2.5 ± 0.1) and B = (1.25 ± 0.02), then A + B with error is:",options:["(3.75 ± 0.03)","(3.75 ± 0.08)","(3.75 ± 0.12)","(3.8 ± 0.12)"],answer:2,steps:["For addition, ABSOLUTE errors add: 0.1 + 0.02 = 0.12.","Sum = 2.5 + 1.25 = 3.75.","Result = (3.75 ± 0.12)."],ans:"(3.75 ± 0.12) (option C)",tip:"Addition/subtraction → add absolute errors (never relative). Option A adds them in quadrature (√(0.1²+0.02²)≈0.10) — wrong rule, right-looking number."},
{type:"hard",q:"The product 2.5 × 1.25, written with the correct number of significant figures, is:",options:["3.125","3.12","3.13","3.1"],answer:3,steps:["Raw product = 3.125.","The least-precise input (2.5) has 2 significant figures.","Round to 2 figures → 3.1."],ans:"3.1 (option D)",tip:"Multiplication result carries the SMALLEST count of significant figures (2 here), so extra digits 25 must be dropped — exactness is not precision."},
{type:"hard",q:"A screw gauge shows a reading of 4.27 mm with a positive zero error of 0.05 mm. The corrected reading is:",options:["4.32 mm","4.22 mm","4.27 mm","4.17 mm"],answer:1,steps:["Positive zero error means the instrument reads HIGH at zero.","Corrected value = observed − zero error.","= 4.27 − 0.05 = 4.22 mm."],ans:"4.22 mm (option B)",tip:"Positive error → subtract; negative error → add. The correction always pushes the reading back toward the true (lower) value for positive error."},
{type:"hard",q:"One parsec is equal to:",options:["3.26 light years","3.26 AU","1.5 × 10⁸ km","3 × 10⁸ m"],answer:0,steps:["1 parsec = distance at which 1 AU subtends 1 arcsecond.","= 206265 AU = 3.08 × 10¹⁶ m.","In light years: 3.08 × 10¹⁶/9.46 × 10¹⁵ ≈ 3.26 ly."],ans:"3.26 light years (option A)",tip:"Parsec > light year > AU in size; any option making a parsec smaller than an AU (B) or equal to light's one-second travel (D) is absurd."},
{type:"hard",q:"Which of the following is NOT a unit of length?",options:["fermi","barn","angstrom","micron"],answer:1,steps:["fermi = 10⁻¹⁵ m, angstrom = 10⁻¹⁰ m, micron = 10⁻⁶ m — all lengths.","barn = 10⁻²⁸ m² — a unit of AREA (nuclear cross-section).","So barn is the odd one out."],ans:"barn (option B)",tip:"Barn measures nuclear cross-sectional AREA (m²), never length — the name sounds like length, which is exactly why it is asked."},
{type:"hard",q:"The Boltzmann constant k (E = kT per molecule) has the dimensional formula:",options:["[ML²T⁻²]","[ML²T⁻²Θ⁻¹]","[ML²T⁻¹Θ⁻¹]","[MLT⁻²Θ⁻¹]"],answer:1,steps:["k = energy/temperature.","= [ML²T⁻²]/[Θ].","= [ML²T⁻²Θ⁻¹], same as entropy and R per mole."],ans:"[ML²T⁻²Θ⁻¹] (option B)",tip:"Energy per kelvin is the whole story; gas constant R and entropy share this dimension, so any of them recalls it for the others."},
{type:"hard",q:"The dimensional formula of the universal gravitational constant G is:",options:["[M⁻¹L²T⁻²]","[ML³T⁻²]","[M⁻¹L³T⁻²]","[ML⁻¹T⁻²]"],answer:2,steps:["From F = Gm₁m₂/r²: G = Fr²/m².","[G] = [MLT⁻²][L²]/[M²].","= [M⁻¹L³T⁻²]."],ans:"[M⁻¹L³T⁻²] (option C)",tip:"G carries the most extreme exponents in mechanics (M⁻¹L³T⁻²) — the lone M⁻¹ L³ combination is unique, so pattern-spot it."},
{type:"hard",q:"The radius of a sphere is measured as (2.0 ± 0.1) cm. The percentage error in its volume is:",options:["5%","10%","45%","15%"],answer:3,steps:["V = (4/3)πr³ → ΔV/V = 3(Δr/r).","Δr/r = 0.1/2.0 = 0.05 = 5%.","ΔV/V = 3 × 5% = 15%."],ans:"15% (option D)",tip:"Volume's r³ triples the 5% radius error; option C (45%) cubes the error itself — powers multiply errors, never exponentiate them."},
{type:"hard",q:"In a pendulum experiment the slope of the T² versus l graph is 4 s²/m. The value of g is:",options:["4.93 m/s²","9.87 m/s²","19.7 m/s²","2.47 m/s²"],answer:1,steps:["T² = (4π²/g)l → slope = 4π²/g.","g = 4π²/slope = 39.48/4.","g = 9.87 m/s²."],ans:"9.87 m/s² (option B)",tip:"Graph slope absorbs 4π²: g = 4π²/slope. Memorise 4π² ≈ 39.5 and the division is one mental step."},
{type:"hard",q:"The value of 1 eV expressed in erg is:",options:["1.6 × 10⁻¹⁹ erg","1.6 × 10⁻⁷ erg","1.6 × 10⁻¹² erg","10⁻⁷ erg"],answer:2,steps:["1 eV = 1.6 × 10⁻¹⁹ J.","1 J = 10⁷ erg.","1 eV = 1.6 × 10⁻¹⁹ × 10⁷ = 1.6 × 10⁻¹² erg."],ans:"1.6 × 10⁻¹² erg (option C)",tip:"Joule → erg multiplies by 10⁷, so the exponent rises from −19 to −12; options A and B skip or botch exactly this step."},
{type:"hard",q:"Which of the following quantities has dimensions [M⁰L⁰T⁻¹]?",options:["frequency","wavelength","Planck's constant","Rydberg constant"],answer:0,steps:["Frequency = 1/period → [T⁻¹] = [M⁰L⁰T⁻¹].","Wavelength is [L], h is [ML²T⁻¹], R_H is [L⁻¹].","Only frequency matches all three exponents."],ans:"frequency (option A)",tip:"Zero exponents on M and L force a pure rate/wavenumber-type quantity; frequency (per second) is the only one listed."},
{type:"hard",q:"The dimensional formula of electric charge is:",options:["[A]","[AT]","[AT⁻¹]","[A²T]"],answer:1,steps:["Current is charge per unit time by definition: I = Q/t.","So Q = It.","[Q] = [AT]."],ans:"[AT] (option B)",tip:"Ampere is a fundamental dimension in SI, so charge (= current × time) is derived in one line — coulomb = ampere·second."},
{type:"hard",q:"The equation v = u + at² is dimensionally wrong because:",options:["velocity [LT⁻¹] and at² [L] have different dimensions","the equation is actually correct","only the units differ while dimensions match","g should replace a"],answer:0,steps:["v and u have [LT⁻¹].","at² has [LT⁻²][T²] = [L].","[LT⁻¹] ≠ [L], so addition is forbidden — dimensions must match term by term."],ans:"velocity [LT⁻¹] and at² [L] have different dimensions (option A)",tip:"For formula-check MCQs, audit the SUSPECT term (the one with the unusual power) first — the mismatch exposes itself in seconds."},
{type:"hard",q:"If force, length and time are fundamental, the dimensional formula of POWER is:",options:["[F L⁻¹ T]","[F L T⁻¹]","[F² L T⁻¹]","[F L T]"],answer:1,steps:["Power = work/time = force × length/time.","[P] = [F][L]/[T].","= [F L T⁻¹]."],ans:"[F L T⁻¹] (option B)",tip:"Work = FL packages two fundamentals into one; dividing by T only flips the time exponent. Watch option D, which forgets the division."},
{type:"hard",q:"A screw gauge has pitch 1 mm and 200 divisions on the circular scale. Its least count is:",options:["0.05 mm","0.5 mm","0.005 mm","0.02 mm"],answer:2,steps:["LC = pitch/N = 1/200 mm.","= 0.005 mm = 5 μm.","Doubling the divisions halves the standard 0.01 mm gauge's least count."],ans:"0.005 mm (option C)",tip:"LC = pitch ÷ divisions, always; 1/200 = 0.005 needs no calculator — count the zeros in 200."},
{type:"hard",q:"The length of a rod is (10.0 ± 0.1) cm. The percentage error in measuring it is:",options:["0.1%","1%","10%","0.01%"],answer:1,steps:["Relative error = Δl/l = 0.1/10.0.","= 0.01.","Percentage = 1%."],ans:"1% (option B)",tip:"0.1 on 10.0 is one part in a hundred — read the ratio directly; rulers always give ~1% on a 10 cm span."},
{type:"hard",q:"The SI unit of the gas constant R is:",options:["J mol⁻¹","J mol⁻¹ K⁻¹","J K⁻¹","N m mol⁻¹"],answer:1,steps:["From PV = nRT: R = PV/(nT).","[R] = ([ML⁻¹T⁻²][L³])/([mol][Θ]).","= J mol⁻¹ K⁻¹."],ans:"J mol⁻¹ K⁻¹ (option B)",tip:"Solve PV = nRT for R and audit units: pressure × volume is joules, so R = J/(mol·K) with no alternatives."},
{type:"hard",q:"The dimensions of the ratio momentum/energy are:",options:["[M⁻¹L⁻²T²]","[MLT⁻¹]","[L⁻¹T]","[MT]"],answer:2,steps:["p/E = [MLT⁻¹]/[ML²T⁻²].","M cancels; L^(1−2) = L⁻¹; T^(−1+2) = T.","= [L⁻¹T] (the reciprocal of velocity)."],ans:"[L⁻¹T] (option C)",tip:"Ratios collapse by cancelling M first; p/E = 1/v dimensionally, so the answer is forced to be inverse-velocity."},
{type:"hard",q:"Which pair has different dimensions?",options:["Young's modulus and pressure","torque and energy","Planck's constant and angular momentum","force and impulse"],answer:3,steps:["Force = [MLT⁻²]; impulse = force × time = [MLT⁻¹].","They differ by one power of T.","The other three pairs share dimensions exactly."],ans:"force and impulse (option D)",tip:"Impulse = F·Δt gains an extra T — a classic different-dimension pair hiding among three identical-dimension pairs."},
{type:"hard",q:"A circular disc has radius (5.0 ± 0.1) cm. The percentage error in its area is:",options:["2%","4%","0.2%","8%"],answer:1,steps:["A = πr² → ΔA/A = 2(Δr/r).","Δr/r = 0.1/5.0 = 0.02 = 2%.","ΔA/A = 2 × 2% = 4%."],ans:"4% (option B)",tip:"Area's r² doubles any radius error; the π is an exact constant and contributes zero error."},
{type:"hard",q:"The quantity √(ε₀μ₀) has the dimensions of:",options:["velocity","1/velocity","time","length"],answer:1,steps:["c = 1/√(ε₀μ₀) by Maxwell's relation.","So √(ε₀μ₀) = 1/c.","Dimensions = [L⁻¹T], i.e. reciprocal velocity."],ans:"1/velocity (option B)",tip:"c = 1/√(ε₀μ₀) is the relation asked backwards; option A (velocity) is the trap for those who forget the reciprocal."},
{type:"hard",q:"The dimensional formula of kinetic energy is:",options:["[ML²T⁻²]","[MLT⁻²]","[ML²T⁻¹]","[ML⁻¹T⁻²]"],answer:0,steps:["KE = ½mv².","= [M][LT⁻¹]² = [M][L²T⁻²].","= [ML²T⁻²], like all forms of energy."],ans:"[ML²T⁻²] (option A)",tip:"All energies share ML²T⁻²; options B (force) and D (pressure) differ by exactly one L — count the L's."},
{type:"hard",q:"One angstrom equals:",options:["10⁻⁸ cm","10⁻¹⁰ m","10⁻⁸ m","10⁻¹² m"],answer:1,steps:["1 Å = 10⁻¹⁰ m by definition.","= 10⁻⁸ cm (since 1 m = 100 cm).","Both forms appear; here the SI form is the answer."],ans:"10⁻¹⁰ m (option B)",tip:"Ångström = 10⁻¹⁰ m = 10⁻⁸ cm; the two forms differ by exactly 10² (the metre–centimetre jump)."},
{type:"hard",q:"The number of significant figures in 100.0 is:",options:["1","3","5","4"],answer:3,steps:["The trailing zero AFTER the decimal is significant.","100.0 has digits 1, 0, 0, 0 — all significant.","Total = 4."],ans:"4 (option D)",tip:"A decimal point makes trailing zeros significant: 100.0 (4 sf) vs 100 (ambiguous). The point is the signal."},
{type:"hard",q:"The dimensional formula of power (in M, L, T) is:",options:["[ML²T⁻³]","[ML²T⁻²]","[MLT⁻²]","[ML²T⁻¹]"],answer:0,steps:["Power = energy/time.","= [ML²T⁻²]/[T].","= [ML²T⁻³]."],ans:"[ML²T⁻³] (option A)",tip:"Energy divided by time adds one more T⁻¹; option B is energy itself — the half-finished derivation trap."},
],
"2. Kinematics": [
{type:"hard",q:"A particle moves with uniform acceleration 4 m/s² starting from rest. The distance travelled in the 4th second is:",options:["14 m","16 m","12 m","28 m"],answer:0,steps:["Distance in nth second: sₙ = u + (a/2)(2n − 1).","= 0 + 2 × (2 × 4 − 1) = 2 × 7.","= 14 m."],ans:"14 m (option A)",tip:"sₙ = u + a(n − ½) — for n = 4, a = 4: 4 × 3.5 = 14 in one line. Total distance is never asked this way."},
{type:"hard",q:"A ball is dropped from a tower of height 80 m (g = 10 m/s²). The time to reach the ground is:",options:["3 s","4 s","8 s","16 s"],answer:1,steps:["h = ½gt² → 80 = 5t².","t² = 16.","t = 4 s."],ans:"4 s (option B)",tip:"t = √(2h/g) = √(160/10) = 4. For h = 5n² the time is just n — spot the perfect square."},
{type:"hard",q:"Two trains A (60 m) and B (40 m) move toward each other at 15 m/s and 10 m/s. The time they take to cross each other is:",options:["2 s","4 s","5 s","10 s"],answer:1,steps:["Relative speed (opposite directions) = 15 + 10 = 25 m/s.","Total distance = 60 + 40 = 100 m.","Time = 100/25 = 4 s."],ans:"4 s (option B)",tip:"Opposite directions → ADD speeds; same direction → subtract. Total length (both trains) divided by relative speed."},
{type:"hard",q:"A stone is thrown vertically up with speed 20 m/s (g = 10 m/s²). The maximum height reached is:",options:["10 m","40 m","20 m","30 m"],answer:2,steps:["At max height v = 0: v² = u² − 2gh.","0 = 400 − 20h.","h = 20 m."],ans:"20 m (option C)",tip:"h = u²/2g — for u = 20, g = 10: 400/20 = 20. Time to top (u/g = 2 s) is the free bonus."},
{type:"hard",q:"A projectile is launched at 60° with speed 20 m/s (g = 10 m/s²). Its time of flight is:",options:["2 s","2√3 s","4 s","√3 s"],answer:1,steps:["T = 2u sinθ/g = 2 × 20 × (√3/2)/10.","= 20√3/10 = 2√3 s.","≈ 3.46 s."],ans:"2√3 s (option B)",tip:"T = 2u sinθ/g — only the VERTICAL component matters; the 60° just supplies √3/2."},
{type:"hard",q:"The horizontal range of a projectile is maximum when the angle of projection is:",options:["30°","45°","60°","90°"],answer:1,steps:["R = u²sin2θ/g.","sin2θ is maximum (= 1) when 2θ = 90°.","θ = 45°."],ans:"45° (option B)",tip:"sin2θ peaks at 2θ = 90°. Complementary angles (30°/60°) give EQUAL ranges — the paired fact JEE loves."},
{type:"hard",q:"A car accelerates uniformly from 10 m/s to 30 m/s over 200 m. Its acceleration is:",options:["1 m/s²","2 m/s²","4 m/s²","0.5 m/s²"],answer:1,steps:["v² − u² = 2as.","900 − 100 = 2 × a × 200.","800 = 400a → a = 2 m/s²."],ans:"2 m/s² (option B)",tip:"No time given → reach for v² − u² = 2as immediately. Option A forgets the factor (v² − u² = 800, not 400)."},
{type:"hard",q:"A particle's position is x = 2t² + 3t (metres). Its velocity at t = 2 s is:",options:["7 m/s","11 m/s","8 m/s","14 m/s"],answer:1,steps:["v = dx/dt = 4t + 3.","At t = 2: v = 8 + 3.","= 11 m/s."],ans:"11 m/s (option B)",tip:"Differentiate first, substitute after. Option A (2t²+3 = 11?) — no: 2(4)+3 = 11 is x, coincidentally equal here but that is position, not velocity."},
{type:"hard",q:"A boat moves at 5 m/s in still water across a 200 m wide river flowing at 3 m/s. The time to cross (shortest time) is:",options:["25 s","40 s","50 s","33.3 s"],answer:1,steps:["For shortest time, aim straight across: crossing speed = 5 m/s.","Time = width/boat speed = 200/5.","= 40 s (drift downstream = 3 × 40 = 120 m)."],ans:"40 s (option B)",tip:"Shortest TIME = width ÷ boat's own speed (aim perpendicular); drift is a separate question. Option C drifts in."},
{type:"hard",q:"A particle is projected horizontally at 10 m/s from a 45 m cliff (g = 10 m/s²). Its time of flight is:",options:["2 s","4.5 s","3 s","1 s"],answer:2,steps:["Vertical motion: u_y = 0, h = ½gt².","45 = 5t² → t² = 9.","t = 3 s (horizontal speed is irrelevant to fall time)."],ans:"3 s (option C)",tip:"Horizontal projection → vertical fall is pure free fall from rest: t = √(2h/g). The 10 m/s only sets the range (30 m)."},
{type:"hard",q:"Two cars start from the same point: car A at 60 km/h and car B (starting 1 hour later) at 90 km/h. B catches A after:",options:["1 h","2 h","3 h","1.5 h"],answer:1,steps:["In 1 hour, A gains a head start of 60 km.","Relative speed = 90 − 60 = 30 km/h.","Catch-up time = 60/30 = 2 h (after B starts)."],ans:"2 h (option B)",tip:"Head start ÷ relative speed — B gains 30 km every hour on the 60 km lead; 2 h exactly."},
{type:"hard",q:"The maximum height H and range R of a projectile satisfy H = R/2. The angle of projection is:",options:["45°","60°","tan⁻¹(2)","76°"],answer:2,steps:["tanθ = 4H/R (standard identity).","Here H/R = 1/2 → tanθ = 4 × 1/2 = 2.","θ = tan⁻¹(2) ≈ 63.4°."],ans:"tan⁻¹(2) (option C)",tip:"tanθ = 4H/R solves every H–R linked question in one line; 45° gives H = R/4 as the benchmark."},
{type:"hard",q:"A particle moves on a circle of radius 2 m with constant speed 4 m/s. Its centripetal acceleration is:",options:["4 m/s²","8 m/s²","16 m/s²","2 m/s²"],answer:1,steps:["a_c = v²/r.","= 16/2 = 8 m/s².","Directed toward the centre; speed is unchanged."],ans:"8 m/s² (option B)",tip:"v²/r with v² = 16, r = 2 — option A divides by diameter instead of radius; read r carefully."},
{type:"hard",q:"A stone dropped from rest falls 45 m in the last second before hitting the ground (g = 10 m/s²). The total fall time is:",options:["4 s","5 s","6 s","3 s"],answer:1,steps:["Distance in last (nth) second: 5(2n − 1) = 45.","2n − 1 = 9 → n = 5.","Total time = 5 s (tower height = 125 m)."],ans:"5 s (option B)",tip:"Last-second distance 5(2n−1) with g = 10: 45/5 = 9 = 2n−1 → n = 5. Works for any last-second distance."},
{type:"hard",q:"A projectile has the same range at 20° and at:",options:["70°","60°","80°","40°"],answer:0,steps:["R(θ) = R(90° − θ) since sin2θ = sin(180° − 2θ).","90° − 20° = 70°.","Complementary angles always share the range."],ans:"70° (option A)",tip:"Complementary angles give identical ranges (times of flight differ). 90 − θ is the whole rule."},
{type:"hard",q:"A train of length 200 m crosses a pole in 10 s. Its speed is:",options:["10 m/s","20 m/s","15 m/s","25 m/s"],answer:1,steps:["Crossing a pole covers one train-length.","Speed = 200/10 = 20 m/s.","= 72 km/h."],ans:"20 m/s (option B)",tip:"Pole/platform problems differ only in distance: one length for a pole, length + platform for a bridge. Speed = distance/time."},
{type:"hard",q:"The velocity-time graph of a body is a straight line with slope 3 and intercept 5 (SI units). Its displacement in the first 4 s is:",options:["32 m","44 m","20 m","68 m"],answer:1,steps:["v = 3t + 5 (slope = a, intercept = u).","s = ∫₀⁴(3t + 5)dt = [1.5t² + 5t]₀⁴.","= 24 + 20 = 44 m."],ans:"44 m (option B)",tip:"Slope = acceleration, intercept = initial velocity; integrate (area) for displacement. Trapezium area gives it too."},
{type:"hard",q:"A particle is thrown up at 30 m/s (g = 10 m/s²). The distance travelled in the 3rd second of its motion is:",options:["5 m","10 m","15 m","25 m"],answer:0,steps:["Upward motion: sₙ = u − g(n − ½) = 30 − 10 × 2.5.","= 30 − 25 = 5 m.","(It reaches the top at t = 3 s, so the 3rd second covers the last 5 m up.)"],ans:"5 m (option A)",tip:"Signed formula sₙ = u − g(n−½) handles upward throws directly; 3rd second with u = 30 gives 30 − 25 = 5."},
{type:"hard",q:"Two bodies fall from heights in ratio 1:4. The ratio of their times of fall is:",options:["1:4","1:2","1:8","2:1"],answer:1,steps:["t = √(2h/g) → t ∝ √h.","Ratio = √1:√4.","= 1:2."],ans:"1:2 (option B)",tip:"Time scales as √h — heights in ratio 1:4 collapse to times 1:2. Square-root scaling is the pattern."},
{type:"hard",q:"A cyclist rounds a curve of radius 50 m at 10 m/s on a banked road (g = 10 m/s²). The angle of banking needed for no friction is:",options:["tan⁻¹(1/5)","tan⁻¹(1/2)","tan⁻¹(2)","45°"],answer:0,steps:["tanθ = v²/(rg).","= 100/(50 × 10) = 1/5.","θ = tan⁻¹(1/5)."],ans:"tan⁻¹(1/5) (option A)",tip:"tanθ = v²/rg for ideal banking; 100/500 = 1/5 needs no calculator. Friction-free cornering in one formula."},
{type:"hard",q:"A man walks 3 km east and then 4 km north. His displacement magnitude is:",options:["7 km","5 km","1 km","25 km"],answer:1,steps:["East and north legs are perpendicular.","Resultant = √(3² + 4²) = √25.","= 5 km (the 3-4-5 triangle)."],ans:"5 km (option B)",tip:"Perpendicular walks → hypotenuse. 3-4-5 is the giveaway triple; option A adds instead of vector-adding."},
{type:"hard",q:"A gun fires a bullet at 100 m/s at 30° above horizontal (g = 10 m/s²). The maximum height is:",options:["500 m","250 m","125 m","1000 m"],answer:2,steps:["H = u²sin²θ/2g = (10000 × 1/4)/20.","= 2500/20 = 125 m.","Only the vertical component u sinθ = 50 m/s matters."],ans:"125 m (option C)",tip:"H = (u sinθ)²/2g — compute u sinθ = 50 first, then 2500/20. Option B forgets the sin² factor."},
{type:"hard",q:"A body slides down a smooth 30° incline of length 20 m (g = 10 m/s²). The time taken is:",options:["2 s","2√2 s","4 s","√2 s"],answer:1,steps:["a = g sin30° = 5 m/s².","s = ½at² → 20 = 2.5t² → t² = 8.","t = 2√2 s."],ans:"2√2 s (option B)",tip:"Smooth incline: a = g sinθ, then s = ½at². 20/2.5 = 8 → √8 = 2√2."},
{type:"hard",q:"Rain falls vertically at 10 m/s. A man runs east at 10 m/s. The rain appears to fall on him at:",options:["vertically","45° from the vertical","30° from the vertical","horizontally"],answer:1,steps:["Relative velocity of rain w.r.t. man = v_rain − v_man.","Vertical 10 m/s down, horizontal 10 m/s backward.","tanθ = 10/10 = 1 → 45° from the vertical."],ans:"45° from the vertical (option B)",tip:"Relative velocity subtracts the man's motion; equal speeds force exactly 45° — the umbrella tilts halfway."},
/* @@P02D@@ */
/* @@P02E@@ */
],
"3. Laws of Motion": [
{type:"hard",q:"A 2 kg block on a rough horizontal floor (μ = 0.4) is pushed by a horizontal force of 20 N (g = 10 m/s²). Its acceleration is:",options:["10 m/s²","6 m/s²","2 m/s²","zero"],answer:1,steps:["Normal N = mg = 20 N → friction = μN = 0.4 × 20 = 8 N.","Net force = 20 − 8 = 12 N.","a = 12/2 = 6 m/s²."],ans:"6 m/s² (option B)",tip:"Friction = μN first; if applied force exceeds it, net = applied − friction. Option A ignores friction entirely."},
{type:"hard",q:"Two blocks 3 kg and 2 kg in contact on a smooth floor are pushed by 10 N on the 3 kg block. The contact force between them is:",options:["10 N","6 N","4 N","5 N"],answer:2,steps:["System acceleration a = 10/(3 + 2) = 2 m/s².","The 2 kg block accelerates at 2 m/s² only via the contact force.","Contact force = 2 × 2 = 4 N."],ans:"4 N (option C)",tip:"Contact force = (mass ahead) × (common acceleration). The pushed mass never enters the contact-force formula."},
{type:"hard",q:"A 5 kg block needs what minimum horizontal force to be held against a vertical wall (μ = 0.5, g = 10 m/s²)?",options:["50 N","100 N","25 N","200 N"],answer:1,steps:["Friction must balance weight: f = 50 N.","f = μN → 50 = 0.5 × N → N = 100 N.","Horizontal push = normal N = 100 N."],ans:"100 N (option B)",tip:"f = μ × (applied force) here since push = normal. Minimum push = mg/μ = 100 N — friction capped by weight."},
{type:"hard",q:"A 1 kg block on a 30° smooth incline is held by a force parallel to the incline. The force is:",options:["10 N","8.66 N","5 N","2.5 N"],answer:2,steps:["Down-slope component of weight = mg sin30°.","= 1 × 10 × 0.5 = 5 N.","Holding force = 5 N up the slope."],ans:"5 N (option C)",tip:"mg sinθ down the plane is the whole story on smooth inclines; 30° halves the weight component."},
{type:"hard",q:"A car of mass 1000 kg takes a flat circular turn of radius 50 m with μ = 0.4 (g = 10 m/s²). The maximum safe speed is:",options:["10 m/s","10√2 m/s","20 m/s","40 m/s"],answer:1,steps:["Friction provides centripetal force: μmg = mv²/r.","v² = μgr = 0.4 × 10 × 50 = 200.","v = 10√2 m/s ≈ 14.1 m/s."],ans:"10√2 m/s (option B)",tip:"v_max = √(μgr) — mass cancels. Option C drops the μ; √200 = 10√2, not 20."},
{type:"hard",q:"A 60 kg man in a lift accelerating DOWN at 2 m/s² (g = 10 m/s²) feels an apparent weight of:",options:["60 kg","48 kg","72 kg","600 N"],answer:1,steps:["Apparent weight = m(g − a) for downward acceleration.","= 60 × (10 − 2) = 480 N.","= 48 kg-force."],ans:"48 kg (option B)",tip:"Down → lighter (g − a); up → heavier (g + a). Sign of a decides; free fall (a = g) gives zero."},
{type:"hard",q:"A bullet of mass 10 g at 400 m/s pierces 5 cm of wood and emerges at 100 m/s. The average resistive force is:",options:["1500 N","15000 N","3000 N","150 N"],answer:1,steps:["Work lost = ½m(v² − u²) = 0.005 × (160000 − 10000).","= 0.005 × 150000 = 750 J.","F = W/d = 750/0.05 = 15000 N."],ans:"15000 N (option B)",tip:"Work–energy in one line: F·d = ΔKE. Grams → kg (0.005) is the conversion that makes or breaks it."},
{type:"hard",q:"Two masses 4 kg and 6 kg hang over a smooth pulley. The tension in the string is (g = 10 m/s²):",options:["60 N","48 N","40 N","24 N"],answer:1,steps:["Acceleration a = (m₂ − m₁)g/(m₁ + m₂) = 2 × 10/10 = 2 m/s².","Tension T = 2m₁m₂g/(m₁ + m₂) = 2 × 4 × 6 × 10/10.","= 48 N."],ans:"48 N (option B)",tip:"Atwood: T = 2m₁m₂g/(m₁+m₂). It must lie BETWEEN the two weights (40–60 N) — option A equals the heavier weight, impossible."},
{type:"hard",q:"A block just slides on a rough incline when the angle is 30°. The coefficient of friction is:",options:["0.5","1/√3","√3","1"],answer:1,steps:["At angle of repose, tanθ = μ.","μ = tan30° = 1/√3.","≈ 0.577."],ans:"1/√3 (option B)",tip:"Angle of repose: μ = tanθ directly. Option A confuses tan30° with sin30°."},
{type:"hard",q:"The minimum force to pull a 10 kg block (μ = 0.5) on a rough floor at the OPTIMUM angle is (g = 10 m/s²):",options:["50 N","25√5 N","20√5 N","100 N"],answer:2,steps:["Minimum pull F_min = μmg/√(1 + μ²).","= 0.5 × 100/√1.25 = 50/√1.25.","= 50√(4/5) = 20√5 ≈ 44.7 N."],ans:"20√5 N (option C)",tip:"F_min = μmg/√(1+μ²) at tanθ = μ. Less than μmg (50 N) — angled pulling beats horizontal dragging."},
{type:"hard",q:"A man of mass 70 kg stands on a weighing scale in a lift moving UP with acceleration 3 m/s² (g = 10 m/s²). The scale reads:",options:["70 kg","91 kg","49 kg","73 kg"],answer:1,steps:["Apparent weight = m(g + a) for upward acceleration.","= 70 × 13 = 910 N.","= 91 kg-force."],ans:"91 kg (option B)",tip:"Up → heavier by m·a (210 N here). Scale reads mass-equivalent: 910/10 = 91 kg."},
{type:"hard",q:"A 4 kg block is pulled by 30 N at 37° above horizontal on a smooth floor (g = 10 m/s², cos37° = 0.8). Its acceleration is:",options:["7.5 m/s²","6 m/s²","5 m/s²","4.5 m/s²"],answer:1,steps:["Horizontal component = 30 × 0.8 = 24 N.","Vertical component lifts slightly; floor is smooth.","a = 24/4 = 6 m/s²."],ans:"6 m/s² (option B)",tip:"Only the horizontal component drives motion: F cosθ/m. cos37° = 0.8 turns 30 N into 24 N instantly."},
{type:"hard",q:"A particle of mass 2 kg moves with velocity (3i + 4j) m/s. A force (6i + 8j) N acts for 2 s. The final speed is:",options:["10 m/s","15 m/s","25 m/s","5 m/s"],answer:1,steps:["F is parallel to v (both along 3:4 direction).","a = F/m = (3i + 4j) → |a| = 5 m/s² along motion.","v_final = 5 + 5 × 2 = 15 m/s."],ans:"15 m/s (option B)",tip:"Parallel F and v → 1D problem along the line: initial speed 5 m/s, a = 5 m/s², 2 s → 15 m/s."},
{type:"hard",q:"A monkey of mass 20 kg climbs a rope with acceleration 2 m/s² upward (g = 10 m/s²). The tension in the rope is:",options:["200 N","240 N","160 N","400 N"],answer:1,steps:["T − mg = ma.","T = m(g + a) = 20 × 12.","= 240 N."],ans:"240 N (option B)",tip:"Climbing up: T = m(g+a); sliding down: T = m(g−a). The monkey's acceleration adds to gravity."},
{type:"hard",q:"A block of mass 2 kg rests on a rough incline of angle 37° (μ = 0.5, g = 10 m/s², sin37° = 0.6, cos37° = 0.8). The friction force is:",options:["12 N","8 N","10 N","6 N"],answer:1,steps:["Down-slope pull = mg sinθ = 2 × 10 × 0.6 = 12 N.","Max static friction = μmg cosθ = 0.5 × 20 × 0.8 = 8 N.","Pull exceeds max friction → kinetic friction 8 N opposes sliding."],ans:"8 N (option B)",tip:"Compare mg sinθ with μmg cosθ first: if pull wins, friction = μN kinetic. Static adjusts, kinetic is fixed."},
{type:"hard",q:"A 10 kg block is pushed by 120 N at 37° below the horizontal on a rough floor (μ = 0.5, g = 10 m/s², sin37° = 0.6, cos37° = 0.8). Its acceleration is:",options:["2 m/s²","1 m/s²","4 m/s²","3 m/s²"],answer:1,steps:["Normal N = mg + F sin37° = 100 + 72 = 172 N.","Friction = 0.5 × 172 = 86 N; horizontal push = 120 × 0.8 = 96 N.","Net = 96 − 86 = 10 N → a = 10/10 = 1 m/s²."],ans:"1 m/s² (option B)",tip:"Pushing DOWN raises the normal (mg + F sinθ), so friction grows too. Down-angled pushes fight extra friction — up-angled pulls relieve it."},
{type:"hard",q:"A man pulls a 50 kg crate with 250 N at 37° above the horizontal (μ = 0.3, g = 10 m/s², sin37° = 0.6, cos37° = 0.8). The acceleration is:",options:["1.9 m/s²","2.8 m/s²","4 m/s²","0.9 m/s²"],answer:0,steps:["Normal N = 500 − 250 × 0.6 = 350 N.","Friction = 0.3 × 350 = 105 N; horizontal pull = 250 × 0.8 = 200 N.","Net = 200 − 105 = 95 N → a = 95/50 = 1.9 m/s²."],ans:"1.9 m/s² (option A)",tip:"Up-angled pull REDUCES the normal (mg − F sinθ), so friction drops too. Normal first, friction second, net last."},
{type:"hard",q:"A 1000 kg rocket ejects gas at 2000 m/s relative to it, burning fuel at 50 kg/s. The initial thrust is:",options:["10⁵ N","10⁴ N","10⁶ N","2 × 10⁵ N"],answer:0,steps:["Thrust = v_rel × (dm/dt).","= 2000 × 50.","= 100000 N = 10⁵ N."],ans:"10⁵ N (option A)",tip:"Thrust = exhaust speed × burn rate — mass of the rocket never enters. Option C multiplies by an extra 10."},
{type:"hard",q:"Two blocks of masses m and 3m are connected over a smooth pulley. The acceleration of the system is:",options:["g/4","g/2","g","2g"],answer:1,steps:["Net driving force = 3mg − mg = 2mg.","Total mass = 4m.","a = 2mg/4m = g/2."],ans:"g/2 (option B)",tip:"a = (difference/sum) × g for Atwood pairs. 2m/4m = 1/2 — ratio thinking beats equations."},
{type:"hard",q:"A force F = (3i + 4j) N displaces a body by s = (2i − j) m. The work done is:",options:["2 J","10 J","−2 J","14 J"],answer:0,steps:["W = F·s = (3)(2) + (4)(−1).","= 6 − 4 = 2 J.","Dot product — perpendicular components contribute nothing."],ans:"2 J (option A)",tip:"Work = dot product component-wise: 3×2 + 4×(−1) = 2. Signs on components decide — option B adds magnitudes blindly."},
],
"4. Work, Energy & Power": [
{type:"hard",q:"A horizontal force F pushes two blocks (2 kg on top of 5 kg, μ between them 0.3) on a smooth floor. The maximum F for no slipping is (g = 10 m/s²):",options:["21 N","6 N","15 N","35 N"],answer:0,steps:["Top block accelerates via friction: a_max = μg = 3 m/s².","Both move together at a ≤ 3 m/s².","F_max = (2 + 5) × 3 = 21 N."],ans:"21 N (option A)",tip:"No-slip limit = μg on the carried block; system force = total mass × that acceleration."},
{type:"hard",q:"A wedge of angle 37° accelerates right at 7.5 m/s². A block on it stays at rest relative to the wedge when the coefficient of friction μ is (g = 10 m/s², sin37° = 0.6, cos37° = 0.8):",options:["0","0.25","0.5","1.0"],answer:0,steps:["Pseudo force on the block = ma, horizontal, to the left.","Along the incline: down-slope drive = mg sinθ − ma cosθ = 6m − 6m = 0.","Zero net push along the slope → no friction needed → μ can be 0."],ans:"0 (option A)",tip:"When ma cosθ exactly balances mg sinθ (a = g tanθ = 7.5 here), the incline is self-holding. a = g tanθ is the magic acceleration."},
{type:"hard",q:"A man of mass 60 kg climbs a rope that can sustain 720 N (g = 10 m/s²). The maximum upward acceleration is:",options:["2 m/s²","12 m/s²","7 m/s²","10 m/s²"],answer:0,steps:["T = m(g + a) ≤ 720.","60(10 + a) = 720 → 10 + a = 12.","a_max = 2 m/s²."],ans:"2 m/s² (option A)",tip:"Rope limit on T caps (g + a): 720/60 = 12 → a = 2. Option B forgets to subtract g."},
{type:"hard",q:"A 3 kg block on a smooth 30° incline is connected over a pulley to a hanging 2 kg mass. The acceleration is (g = 10 m/s²):",options:["2 m/s²","1 m/s²","4 m/s²","5 m/s²"],answer:1,steps:["Driving force = 2g − 3g sin30° = 20 − 15 = 5 N.","Total mass = 5 kg.","a = 5/5 = 1 m/s²."],ans:"1 m/s² (option B)",tip:"Net drive = hanging weight minus slope component; divide by TOTAL mass. Incline component 3×10×½ = 15 opposes 20."},
{type:"hard",q:"The work done in lifting a 5 kg mass through 4 m vertically (g = 10 m/s²) is:",options:["20 J","200 J","100 J","50 J"],answer:1,steps:["W = mgh against gravity.","= 5 × 10 × 4.","= 200 J."],ans:"200 J (option B)",tip:"W = mgh for vertical lifts — 5 × 10 × 4 = 200. Option A forgets g."},
{type:"hard",q:"A spring of constant 200 N/m is stretched by 0.1 m. The stored potential energy is:",options:["1 J","2 J","0.5 J","10 J"],answer:0,steps:["U = ½kx².","= ½ × 200 × 0.01.","= 1 J."],ans:"1 J (option A)",tip:"½kx²: the ½ halves 200 × 0.01 = 2 to 1. Option B drops the half."},
{type:"hard",q:"A 2 kg body moving at 6 m/s collides elastically head-on with a stationary 4 kg body. The velocity of the 2 kg body after collision is:",options:["−2 m/s","+2 m/s","−6 m/s","+6 m/s"],answer:0,steps:["v₁' = (m₁ − m₂)u₁/(m₁ + m₂) = (2 − 4) × 6/6.","= −12/6 = −2 m/s.","Negative = rebounds backward."],ans:"−2 m/s (option A)",tip:"Lighter hits heavier stationary → rebounds. (m₁−m₂)/(m₁+m₂) × u gives −2 directly."},
{type:"hard",q:"A machine does 500 J of work in 10 s. Its power is:",options:["5000 W","50 W","5 W","500 W"],answer:1,steps:["P = W/t.","= 500/10.","= 50 W."],ans:"50 W (option B)",tip:"Watts = joules per second: 500/10 = 50. Option A multiplies instead."},
{type:"hard",q:"A bullet of mass 20 g at 300 m/s is stopped by a sandbag, penetrating 30 cm. The average resistive force is:",options:["300 N","3000 N","30000 N","30 N"],answer:1,steps:["KE = ½ × 0.02 × 90000 = 900 J.","F = W/d = 900/0.3.","= 3000 N."],ans:"3000 N (option B)",tip:"KE first (0.02 × 90000/2 = 900), then divide by depth in METRES (0.3). Centimetre-to-metre is the trap."},
{type:"hard",q:"A 1 kW motor lifts water to 10 m. The mass lifted per second (g = 10 m/s²) is:",options:["10 kg","100 kg","1 kg","1000 kg"],answer:0,steps:["Power = mgh/t → 1000 = m × 10 × 10.","m = 1000/100.","= 10 kg/s."],ans:"10 kg (option A)",tip:"P = (mass rate) × g × h: 1000/(10×10) = 10. kW → W (×1000) is the first step."},
],
"5. Rotational Motion": [
{type:"hard",q:"A solid sphere of mass 2 kg and radius 0.5 m rolls without slipping at 4 m/s. Its total kinetic energy is:",options:["16 J","22.4 J","32 J","11.2 J"],answer:1,steps:["Translational KE = ½mv² = ½ × 2 × 16 = 16 J.","Rotational KE = ½Iω² = ½(2/5 mr²)(v/r)² = (1/5)mv² = 6.4 J.","Total = 16 + 6.4 = 22.4 J."],ans:"22.4 J (option B)",tip:"Rolling = translate + spin: (1/2 + 1/5)mv² = 0.7mv² for a solid sphere. Option A forgets rotation."},
{type:"hard",q:"The moment of inertia of a thin rod of mass M and length L about its centre (perpendicular axis) is:",options:["ML²/12","ML²/3","ML²/2","ML²"],answer:0,steps:["Standard result: I_cm = ML²/12.","(About one end: ML²/3 = 4× larger.)","Parallel-axis shift by L/2 converts between them."],ans:"ML²/12 (option A)",tip:"Centre ML²/12 vs end ML²/3 — factor 4 apart. Option B is the END value; read the axis location."},
{type:"hard",q:"A disc of mass M and radius R has moment of inertia about its central perpendicular axis equal to:",options:["MR²/2","MR²","2MR²/5","2MR²/3"],answer:0,steps:["Standard result for a solid disc: I = MR²/2.","(Ring: MR²; solid sphere: 2MR²/5.)","Memorise the family: ring 1, disc 1/2, sphere 2/5 (all ×MR²)."],ans:"MR²/2 (option A)",tip:"Ring MR² → disc MR²/2 → sphere 2MR²/5: the coefficients shrink as mass concentrates centrally. Option B is the ring."},
{type:"hard",q:"A particle has angular momentum L = 10 units and rotational KE = 5 units about an axis. Its moment of inertia is:",options:["5 units","10 units","2 units","25 units"],answer:1,steps:["KE_rot = L²/(2I).","5 = 100/(2I) → 2I = 20.","I = 10 units."],ans:"10 units (option B)",tip:"I = L²/(2KE) in one rearrangement: 100/10 = 10. Option A halves instead of the formula's doubling."},
{type:"hard",q:"A solid cylinder rolls down an incline of height h. Its speed at the bottom is:",options:["√(2gh)","√(4gh/3)","√(gh)","√(3gh/2)"],answer:1,steps:["mgh = ½mv² + ½Iω² with I = ½mR², ω = v/R.","mgh = ½mv² + ¼mv² = ¾mv².","v² = 4gh/3 → v = √(4gh/3)."],ans:"√(4gh/3) (option B)",tip:"Rolling split: cylinder keeps 1/3 of energy in spin (sphere 2/7, ring 1/2). v = √(2gh/(1+k)) with k = 1/2."},
{type:"hard",q:"Two satellites A and B orbit at radii R and 4R. The ratio of their orbital speeds v_A : v_B is:",options:["2:1","1:2","4:1","1:4"],answer:0,steps:["v = √(GM/r), so v ∝ 1/√r.","Ratio = √(4R/R) = √4 = 2.","v_A : v_B = 2:1 (inner satellite faster)."],ans:"2:1 (option A)",tip:"v ∝ 1/√r: radius ×4 → speed ÷2. Inner always faster — higher, slower, longer period."},
{type:"hard",q:"The angular momentum of a 2 kg mass moving at 5 m/s in a circle of radius 3 m about the centre is:",options:["30 kg·m²/s","15 kg·m²/s","10 kg·m²/s","45 kg·m²/s"],answer:0,steps:["L = mvr.","= 2 × 5 × 3.","= 30 kg·m²/s."],ans:"30 kg·m²/s (option A)",tip:"L = mvr for circular motion — 2 × 5 × 3 = 30. Direction by right-hand rule, out of the plane."},
{type:"hard",q:"A torque of 10 N·m acts on a wheel of moment of inertia 2 kg·m². Its angular acceleration is:",options:["5 rad/s²","20 rad/s²","0.2 rad/s²","12 rad/s²"],answer:0,steps:["τ = Iα.","α = 10/2.","= 5 rad/s²."],ans:"5 rad/s² (option A)",tip:"τ = Iα is F = ma for rotation: 10/2 = 5. Option B multiplies instead."},
{type:"hard",q:"A ring and a disc of equal mass and radius roll down the same incline. Which reaches first?",options:["the disc","the ring","both together","depends on mass"],answer:0,steps:["Acceleration a = g sinθ/(1 + k) with k = I/mR².","Ring k = 1, disc k = 1/2 → disc accelerates faster.","Smaller k (mass nearer centre) always wins."],ans:"the disc (option A)",tip:"Race rule: smallest I/mR² wins — solid sphere beats disc beats ring. Mass and radius cancel entirely."},
{type:"hard",q:"The direction of angular velocity of a clockwise-rotating wheel (viewed from the left) is:",options:["to the right","to the left","up","down"],answer:1,steps:["Right-hand rule: curl fingers with rotation, thumb gives ω.","Clockwise viewed from the left → thumb points left.","Axial vector, not in the plane of rotation."],ans:"to the left (option B)",tip:"Right-hand rule decides axial directions; clockwise from one side is anticlockwise from the other — state the viewpoint."},
{type:"hard",q:"A figure skater pulls in her arms, halving her moment of inertia. Her angular speed:",options:["halves","doubles","quadruples","stays same"],answer:1,steps:["No external torque → L = Iω conserved.","I → I/2.","ω → 2ω to keep Iω constant."],ans:"doubles (option B)",tip:"Iω = constant: halve I, double ω. KE rises (work done pulling in) — energy is NOT conserved here."},
{type:"hard",q:"The SI unit of angular momentum is:",options:["kg·m²/s","kg·m/s²","N·m","J·s⁻¹"],answer:0,steps:["L = mvr → kg × m/s × m.","= kg·m²/s.","Same as Planck's constant h (action)."],ans:"kg·m²/s (option A)",tip:"mvr gives kg·m²/s; option C (N·m = joule) is torque/energy — same dimensions as energy, different unit context."},
{type:"hard",q:"Two satellites A and B orbit at radii R and 4R. The ratio of their orbital speeds v_A : v_B is:",options:["2:1","1:2","4:1","1:4"],answer:0,steps:["v = √(GM/r) → v ∝ 1/√r.","Ratio = √(4R/R) = √4 = 2.","v_A : v_B = 2:1 (inner satellite faster)."],ans:"2:1 (option A)",tip:"v ∝ 1/√r: radius ×4 → speed ÷2. Inner always faster — higher, slower, longer period."},
{type:"hard",q:"A hollow sphere (I = 2MR²/3) rolls down an incline. Its acceleration is:",options:["3g sinθ/5","g sinθ/2","5g sinθ/7","g sinθ"],answer:0,steps:["a = g sinθ/(1 + k), k = 2/3.","= g sinθ/(5/3).","= 3g sinθ/5."],ans:"3g sinθ/5 (option A)",tip:"a = g sinθ/(1+k): ring k=1 → g sinθ/2; disc k=1/2 → 2g sinθ/3; sphere k=2/5 → 5g sinθ/7. Memorise the ladder."},
{type:"hard",q:"A 60 kg man stands at the edge of a 120 kg stationary turntable (disc, R = 2 m) and starts walking along the rim tangentially. The turntable:",options:["starts rotating opposite to his walk","stays still","moves linearly","topples"],answer:0,steps:["No external torque about the centre → total L stays zero.","The man's tangential motion carries angular momentum one way.","The disc must rotate the opposite way to keep total L = 0."],ans:"starts rotating opposite to his walk (option A)",tip:"Action–reaction in rotation: walk one way, platform spins the other. Total L = 0 is the whole argument."},
{type:"hard",q:"The centre of mass of a uniform rod lies at its:",options:["one end","midpoint","quarter point","outside the rod"],answer:1,steps:["Symmetry: mass distributed evenly about the centre.","Centre of mass = geometric centre for uniform bodies.","Midpoint."],ans:"midpoint (option B)",tip:"Uniform + symmetric → COM at the symmetry centre. Option A is the COM of a non-uniform (triangular) lamina measured from base — different shape."},
{type:"hard",q:"A couple consists of:",options:["two equal opposite parallel forces","a single force","two equal same-direction forces","force plus mass"],answer:0,steps:["A couple = F and −F separated by distance d.","Net force zero, net torque = Fd.","Pure rotation, no translation."],ans:"two equal opposite parallel forces (option A)",tip:"Couple → torque only (Fd), no net force. Option C gives 2F net force — that translates, not just rotates."},
],
"6. Gravitation": [
{type:"hard",q:"The escape velocity from Earth's surface is approximately:",options:["7.9 km/s","11.2 km/s","3.1 km/s","22.4 km/s"],answer:1,steps:["v_e = √(2GM/R) = √(2gR).","= √(2 × 9.8 × 6.4 × 10⁶) ≈ 11.2 × 10³ m/s.","11.2 km/s (orbital velocity 7.9 × √2)."],ans:"11.2 km/s (option B)",tip:"v_escape = √2 × v_orbital = 1.414 × 7.9 = 11.2. Option A is the orbital (first cosmic) velocity."},
{type:"hard",q:"A satellite orbits at height R above Earth's surface (R = Earth's radius). Its orbital speed is:",options:["7.9 km/s","5.6 km/s","11.2 km/s","3.9 km/s"],answer:1,steps:["v = √(GM/2R) = v_surface/√2.","= 7.9/1.414.","≈ 5.6 km/s."],ans:"5.6 km/s (option B)",tip:"Double the orbital radius → divide speed by √2. 7.9/1.414 = 5.6 — one division."},
{type:"hard",q:"The time period of a geostationary satellite is:",options:["12 h","24 h","365 days","90 min"],answer:1,steps:["Geostationary = fixed over one point on the equator.","Must match Earth's rotation period.","24 h."],ans:"24 h (option B)",tip:"Geo-stationary = Earth's 24 h spin. Option D (90 min) is low-orbit period; option A is GPS semi-synchronous."},
{type:"hard",q:"If the radius of Earth's orbit around the Sun were doubled, the year would become:",options:["2 years","2√2 years","4 years","√2 years"],answer:1,steps:["Kepler III: T² ∝ r³.","T' = T × 2^(3/2) = 2√2 years.","≈ 2.83 years."],ans:"2√2 years (option B)",tip:"T ∝ r^1.5: double r → ×2√2, not ×2. The 3/2 power is the whole question — option A forgets it."},
{type:"hard",q:"The acceleration due to gravity at a depth d below Earth's surface (d << R) varies as:",options:["decreases linearly with d","increases with d","stays constant","becomes zero immediately"],answer:0,steps:["g_d = g(1 − d/R).","Linear decrease with depth.","Zero only at the centre (d = R)."],ans:"decreases linearly with d (option A)",tip:"Inside Earth: g ∝ (R−d), linear fall. Outside: g ∝ 1/r². Depth vs altitude are mirror-image traps."},
{type:"hard",q:"The potential energy of a satellite of mass m in orbit of radius r is:",options:["−GMm/r","−GMm/2r","+GMm/r","−2GMm/r"],answer:0,steps:["PE = −GMm/r by definition (zero at infinity).","Total energy E = −GMm/2r; KE = +GMm/2r.","Option B is the TOTAL energy, not PE."],ans:"−GMm/r (option A)",tip:"PE = −GMm/r; KE = +GMm/2r; E = −GMm/2r. The 1:−2:−1 fingerprint — option B is E, the classic mix-up."},
{type:"hard",q:"The weight of a body at the centre of the Earth is:",options:["maximum","zero","same as surface","half of surface"],answer:1,steps:["g = 0 at the centre (mass pulls equally all ways).","Weight = mg = 0.","Mass stays the same; weight vanishes."],ans:"zero (option B)",tip:"g_centre = 0 → weightless at the centre. Weight needs g; mass never changes."},
{type:"hard",q:"Two planets have densities in ratio 1:2 and radii in ratio 3:1. The ratio of g on their surfaces is:",options:["3:2","9:2","1:6","3:1"],answer:0,steps:["g = (4/3)πGρR → g ∝ ρR.","Ratio = (1 × 3)/(2 × 1) = 3/2.","3:2."],ans:"3:2 (option A)",tip:"g ∝ ρR combines both ratios multiplicatively: (1×3):(2×1) = 3:2. Density × radius, one line."},
{type:"hard",q:"The gravitational field inside a uniform spherical shell is:",options:["GM/r²","zero","GM/2r²","maximum at centre"],answer:1,steps:["Shell theorem: no net force inside a hollow shell.","Field = 0 everywhere inside.","Potential is constant (−GM/R) inside."],ans:"zero (option B)",tip:"Inside a shell: field 0, potential constant. Inside a SOLID sphere: field ∝ r. Shell vs solid is the distinction."},
{type:"hard",q:"A satellite in circular orbit has KE = E₀. Its total mechanical energy is:",options:["−E₀","−2E₀","+E₀","zero"],answer:0,steps:["KE:PE:E = 1:−2:−1.","KE = E₀ → E = −E₀.","(PE = −2E₀.)"],ans:"−E₀ (option A)",tip:"Circular orbit fingerprint 1:−2:−1: E = −KE always. Option B is PE, the double-trap."},
],
"7. Properties of Solids & Liquids": [
/* @@P07A@@ */
/* @@P07B@@ */
/* @@P07C@@ */
/* @@P07D@@ */
/* @@P07E@@ */
],
"8. Thermodynamics": [
/* @@P08A@@ */
/* @@P08B@@ */
/* @@P08C@@ */
/* @@P08D@@ */
/* @@P08E@@ */
],
"9. Kinetic Theory of Gases": [
/* @@P09A@@ */
/* @@P09B@@ */
/* @@P09C@@ */
/* @@P09D@@ */
/* @@P09E@@ */
],
"10. Oscillations & Waves": [
/* @@P10A@@ */
/* @@P10B@@ */
/* @@P10C@@ */
/* @@P10D@@ */
/* @@P10E@@ */
],
"11. Electrostatics": [
{type:"hard",q:"Two point charges +4 μC and −4 μC are placed 0.2 m apart. The electric field at the midpoint is:",options:["3.6 × 10⁶ N/C toward the negative charge","1.8 × 10⁶ N/C toward the positive charge","zero","7.2 × 10⁶ N/C toward the negative charge"],answer:3,steps:["At midpoint (r = 0.1 m), field from each charge: E = kq/r² = 9 × 10⁹ × 4 × 10⁻⁶/0.01 = 3.6 × 10⁶ N/C.","Field of a positive charge points AWAY from it; field of a negative charge points TOWARD it — both point toward the −4 μC charge.","Both add: 3.6 × 10⁶ + 3.6 × 10⁶ = 7.2 × 10⁶ N/C toward the negative charge."],ans:"7.2 × 10⁶ N/C toward the negative charge (option D)",tip:"Dipole midpoint: fields REINFORCE (never cancel). Each contributes kq/(d/2)² — the halved distance quadruples each field."},
{type:"hard",q:"The electric field at the centre of a uniformly charged ring of radius R and total charge Q is:",options:["kQ/R²","2kQ/R²","zero","kQ/2R²"],answer:2,steps:["Every charge element has a diametrically opposite twin.","Field contributions cancel pairwise by symmetry.","Net field = zero (though the potential there is kQ/R)."],ans:"zero (option C)",tip:"Symmetry kills centre-field for rings, shells and spheres; centre POTENTIAL stays maximum. Field zero ≠ potential zero."},
{type:"hard",q:"An electric dipole of moment p is placed in a uniform field E. The torque and potential energy are:",options:["τ = pE sinθ, U = −pE cosθ","τ = pE cosθ, U = pE sinθ","τ = pE, U = zero","τ = zero, U = pE"],answer:0,steps:["Torque on a dipole: τ = p × E, magnitude pE sinθ.","Potential energy: U = −p·E = −pE cosθ.","Stable equilibrium at θ = 0 (U minimum = −pE)."],ans:"τ = pE sinθ, U = −pE cosθ (option A)",tip:"Torque ∝ sinθ (cross product), energy ∝ −cosθ (dot product with minus). Maximum torque at 90°, minimum energy at 0°."},
/* @@P11B@@ */
/* @@P11C@@ */
/* @@P11D@@ */
/* @@P11E@@ */
],
"12. Current Electricity": [
{type:"hard",q:"A wire of length 2 m and area 10⁻⁶ m² has resistance 4 Ω. Its resistivity is:",options:["2 × 10⁻⁶ Ω·m","8 × 10⁻⁶ Ω·m","2 × 10⁻⁷ Ω·m","4 × 10⁻⁶ Ω·m"],answer:0,steps:["R = ρl/A → ρ = RA/l.","= 4 × 10⁻⁶/2.","= 2 × 10⁻⁶ Ω·m."],ans:"2 × 10⁻⁶ Ω·m (option A)",tip:"ρ = RA/l: 4 × 10⁻⁶ ÷ 2 = 2 × 10⁻⁶. Option B multiplies by length instead."},
{type:"hard",q:"Two resistors 2 Ω and 3 Ω in parallel are connected to 6 V. The total current is:",options:["5 A","2.5 A","1 A","6 A"],answer:0,steps:["R_eq = (2 × 3)/5 = 1.2 Ω.","I = V/R = 6/1.2.","= 5 A."],ans:"5 A (option A)",tip:"Parallel: product/sum = 6/5 = 1.2 Ω, then 6/1.2 = 5 A. Option B uses series resistance."},
{type:"hard",q:"Three 2 Ω resistors in series are connected to 12 V. The current is:",options:["2 A","6 A","12 A","1 A"],answer:0,steps:["R = 2 + 2 + 2 = 6 Ω.","I = 12/6.","= 2 A."],ans:"2 A (option A)",tip:"Series adds directly: 6 Ω total, 12/6 = 2 A. Same current everywhere in series."},
{type:"hard",q:"A cell of emf 1.5 V and internal resistance 0.5 Ω is connected to 2.5 Ω. The terminal voltage is:",options:["1.5 V","1.25 V","1.0 V","0.5 V"],answer:1,steps:["I = E/(R + r) = 1.5/3 = 0.5 A.","V = E − Ir = 1.5 − 0.25.","= 1.25 V."],ans:"1.25 V (option B)",tip:"V = E − Ir under load: 1.5 − 0.25 = 1.25. Option A is the open-circuit emf."},
{type:"hard",q:"A 10 Ω and a 15 Ω resistor in parallel give equivalent resistance:",options:["25 Ω","6 Ω","5 Ω","12.5 Ω"],answer:1,steps:["1/R = 1/10 + 1/15 = (3 + 2)/30.","= 5/30 = 1/6.","R = 6 Ω."],ans:"6 Ω (option B)",tip:"Parallel: (10×15)/(10+15) = 150/25 = 6. Option A adds — series thinking in a parallel question."},
{type:"hard",q:"The power dissipated in a 10 Ω resistor carrying 2 A is:",options:["20 W","40 W","200 W","4 W"],answer:1,steps:["P = I²R.","= 4 × 10.","= 40 W."],ans:"40 W (option B)",tip:"I²R = 4 × 10 = 40. Option A computes VI with V = 10 (wrong V); find V = IR = 20 first if using VI."},
{type:"hard",q:"A potentiometer wire 10 m long has resistance 5 Ω. With a 2 V driver (no series resistor), the potential gradient is:",options:["0.2 V/m","0.1 V/m","2 V/m","0.02 V/m"],answer:0,steps:["The full 2 V drops across the 10 m wire (no series resistor).","Gradient = total drop/length = 2/10.","= 0.2 V/m."],ans:"0.2 V/m (option A)",tip:"No series resistor → whole emf sits on the wire: emf/length = 0.2 V/m. Current (0.4 A) is never needed."},
{type:"hard",q:"In a metre bridge, the balance point is at 25 cm from the left. If the left gap has 2 Ω, the right-gap resistance is:",options:["6 Ω","2 Ω","0.5 Ω","8 Ω"],answer:0,steps:["R/S = l/(100 − l) = 25/75 = 1/3.","S = 3R = 6 Ω.","(Unknown on the longer side, as expected.)"],ans:"6 Ω (option A)",tip:"R/S = l/(100−l): 25/75 = 1/3 → right = 3 × left. Balance near an end means a 3:1 ratio."},
{type:"hard",q:"The drift velocity in a copper wire (n = 8.5 × 10²⁸ m⁻³) carrying 1.7 A through 1 mm² is approximately:",options:["1.25 × 10⁻⁴ m/s","1.25 × 10⁻³ m/s","1.25 × 10⁻⁵ m/s","12.5 m/s"],answer:0,steps:["v = I/(neA) = 1.7/(8.5 × 10²⁸ × 1.6 × 10⁻¹⁹ × 10⁻⁶).","Denominator = 8.5 × 1.6 × 10³ = 1.36 × 10⁴.","v = 1.7/1.36 × 10⁴ = 1.25 × 10⁻⁴ m/s."],ans:"1.25 × 10⁻⁴ m/s (option A)",tip:"v = I/(neA): powers 10^(28−19−6) = 10³ in the denominator force ~10⁻⁴ m/s. Any m/s-scale option is absurd."},
],
"13. Magnetic Effects of Current & Magnetism": [
{type:"hard",q:"A circular loop of radius R carries current I. The torque on it in a field B parallel to its plane is maximum and equals:",options:["πR²IB","2πRIB","zero","πR²IB/2"],answer:0,steps:["τ = NIAB sinθ with N = 1, A = πR².","Plane parallel to B → normal perpendicular → θ = 90°.","τ_max = πR²IB."],ans:"πR²IB (option A)",tip:"Area πR² times IB at θ = 90°. Option B confuses area with circumference 2πR."},
{type:"hard",q:"A proton of mass m and charge q enters a uniform field B perpendicularly with speed v. The radius of its path is:",options:["mv/qB","qB/mv","mv²/qB","qmv/B"],answer:0,steps:["Magnetic force = centripetal: qvB = mv²/r.","Cancel one v: qB = mv/r.","r = mv/qB."],ans:"mv/qB (option A)",tip:"qvB = mv²/r → r = mv/qB. Bigger momentum → bigger circle; stronger field → tighter circle."},
{type:"hard",q:"A straight wire carries 5 A. The field at 0.1 m from it is:",options:["10⁻⁵ T","10⁻⁶ T","10⁻⁴ T","5 × 10⁻⁶ T"],answer:0,steps:["B = μ₀I/2πr.","= (4π × 10⁻⁷ × 5)/(2π × 0.1).","= 10⁻⁵ T."],ans:"10⁻⁵ T (option A)",tip:"μ₀/2π = 2 × 10⁻⁷: B = 2×10⁻⁷×I/r = 2×10⁻⁷×50 = 10⁻⁵. Memorise 2×10⁻⁷."},
{type:"hard",q:"An electron (e, m) moves perpendicular to B with speed v. Its time period is:",options:["2πm/eB","eB/2πm","2πeB/m","m/eB"],answer:0,steps:["r = mv/eB and T = 2πr/v.","T = 2πm/eB.","Independent of v (cyclotron principle)."],ans:"2πm/eB (option A)",tip:"T = 2πm/qB — no v, no r. Faster particles circle bigger, not quicker."},
{type:"hard",q:"A circular loop of radius 0.1 m carries 5 A. The field at its centre is:",options:["π × 10⁻⁵ T","10⁻⁵ T","5π × 10⁻⁶ T","2π × 10⁻⁵ T"],answer:0,steps:["B = μ₀I/2R = (4π × 10⁻⁷ × 5)/0.2.","= 100π × 10⁻⁷ = π × 10⁻⁵ T.","≈ 3.14 × 10⁻⁵ T."],ans:"π × 10⁻⁵ T (option A)",tip:"μ₀/2R = 2π × 10⁻⁶ here: ×5 A = π × 10⁻⁵. Keep π symbolic — options do too."},
{type:"hard",q:"The force per unit length between two parallel wires 0.1 m apart carrying 10 A each is:",options:["2 × 10⁻⁴ N/m","2 × 10⁻⁵ N/m","10⁻⁴ N/m","4 × 10⁻⁴ N/m"],answer:0,steps:["F/l = μ₀I₁I₂/2πd.","= (4π × 10⁻⁷ × 100)/(2π × 0.1).","= 2 × 10⁻⁴ N/m (attractive if same direction)."],ans:"2 × 10⁻⁴ N/m (option A)",tip:"μ₀/2π = 2×10⁻⁷: F/l = 2×10⁻⁷×I₁I₂/d = 2×10⁻⁷×1000 = 2×10⁻⁴. Same direction attracts."},
{type:"hard",q:"A solenoid of length 0.5 m with 1000 turns carries 2 A. The field inside is:",options:["1.6π mT","5.0 mT","16 mT","0.5 mT"],answer:1,steps:["B = μ₀nI with n = 1000/0.5 = 2000 m⁻¹.","= 4π × 10⁻⁷ × 2000 × 2 = 16π × 10⁻⁴.","= 5.03 × 10⁻³ T ≈ 5.0 mT."],ans:"5.0 mT (option B)",tip:"n = turns per METRE (2000 here), not total turns. Option A keeps π symbolic but misplaces the decimal."},
{type:"hard",q:"The magnetic moment of a 10 cm × 10 cm loop with 100 turns carrying 1 A is:",options:["1 A·m²","0.1 A·m²","10 A·m²","100 A·m²"],answer:0,steps:["M = NIA = 100 × 1 × 0.01.","= 1 A·m².","(Area: 0.1 × 0.1 = 0.01 m².)"],ans:"1 A·m² (option A)",tip:"cm → m first: 10 cm = 0.1 m, area 0.01 m². Option C skips the conversion (uses 1 m²)."},
{type:"hard",q:"A charged particle enters a magnetic field at 30° to B. Its path is:",options:["a circle","a helix","a straight line","a parabola"],answer:1,steps:["Parallel component → uniform drift along B.","Perpendicular component → circular motion.","Combined = helix."],ans:"a helix (option B)",tip:"Split v into parallel (drift) + perpendicular (circle): helix. 90° gives a pure circle; 0° a straight line."},
{type:"hard",q:"The cyclotron frequency of a proton (m = 1.67 × 10⁻²⁷ kg) in B = 1 T is approximately:",options:["9.6 × 10⁷ rad/s","1.6 × 10⁻¹⁹ rad/s","6 × 10²³ rad/s","10⁷ Hz"],answer:0,steps:["ω = qB/m = 1.6 × 10⁻¹⁹ × 1/(1.67 × 10⁻²⁷).","= 0.958 × 10⁸.","≈ 9.6 × 10⁷ rad/s."],ans:"9.6 × 10⁷ rad/s (option A)",tip:"ω = qB/m: 1.6/1.67 × 10⁸ ≈ 0.96 × 10⁸. Option D confuses rad/s with Hz (÷2π)."},
],
"14. EMI & Alternating Currents": [
{type:"hard",q:"The induced emf in a coil of 100 turns with flux changing at 0.02 Wb/s is:",options:["2 V","0.02 V","0.2 V","50 V"],answer:0,steps:["ε = −N(dΦ/dt).","= 100 × 0.02.","= 2 V (magnitude)."],ans:"2 V (option A)",tip:"Multiply by N = 100: 100 × 0.02 = 2. Option B forgets the turns."},
{type:"hard",q:"A magnet is dropped through a copper ring. The induced current:",options:["opposes the fall (slows it)","speeds the fall","is zero","reverses gravity"],answer:0,steps:["Lenz's law: induced effects oppose the change.","Approaching pole is repelled; receding pole is attracted.","Both phases brake the fall (electromagnetic damping)."],ans:"opposes the fall (option A)",tip:"Lenz = opposition always: fall is braked both entering and leaving. Option C claims no flux change — false."},
{type:"hard",q:"An AC source v = 100sin(100πt) has rms voltage and frequency:",options:["70.7 V, 50 Hz","100 V, 100 Hz","70.7 V, 100 Hz","141 V, 50 Hz"],answer:0,steps:["V_rms = V₀/√2 = 100/1.414 = 70.7 V.","ω = 100π → f = ω/2π = 50 Hz.","70.7 V, 50 Hz."],ans:"70.7 V, 50 Hz (option A)",tip:"V₀/√2 for rms; ω/2π for frequency. Option B reports peak voltage as rms."},
{type:"hard",q:"In a purely capacitive AC circuit, current _____ voltage by:",options:["lags, 90°","leads, 90°","leads, 45°","is in phase"],answer:1,steps:["I = C(dV/dt): current peaks when voltage changes fastest.","For sine voltage, current is a cosine — 90° ahead.","Leads by 90° (ICE: I before E in Capacitor)."],ans:"leads, 90° (option B)",tip:"ICE mnemonic: I leads E in C; ELI: E leads I in L. Capacitor → current first by a quarter cycle."},
{type:"hard",q:"At resonance in a series LCR circuit, the impedance is:",options:["R","zero","infinite","√(R² + X²)"],answer:0,steps:["X_L = X_C → net reactance zero.","Z = √(R² + 0) = R (minimum).","Current maximum = V/R."],ans:"R (option A)",tip:"Resonance cancels reactances: Z = R minimum, current maximum, power factor 1. Option B confuses with parallel-tank current."},
{type:"hard",q:"A transformer steps 220 V to 22 V. Its turns ratio N_p:N_s is:",options:["1:10","10:1","1:1","100:1"],answer:1,steps:["V_p/V_s = N_p/N_s.","= 220/22 = 10.","N_p:N_s = 10:1."],ans:"10:1 (option B)",tip:"Voltage ratio = turns ratio: 220/22 = 10. Step-DOWN means more primary turns — option A inverts."},
{type:"hard",q:"The resonant frequency of an LC circuit with L = 1 mH and C = 40 μF is approximately:",options:["796 Hz","398 Hz","1592 Hz","250 Hz"],answer:0,steps:["f = 1/(2π√(LC)).","LC = 10⁻³ × 40 × 10⁻⁶ = 4 × 10⁻⁸; √ = 2 × 10⁻⁴.","f = 1/(2π × 2 × 10⁻⁴) = 10⁴/(4π) ≈ 796 Hz."],ans:"796 Hz (option A)",tip:"√(LC) = 2×10⁻⁴ s here; f = 1/(2π × 2×10⁻⁴) = 10⁴/4π. Memorise 1/4π ≈ 0.0796."},
{type:"hard",q:"The energy stored in a 2 H inductor carrying 3 A is:",options:["9 J","18 J","6 J","12 J"],answer:0,steps:["U = ½LI².","= ½ × 2 × 9.","= 9 J."],ans:"9 J (option A)",tip:"½ × 2 × 9 = 9. Option B drops the half — the eternal inductor/capacitor trap."},
{type:"hard",q:"An LR circuit has L = 4 H, R = 2 Ω. Its time constant is:",options:["2 s","0.5 s","8 s","4 s"],answer:0,steps:["τ = L/R.","= 4/2.","= 2 s."],ans:"2 s (option A)",tip:"τ = L/R (henry/ohm = second). Option C multiplies — resistance belongs in the denominator."},
],
"15. Electromagnetic Waves": [
{type:"hard",q:"The displacement current flows through:",options:["conductors only","the gap between capacitor plates","resistors only","superconductors"],answer:1,steps:["Maxwell: changing E-field acts as current.","Between charging capacitor plates, D-field changes.","Displacement current = ε₀dΦ_E/dt there."],ans:"the gap between capacitor plates (option B)",tip:"Displacement current lives where conduction current cannot — the capacitor gap. It completes Ampere's loop."},
{type:"hard",q:"Which wave is NOT an electromagnetic wave?",options:["X-rays","sound waves","gamma rays","microwaves"],answer:1,steps:["Sound needs a material medium (mechanical).","EM waves travel through vacuum.","X-rays, gamma, microwaves are all EM."],ans:"sound waves (option B)",tip:"Mechanical vs EM is the divide: sound needs air; EM needs nothing. Option A–D minus B are all EM spectrum members."},
{type:"hard",q:"The speed of EM waves in vacuum is:",options:["3 × 10⁸ m/s","3 × 10⁶ m/s","1.5 × 10⁸ m/s","infinite"],answer:0,steps:["c = 1/√(ε₀μ₀).","= 3 × 10⁸ m/s.","Same for all frequencies (dispersion-free vacuum)."],ans:"3 × 10⁸ m/s (option A)",tip:"c = 3×10⁸ m/s for every EM wave — frequency changes λ, never c. Option C halves it (glass speed)."},
{type:"hard",q:"Greenhouse gases absorb mainly:",options:["ultraviolet","infrared","X-rays","visible"],answer:1,steps:["Earth re-radiates absorbed sunlight as IR.","CO₂/H₂O/CH₄ absorb IR bands.","Trapped IR warms the surface."],ans:"infrared (option B)",tip:"Sun in (visible) → Earth out (infrared) → gases trap IR. Ozone handles UV — different gas, different band."},
{type:"hard",q:"Ozone layer absorbs:",options:["infrared","ultraviolet","microwaves","radio waves"],answer:1,steps:["O₃ absorbs UV (Hartley band, ~255 nm).","Protects life from UV-B/C.","IR is absorbed by CO₂/H₂O instead."],ans:"ultraviolet (option B)",tip:"Ozone ↔ UV is a fixed pair; greenhouse gases ↔ IR is the other. Swapping them is the trap."},
{type:"hard",q:"The frequency range of visible light is approximately:",options:["10¹⁴–10¹⁵ Hz","10⁹ Hz","10¹⁸ Hz","10⁶ Hz"],answer:0,steps:["Visible λ: 400–700 nm.","f = c/λ ≈ 4.3–7.5 × 10¹⁴ Hz.","10¹⁴–10¹⁵ Hz band."],ans:"10¹⁴–10¹⁵ Hz (option A)",tip:"c/λ with λ ~ 500 nm gives ~6×10¹⁴ Hz. Options B (micro), C (X-ray) are orders away."},
{type:"hard",q:"Microwaves are used in radar because they:",options:["have long wavelength","reflect from small objects and pass through clouds","are visible","are sound waves"],answer:1,steps:["cm-wavelength reflects off metre-scale targets.","Penetrates fog/clouds better than visible light.","Radar = detection via reflected microwaves."],ans:"reflect from small objects and pass through clouds (option B)",tip:"Wavelength ~ target size reflects well; microwaves beat fog where visible light dies. Option A inverts the wavelength logic."},
{type:"hard",q:"The energy of a photon of wavelength 600 nm is approximately:",options:["2.07 eV","3.1 eV","1.24 eV","6.2 eV"],answer:0,steps:["E = 1240/λ(nm).","= 1240/600.","≈ 2.07 eV."],ans:"2.07 eV (option A)",tip:"1240/λ(nm) in eV: 1240/600 ≈ 2.07. Option B is 400 nm light — shorter λ, higher E."},
{type:"hard",q:"In the EM spectrum, the wave with the LONGEST wavelength is:",options:["gamma rays","radio waves","X-rays","ultraviolet"],answer:1,steps:["Order by λ: radio > micro > IR > visible > UV > X > gamma.","Radio waves: metres to kilometres.","Gamma: picometres."],ans:"radio waves (option B)",tip:"Radio longest, gamma shortest — the spectrum ladder never changes. Option A is the shortest, the mirror trap."},
{type:"hard",q:"A 100 W bulb emits 2% as visible light (~550 nm). The number of photons per second is approximately:",options:["5.5 × 10¹⁸","5.5 × 10¹⁹","3 × 10⁸","10¹⁵"],answer:0,steps:["Visible power = 2 W.","Photon energy = hc/λ = 6.63×10⁻³⁴ × 3×10⁸/(5.5×10⁻⁷) = 3.6 × 10⁻¹⁹ J.","Rate = 2/(3.6 × 10⁻¹⁹) ≈ 5.5 × 10¹⁸ s⁻¹."],ans:"5.5 × 10¹⁸ (option A)",tip:"Power ÷ photon energy: 2/(3.6×10⁻¹⁹) = 5.5×10¹⁸. Option B uses 100 W (ignores the 2%)."},
],
"16. Optics": [
{type:"hard",q:"A concave mirror of focal length 10 cm forms an image of an object placed 30 cm in front of it. The image distance and nature are:",options:["15 cm behind the mirror, virtual","15 cm in front of the mirror, real","30 cm in front, real","30 cm behind, virtual"],answer:1,steps:["Mirror formula with sign convention: u = −30 cm, f = −10 cm.","1/v = 1/f − 1/u = −1/10 + 1/30 = −2/30.","v = −15 cm → 15 cm in front of the mirror, real and inverted."],ans:"15 cm in front of the mirror, real (option B)",tip:"Cartesian signs (u, f negative) keep mirrors consistent. Object beyond C (30 > 20) → image between F and C, diminished."},
{type:"hard",q:"A concave mirror of focal length 10 cm forms an image of an object placed 30 cm in front of it. The image distance and nature are:",options:["15 cm behind the mirror, virtual","15 cm in front of the mirror, real","30 cm in front, real","30 cm behind, virtual"],answer:1,steps:["Mirror formula with sign convention: u = −30 cm, f = −10 cm.","1/v = 1/f − 1/u = −1/10 + 1/30 = −2/30.","v = −15 cm → 15 cm in front of the mirror, real and inverted."],ans:"15 cm in front of the mirror, real (option B)",tip:"Cartesian signs (u, f negative) keep mirrors consistent. Object beyond C (30 > 20) → image between F and C, diminished."},
{type:"hard",q:"An object 2 cm tall is placed 20 cm from a concave mirror of focal length 10 cm. The image height is:",options:["2 cm, erect","2 cm, inverted","4 cm, inverted","1 cm, erect"],answer:1,steps:["u = −20 = 2f → image at v = −20 (same size).","Magnification m = −v/u = −(−20)/(−20) = −1.","Height = 2 cm, inverted (m = −1)."],ans:"2 cm, inverted (option B)",tip:"Object at C (2F) → image at C, same size, inverted. m = −v/u = −1 is the check."},
{type:"hard",q:"A convex lens of focal length 20 cm forms an image of an object at 30 cm. The image is:",options:["real, at 60 cm","virtual, at 60 cm","real, at 15 cm","virtual, at 15 cm"],answer:0,steps:["1/v = 1/f − 1/u... lens formula 1/v − 1/u = 1/f with u = −30, f = +20.","1/v = 1/20 − 1/30 = 1/60.","v = +60 cm → real, on the opposite side."],ans:"real, at 60 cm (option A)",tip:"u = −30 (2F would be −40; object between F and 2F) → image beyond 2F, magnified, real. 1/20 − 1/30 = 1/60."},
{type:"hard",q:"Two thin lenses of focal lengths +10 cm and −15 cm in contact have equivalent focal length:",options:["+30 cm","−30 cm","+6 cm","−6 cm"],answer:0,steps:["1/F = 1/f₁ + 1/f₂ = 1/10 − 1/15 = (3 − 2)/30.","= 1/30.","F = +30 cm (converging)."],ans:"+30 cm (option A)",tip:"Add reciprocal focal lengths directly: 1/10 − 1/15 = 1/30. Stronger convex wins → net converging."},
{type:"hard",q:"In Young's double-slit experiment with λ = 600 nm, d = 0.5 mm, D = 1.5 m, the fringe width is:",options:["1.8 mm","0.9 mm","3.6 mm","0.45 mm"],answer:0,steps:["β = λD/d.","= (6 × 10⁻⁷ × 1.5)/(5 × 10⁻⁴).","= 1.8 × 10⁻³ m = 1.8 mm."],ans:"1.8 mm (option A)",tip:"β = λD/d: 6×10⁻⁷×1.5 = 9×10⁻⁷, ÷5×10⁻⁴ = 1.8×10⁻³. Powers: −7+4 = −3 (mm)."},
{type:"hard",q:"If one slit is covered in YDSE, the interference pattern:",options:["fringe width doubles","disappears (uniform illumination)","shifts up","becomes brighter"],answer:1,steps:["Interference needs TWO coherent sources.","One slit → single-slit diffraction only.","No fringes; screen uniformly lit (with a broad envelope)."],ans:"disappears (option B)",tip:"No second source → no interference. Option A confuses with changing d; covering kills, not widens."},
/* @@P16E@@ */
],
"17. Dual Nature of Matter & Radiation": [
{type:"hard",q:"Light of wavelength 500 nm incident on a metal (work function 2.0 eV) ejects electrons with maximum KE:",options:["0.48 eV","2.48 eV","4.48 eV","zero"],answer:0,steps:["Photon energy = 1240/500 = 2.48 eV.","KE_max = hν − φ = 2.48 − 2.0.","= 0.48 eV."],ans:"0.48 eV (option A)",tip:"1240/λ first (2.48), minus φ (2.0). Option B forgets to subtract the work function."},
{type:"hard",q:"If the intensity of incident light is doubled (frequency fixed), the photoelectric current:",options:["doubles","halves","stays same","becomes zero"],answer:0,steps:["Intensity ∝ photon count per second.","More photons → more electrons ejected.","Current doubles; KE unchanged."],ans:"doubles (option B is wrong; correct option A: doubles)"},
/* @@P17B@@ */
/* @@P17C@@ */
/* @@P17D@@ */
/* @@P17E@@ */
],
"18. Atoms & Nuclei": [
/* @@P18A@@ */
/* @@P18B@@ */
/* @@P18C@@ */
/* @@P18D@@ */
/* @@P18E@@ */
],
"19. Electronic Devices": [
/* @@P19A@@ */
/* @@P19B@@ */
/* @@P19C@@ */
/* @@P19D@@ */
/* @@P19E@@ */
],
"20. Experimental Skills": [
/* @@P20A@@ */
/* @@P20B@@ */
/* @@P20C@@ */
/* @@P20D@@ */
/* @@P20E@@ */
],
};
