/* ===== HARD CHEMISTRY BANK — tough multi-concept JEE Main level MCQs, merged by chapter name in app.js ===== */
/* Schema matches app.js: {type:"hard", q, options[4], answer(index 0-3), steps[], ans, tip} */
const HARD_CHEMISTRY = {
"1. Some Basic Concepts in Chemistry": [
{type:"hard",q:"Concentrated H₂SO₄ is 98% by mass and has a density of 1.8 g/mL. Its molarity is:",options:["18 M","9 M","36 M","12 M"],answer:0,steps:["Take 100 g of solution → mass of H₂SO₄ = 98 g → moles = 98/98 = 1 mol.","Volume of 100 g solution = 100/1.8 = 55.6 mL = 0.0556 L.","M = 1/0.0556 = 18 M."],ans:"18 M (option A)",tip:"Plug-and-play: M = (10 × %w/w × density)/molar mass = (10 × 98 × 1.8)/98 = 18 M. Density must be in g/mL, which is exactly why the 10 appears."},
{type:"hard",q:"The mass of a single molecule of a compound of molar mass 88 g/mol is about:",options:["1.46 × 10⁻²² g","1.46 × 10⁻²³ g","8.8 × 10⁻²³ g","6.02 × 10⁻²² g"],answer:0,steps:["6.022 × 10²³ molecules weigh 88 g.","Mass of one molecule = 88/(6.022 × 10²³).","= 1.46 × 10⁻²² g (≈ 0.146 zeptogram)."],ans:"1.46 × 10⁻²² g (option A)",tip:"Mass of one molecule = M/N_A. Do the division against 6 × 10²³, not 10²³ — most students slip one power of ten here."},
{type:"hard",q:"What volume of 0.1 N NaOH is required to neutralise 20 mL of 0.2 M oxalic acid? (oxalic acid is diprotic)",options:["80 mL","40 mL","20 mL","160 mL"],answer:0,steps:["Normality of oxalic acid = molarity × n-factor = 0.2 × 2 = 0.4 N.","Use N₁V₁ = N₂V₂: 0.4 × 20 = 0.1 × V.","V = 8/0.1 = 80 mL."],ans:"80 mL (option A)",tip:"Convert to normality the moment an acid or base is not monoprotic. Doing it with molarity alone gives 40 mL — the standard trap answer."},
{type:"hard",q:"The mole fraction of the solute in a 1 molal aqueous solution is:",options:["0.0177","0.982","0.0018","0.360"],answer:0,steps:["1 molal = 1 mol solute in 1000 g of water.","Moles of water = 1000/18 = 55.56 mol.","Total moles = 56.56 → x_solute = 1/56.56 = 0.0177."],ans:"0.0177 (option A)",tip:"1 molal aqueous solution always has x_solute = 1/(1 + 55.56) ≈ 0.0177 and x_water ≈ 0.982 — memorise the pair, the numbers never change."},
{type:"hard",q:"Which of the following one-gram samples contains the MAXIMUM number of atoms? [M: Li = 7, O = 16, Mg = 24, Ag = 108]",options:["1 g of Li","1 g of O₂","1 g of Mg","1 g of Ag"],answer:0,steps:["Number of atoms = (mass/M) × N_A × (atoms per formula unit).","O₂: (1/32) × 2N_A = 0.0625 N_A; Mg: (1/24) × N_A = 0.042 N_A; Ag: (1/108) N_A = 0.0093 N_A.","Li: (1/7) N_A = 0.143 N_A — the largest by a wide margin."],ans:"1 g of Li (option A)",tip:"Rank by (atoms per formula unit)/M, not by mass. Smallest molar mass with a monoatomic formula wins instantly — spotting Li at M = 7 settles it without any arithmetic."}
],
"2. Atomic Structure": [
{type:"hard",q:"According to Bohr's quantisation condition, the de Broglie wavelength of the electron in the FIRST orbit of hydrogen (a₀ = 0.529 Å) is:",options:["1.06 Å","3.32 Å","0.53 Å","2.12 Å"],answer:1,steps:["Angular momentum quantisation (mvr = nh/2π) is equivalent to fitting whole wavelengths around the orbit: nλ = 2πr.","For n = 1: λ = 2πa₀.","λ = 2 × 3.14 × 0.529 = 3.32 Å."],ans:"3.32 Å (option B)",tip:"λ = 2πa₀/n, i.e. the circumference divided by n. The first Bohr orbit holds exactly one electron wavelength."},
{type:"hard",q:"The energy needed to excite hydrogen from n = 1 to n = 2 is 10.2 eV. The wavelength of the photon emitted when the electron falls back is about:",options:["91.2 nm","656 nm","121.6 nm","102.6 nm"],answer:2,steps:["The emitted photon carries E = 10.2 eV.","λ(nm) = 1240/E(eV) (the standard hc shortcut).","λ = 1240/10.2 = 121.6 nm — the Lyman-alpha line."],ans:"121.6 nm (option C)",tip:"Memorise λ(nm) = 1240/E(eV). Also remember 10.2 eV → 121.6 nm (Lyman α) and 1.89 eV → 656 nm (H α); these two cover most numericals."},
{type:"hard",q:"The maximum number of electrons that can be accommodated in a subshell with azimuthal quantum number l = 3 is:",options:["6","10","2","14"],answer:3,steps:["Number of orbitals with a given l is (2l + 1) = 2(3) + 1 = 7.","Each orbital holds 2 electrons (Pauli).","Capacity = 2(2l + 1) = 14 (the f subshell)."],ans:"14 (option D)",tip:"Capacity = 2(2l + 1): s → 2, p → 6, d → 10, f → 14. Note l = 3 means f, not d — a very common misread."},
{type:"hard",q:"Which of the following sets of quantum numbers is NOT permissible for an electron in an atom?",options:["n = 3, l = 3, m = 0, s = +1/2","n = 3, l = 2, m = −2, s = −1/2","n = 2, l = 1, m = 0, s = +1/2","n = 4, l = 0, m = 0, s = −1/2"],answer:0,steps:["Rules: 0 ≤ l ≤ n − 1, −l ≤ m ≤ +l, s = ±1/2.","For n = 3 the allowed l values are 0, 1, 2 — so l = 3 is impossible.","The remaining three sets satisfy all three rules."],ans:"n = 3, l = 3, m = 0, s = +1/2 — not permissible (option A)",tip:"Check only l first: l must be strictly less than n. If l = n, the set is invalid instantly, no need to examine m or s."},
{type:"hard",q:"An electron is accelerated through a potential difference of 100 V. Its de Broglie wavelength is approximately:",options:["12.3 Å","0.123 Å","1.23 Å","0.246 Å"],answer:2,steps:["For an electron, λ = h/√(2meV) = 12.27/√V Å.","λ = 12.27/√100.","= 12.27/10 = 1.227 Å ≈ 1.23 Å."],ans:"1.23 Å (option C)",tip:"Memorise the electron shortcut λ = 12.27/√V Å (V in volts). For 100 V it lands exactly at 1.23 Å, a favourite JEE number."}
],
"3. Chemical Bonding & Molecular Structure": [
{type:"hard",q:"The bond order and magnetic character of the superoxide ion O₂⁻ are respectively:",options:["1.5 and paramagnetic","2 and paramagnetic","1.5 and diamagnetic","1 and paramagnetic"],answer:0,steps:["O₂⁻ has 17 valence electrons: σ2s²σ*2s²σ2p² π2p⁴ π*2p³.","Bond order = (bonding − antibonding)/2 = (10 − 7)/2 = 1.5.","The single unpaired electron in π*2p makes it paramagnetic."],ans:"1.5 and paramagnetic (option A)",tip:"Each electron added to an antibonding MO lowers the bond order by 0.5: O₂⁺ 2.5, O₂ 2, O₂⁻ 1.5, O₂²⁻ 1. Species with more than 16 valence electrons have unpaired π* electrons → paramagnetic."},
{type:"hard",q:"Which of the following species is paramagnetic AND has a bond order of 1.5?",options:["O₂⁻","O₂","N₂","NO⁺"],answer:0,steps:["O₂⁻ (superoxide) has 17 valence electrons → one unpaired electron in π* → paramagnetic; bond order = (10 − 7)/2 = 1.5.","O₂ has bond order 2 (paramagnetic but wrong bond order).","N₂ (14 electrons, bond order 3) and NO⁺ (14 electrons, bond order 3) are diamagnetic."],ans:"O₂⁻ (option A)",tip:"Count valence electrons first: 16 → O₂ (BO 2), 17 → O₂⁻ (BO 1.5), 18 → O₂²⁻ (BO 1). Only odd electron counts give paramagnetism here."},
{type:"hard",q:"The hybridisation and shape of XeF₄ are:",options:["sp³d² and square planar","sp³d and see-saw","sp³d² and tetrahedral","sp³ and square planar"],answer:0,steps:["Xe has 8 valence electrons and forms 4 bonds with F, leaving 2 lone pairs.","Steric number = 4 bond pairs + 2 lone pairs = 6 → sp³d² hybridisation (octahedral electron geometry).","To minimise lone pair-lone pair repulsion the two lone pairs occupy the axial positions → the molecule is square planar."],ans:"sp³d² and square planar (option A)",tip:"VSEPR recipe: steric number 6 → sp³d²; then place lone pairs in the least repulsive (axial) sites. Same trick gives XeF₂ linear, BrF₅ square pyramidal and SF₄ see-saw."},
{type:"hard",q:"Which of the following molecules has a ZERO net dipole moment?",options:["BF₃","NH₃","H₂O","CHCl₃"],answer:0,steps:["BF₃ is trigonal planar with three identical B-F bond dipoles at 120°; their vector sum cancels.","NH₃ is pyramidal (lone pair) and H₂O is bent → their bond dipoles do not cancel.","CHCl₃ is tetrahedral with three Cl and one H, so the C-Cl dipoles are not balanced by a single C-H."],ans:"BF₃ (option A)",tip:"Rule: identical substituents + symmetric geometry ⇒ μ = 0. Replacing even ONE substituent in a symmetric molecule (CHCl₃, CH₃Cl) immediately makes μ non-zero."},
{type:"hard",q:"According to molecular orbital theory, which of the following species has the LONGEST bond length?",options:["O₂²⁻","O₂⁻","O₂","O₂⁺"],answer:0,steps:["Bond orders: O₂⁺ 2.5, O₂ 2, O₂⁻ 1.5, O₂²⁻ 1.","Bond length is inversely related to bond order: shorter bond order means a longer bond.","So the peroxide ion O₂²⁻ (bond order 1) has the longest bond."],ans:"O₂²⁻ (option A)",tip:"Bond order ↑ ⇒ bond length ↓ and bond energy ↑. Sequence the four oxygen species once (2.5, 2, 1.5, 1) and every question of this type is answered instantly."}
],
"4. Chemical Thermodynamics": [
{type:"hard",q:"For N₂(g) + 3H₂(g) → 2NH₃(g) at 298 K, ΔH = −92 kJ and ΔS = −198.7 J/K. The reaction is:",options:["Spontaneous at all temperatures","Spontaneous below 463 K","Spontaneous above 463 K","Never spontaneous"],answer:1,steps:["ΔG = ΔH − TΔS. With ΔH < 0 and ΔS < 0 both signs are unfavourable for high T.","ΔG < 0 requires T < ΔH/ΔS = 92000/198.7.","= 463 K, so the reaction is spontaneous below 463 K (298 K qualifies)."],ans:"Spontaneous below 463 K (option B)",tip:"Four-case table: ΔH<0,ΔS>0 always spontaneous; ΔH>0,ΔS<0 never; same signs → crossover at T = ΔH/ΔS. Compute the crossover and compare with the given T."},
{type:"hard",q:"Given C(s) + O₂(g) → CO₂(g), ΔH = −393.5 kJ; CO(g) + ½O₂(g) → CO₂(g), ΔH = −283.0 kJ. The standard enthalpy of formation of CO(g) is:",options:["−110.5 kJ/mol","−676.5 kJ/mol","+110.5 kJ/mol","−221.0 kJ/mol"],answer:0,steps:["Target equation: C(s) + ½O₂(g) → CO(g) = equation (i) minus equation (ii).","ΔH = −393.5 − (−283.0).","= −110.5 kJ/mol."],ans:"−110.5 kJ/mol (option A)",tip:"Hess law: combine equations, and carry out exactly the same operations on their ΔH values. Adding the two ΔH values (−676.5) is the classic blunder."},
{type:"hard",q:"If the bond enthalpies of H₂, Cl₂ and HCl are 435, 243 and 431 kJ/mol, the enthalpy change for H₂(g) + Cl₂(g) → 2HCl(g) is:",options:["−184 kJ","+184 kJ","−247 kJ","−862 kJ"],answer:0,steps:["ΔH = Σ(bond enthalpies broken) − Σ(bond enthalpies formed).","Bonds broken: H-H (435) + Cl-Cl (243) = 678 kJ. Bonds formed: 2 × H-Cl = 862 kJ.","ΔH = 678 − 862 = −184 kJ."],ans:"−184 kJ (option A)",tip:"Broken minus formed. Never forget the coefficient 2 on HCl — that single factor decides between −184 and −431."},
{type:"hard",q:"For which of the following processes is ΔS NEGATIVE?",options:["2H₂O₂(l) → 2H₂O(l) + O₂(g)","CaCO₃(s) → CaO(s) + CO₂(g)","N₂(g) + 3H₂(g) → 2NH₃(g)","H₂O(s) → H₂O(l)"],answer:2,steps:["ΔS < 0 means the system becomes more ordered — usually fewer moles of gas.","N₂ + 3H₂ → 2NH₃ goes from 4 gas moles to 2 gas moles → order increases → ΔS < 0.","The other three all generate gas or melt a solid, so their entropy increases."],ans:"N₂(g) + 3H₂(g) → 2NH₃(g) (option C)",tip:"Just count gas moles on each side: products fewer than reactants ⇒ ΔS negative. Gas-mole count beats any structural reasoning in an exam."},
{type:"hard",q:"When 0.1 mol of HCl is neutralised by NaOH solution, 5.7 kJ of heat is liberated. The enthalpy of neutralisation of HCl is:",options:["−57 kJ/mol","−5.7 kJ/mol","−114 kJ/mol","+57 kJ/mol"],answer:0,steps:["Heat per mole = 5.7/0.1.","= 57 kJ per mole of water formed.","Heat is liberated, so ΔH = −57 kJ/mol."],ans:"−57 kJ/mol (option A)",tip:"Strong acid + strong base is ALWAYS −57.1 kJ/mol (just H⁺ + OH⁻ → H₂O), independent of which strong acid or base is used. Only weak acids/bases differ."}
],
"5. Solutions": [
{type:"hard",q:"The vapour pressure of a pure solvent is 200 mm Hg. On dissolving a non-volatile solute, the mole fraction of the solvent in the solution becomes 0.8. The vapour pressure of the solution is:",options:["160 mm Hg","40 mm Hg","180 mm Hg","200 mm Hg"],answer:0,steps:["Raoult law for the solvent: P = x_solvent × P°_solvent.","P = 0.8 × 200.","= 160 mm Hg (a lowering of 40 mm Hg)."],ans:"160 mm Hg (option A)",tip:"P_solution = x_solvent × P°. The RELATIVE lowering is x_solute and the absolute lowering is x_solute × P° = 0.2 × 200 = 40 mm Hg — option B is that number, a classic trap."},
{type:"hard",q:"Which of the following aqueous solutions will have the HIGHEST boiling point?",options:["0.1 M CaCl₂","0.1 M NaCl","0.1 M glucose","0.1 M urea"],answer:0,steps:["Elevation of boiling point ΔTb = i·Kb·m, so compare the effective particle concentrations i·m.","i values: CaCl₂ = 3, NaCl = 2, glucose = 1, urea = 1.","i·m: CaCl₂ 0.3 > NaCl 0.2 > glucose/urea 0.1 → CaCl₂ boils highest."],ans:"0.1 M CaCl₂ (option A)",tip:"Multiply molarity by the van't Hoff factor i (number of ions). The same reasoning ranks freezing-point depression, so these two questions are one memorised idea."},
{type:"hard",q:"Acetic acid dissociates to the extent of 10% in aqueous solution. The van't Hoff factor i for the solution is:",options:["1.1","1.2","0.9","2.0"],answer:0,steps:["Acetic acid gives 2 ions: CH₃COOH ⇌ CH₃COO⁻ + H⁺, so n = 2.","i = 1 + (n − 1)α = 1 + (1)(0.1).","i = 1.1 (observed colligative property is 10% larger than expected)."],ans:"1.1 (option A)",tip:"i = 1 + (n − 1)α for dissociation and i = 1 − α + α/n for association (benzoic acid in benzene). i > 1 ⇒ dissociation, i < 1 ⇒ association."},
{type:"hard",q:"A 1 L aqueous solution containing 1.8 g of glucose (M = 180) is isotonic with a 1 L solution containing x g of urea (M = 60). Then x equals:",options:["0.6 g","1.8 g","6.0 g","0.18 g"],answer:0,steps:["π = CRT, so isotonic solutions have equal molar concentrations.","Glucose: 1.8/180 = 0.01 mol in 1 L → C = 0.01 M.","Urea needed = 0.01 × 60 = 0.6 g."],ans:"0.6 g (option A)",tip:"Isotonic ⇒ equal molarity, not equal mass. The masses differ by the molar-mass ratio 60/180 = 1/3, giving 0.6 g — and the colligative property used here (osmotic pressure) also works at body temperature, unlike boiling/freezing methods."},
{type:"hard",q:"According to Henry's law, if the partial pressure of a gas above a liquid is doubled at constant temperature, its solubility in the liquid:",options:["Doubles","Halves","Remains unchanged","Becomes four times"],answer:0,steps:["Henry law: p = K_H · x (solubility proportional to partial pressure).","x = p/K_H, with K_H constant at a given temperature.","Doubling p doubles the solubility x."],ans:"Doubles (option A)",tip:"More pressure ⇒ more dissolved gas — the reason soda bottles stay fizzy and divers suffer the bends on surfacing. K_H depends only on the gas-liquid pair and the temperature."}
],
/* @@END_HARD_CHEMISTRY@@ */
};
