/* ===== HARD PHYSICS BANK — tough multi-concept JEE Main level MCQs (chapters 6-20) ===== */
/* Schema matches app.js: {type:"hard", q, options[4], answer(index 0-3), steps[], ans, tip}
   "hard" renders as the TOUGH · MCQ badge. Merged by chapter name inside app.js. */
const HARD_PHYSICS = {
"6. Gravitation": [
{type:"hard",q:"Two spheres of masses m and 4m are separated by a distance d. The point on the line joining their centres where the gravitational field is ZERO lies at a distance from the smaller mass equal to:",options:["d/3","d/2","2d/3","3d/4"],answer:0,steps:["Equate field magnitudes: G m/x² = G(4m)/(d − x)².","Cancel Gm: 1/x² = 4/(d − x)² → taking positive square roots, 1/x = 2/(d − x).","d − x = 2x → x = d/3, i.e. closer to the LIGHTER sphere."],ans:"d/3 from the mass m (option A)",tip:"Null point: x = d/(1 + √(m₂/m₁)) = d/(1 + 2) = d/3. The ratio of distances equals √(m₂/m₁), never 1."},
{type:"hard",q:"A satellite of mass m moves in a circular orbit of radius r. If its total mechanical energy is −E (with E > 0), its kinetic energy is:",options:["E","2E","E/2","−E"],answer:0,steps:["For a circular orbit E_total = −GMm/2r = −E, hence GMm/2r = E.","KE = ½mv² = GMm/2r = E.","PE = −GMm/r = −2E, i.e. twice the KE in magnitude."],ans:"E (option A)",tip:"Circular orbit signature: KE : PE : E = 1 : −2 : −1. So KE = |E|, always positive — a negative KE option is an instant elimination."},
{type:"hard",q:"At what height above the earth's surface does g become 1% of its surface value? (R = 6400 km)",options:["6400 km","57600 km","640 km","3200 km"],answer:1,steps:["g_h = g(R/(R + h))² = g/100 → (R/(R + h))² = 1/100.","Square root: R/(R + h) = 1/10 → R + h = 10R.","h = 9R = 9 × 6400 = 57600 km."],ans:"57600 km (option B)",tip:"g ∝ 1/r², so a 100× drop in g needs r to grow √100 = 10 times. Heights outside the earth scale as g ∝ 1/r², depths as g ∝ r — mixing them is the classic trap."},
{type:"hard",q:"A body is projected vertically from the earth's surface with speed equal to half the escape speed. Neglecting air resistance and rotation, the maximum height reached is (R = radius of earth):",options:["R/3","R/2","R/4","3R/4"],answer:0,steps:["Energy: ½v² − GM/R = −GM/(R + h).","Here v = ½v_e, so v² = v_e²/4 = (2GM/R)/4 = GM/2R.","½v² = GM/4R → GM/4R − GM/R = −GM/(R + h).","−3GM/4R = −GM/(R + h) → R + h = 4R/3 → h = R/3."],ans:"R/3 (option A)",tip:"Never use h = u²/2g for large heights. Use the energy form and the neat substitution v² = v_e²/4 = gR/2 → h = R/3."},
{type:"hard",q:"A satellite is shifted from a circular orbit of radius r to one of radius 4r. Its time period and orbital speed respectively become:",options:["8T and v/2","4T and v/2","8T and v/4","2T and v/2"],answer:0,steps:["Kepler: T² ∝ r³ → T' = T(4)^(3/2) = T × 8 = 8T.","v = √(GM/r) → v' = v/√4 = v/2.","So the period rises 8× while the speed halves — a satellite higher up moves slower."],ans:"8T and v/2 (option A)",tip:"T ∝ r^(3/2) and v ∝ 1/√r. Note 4^(3/2) = 8, not 4 — the most common slip in this question type."},
{type:"hard",q:"For a satellite revolving in a circular orbit around the earth, which of the following statements is INCORRECT?",options:["Its kinetic energy is negative","Its angular momentum about the earth's centre is constant","Its orbital speed is independent of its own mass","Its total mechanical energy is negative"],answer:0,steps:["KE = GMm/2r is always POSITIVE, so calling it negative is the false statement.","PE = −GMm/r and E = −GMm/2r are negative — correct.","Gravity is a central force (zero torque) → angular momentum constant.","v = √(GM/r) has no satellite mass in it → speed is mass-independent."],ans:"Its kinetic energy is negative — that statement is INCORRECT (option A)",tip:"In a bound orbit only PE and total energy are negative. KE and speed are positive quantities — an option making them negative is always the wrong statement."}
],
"7. Properties of Solids & Liquids": [
{type:"hard",q:"A steel wire (Y = 2 × 10¹¹ N/m²) of length 2 m and cross-section 1 mm² is stretched by 1 mm. The elastic potential energy stored in it is:",options:["0.5 J","0.05 J","0.1 J","0.025 J"],answer:1,steps:["Strain = ΔL/L = (1 × 10⁻³)/2 = 5 × 10⁻⁴.","Stress = Y × strain = 2 × 10¹¹ × 5 × 10⁻⁴ = 1 × 10⁸ N/m².","Volume = A × L = 10⁻⁶ × 2 = 2 × 10⁻⁶ m³.","U = ½ × stress × strain × volume = ½ × 10⁸ × 5 × 10⁻⁴ × 2 × 10⁻⁶ = 0.05 J."],ans:"0.05 J (option B)",tip:"Energy density is ½ × stress × strain = ½Yε² — using force × extension/2 needs the average force and is where most students slip a factor of 2."},
{type:"hard",q:"A steel rod (Y = 2 × 10¹¹ N/m², α = 1.2 × 10⁻⁵ per °C) is clamped rigidly between two walls and heated by 100 °C. The thermal stress developed is:",options:["2.4 × 10⁷ N/m²","1.2 × 10⁸ N/m²","2.4 × 10⁸ N/m²","4.8 × 10⁸ N/m²"],answer:2,steps:["Prevented expansion creates a strain equal to the free thermal strain: strain = αΔT = 1.2 × 10⁻⁵ × 100 = 1.2 × 10⁻³.","Thermal stress = Y × strain = 2 × 10¹¹ × 1.2 × 10⁻³.","= 2.4 × 10⁸ N/m² (compressive)."],ans:"2.4 × 10⁸ N/m² (option C)",tip:"Thermal stress = YαΔT — no length or area needed. Note it is independent of the rod's dimensions, which makes it a one-line answer."},
{type:"hard",q:"The excess pressure inside a soap bubble of radius r and surface tension T is:",options:["T/r","2T/r","8T/r","4T/r"],answer:3,steps:["A soap bubble has TWO liquid-air surfaces (inner and outer film).","Each surface contributes 2T/r of excess pressure for a spherical film.","Total excess pressure = 4T/r (a liquid drop, having one surface, gives 2T/r)."],ans:"4T/r (option D)",tip:"Bubble 4T/r, drop 2T/r, and an air bubble INSIDE a liquid behaves like a drop (2T/r). Counting the number of surfaces is the whole question."},
{type:"hard",q:"Water rises to a height h in a capillary tube dipped in water. The tube is now cut at a height h/2 above the water surface. Then the water in the tube:",options:["Overflows continuously till the tube empties","Does not overflow; the meniscus becomes flatter so that equilibrium is restored","Rises to the full height h and spills over the edge","Falls back and the tube empties completely"],answer:1,steps:["Capillary rise is governed by h = 2T cos θ/(r ρ g).","When the tube is cut at h/2 the required rise is larger than h/2, so the only adjustable quantity is cos θ, which decreases.","A flatter meniscus means the water stands at the rim without crossing it — no overflow."],ans:"Does not overflow — the meniscus flattens to restore equilibrium (option B)",tip:"h = 2T cosθ/(rρg): with the tube shortened, cosθ must decrease (flatter meniscus). Surface tension cannot pull water beyond what it can support, so no overflow."},
{type:"hard",q:"Water flows steadily through a horizontal pipe whose cross-sectional area halves at a constriction. If the speed in the wider part is v, the pressure drop between the wide and narrow sections is (density of water = ρ):",options:["0.5ρv²","3ρv²","1.5ρv²","2ρv²"],answer:2,steps:["Continuity: A·v = (A/2)·v₂ → v₂ = 2v.","Bernoulli along the horizontal pipe: P₁ + ½ρv² = P₂ + ½ρ(2v)².","ΔP = P₁ − P₂ = ½ρ(4v² − v²) = 1.5ρv²."],ans:"1.5ρv² (option C)",tip:"Memorise ΔP = ½ρv²(n² − 1) when the area shrinks by factor n. Here n = 2 → 3ρv²/2 in a single substitution."},
{type:"hard",q:"A spherical liquid drop falls through air with terminal velocity v. If it breaks into 8 identical droplets, the terminal velocity of each droplet becomes:",options:["v/8","v/2","v","v/4"],answer:3,steps:["Terminal velocity v = 2r²(ρ − σ)g/9η, so v ∝ r².","Splitting into 8 drops means volume ÷ 8 → r³ ÷ 8 → r becomes r/2.","v' = v(r/2)²/r² = v/4."],ans:"v/4 (option D)",tip:"v ∝ r², so halving the radius quarters the speed. If a drop breaks into n parts the new velocity is v/n^(2/3) — 8^(2/3) = 4 here."}
],
"8. Thermodynamics": [
{type:"hard",q:"One mole of an ideal gas at 300 K expands isothermally from 1 L to 10 L. The work done by the gas is (R = 8.3 J/mol·K, ln 10 = 2.3):",options:["5.73 kJ","2.49 kJ","1.25 kJ","8.30 kJ"],answer:0,steps:["Isothermal work by an ideal gas: W = nRT ln(V₂/V₁).","nRT = 1 × 8.3 × 300 = 2490 J.","W = 2490 × ln 10 = 2490 × 2.3 = 5727 J ≈ 5.73 kJ."],ans:"5.73 kJ (option A)",tip:"Isothermal work = 2.303 nRT log₁₀(V₂/V₁), and for 1 mole at 300 K the factor nRT is 2490 J. In an isothermal expansion of an ideal gas ΔU = 0, so Q = W = 5.73 kJ too."},
{type:"hard",q:"For an ideal gas with γ = 1.4, the molar heat capacity at constant volume is (R = 8.3 J/mol·K):",options:["29.1 J/mol·K","20.8 J/mol·K","14.5 J/mol·K","12.4 J/mol·K"],answer:1,steps:["Cv = R/(γ − 1).","= 8.3/(1.4 − 1) = 8.3/0.4.","= 20.75 ≈ 20.8 J/mol·K (and Cp = γCv = 29.1)."],ans:"20.8 J/mol·K (option B)",tip:"Both formulas come from Cv = R/(γ − 1) and Cp = γR/(γ − 1). Check with the diatomic gas: Cv = 5R/2 = 20.8 — the γ = 1.4 gas IS diatomic."},
{type:"hard",q:"A Carnot engine has an efficiency of 40% with a sink at 300 K. To raise the efficiency to 60% while keeping the same sink, the source temperature must be increased by:",options:["150 K","500 K","300 K","250 K"],answer:3,steps:["η = 1 − T₂/T₁ → T₁ = T₂/(1 − η).","For 40%: T₁ = 300/0.6 = 500 K. For 60%: T₁ = 300/0.4 = 750 K.","Required increase = 750 − 500 = 250 K."],ans:"250 K (option D)",tip:"Use T₁ = T_sink/(1 − η) twice and subtract. There is no linear rule for efficiency — doubling the efficiency does NOT double the temperature."},
{type:"hard",q:"An ideal gas undergoes a rectangular cyclic process on a P-V diagram between P = 2 atm, 1 atm and V = 1 L, 3 L. The net work output per cycle is (1 atm·L = 101 J):",options:["404 J","101 J","202 J","303 J"],answer:2,steps:["Work per cycle = area enclosed by the loop = ΔP × ΔV.","= (2 − 1) atm × (3 − 1) L = 2 atm·L.","= 2 × 101 = 202 J."],ans:"202 J (option C)",tip:"Net work in a cycle = enclosed area (clockwise = positive). For a rectangle it is simply ΔP·ΔV — no integration needed. Remember 1 atm·L ≈ 101 J."},
{type:"hard",q:"An ideal gas is compressed adiabatically by an external agent. Then:",options:["ΔU > 0 and the temperature rises","ΔU < 0 but the temperature rises","ΔU = 0 and the temperature stays constant","ΔU > 0 but the temperature falls"],answer:0,steps:["Adiabatic ⇒ Q = 0, so the first law gives ΔU = −W.","Compression ⇒ work is done ON the gas ⇒ W < 0.","ΔU = −W > 0; for an ideal gas U depends only on T, so the temperature must rise."],ans:"ΔU > 0 and the temperature rises (option A)",tip:"Sign discipline: W is positive only when the gas EXPANDS. Adiabatic compression always heats (diesel-engine ignition) and adiabatic expansion always cools."},
{type:"hard",q:"Two moles of a diatomic ideal gas are heated from 300 K to 400 K by some unspecified process. The change in internal energy is (R = 8.3 J/mol·K):",options:["2490 J","3320 J","8300 J","4150 J"],answer:3,steps:["For a diatomic gas Cv = 5R/2 = 2.5R.","ΔU = nCvΔT = 2 × 2.5 × 8.3 × (400 − 300).","= 5 × 8.3 × 100 = 4150 J."],ans:"4150 J (option D)",tip:"ΔU = nCvΔT holds for EVERY process, because U depends only on temperature for an ideal gas. Only Q and W are path-dependent."}
],
"9. Kinetic Theory of Gases": [
{type:"hard",q:"The rms speed of hydrogen molecules (M = 2) at 300 K is v. At what temperature does the rms speed of oxygen molecules (M = 32) also become v?",options:["4800 K","300 K","9600 K","2400 K"],answer:0,steps:["v_rms = √(3RT/M), so v_rms ∝ √(T/M).","Equal speeds require T_H/M_H = T_O/M_O.","T_O = 300 × (32/2) = 4800 K."],ans:"4800 K (option A)",tip:"Use the ratio form: to match speeds, T ∝ M. Oxygen is 16 times heavier, so it needs 16 times the temperature — no need to compute √(3R)."},
{type:"hard",q:"The average translational kinetic energy of a molecule of an ideal gas at 300 K is (k = 1.38 × 10⁻²³ J/K):",options:["6.21 × 10⁻²¹ J","4.14 × 10⁻²¹ J","2.07 × 10⁻²¹ J","1.38 × 10⁻²³ J"],answer:0,steps:["Average translational KE per molecule = (3/2)kT.","= 1.5 × 1.38 × 10⁻²³ × 300.","= 6.21 × 10⁻²¹ J."],ans:"6.21 × 10⁻²¹ J (option A)",tip:"(3/2)kT contains no mass — every ideal-gas molecule has this same translational energy at a given temperature. Option B is the rotational-plus-translational trap for a diatomic gas."},
{type:"hard",q:"A mixture contains 1 mole of a monoatomic gas and 1 mole of a rigid diatomic gas. The value of Cp/Cv for the mixture is:",options:["1.5","1.67","1.4","1.33"],answer:0,steps:["Cv(mono) = 3R/2, Cv(diatomic) = 5R/2.","Cv(mixture) = (3R/2 + 5R/2)/2 = 2R; so Cp = 2R + R = 3R.","γ = Cp/Cv = 3R/2R = 1.5."],ans:"1.5 (option A)",tip:"For a mixture, average Cv over the total number of moles and then add R for Cp. Note the answer lies BETWEEN 1.4 and 1.67, so the pure-gas values are instantly eliminable."},
{type:"hard",q:"If the pressure of a gas is doubled while the temperature is kept constant, its mean free path becomes:",options:["λ/2","2λ","λ","λ/4"],answer:0,steps:["Mean free path λ = kT/(√2 π d² P).","At constant T and fixed molecular diameter, λ ∝ 1/P.","Doubling P halves λ."],ans:"λ/2 (option A)",tip:"λ ∝ T/P. Compressing a gas (P up at fixed T) shortens the mean free path because molecules crowd together; heating lengthens it."},
{type:"hard",q:"A vessel contains 1 mole of helium (M = 4) and 1 mole of argon (M = 40) at the same temperature. The ratio of their rms speeds v_He : v_Ar is:",options:["√10 : 1","1 : √10","10 : 1","1 : 1"],answer:0,steps:["At a common temperature, v_rms ∝ 1/√M.","Ratio = √(M_Ar/M_He) = √(40/4).","= √10 : 1 ≈ 3.16 : 1."],ans:"√10 : 1 (option A)",tip:"v_rms ∝ 1/√M at fixed T, so the LIGHTER gas is faster. Remember the ratio is inverted (heavy in the numerator under the root) — the reverse option is the standard trap."},
{type:"hard",q:"The internal energy of 2 moles of a rigid diatomic ideal gas at 300 K is (R = 8.3 J/mol·K):",options:["12450 J","7470 J","4980 J","8310 J"],answer:0,steps:["Internal energy U = (f/2)nRT with f = 5 for a rigid diatomic gas.","U = (5/2) × 2 × 8.3 × 300.","= 5 × 8.3 × 300 = 12450 J."],ans:"12450 J (option A)",tip:"U = nCvT with Cv = fR/2 (f = 3 mono, 5 diatomic, 6 polyatomic). Option C is the monoatomic value — check f before substituting."}
],
"10. Oscillations & Waves": [
{type:"hard",q:"A particle executes SHM with amplitude A. At what displacement from the mean position are its kinetic and potential energies equal?",options:["A/√2","A/2","A/√3","A/4"],answer:0,steps:["Total energy E = ½kA², PE = ½kx², KE = ½k(A² − x²).","KE = PE ⇒ (A² − x²) = x².","x² = A²/2 → x = A/√2 ≈ 0.707A."],ans:"x = A/√2 (option A)",tip:"Three memorised ratios: KE = PE at x = A/√2, KE = 3PE at x = A/2, PE = 3KE at x = √3A/2. This kills every SHM energy question instantly."},
{type:"hard",q:"The time period of a simple pendulum of length l inside a lift accelerating upward with acceleration a is:",options:["2π√(l/(g + a))","2π√(l/(g − a))","2π√(l/g)","2π√(l/a)"],answer:0,steps:["In a lift accelerating up, the effective gravity is g_eff = g + a.","T = 2π√(l/g_eff).","T = 2π√(l/(g + a))."],ans:"2π√(l/(g + a)) (option A)",tip:"Upward acceleration → heavier feel → larger g_eff → SHORTER period. Free fall (a = g downward) gives g_eff = 0 and an infinite period."},
{type:"hard",q:"Two springs of spring constants k₁ and k₂ are joined end to end (in series) and the combination is loaded. The effective spring constant is:",options:["k₁k₂/(k₁ + k₂)","k₁ + k₂","(k₁ + k₂)/2","k₁ − k₂"],answer:0,steps:["In series the forces are equal and the extensions add, so 1/k = 1/k₁ + 1/k₂.","Taking the LCM: 1/k = (k₁ + k₂)/(k₁k₂).","k = k₁k₂/(k₁ + k₂)."],ans:"k₁k₂/(k₁ + k₂) (option A)",tip:"Springs in series behave like capacitors in series (reciprocals add) and like resistors in parallel. Parallel springs simply add: k = k₁ + k₂."},
{type:"hard",q:"A source emitting sound of frequency f moves towards a stationary observer with speed v/5, where v is the speed of sound. The apparent frequency heard is:",options:["1.25f","0.8f","1.2f","1.5f"],answer:0,steps:["Observer at rest, source approaching: f' = f·v/(v − v_s).","v_s = v/5 → f' = f·v/(v − v/5) = f·v/(4v/5).","f' = 5f/4 = 1.25f."],ans:"1.25f (option A)",tip:"Formula set: source approaches v/(v − v_s), recedes v/(v + v_s); observer approaches (v + v_o)/v, recedes (v − v_o)/v. Mixing the source and observer formulas is the classic error."},
{type:"hard",q:"The fundamental frequency of an open organ pipe of length L is f. If the same pipe is closed at one end, its fundamental frequency becomes:",options:["f/2","2f","f","f/4"],answer:0,steps:["Open pipe fundamental: λ = 2L → f = v/2L.","Closed pipe fundamental: λ = 4L → f' = v/4L.","f' = f/2."],ans:"f/2 (option A)",tip:"Closing one end HALVES the fundamental and kills all even harmonics (only odd multiples survive: 1f, 3f, 5f). Remember 2L for open, 4L for closed."},
{type:"hard",q:"A travelling wave is described by y = 0.02 sin(100πt − 0.5πx) (SI units). The speed of the wave is:",options:["200 m/s","100 m/s","50 m/s","0.005 m/s"],answer:0,steps:["Compare with y = A sin(ωt − kx): ω = 100π rad/s and k = 0.5π rad/m.","Wave speed v = ω/k.","v = 100π/0.5π = 200 m/s."],ans:"200 m/s (option A)",tip:"v = ω/k (coefficient of t divided by the coefficient of x). Equivalently λ = 2π/k = 4 m and v = λf = 4 × 50 = 200 m/s — both routes agree."}
],
"11. Electrostatics": [
{type:"hard",q:"Two identical conducting spheres carrying charges +4 µC and −2 µC are brought into contact and then separated. The charge on each sphere is now:",options:["+1 µC each","+3 µC each","+2 µC each","−1 µC each"],answer:0,steps:["Total charge is conserved: (+4) + (−2) = +2 µC.","For identical conductors in contact, the charge divides equally.","Each sphere carries 2/2 = +1 µC."],ans:"+1 µC each (option A)",tip:"Contact sharing for identical spheres = (q₁ + q₂)/2. If the spheres are of different radii the charge divides in proportion to the radii (surface-charge density equalises)."},
{type:"hard",q:"A uniformly charged thin spherical shell of radius R carries a charge Q. The electric field at a point r < R from its centre is:",options:["0","kQ/r²","kQ/R²","kQr/R³"],answer:0,steps:["Draw a Gaussian sphere of radius r < R concentric with the shell.","It encloses zero charge, so by Gauss law ∮E·dA = 0.","By symmetry E = 0 everywhere inside the shell."],ans:"0 (option A)",tip:"Shell: E = 0 inside, E = kQ/r² outside (as if the whole charge sat at the centre) and V = kQ/R constant inside. A uniformly charged SOLID sphere gives E = kQr/R³ inside — the linear-growth option is that trap."},
{type:"hard",q:"A 6 µF capacitor charged to 100 V is connected across an uncharged 4 µF capacitor (like plates joined). The common potential difference is:",options:["60 V","40 V","100 V","50 V"],answer:0,steps:["Initial charge = CV = 6 × 100 = 600 µC and it is conserved.","After connection total capacitance = 6 + 4 = 10 µF.","V = Q/C = 600/10 = 60 V."],ans:"60 V (option A)",tip:"Charge is conserved, energy is NOT (part is lost as heat/sparks). Formula: V = C₁V₁/(C₁ + C₂). If the opposite plates were joined, the charges would subtract instead."},
{type:"hard",q:"An electric dipole of moment p is placed in a uniform electric field E with its axis at 60° to the field. The torque acting on it and its potential energy are respectively:",options:["pE√3/2 and −pE/2","pE/2 and −pE√3/2","pE and 0","0 and −pE"],answer:0,steps:["Torque τ = pE sin θ = pE sin 60° = pE(√3/2).","Potential energy U = −pE cos θ = −pE cos 60° = −pE/2.","At θ = 60° the dipole is in stable-side equilibrium, so U is negative."],ans:"pE√3/2 and −pE/2 (option A)",tip:"Torque carries the sine, energy carries the cosine. Memorise the ends: θ = 0 → τ = 0, U = −pE (stable); θ = 90° → τ = pE, U = 0; θ = 180° → τ = 0, U = +pE (unstable)."},
{type:"hard",q:"A 10 µF capacitor is charged to a potential difference of 100 V. The energy stored in it is:",options:["0.05 J","0.5 J","0.1 J","1 J"],answer:0,steps:["U = ½CV².","= ½ × 10 × 10⁻⁶ × (100)².","= 5 × 10⁻⁶ × 10⁴ = 0.05 J."],ans:"0.05 J (option A)",tip:"Three equivalent forms: ½CV², ½QV, Q²/2C. Option B comes from forgetting the ½ and option C from using ½QV with Q in microcoulombs wrongly."},
{type:"hard",q:"A point charge q is placed at the centre of a cube. The electric flux through ONE face of the cube is:",options:["q/(6ε₀)","q/ε₀","q/(3ε₀)","q/(2ε₀)"],answer:0,steps:["Total flux through any closed surface enclosing q is q/ε₀ (Gauss law).","By symmetry all 6 faces of the cube receive equal flux.","Flux per face = q/(6ε₀)."],ans:"q/(6ε₀) (option A)",tip:"Symmetry divisor: 6 for a cube, 8 for an octant, 3 for an infinite sheet, 2 for a half-space. The charge must be symmetrically placed for this division to be valid."}
],
/* @@END_HARD_PHYSICS@@ */
};
