/* ===== CHEMISTRY — EXTRA TOUGH BANK (54 Qs, JEE Main PYQ-pattern, merged by topic name) ===== */
/* Schema matches app.js: {type:"pyq"|"imp", q, options[4], answer(index), steps[], ans, tip}
   "pyq" = previous-year-pattern JEE Main question (no fabricated year tag is claimed). */
const EXTRA_CHEMISTRY = {

"1. Some Basic Concepts in Chemistry": [
  {type:"pyq", q:"8.0 g of CH₄ is burnt in 24.0 g of O₂ (CH₄ + 2O₂ → CO₂ + 2H₂O). The mass of CO₂ formed is:",
   options:["33.0 g","11.0 g","16.5 g","22.0 g"], answer:2,
   steps:["moles: CH₄ = 8/16 = 0.5 mol; O₂ = 24/32 = 0.75 mol.",
    "O₂ needed by 0.5 mol CH₄ = 2 × 0.5 = 1.0 mol > 0.75 mol available → O₂ is the limiting reagent.",
    "CO₂ from O₂ = 0.75 × (1/2) = 0.375 mol → 0.375 × 44 = 16.5 g."],
   ans:"16.5 g (option C)", tip:"Divide every reactant by its stoichiometric coefficient — the smallest quotient is the limiting reagent. Comparing masses directly is the classic trap."},
  {type:"imp", q:"750 mL of 0.5 M HCl is mixed with 250 mL of 2 M HCl. The molarity of the resulting solution is:",
   options:["0.875 M","0.625 M","1.25 M","1.0 M"], answer:0,
   steps:["Work in millimoles: HCl from first solution = 750 × 0.5 = 375 mmol.",
    "HCl from second = 250 × 2 = 500 mmol. Total = 875 mmol.",
    "Total volume = 1000 mL → M = 875/1000 = 0.875 M."],
   ans:"0.875 M (option A)", tip:"Mixing problems: find mmol (M × mL) then divide by total mL. Never average the molarities."},
  {type:"pyq", q:"How many moles of electrons weigh 1 kg? (mass of one electron = 9.1 × 10⁻³¹ kg)",
   options:["9.1 × 10³¹ mol","1.1 × 10³⁰ mol","1.82 × 10⁶ mol","6.02 × 10²³ mol"], answer:2,
   steps:["Number of electrons in 1 kg = 1 / (9.1 × 10⁻³¹) = 1.099 × 10³⁰.",
    "Moles = particles / N_A = 1.099 × 10³⁰ / 6.022 × 10²³.",
    "= 1.82 × 10⁶ mol."],
   ans:"1.82 × 10⁶ mol (option C)", tip:"Mass → particles (÷ mass of one particle) → moles (÷ N_A). Two divisions; chain them in one line."}
],

"2. Atomic Structure": [
  {type:"pyq", q:"The de Broglie wavelength of the electron in the 3rd Bohr orbit of hydrogen is: (r = 4.76 Å)",
   options:["2.0 nm","0.53 nm","4.76 nm","1.0 nm"], answer:3,
   steps:["Standing-wave condition: nλ = 2πr → λ = 2πr₃/3.",
    "λ = (2 × 3.14 × 4.76 Å)/3 = 9.97 Å.",
    "9.97 Å = 0.997 nm ≈ 1.0 nm."],
   ans:"1.0 nm (option D)", tip:"Only one relation is needed: 2πr = nλ. Every 'wavelength in the nth orbit' question then takes 20 seconds."},
  {type:"pyq", q:"For a 4f orbital, the numbers of angular and radial nodes respectively are:",
   options:["0 and 3","3 and 0","2 and 1","3 and 3"], answer:1,
   steps:["Angular nodes = l = 3 (f orbital).",
    "Radial nodes = n − l − 1 = 4 − 3 − 1 = 0.",
    "Check: total nodes = n − 1 = 3 ✓"],
   ans:"3 and 0 (option B)", tip:"Radial = n−l−1, angular = l, total = n−1. 4f is the only n = 4 orbital with zero radial nodes."},
  {type:"pyq", q:"If the uncertainties in position and momentum of an electron are equal, the minimum uncertainty in its velocity is about: (h = 6.6 × 10⁻³⁴ J s, mₑ = 9.1 × 10⁻³¹ kg)",
   options:["6.6 × 10⁻³⁴ m/s","7.9 × 10¹² m/s","2.3 × 10⁹ m/s","1.1 × 10⁻¹⁹ m/s"], answer:1,
   steps:["Δx = Δp → (Δp)² ≥ ħ/2 → Δp = √(ħ/2).",
    "ħ/2 = 1.055 × 10⁻³⁴/2 = 5.3 × 10⁻³⁵ → Δp = 7.27 × 10⁻¹⁸ kg m s⁻¹.",
    "Δv = Δp/mₑ = 7.27 × 10⁻¹⁸ / 9.1 × 10⁻³¹ ≈ 7.9 × 10¹² m/s."],
   ans:"≈ 7.9 × 10¹² m/s (option B)", tip:"Set Δx = Δp in Δx·Δp ≥ h/4π, then Δv = √(h/4π)/m — one substitution, no algebra."}
],
"3. Chemical Bonding & Molecular Structure": [
  {type:"pyq", q:"Which of the following has the highest bond order?",
   options:["O₂","O₂⁻","O₂²⁻","O₂⁺"], answer:3,
   steps:["MOT: bond order = (N_bonding − N_antibonding)/2.",
    "O₂ = 2.0; O₂⁻ = 1.5; O₂²⁻ = 1.0.",
    "O₂⁺ = 2.5 — the electron removed is from the antibonding π* level, so bond order rises."],
   ans:"O₂⁺ with bond order 2.5 (option D)", tip:"The O₂ ladder: 2.5 (O₂⁺) > 2.0 (O₂) > 1.5 (O₂⁻) > 1.0 (O₂²⁻). Remember it once and use it every year."},
  {type:"pyq", q:"The maximum number of lone pairs on the central atom is present in:",
   options:["ClF₃","XeF₄","XeF₂","SF₄"], answer:2,
   steps:["Lone pairs = (valence electrons − bonding electrons)/2 on the central atom.",
    "ClF₃ → 2; XeF₄ (sp³d²) → 2; SF₄ (sp³d) → 1; XeF₂ (sp³d) → 3.",
    "XeF₂ is linear with 3 lone pairs → maximum."],
   ans:"XeF₂ with 3 lone pairs (option C)", tip:"Draw the VSEPR structure first. XeF₂ (3 lone pairs) is the standard 'most idle electrons' trap."},
  {type:"imp", q:"The correct order of bond angle is:",
   options:["H₂O > H₂S > H₂Se > H₂Te","H₂O > H₂Se > H₂S > H₂Te","H₂S > H₂O > H₂Se > H₂Te","H₂Te > H₂Se > H₂S > H₂O"], answer:0,
   steps:["Water: small, electronegative O, sp³ hybridised with strong bond-pair repulsion → 104.5°.",
    "For S, Se, Te the large, less electronegative central atom bonds through nearly pure p orbitals → ~90°.",
    "Angles: 104.5° > 92° > 91° > 90°."],
   ans:"H₂O > H₂S > H₂Se > H₂Te (option A)", tip:"Down group 16 the angle collapses towards 90° (pure p bonding). H₂O is the 'hybridised' outlier at 104.5°."}
],

"4. Chemical Thermodynamics": [
  {type:"pyq", q:"For C₆H₆(l) + 15/2 O₂(g) → 6CO₂(g) + 3H₂O(l) at 298 K, the value of (ΔH − ΔU) is:",
   options:["zero","−1.86 kJ","−3.72 kJ","+3.72 kJ"], answer:2,
   steps:["ΔH − ΔU = Δn_g RT (only gaseous species are counted).",
    "Δn_g = 6 − 7.5 = −1.5.",
    "ΔH − ΔU = −1.5 × 8.314 × 298 J = −3716 J ≈ −3.72 kJ."],
   ans:"−3.72 kJ (option C)", tip:"Δn_g counts gases only — liquid benzene and liquid water are ignored. The sign of (ΔH − ΔU) equals the sign of Δn_g."},
  {type:"imp", q:"At 273 K and 1 atm, ice ⇌ water is at equilibrium. Which statement is correct?",
   options:["ΔG > 0 and ΔS_total < 0","ΔG = 0 and ΔS_system = 0","ΔG < 0 and ΔS_total > 0","ΔG = 0 and ΔS_total = 0"], answer:3,
   steps:["At equilibrium the free-energy change of the phase change is zero: ΔG = 0.",
    "ΔS_total = ΔS_system + ΔS_surroundings = −ΔG/T.",
    "ΔG = 0 → ΔS_total = 0 → melting at 273 K is reversible."],
   ans:"ΔG = 0 and ΔS_total = 0 (option D)", tip:"ΔG < 0, = 0, > 0 map exactly onto ΔS_total > 0, = 0, < 0. This one link answers every spontaneity question."},
  {type:"imp", q:"For a reaction ΔH = +40 kJ mol⁻¹ and ΔS = +100 J K⁻¹ mol⁻¹. At 300 K the reaction is:",
   options:["non-spontaneous with ΔG = +10 kJ","spontaneous with ΔG = −10 kJ","non-spontaneous with ΔG = +30 kJ","at equilibrium with ΔG = 0"], answer:0,
   steps:["ΔG = ΔH − TΔS = 40000 − 300(100) J.",
    "= +10000 J = +10 kJ → non-spontaneous at 300 K.",
    "It becomes spontaneous above T = 40000/100 = 400 K."],
   ans:"non-spontaneous, ΔG = +10 kJ (option A)", tip:"Convert ΔS to kJ (divide by 1000) before subtracting — the most common magnitude error in these questions."}
],

"5. Solutions": [
  {type:"pyq", q:"Which aqueous solution has the highest freezing point?",
   options:["0.1 m glucose","0.1 m AlCl₃","0.1 m NaCl","0.1 m CaCl₂"], answer:0,
   steps:["ΔT_f = i·K_f·m — more particles means a larger depression and a lower freezing point.",
    "van't Hoff factors: glucose 1, NaCl 2, CaCl₂ 3, AlCl₃ 4.",
    "Smallest ΔT_f (i = 1) → highest freezing point → glucose."],
   ans:"0.1 m glucose (option A)", tip:"Depression ∝ number of particles. The non-electrolyte always keeps the highest freezing point and the lowest boiling point."},
  {type:"imp", q:"The vapour pressures of pure A and B are 400 and 600 mm Hg. An ideal mixture of 2 mol A + 3 mol B has total vapour pressure:",
   options:["520 mm Hg","480 mm Hg","500 mm Hg","560 mm Hg"], answer:0,
   steps:["Mole fractions: x_A = 2/5 = 0.4; x_B = 0.6.",
    "P_total = x_A P°_A + x_B P°_B = 0.4(400) + 0.6(600).",
    "= 160 + 360 = 520 mm Hg."],
   ans:"520 mm Hg (option A)", tip:"For an ideal solution the total pressure is just the mole-fraction-weighted average of the pure vapour pressures."}
],

"6. Equilibrium": [
  {type:"pyq", q:"For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the relation between Kp and Kc is:",
   options:["Kp = Kc","Kp = Kc(RT)⁻¹","Kp = Kc(RT)²","Kp = Kc(RT)⁻²"], answer:3,
   steps:["Kp = Kc(RT)^Δn where Δn counts gaseous species only.",
    "Δn = 2 − (1 + 3) = −2.",
    "Therefore Kp = Kc(RT)⁻²."],
   ans:"Kp = Kc(RT)⁻² (option D)", tip:"Δn = Σ gaseous products − Σ gaseous reactants. Sum the coefficients — that is the entire question."},
  {type:"pyq", q:"The pH of a solution that is 0.1 M in CH₃COOH and 0.1 M in CH₃COONa is: (Ka = 1.8 × 10⁻⁵)",
   options:["9.26","4.74","5.04","2.87"], answer:1,
   steps:["Henderson equation: pH = pKa + log([salt]/[acid]).",
    "[salt] = [acid] = 0.1 M → log(1) = 0, so pH = pKa.",
    "pKa = −log(1.8 × 10⁻⁵) = 4.74."],
   ans:"4.74 (option B)", tip:"Equal acid and salt concentrations make pH = pKa exactly. Only compute pKa and skip the log entirely."},
  {type:"imp", q:"The solubility of AgCl (Ksp = 1.8 × 10⁻¹⁰) in 0.01 M NaCl solution is:",
   options:["1.8 × 10⁻¹⁰ M","1.8 × 10⁻⁸ M","1.8 × 10⁻¹² M","1.34 × 10⁻⁵ M"], answer:1,
   steps:["Common-ion effect: [Cl⁻] is fixed by NaCl at 0.01 M.",
    "Ksp = [Ag⁺][Cl⁻] → [Ag⁺] = Ksp/[Cl⁻] (the extra Ag⁺ contribution to [Cl⁻] is negligible).",
    "s = 1.8 × 10⁻¹⁰ / 10⁻² = 1.8 × 10⁻⁸ M."],
   ans:"1.8 × 10⁻⁸ M (option B)", tip:"With a common ion present, solubility = Ksp / [common ion]. One division — no quadratic equation ever."}
],

"7. Redox Reactions & Electrochemistry": [
  {type:"imp", q:"The equivalent mass of KMnO₄ (molar mass M) acting as an oxidising agent in acidic medium is:",
   options:["M/5","M","M/3","M/7"], answer:0,
   steps:["In acidic medium: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O.",
    "n-factor = change in oxidation number of Mn = 7 − 2 = 5.",
    "Equivalent mass = M/5 = 158/5 = 31.6."],
   ans:"M/5 (option A)", tip:"KMnO₄ n-factor: 5 in acidic, 3 in neutral/weakly basic (MnO₂), 1 in strongly basic (MnO₄²⁻). This is a standing MCQ trap."},
  {type:"pyq", q:"For the cell Zn|Zn²⁺(0.1 M)||Cu²⁺(0.01 M)|Cu, E°cell = 1.10 V. The EMF at 298 K is:",
   options:["1.07 V","1.10 V","1.04 V","1.13 V"], answer:0,
   steps:["Nernst equation: E = E° − (0.059/2)·log([Zn²⁺]/[Cu²⁺]).",
    "= 1.10 − 0.0295 × log(0.1/0.01) = 1.10 − 0.0295 × 1.",
    "= 1.070 V."],
   ans:"≈ 1.07 V (option A)", tip:"The log takes the ratio (anode ion / cathode ion) and the factor is 0.059/n. Since the anode ion is more concentrated, E must be less than E° — check the sign and you have caught half the errors."},
  {type:"imp", q:"The charge required to deposit 0.1 mol of aluminium from molten Al₂O₃ is:",
   options:["9650 C","28950 C","32051 C","96500 C"], answer:1,
   steps:["Al³⁺ + 3e⁻ → Al, so 3 mol electrons are needed per mol of Al.",
    "n(e⁻) = 3 × 0.1 = 0.3 mol.",
    "Q = 0.3 × 96500 = 28950 C (= 0.3 F)."],
   ans:"28950 C (option B)", tip:"Path: n-factor → moles of electrons → multiply by 96500 C. Al is always 3 F per mole, never 1 F."}
],

"8. Chemical Kinetics": [
  {type:"pyq", q:"A first-order reaction is 50% complete in 30 minutes. The time to become 75% complete is:",
   options:["120 min","45 min","90 min","60 min"], answer:3,
   steps:["For a first-order reaction the half-life is independent of concentration: t½ = 30 min.",
    "75% completion = two half-lives (50% then 50% of the remainder).",
    "t = 2 × 30 = 60 min."],
   ans:"60 min (option D)", tip:"First order: 50% → t½, 75% → 2t½, 87.5% → 3t½. Count half-lives instead of using the integrated law."},
  {type:"imp", q:"For the rate law rate = k[A][B]², if [A] is doubled and [B] is halved, the rate becomes:",
   options:["one-fourth","double","unchanged","half"], answer:3,
   steps:["Rate ∝ [A]¹[B]².",
    "New factor = 2 × (1/2)² = 2 × ¼ .",
    "= ½ → the rate becomes half."],
   ans:"half (option D)", tip:"Substitute the multipliers straight into the order powers: 2 × 0.25 = 0.5 in one line."},
  {type:"pyq", q:"The rate constant of a reaction doubles when the temperature rises from 300 K to 310 K. Ea is nearly: (R = 8.314 J K⁻¹ mol⁻¹)",
   options:["53.6 kJ mol⁻¹","26.8 kJ mol⁻¹","107 kJ mol⁻¹","8.3 kJ mol⁻¹"], answer:0,
   steps:["log(k₂/k₁) = (Ea / 2.303R)·(T₂ − T₁)/(T₁T₂).",
    "log 2 = 0.301 and (T₁T₂)/(T₂ − T₁) = (300 × 310)/10 = 9300.",
    "Ea = 2.303 × 8.314 × 0.301 × 9300 ≈ 53.6 kJ mol⁻¹."],
   ans:"≈ 53.6 kJ mol⁻¹ (option A)", tip:"'Rate constant doubles per 10 K rise' ≈ 50–55 kJ/mol. Remember this as a sanity check and you can eliminate wrong options instantly."}
],

"9. Classification of Elements & Periodicity": [
  {type:"pyq", q:"The correct order of first ionisation enthalpy is:",
   options:["Be < B < N < O","N < O < Be < B","B < Be < O < N","B < Be < N < O"], answer:2,
   steps:["Be (2s²) has a filled s subshell, which is more stable than B (2p¹) → Be > B.",
    "N (2p³) is half-filled and stable; adding a 4th electron in O (2p⁴) introduces pairing repulsion → N > O.",
    "Values (kJ mol⁻¹): B 801 < Be 899 < O 1314 < N 1402."],
   ans:"B < Be < O < N (option C)", tip:"Two famous anomalies decide this: Be > B (2s² vs 2p¹) and N > O (half-filled vs paired 2p). Both appear almost every year."},
  {type:"pyq", q:"The correct order of ionic radii is:",
   options:["F⁻ > O²⁻ > N³⁻ > Na⁺ > Mg²⁺","O²⁻ > F⁻ > N³⁻ > Mg²⁺ > Na⁺","Mg²⁺ > Na⁺ > F⁻ > O²⁻ > N³⁻","N³⁻ > O²⁻ > F⁻ > Na⁺ > Mg²⁺"], answer:3,
   steps:["These five ions are isoelectronic (10 electrons each).",
    "For isoelectronic species the radius decreases as nuclear charge increases (electrons pulled in more strongly).",
    "Z: N 7 < O 8 < F 9 < Na 11 < Mg 12 → radii 171 > 140 > 133 > 95 > 65 pm."],
   ans:"N³⁻ > O²⁻ > F⁻ > Na⁺ > Mg²⁺ (option D)", tip:"Isoelectronic series: radius ∝ 1/nuclear charge. Sort by Z and you have the answer."}
],

"10. p-Block Elements": [
  {type:"pyq", q:"The correct order of acidic strength of the oxoacids of chlorine is:",
   options:["HClO₂ > HClO > HClO₄ > HClO₃","HClO > HClO₂ > HClO₃ > HClO₄","HClO₄ > HClO₃ > HClO₂ > HClO","HClO₃ > HClO > HClO₂ > HClO"], answer:2,
   steps:["More terminal oxygen atoms → more resonance stabilisation of the conjugate base.",
    "Acidity increases with the oxidation state of chlorine: +7 > +5 > +3 > +1.",
    "Hence HClO₄ > HClO₃ > HClO₂ > HClO."],
   ans:"HClO₄ > HClO₃ > HClO₂ > HClO (option C)", tip:"For oxoacids of the same element, count the terminal O atoms: more O = stronger acid (electronegativity of the central atom being the same)."},
  {type:"imp", q:"The correct order of bond angle in the hydrides of group 15 is:",
   options:["NH₃ > PH₃ > AsH₃ > SbH₃","PH₃ > NH₃ > AsH₃ > SbH₃","SbH₃ > AsH₃ > PH₃ > NH₃","NH₃ > AsH₃ > PH₃ > SbH₃"], answer:0,
   steps:["NH₃ is sp³ hybridised with 107° angle (lone-pair repulsion opens it up).",
    "For P, As, Sb the central atom is large/less electronegative → bonding approaches pure p; angles drop to 93.5°, 92°, 91°.",
    "So the angle decreases down the group."],
   ans:"NH₃ > PH₃ > AsH₃ > SbH₃ (option A)", tip:"Down group 15 the angle falls towards 90° because the heavier atoms stop hybridising effectively — the reverse of what most students assume."},
  {type:"pyq", q:"Which of the following tetrahalides is NOT hydrolysed by water?",
   options:["SnCl₄","TiCl₄","CCl₄","SiCl₄"], answer:2,
   steps:["Hydrolysis requires the central atom to accept a water molecule/lone pair — i.e. an available d orbital (or enough size).",
    "Carbon has no d orbitals in its valence shell, so the C–Cl bond is not attacked.",
    "Si, Sn and Ti have vacant d orbitals → SiCl₄ fumes in moist air, SnCl₄ and TiCl₄ hydrolyse readily."],
   ans:"CCl₄ (option C)", tip:"'Vacant d-orbital' is the whole reason SiCl₄ hydrolyses but CCl₄ is an inert solvent. Same logic explains why CCl₄ has no C(OH)₄."}
],

"11. d- and f-Block Elements": [
  {type:"pyq", q:"The spin-only magnetic moment of Fe³⁺ is:",
   options:["1.73 BM","3.87 BM","4.90 BM","5.92 BM"], answer:3,
   steps:["Fe (Z = 26) = [Ar]3d⁶4s² → Fe³⁺ = [Ar]3d⁵.",
    "3d⁵ high spin → 5 unpaired electrons.",
    "μ = √(n(n+2)) = √(5 × 7) = √35 = 5.92 BM."],
   ans:"5.92 BM (option D)", tip:"Memorise the ladder: n = 1 → 1.73, 2 → 2.83, 3 → 3.87, 4 → 4.90, 5 → 5.92 BM. Then no calculation is needed in the exam."},
  {type:"imp", q:"Zr and Hf have almost identical atomic radii and are very difficult to separate. This is because of:",
   options:["the diagonal relationship","lanthanoid contraction","identical ionisation enthalpies","the inert pair effect of the f block"], answer:1,
   steps:["The 4f lanthanoids lie immediately before Hf in the periodic table.",
    "4f electrons shield the nuclear charge poorly, so the size contracts steadily across the lanthanoids.",
    "By the time Hf is reached, this contraction almost cancels the expected increase from 5d → Zr ≈ Hf in size."],
   ans:"lanthanoid contraction (option B)", tip:"Quote two consequences: Zr–Hf and Nb–Ta pairs are chemically near-identical, and 5d elements are abnormally dense."},
  {type:"pyq", q:"The intense purple colour of KMnO₄ is due to:",
   options:["f–f transition of Mn⁷⁺","ligand-to-metal charge transfer, since Mn(VII) is d⁰","d–d transition of Mn⁷⁺","an interstitial defect in the crystal"], answer:1,
   steps:["In MnO₄⁻ manganese is in the +7 state → d⁰, so d–d transitions are impossible.",
    "The colour comes from charge transfer: an electron moves from an O(2p) orbital to Mn.",
    "Charge-transfer bands are fully allowed → very intense colour."],
   ans:"ligand-to-metal charge transfer (option B)", tip:"d⁰ and d¹⁰ ions cannot show d–d transitions. Deep colours of MnO₄⁻, CrO₄²⁻ and Cr₂O₇²⁻ are all charge-transfer bands."}
],

"12. Coordination Compounds": [
  {type:"pyq", q:"The number of geometrical isomers of [Co(NH₃)₃Cl₃] is:",
   options:["1","4","2","3"], answer:2,
   steps:["This is an octahedral Ma₃b₃ complex.",
    "fac: the three NH₃ occupy a face; mer: they lie along a meridian, with the three Cl⁻ also in a meridian.",
    "Only 2 geometrical isomers; neither is optically active."],
   ans:"2 (fac and mer) (option C)", tip:"Ma₃b₃ octahedral = fac + mer. The other patterns to memorise: Ma₂b₂ square planar (cis/trans) and Mabcd (optically active)."},
  {type:"pyq", q:"[Fe(CN)₆]³⁻ has a magnetic moment of 1.73 BM. This corresponds to:",
   options:["low-spin d⁶ with 0 unpaired electrons","high-spin d⁵ with 5 unpaired electrons","d⁵ with 3 unpaired electrons","low-spin d⁵ with 1 unpaired electron (t₂g⁵)"], answer:3,
   steps:["Fe³⁺ = 3d⁵ and CN⁻ is a strong-field ligand (large Δo).",
    "Electrons pair up in t₂g before occupying e_g → t₂g⁵ e_g⁰.",
    "1 unpaired electron → μ = √(1 × 3) = 1.73 BM."],
   ans:"low-spin d⁵ with 1 unpaired electron (option D)", tip:"Strong-field ligands (CN⁻, CO, NO₂⁻) pair up first; weak-field (H₂O, F⁻, Cl⁻) maximise unpaired electrons. 1.73 BM always means exactly one unpaired electron."},
  {type:"imp", q:"The effective atomic number (EAN) of cobalt in [Co(NH₃)₆]³⁺ is:",
   options:["36","35","34","33"], answer:0,
   steps:["Electrons already on Co³⁺ = 27 − 3 = 24.",
    "Each of the 6 NH₃ ligands donates 2 electrons → 12 electrons.",
    "EAN = 24 + 12 = 36 (krypton configuration)."],
   ans:"36 (option A)", tip:"EAN = (Z − oxidation state) + 2 × (number of donor atoms). It normally lands on a noble-gas number — use that to check yourself."}
],

"13. Purification & Characterisation of Organic Compounds": [
  {type:"imp", q:"A liquid that decomposes below its boiling point is best purified by:",
   options:["fractional distillation","sublimation","distillation under reduced pressure","steam distillation"], answer:2,
   steps:["Lowering the external pressure lowers the boiling point of the liquid.",
    "It can then distil at a temperature below its decomposition temperature.",
    "Standard examples: glycerol, aniline and sugar solutions."],
   ans:"distillation under reduced pressure (option C)", tip:"'Decomposes on heating' → reduce the pressure, not the temperature. Steam distillation is only for steam-volatile, water-immiscible liquids."},
  {type:"pyq", q:"In Lassaigne's test, the appearance of Prussian blue confirms the presence of:",
   options:["a halogen","nitrogen","phosphorus","sulphur"], answer:1,
   steps:["Fusion with sodium converts nitrogen into sodium cyanide (NaCN).",
    "NaCN + FeSO₄ gives sodium ferrocyanide Na₄[Fe(CN)₆], which is then oxidised by Fe³⁺.",
    "The blue complex Fe₄[Fe(CN)₆]₃ is ferric ferrocyanide = Prussian blue."],
   ans:"nitrogen (option B)", tip:"Colour codes: Prussian blue = N alone; blood-red Fe(SCN)²⁺ = N and S together. That is how examiners separate N from N + S."}
],

"14. Some Basic Principles of Organic Chemistry (GOC)": [
  {type:"pyq", q:"The number of monochloro derivatives (excluding stereoisomers) of 2-methylbutane is:",
   options:["2","5","3","4"], answer:3,
   steps:["Structure: CH₃–CH(CH₃)–CH₂–CH₃. Count distinct sets of hydrogens, not hydrogens.",
    "The two methyls on C-2 are equivalent by free rotation → one set; then the C-2 H, the C-3 CH₂ and the terminal C-4 CH₃ are three more sets.",
    "4 distinct sets → 4 monochloro products."],
   ans:"4 (option D)", tip:"Count hydrogen 'sets'. The two methyl groups on the same carbon are always equivalent — the most common counting error."},
  {type:"imp", q:"The correct order of stability of the carbocations is:",
   options:["CH₃⁺ > (CH₃)₃C⁺ > C₆H₅CH₂⁺ > (C₆H₅)₃C⁺","(C₆H₅)₃C⁺ > C₆H₅CH₂⁺ > (CH₃)₃C⁺ > CH₃⁺","C₆H₅CH₂⁺ > (C₆H₅)₃C⁺ > CH₃⁺ > (CH₃)₃C⁺","(CH₃)₃C⁺ > (C₆H₅)₃C⁺ > C₆H₅CH₂⁺ > CH₃⁺"], answer:1,
   steps:["Stabilisation = resonance + hyperconjugation + inductive effects.",
    "Three phenyl rings delocalise the positive charge best → triphenylmethyl cation is most stable.",
    "Then benzyl (one ring), then tertiary alkyl, then methyl."],
   ans:"(C₆H₅)₃C⁺ > C₆H₅CH₂⁺ > (CH₃)₃C⁺ > CH₃⁺ (option B)", tip:"Resonance beats hyperconjugation, which beats induction. Phenyl groups win every carbocation-stability question."},
  {type:"pyq", q:"Which of the following is antiaromatic?",
   options:["benzene","cyclopentadienyl anion","cyclopentadienyl cation","cycloheptatrienyl cation"], answer:2,
   steps:["Aromatic = planar, cyclic, fully conjugated and (4n + 2)π electrons.",
    "The cyclopentadienyl cation has 4π electrons = 4n → antiaromatic (destabilised).",
    "The cyclopentadienyl anion (6π), tropylium cation (6π) and benzene (6π) are all aromatic."],
   ans:"cyclopentadienyl cation (option C)", tip:"Aromatic 4n + 2, antiaromatic 4n — both need planarity and full conjugation. Lone pairs count only if they sit in the π system."}
],

"15. Hydrocarbons": [
  {type:"pyq", q:"Propene reacts with HBr in the presence of benzoyl peroxide to give mainly:",
   options:["2-bromopropane","1,2-dibromopropane","propan-2-ol","1-bromopropane"], answer:3,
   steps:["Peroxide generates radicals → free-radical (anti-Markovnikov) addition.",
    "Br• adds to the terminal carbon first, giving the more stable secondary radical.",
    "Hydrogen abstraction then gives 1-bromopropane."],
   ans:"1-bromopropane (option D)", tip:"'Peroxide effect' = anti-Markovnikov. Without peroxide the product is 2-bromopropane — the single most-tested addition pair."},
  {type:"pyq", q:"An alkene on ozonolysis gives 2 moles of acetone. The alkene is:",
   options:["2-methylpropene","2,3-dimethylbut-1-ene","2,3-dimethylbut-2-ene","but-2-ene"], answer:2,
   steps:["Ozonolysis cleaves the C=C and gives one carbonyl compound per side of the double bond.",
    "Acetone (CH₃)₂C=O appearing twice means BOTH alkene carbons are C(CH₃)₂.",
    "Joining them: (CH₃)₂C=C(CH₃)₂ = 2,3-dimethylbut-2-ene."],
   ans:"2,3-dimethylbut-2-ene (option C)", tip:"Reverse-join the carbonyl carbons across a double bond. One mole of carbonyl = one side of the original C=C."},
  {type:"imp", q:"The correct order of acidic strength of the hydrocarbons is:",
   options:["HC≡CH > CH₂=CH₂ > CH₃CH₃","CH₃CH₃ > CH₂=CH₂ > HC≡CH","CH₂=CH₂ > HC≡CH > CH₃CH₃","all three are equally acidic"], answer:0,
   steps:["Acidity depends on the stability of the carbanion, which depends on the s-character of the carbon orbital.",
    "More s-character holds the electron pair closer: sp (50%) > sp² (33%) > sp³ (25%).",
    "So ethyne loses H⁺ most easily (with NaNH₂), ethane least."],
   ans:"HC≡CH > CH₂=CH₂ > CH₃CH₃ (option A)", tip:"pKa values: ~25 (alkyne), ~44 (alkene), ~50 (alkane). More s-character = more acidic, always."}
],

"16. Organic Compounds Containing Halogens": [
  {type:"pyq", q:"The correct order of SN² reactivity is:",
   options:["(CH₃)₂CHBr > CH₃Br > (CH₃)₃CBr > CH₃CH₂Br","CH₃Br > CH₃CH₂Br > (CH₃)₂CHBr > (CH₃)₃CBr","(CH₃)₃CBr > (CH₃)₂CHBr > CH₃CH₂Br > CH₃Br","CH₃CH₂Br > CH₃Br > (CH₃)₂CHBr > (CH₃)₃CBr"], answer:1,
   steps:["SN² proceeds through a 5-coordinate transition state, so steric hindrance decides the rate.",
    "Back-side attack is easiest in CH₃Br and impossible practically in tert-butyl bromide.",
    "Order: methyl > primary > secondary > tertiary."],
   ans:"CH₃Br > CH₃CH₂Br > (CH₃)₂CHBr > (CH₃)₃CBr (option B)", tip:"SN² is decided by sterics (methyl fastest); SN¹ is decided by carbocation stability (3° fastest). The two orders are exactly reversed — the examiner's favourite trap."},
  {type:"pyq", q:"Chlorobenzene heated with NaOH at 623 K and 300 atm gives:",
   options:["benzyl alcohol","sodium benzoate","phenol (via sodium phenoxide)","benzene"], answer:2,
   steps:["This is Dow's process — nucleophilic substitution under drastic conditions.",
    "C₆H₅Cl + 2NaOH → C₆H₅ONa + NaCl + H₂O.",
    "Acidification of the phenoxide gives phenol."],
   ans:"phenol (option C)", tip:"Chlorobenzene is inert under normal SN conditions. If you see '623 K / 300 atm' with chlorobenzene, the answer is phenol."}
],

"17. Organic Compounds Containing Oxygen": [
  {type:"pyq", q:"Phenol reacts with CHCl₃ and aqueous NaOH to give mainly:",
   options:["salicylic acid","benzaldehyde","benzoic acid","salicylaldehyde (2-hydroxybenzaldehyde)"], answer:3,
   steps:["This is the Reimer–Tiemann reaction; the electrophile is dichlorocarbene (:CCl₂) generated from CHCl₃ + NaOH.",
    "The phenoxide ion directs it to the ortho position.",
    "Hydrolysis of the intermediate gives salicylaldehyde as the major product."],
   ans:"salicylaldehyde (option D)", tip:"Reimer–Tiemann (CHCl₃/NaOH) = ortho aldehyde; Kolbe's reaction (CO₂/NaOH) = ortho acid (salicylic acid). Never mix the two reagents."},
  {type:"pyq", q:"Which of the following does NOT give a silver mirror with Tollens' reagent?",
   options:["acetone","acetaldehyde","formic acid","benzaldehyde"], answer:0,
   steps:["Tollens' reagent (ammoniacal AgNO₃) is oxidised by aldehydes and by α-hydroxy ketones.",
    "Acetone is a simple ketone with no –OH on the α-carbon → no reaction.",
    "Formic acid is a 'hidden aldehyde' (HCO–OH) and does reduce Tollens'."],
   ans:"acetone (option A)", tip:"Tollens'/Fehling's answer three groups: aldehydes, α-hydroxy ketones and formic acid. Every other ketone says no."},
  {type:"imp", q:"Which of the following does NOT undergo the Cannizzaro reaction?",
   options:["C₆H₅CHO","(CH₃)₃C–CHO","CH₃CHO","HCHO"], answer:2,
   steps:["Cannizzaro reaction (disproportionation in concentrated alkali) needs an aldehyde with NO α-hydrogen.",
    "Acetaldehyde has three α-hydrogens → it undergoes aldol condensation instead.",
    "HCHO, benzaldehyde and trimethylacetaldehyde have no α-H → they do undergo Cannizzaro."],
   ans:"CH₃CHO (option C)", tip:"One test decides it: α-hydrogen present → aldol; absent → Cannizzaro. Check for the H on the carbon next to the CHO."}
],

"18. Organic Compounds Containing Nitrogen": [
  {type:"pyq", q:"The correct order of base strength in aqueous solution is:",
   options:["(C₂H₅)₃N > (C₂H₅)₂NH > C₂H₅NH₂ > NH₃","(C₂H₅)₂NH > (C₂H₅)₃N > C₂H₅NH₂ > NH₃","C₂H₅NH₂ > NH₃ > (C₂H₅)₂NH > (C₂H₅)₃N","NH₃ > C₂H₅NH₂ > (C₂H₅)₂NH > (C₂H₅)₃N"], answer:1,
   steps:["In water three effects compete: +I effect of alkyl groups (increases basicity), steric hindrance and solvation of the conjugate acid (decrease it).",
    "The secondary amine has the best balance of +I and solvation of (C₂H₅)₂NH₂⁺.",
    "The tertiary amine, though richest in electrons, loses H-bonding solvation → falls below the 2° amine."],
   ans:"(C₂H₅)₂NH > (C₂H₅)₃N > C₂H₅NH₂ > NH₃ (option B)", tip:"In water: 2° > 3° > 1° > NH₃. In the gas phase (no solvation) it is simply 3° > 2° > 1° > NH₃ — the medium decides."},
  {type:"pyq", q:"A secondary amine reacts with nitrous acid (HNO₂) to give:",
   options:["a colourless gas (N₂)","a yellow oily N-nitrosamine","an isocyanide","a diazonium salt"], answer:1,
   steps:["Primary amine + HNO₂ → alcohol + N₂ (gas bubbles).",
    "Secondary amine + HNO₂ → N-nitrosamine, a yellow oily liquid that is insoluble in water.",
    "Tertiary amine + HNO₂ → only a soluble nitrite salt, no visible change."],
   ans:"yellow oily N-nitrosamine (option B)", tip:"Nitrous-acid fingerprint: 1° → N₂ bubbles, 2° → yellow oil, 3° → nothing visible. That is the whole test."}
],

"19. Biomolecules": [
  {type:"pyq", q:"Which of the following is a non-reducing sugar?",
   options:["sucrose","maltose","glucose","lactose"], answer:0,
   steps:["A reducing sugar has a free anomeric –OH (hemiacetal) that can open to the aldehyde form.",
    "In sucrose, C-1 of glucose and C-2 of fructose are joined through the glycosidic oxygen, so BOTH anomeric carbons are locked.",
    "No free anomeric –OH → sucrose cannot reduce Tollens' or Fehling's solution."],
   ans:"sucrose (option A)", tip:"Sucrose = glucose α1→β2 fructose (both ends blocked). Maltose (α1→4) and lactose (β1→4) keep one free anomeric carbon, so both are reducing."},
  {type:"imp", q:"Denaturation of a protein destroys its:",
   options:["primary and secondary structure","primary structure only","peptide bonds only","secondary and tertiary structure, but not the primary structure"], answer:3,
   steps:["Denaturation (heat, pH change, urea) breaks hydrogen bonds and hydrophobic interactions that hold the folding.",
    "Covalent peptide bonds are strong and are NOT broken.",
    "Hence the amino-acid sequence (primary structure) survives while the folding is lost."],
   ans:"secondary and tertiary structure, not primary (option D)", tip:"Boiled-egg logic: the sequence is untouched, only the shape is destroyed. Denaturation ≠ hydrolysis."},
  {type:"pyq", q:"The number of hydrogen bonds between guanine and cytosine in DNA is:",
   options:["3","2","1","4"], answer:0,
   steps:["Base pairing: A pairs with T through 2 hydrogen bonds.",
    "G pairs with C through 3 hydrogen bonds (extra donor–acceptor set on the guanine).",
    "Therefore GC-rich DNA has a higher melting temperature."],
   ans:"3 (option A)", tip:"A–T = 2, G–C = 3. A standard follow-up: higher GC content → more stable DNA → higher Tm."}
],

"20. Principles Related to Practical Chemistry": [
  {type:"imp", q:"A cation gives a gelatinous white precipitate with NH₄OH in the presence of NH₄Cl that dissolves in excess NaOH but NOT in excess NH₄OH. The cation is:",
   options:["Zn²⁺","Al³⁺","Fe³⁺","Cr³⁺"], answer:1,
   steps:["Group III reagent is buffered NH₄OH + NH₄Cl.",
    "Al³⁺ gives gelatinous white Al(OH)₃ which is amphoteric → dissolves in excess NaOH forming aluminate.",
    "Zn(OH)₂ is also white but dissolves in excess NH₄OH; Fe(OH)₃ is reddish-brown and Cr(OH)₃ grey-green."],
   ans:"Al³⁺ (option B)", tip:"Group III colours to memorise: Al³⁺ gelatinous white, Fe³⁺ reddish-brown, Cr³⁺ grey-green. Solubility in excess NH₄OH separates Al³⁺ from Zn²⁺."},
  {type:"pyq", q:"The brown ring test confirms the presence of the anion:",
   options:["NO₂⁻","Cl⁻","SO₄²⁻","NO₃⁻"], answer:3,
   steps:["Add freshly prepared FeSO₄ solution, then pour concentrated H₂SO₄ slowly down the side of the test tube.",
    "Nitrate is reduced to NO, which coordinates to Fe²⁺ forming the complex [Fe(H₂O)₅NO]²⁺.",
    "This nitrosyl complex appears as a brown ring at the junction of the two layers."],
   ans:"NO₃⁻ (option D)", tip:"The brown ring complex is [Fe(H₂O)₅NO]²⁺. The acid must be added along the wall — the ring only forms at the interface."}
]

};


