/* ===== BULK BANK C — 50 hard JEE Main PYQ-pattern MCQs per chapter ===== */
const BULK_CH = {
"1. Some Basic Concepts in Chemistry": [
{type:"hard",q:"A sample of CaCO₃ (100 g) is heated until fully decomposed (CaCO₃ → CaO + CO₂). The mass of CO₂ produced is:",options:["22 g","44 g","56 g","100 g"],answer:1,steps:["Moles of CaCO₃ = 100/100 = 1 mol.","1 mol CaCO₃ gives 1 mol CO₂.","Mass of CO₂ = 1 × 44 = 44 g."],ans:"44 g (option B)",tip:"Molar masses: CaCO₃ = 100, CO₂ = 44. One mole in → one mole out; the leftover 56 g is CaO by mass balance."},
{type:"hard",q:"The number of molecules in 4.4 g of CO₂ is:",options:["6.022 × 10²³","6.022 × 10²²","6.022 × 10²¹","3.011 × 10²³"],answer:1,steps:["Molar mass of CO₂ = 44 g/mol.","Moles = 4.4/44 = 0.1 mol.","Molecules = 0.1 × 6.022 × 10²³ = 6.022 × 10²²."],ans:"6.022 × 10²² (option B)",tip:"4.4 g is one-tenth of a mole (44 g) — scale Avogadro's number by the same tenth. Powers of ten decide it."},
{type:"hard",q:"1.0 g of hydrogen contains approximately the same number of atoms as:",options:["12 g of carbon","16 g of oxygen","1 g of helium","71 g of chlorine"],answer:0,steps:["1.0 g H = 1.0 mol of H atoms.","12 g C = 12/12 = 1.0 mol of atoms.","Equal moles → equal atom counts."],ans:"12 g of carbon (option A)",tip:"Convert everything to moles of ATOMS (not molecules): H (1) and C (12) line up 1 g ↔ 12 g exactly."},
{type:"hard",q:"The molarity of a solution prepared by dissolving 4.0 g of NaOH in water to make 250 mL of solution is (Na = 23):",options:["0.1 M","0.4 M","1.0 M","0.16 M"],answer:1,steps:["Molar mass of NaOH = 40 g/mol → moles = 4.0/40 = 0.1 mol.","Volume = 0.25 L.","M = 0.1/0.25 = 0.4 M."],ans:"0.4 M (option B)",tip:"Moles first (4/40 = 0.1), then divide by litres (0.25). Watch option A, which forgets the volume conversion."},
{type:"hard",q:"The simplest (empirical) formula of a compound with 40% C, 6.7% H and 53.3% O by mass is:",options:["CH₂O","C₂H₄O₂","CHO","CH₃O"],answer:0,steps:["Moles: C = 40/12 = 3.33, H = 6.7/1 = 6.7, O = 53.3/16 = 3.33.","Divide by smallest: C:H:O = 1:2:1.","Empirical formula = CH₂O."],ans:"CH₂O (option A)",tip:"Percentages → divide by atomic masses → divide by the smallest. 1:2:1 falls out; molecular formula would need the molar mass."},
{type:"hard",q:"10 mL of 0.5 M HCl is diluted to 100 mL. The molarity of the diluted solution is:",options:["0.5 M","0.05 M","0.005 M","5 M"],answer:1,steps:["M₁V₁ = M₂V₂.","M₂ = (0.5 × 10)/100 = 5/100.","= 0.05 M."],ans:"0.05 M (option B)",tip:"Ten-fold volume increase → ten-fold molarity drop. M₁V₁ = M₂V₂ in one line; volume units cancel."},
{type:"hard",q:"The volume of CO₂ at STP liberated when 2.5 g of CaCO₃ reacts completely with excess HCl is:",options:["0.56 L","2.24 L","0.28 L","22.4 L"],answer:0,steps:["Moles of CaCO₃ = 2.5/100 = 0.025 mol.","Each mole gives one mole of CO₂.","V = 0.025 × 22.4 = 0.56 L."],ans:"0.56 L (option A)",tip:"0.025 mol × 22.4 L/mol: halve 22.4 twice mentally (11.2 → 0.56). Small mole counts give sub-litre volumes."},
{type:"hard",q:"The number of moles of water in 90 g of water is:",options:["90","18","5","5.5"],answer:2,steps:["Molar mass of H₂O = 18 g/mol.","Moles = 90/18.","= 5 mol."],ans:"5 (option C)",tip:"90/18 = 5 exactly — water's molar mass (18) is the divisor for every such mass in grams."},
{type:"hard",q:"An oxide of nitrogen contains 30.4% N by mass (N = 14, O = 16). Its empirical formula is:",options:["NO","NO₂","N₂O","N₂O₅"],answer:1,steps:["N: 30.4/14 = 2.17; O: 69.6/16 = 4.35.","Ratio N:O = 2.17:4.35 = 1:2.","Empirical formula = NO₂."],ans:"NO₂ (option B)",tip:"Divide by atomic masses, then by the smaller: 1:2 emerges. Never guess the formula from mass percentages directly."},
{type:"hard",q:"The mass of one molecule of water is approximately:",options:["18 g","3.0 × 10⁻²³ g","3.0 × 10⁻²⁶ kg","1.66 × 10⁻²⁴ g"],answer:1,steps:["18 g of water = 6.022 × 10²³ molecules.","One molecule = 18/(6.022 × 10²³) g.","≈ 3.0 × 10⁻²³ g."],ans:"3.0 × 10⁻²³ g (option B)",tip:"Molar mass ÷ Avogadro's number gives mass of one molecule; option C has the right digits but the wrong unit (kg vs g)."},
{type:"hard",q:"The vapour density of a gas is 22. Its molecular mass is:",options:["11","22","44","88"],answer:2,steps:["Vapour density = molecular mass/2.","Molecular mass = 2 × VD.","= 2 × 22 = 44."],ans:"44 (option C)",tip:"Molecular mass = 2 × VD, always. Option B forgets the doubling — the single most-tested definition in the chapter."},
{type:"hard",q:"The equivalent weight of H₂SO₄ in the reaction H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O is (M = 98):",options:["98","49","32.7","196"],answer:1,steps:["Both H⁺ are neutralised → n-factor = 2.","Equivalent weight = M/n-factor.","= 98/2 = 49."],ans:"49 (option B)",tip:"n-factor for acids = replaceable H⁺ IN THE GIVEN reaction; both protons react here. If only one reacted it would be 98."},
{type:"hard",q:"A sample of limestone is 80% pure CaCO₃. The mass of CO₂ obtained from 125 g of the sample is:",options:["44 g","55 g","35.2 g","70.4 g"],answer:2,steps:["Pure CaCO₃ = 0.8 × 125 = 100 g = 1 mol.","1 mol CaCO₃ → 1 mol CO₂.","Mass = 44 × 0.8 = 35.2 g."],ans:"35.2 g (option C)",tip:"Apply purity FIRST (100 g reactive), then the 100→44 ratio. Option B computes CO₂ for 100% purity then forgets to scale."},
{type:"hard",q:"For the reaction N₂ + 3H₂ → 2NH₃, if 14 g N₂ reacts with 6 g H₂, the limiting reagent is:",options:["N₂","H₂","neither (exact)","NH₃"],answer:0,steps:["Moles: N₂ = 14/28 = 0.5; H₂ = 6/2 = 3.","Required ratio N₂:H₂ = 1:3 → 0.5 mol N₂ needs 1.5 mol H₂.","N₂ runs out first (0.5 < 3/3 = 1.0 equivalent) → N₂ limits."],ans:"N₂ (option A)",tip:"Divide each mole count by its coefficient: 0.5/1 vs 3/3 — the smaller quotient (0.5) is limiting. Masses alone deceive."},
{type:"hard",q:"The normality of 0.5 M H₂SO₄ solution (complete neutralisation) is:",options:["0.5 N","1.0 N","0.25 N","2.0 N"],answer:1,steps:["Normality = molarity × n-factor.","n-factor of H₂SO₄ (dibasic) = 2.","N = 0.5 × 2 = 1.0 N."],ans:"1.0 N (option B)",tip:"N = M × n-factor in one step; option A ignores the n-factor — normality exceeds molarity for all polybasic acids."},
{type:"hard",q:"The number of atoms in 0.5 mol of O₂ molecules is:",options:["3.011 × 10²³","6.022 × 10²³","1.5 × 6.022 × 10²³","6.044 × 10²³"],answer:1,steps:["0.5 mol O₂ molecules = 0.5 × 6.022 × 10²³ molecules.","Each molecule has 2 atoms → multiply by 2.","Atoms = 6.022 × 10²³."],ans:"6.022 × 10²³ (option B)",tip:"Moles of MOLECULES × atomicity = moles of atoms. The ×2 exactly cancels the 0.5 — engineered to trap the careless."},
{type:"hard",q:"The mass percentage of oxygen in H₂SO₄ (H = 1, S = 32) is:",options:["65.3%","32.7%","16.3%","96%"],answer:0,steps:["M(H₂SO₄) = 2 + 32 + 64 = 98.","Mass of O = 4 × 16 = 64.","%O = 64/98 × 100 = 65.3%."],ans:"65.3% (option A)",tip:"Oxygen's 64 of 98 dominates the mass; option B is sulphur's share. Cross-total: 2.04 + 32.7 + 65.3 ≈ 100."},
{type:"hard",q:"25 mL of 0.1 M NaOH completely neutralises 20 mL of HCl. The molarity of HCl is:",options:["0.08 M","0.125 M","0.2 M","0.1 M"],answer:1,steps:["N₁V₁ = N₂V₂ (both monobasic/monoacidic, so N = M).","M_HCl = (0.1 × 25)/20 = 2.5/20.","= 0.125 M."],ans:"0.125 M (option B)",tip:"N₁V₁ = N₂V₂ at neutralisation; with n-factors of 1 this is M₁V₁ = M₂V₂. Volume ratio 25:20 inverts to 0.125."},
{type:"hard",q:"The number of moles of electrons in 1.0 g of electrons is approximately (m_e = 9.1 × 10⁻³¹ kg):",options:["1820","9.1 × 10³¹","6.022 × 10²³","1.1 × 10⁻²⁷"],answer:0,steps:["Number of electrons = 10⁻³/(9.1 × 10⁻³¹) = 1.099 × 10²⁷.","Moles = 1.099 × 10²⁷/(6.022 × 10²³).","≈ 1820 mol."],ans:"1820 (option A)",tip:"Mass → particles (÷ m_e) → moles (÷ N_A); the kilogram-to-gram 10⁻³ is the step everyone drops."},
{type:"hard",q:"A hydrocarbon contains 85.7% C (H = 1, C = 12). Its empirical formula is:",options:["CH","CH₂","CH₃","C₂H₃"],answer:1,steps:["C: 85.7/12 = 7.14; H: 14.3/1 = 14.3.","Ratio = 7.14:14.3 = 1:2.","Empirical formula = CH₂."],ans:"CH₂ (option B)",tip:"85.7:14.3 is the signature CH₂ fingerprint (alkenes). Divide by masses, then by the smaller — 1:2 every time."},
{type:"hard",q:"The percentage composition of hydrogen in water (H = 1, O = 16) is:",options:["5.6%","11.1%","88.9%","50%"],answer:1,steps:["M(H₂O) = 18.","Mass of H = 2.","%H = 2/18 × 100 = 11.1%."],ans:"11.1% (option B)",tip:"2/18 = 1/9 = 11.1% — the complement 88.9% is oxygen's share. Cross-total must reach 100."},
{type:"hard",q:"The ratio of the number of oxygen atoms in 32 g O₂ to that in 44 g CO₂ is:",options:["1:1","2:1","1:2","4:1"],answer:1,steps:["32 g O₂ = 1 mol → 2 mol O atoms.","44 g CO₂ = 1 mol → 2 mol O atoms.","Ratio = 1:1."],ans:"1:1 (option B)",tip:"Convert to moles of OXYGEN atoms, not molecules: both give 2 mol of O. Equal atom-moles → 1:1."},
{type:"hard",q:"For the reaction 2Al + 6HCl → 2AlCl₃ + 3H₂, 5.4 g Al (Al = 27) produces H₂ equal to:",options:["0.2 mol","0.3 mol","0.6 mol","0.1 mol"],answer:1,steps:["Moles of Al = 5.4/27 = 0.2 mol.","2 mol Al → 3 mol H₂.","H₂ = 0.2 × 3/2 = 0.3 mol."],ans:"0.3 mol (option B)",tip:"Scale by the coefficient ratio 3/2 after finding moles of Al. Option A forgets the 3-for-2 stoichiometry."},
{type:"hard",q:"The molality of a solution with 0.5 mol solute in 500 g solvent is:",options:["1 m","0.5 m","2 m","0.25 m"],answer:0,steps:["Molality = moles of solute/kg of solvent.","= 0.5/0.5 = 1 m.","Unlike molarity it is temperature-independent."],ans:"1 m (option A)",tip:"Molality uses kg of SOLVENT only — 500 g = 0.5 kg. Molarity would need total solution volume instead."},
{type:"hard",q:"The number of water molecules in 1 mL of water (density 1 g/mL) is:",options:["3.34 × 10²²","6.022 × 10²³","1.8 × 10²³","3.011 × 10²²"],answer:0,steps:["1 mL = 1 g = 1/18 mol.","Molecules = (1/18) × 6.022 × 10²³.","= 3.34 × 10²²."],ans:"3.34 × 10²² (option A)",tip:"1 g water = 1/18 mol — memorise 3.34 × 10²² molecules per mL; it recurs in density-based MCQs."},
{type:"hard",q:"In the reaction 2KMnO₄ + 10FeSO₄ + 8H₂SO₄ → products, the n-factor of KMnO₄ in acidic medium is:",options:["1","5","3","2"],answer:1,steps:["Mn(VII) → Mn(II): change = 7 − 2 = 5 electrons.","n-factor = total electron change per formula.","= 5."],ans:"5 (option B)",tip:"Acidic KMnO₄ always gains 5 e⁻ (VII→II); neutral gives 3, alkaline gives 1. Medium decides the n-factor."},
{type:"hard",q:"The mass of 2.5 mol of CaCO₃ (Ca = 40) is:",options:["100 g","250 g","40 g","25 g"],answer:1,steps:["M(CaCO₃) = 40 + 12 + 48 = 100.","Mass = moles × molar mass.","= 2.5 × 100 = 250 g."],ans:"250 g (option B)",tip:"Molar mass 100 makes it trivial: 2.5 × 100 = 250. Option A is the mass of 1 mol."},
{type:"hard",q:"A 100 mL solution of 0.2 M Na₂CO₃ contains Na⁺ ions equal to:",options:["0.02 mol","0.04 mol","0.01 mol","0.2 mol"],answer:1,steps:["Moles of Na₂CO₃ = 0.2 × 0.1 = 0.02 mol.","Each formula gives 2 Na⁺.","Na⁺ = 0.04 mol."],ans:"0.04 mol (option B)",tip:"Ion-moles = salt-moles × subscript. The ×2 doubles 0.02 to 0.04 — option A stops one step early."},
{type:"hard",q:"The volume of 0.1 M H₂SO₄ needed to neutralise 25 mL of 0.2 M NaOH is:",options:["25 mL","50 mL","12.5 mL","100 mL"],answer:0,steps:["N(H₂SO₄) = 0.1 × 2 = 0.2 N; N(NaOH) = 0.2 N.","N₁V₁ = N₂V₂ → 0.2 × V = 0.2 × 25.","V = 25 mL."],ans:"25 mL (option A)",tip:"Convert to normality first — equal normalities neutralise in EQUAL volumes. Option B uses molarity directly."},
{type:"hard",q:"The molecular formula of a compound with empirical formula CH₂O and molar mass 180 is:",options:["CH₂O","C₆H₁₂O₆","C₂H₄O₂","C₃H₆O₃"],answer:1,steps:["Empirical mass = 12 + 2 + 16 = 30.","n = 180/30 = 6.","Molecular formula = (CH₂O)₆ = C₆H₁₂O₆."],ans:"C₆H₁₂O₆ (option B)",tip:"n = molar mass ÷ empirical mass = 6, then multiply every subscript. Glucose emerges — recognise it."},
{type:"hard",q:"The density of a 2 M NaCl solution is 1.12 g/mL. Its molality is approximately (Na = 23, Cl = 35.5):",options:["1.99 m","2.18 m","1.79 m","2.24 m"],answer:0,steps:["1 L of solution = 1120 g; solute = 2 × 58.5 = 117 g.","Solvent = 1120 − 117 = 1003 g = 1.003 kg.","m = 2/1.003 = 1.994 ≈ 1.99 m."],ans:"1.99 m (option A)",tip:"Mass of 1 L first (density × 1000), subtract solute mass, then divide moles by kg of SOLVENT. Skipping the subtraction gives the 2.24 trap."},
{type:"hard",q:"In the reaction 2H₂ + O₂ → 2H₂O, 4 g H₂ reacts with 32 g O₂. The mass of water formed is:",options:["36 g","18 g","40 g","9 g"],answer:0,steps:["Moles: H₂ = 4/2 = 2; O₂ = 32/32 = 1.","Stoichiometry needs 2:1 — exact match, neither limits.","Water = 2 mol × 18 = 36 g."],ans:"36 g (option A)",tip:"Check the coefficient ratio first: 2/2 vs 1/1 — equal quotients mean no limiting reagent, full conversion."},
{type:"hard",q:"The oxidation number of Mn in KMnO₄ is:",options:["+7","+6","+4","+2"],answer:0,steps:["K = +1, each O = −2.","x + 1 + 4(−2) = 0.","x = +7."],ans:"+7 (option A)",tip:"Alkali metal +1 fixed, oxygen −2 fixed — one equation gives Mn. Permanganate's +7 is the most common oxidation-state answer."},
{type:"hard",q:"Which of the following has the maximum number of molecules?",options:["36 g H₂O","28 g CO","46 g C₂H₅OH","54 g N₂O₅"],answer:0,steps:["Moles: H₂O = 36/18 = 2; CO = 28/28 = 1; C₂H₅OH = 46/46 = 1; N₂O₅ = 54/108 = 0.5.","2 mol is the largest.","36 g H₂O."],ans:"36 g H₂O (option A)",tip:"Convert every mass to moles — the largest mole count wins regardless of mass. Option A is 2 full moles."},
{type:"hard",q:"The volume occupied by 11 g of CO₂ at STP is:",options:["5.6 L","11.2 L","2.8 L","22.4 L"],answer:0,steps:["Moles of CO₂ = 11/44 = 0.25 mol.","V = 0.25 × 22.4.","= 5.6 L."],ans:"5.6 L (option A)",tip:"11 g CO₂ = quarter mole → quarter of 22.4 L. Molar mass 44 makes quarter-mole masses (11 g) instant."},
],
"2. Atomic Structure": [
{type:"hard",q:"The atomic number of an element with electronic configuration [Ar] 3d⁵ 4s¹ is:",options:["24","25","26","23"],answer:0,steps:["Ar = 18 electrons.","3d⁵ 4s¹ adds 6 more.","Z = 18 + 6 = 24 (chromium)."],ans:"24 (option A)",tip:"Add subshell electrons to the noble-gas core: 18 + 5 + 1 = 24. Half-filled d⁵ + s¹ is chromium's signature."},
{type:"hard",q:"The number of unpaired electrons in Fe²⁺ (Z = 26) is:",options:["4","6","2","0"],answer:0,steps:["Fe: [Ar] 3d⁶ 4s²; Fe²⁺ loses the 4s electrons first → [Ar] 3d⁶.","Five d-orbitals hold 6 electrons: one pair + four singles.","Unpaired = 4."],ans:"4 (option A)",tip:"Transition-metal ions lose ns electrons before (n−1)d. d⁶ high-spin always gives 4 unpaired — count boxes, not electrons."},
{type:"hard",q:"The de Broglie wavelength of a 54 eV electron is approximately:",options:["1.67 Å","0.167 Å","16.7 Å","5.4 Å"],answer:0,steps:["λ = 12.27/√V Å.","√54 ≈ 7.35.","λ = 12.27/7.35 ≈ 1.67 Å."],ans:"1.67 Å (option A)",tip:"12.27/√V Å is the electron shortcut; √54 ≈ 7.35 needs only rough estimation. Davisson–Germer used exactly 54 eV."},
{type:"hard",q:"The uncertainty in position of an electron (m = 9.1 × 10⁻³¹ kg) with velocity known to ±100 m/s is at least (h = 6.63 × 10⁻³⁴ J·s):",options:["5.8 × 10⁻⁷ m","5.8 × 10⁻⁴ m","1.16 × 10⁻⁶ m","2.9 × 10⁻⁷ m"],answer:0,steps:["Δx·Δp ≥ h/4π; Δp = mΔv = 9.1 × 10⁻³¹ × 100 = 9.1 × 10⁻²⁹.","Δx ≥ 6.63 × 10⁻³⁴/(4π × 9.1 × 10⁻²⁹).","= 6.63 × 10⁻³⁴/(1.14 × 10⁻²⁷) = 5.8 × 10⁻⁷ m."],ans:"5.8 × 10⁻⁷ m (option A)",tip:"Δx ≥ h/(4πmΔv) — plug mΔv first (9.1 × 10⁻²⁹), then divide h. Option C uses h/2π (sloppy Δp·Δx ≥ h/2π mixes)."},
{type:"hard",q:"Which set of quantum numbers is NOT possible?",options:["n = 3, l = 2, m = −2","n = 2, l = 1, m = 0","n = 4, l = 4, m = 0","n = 1, l = 0, m = 0"],answer:2,steps:["Rule: l ranges 0 to n−1, and |m| ≤ l.","For n = 4, l max = 3 — l = 4 is forbidden.","All other sets obey both rules."],ans:"n = 4, l = 4, m = 0 (option C)",tip:"l < n always; then |m| ≤ l. Audit l against n first — option C dies immediately."},
{type:"hard",q:"The maximum number of electrons with n = 3 is:",options:["8","18","32","2"],answer:1,steps:["Capacity of shell n = 2n².","n = 3 → 2 × 9.","= 18."],ans:"18 (option B)",tip:"2n² per shell — 2, 8, 18, 32. Option A is the n = 2 shell; read n carefully."},
{type:"hard",q:"An electron in the 2nd Bohr orbit of hydrogen has angular momentum:",options:["h/π","h/2π","2h/π","h/4π"],answer:0,steps:["Bohr: mvr = nh/2π.","n = 2 → L = 2h/2π.","= h/π."],ans:"h/π (option A)",tip:"L = nh/2π — substitute n and cancel. Option B is the n = 1 value; read n."},
{type:"hard",q:"The energy of the electron in the ground state of hydrogen is −13.6 eV. Its potential energy is:",options:["−27.2 eV","+13.6 eV","−13.6 eV","−6.8 eV"],answer:0,steps:["For hydrogen: KE = +13.6 eV, total E = −13.6 eV.","E = KE + PE gives PE = E − KE.","PE = −13.6 − 13.6 = −27.2 eV."],ans:"−27.2 eV (option A)",tip:"PE = 2E = −2KE for hydrogen — the virial fingerprint KE:PE:E = 1:−2:−1. Option B states KE, not PE."},
{type:"hard",q:"The radius of the 2nd Bohr orbit of hydrogen is (r₁ = 0.53 Å):",options:["1.06 Å","2.12 Å","0.265 Å","4.24 Å"],answer:1,steps:["rₙ = n²r₁.","n = 2 → r = 4 × 0.53.","= 2.12 Å."],ans:"2.12 Å (option B)",tip:"r scales as n²: 1, 4, 9. Option A forgets the square (2 × instead of 2² ×)."},
{type:"hard",q:"The wavelength of the first line of the Lyman series is (R_H = 1.097 × 10⁷ m⁻¹):",options:["1215 Å","6563 Å","1026 Å","911 Å"],answer:0,steps:["1/λ = R_H(1/1² − 1/2²) = R_H × 3/4.","= 1.097 × 10⁷ × 0.75 = 8.23 × 10⁶.","λ = 1.215 × 10⁻⁷ m = 1215 Å."],ans:"1215 Å (option A)",tip:"Lyman first line: n = 2 → 1, factor 3/4. 1215 Å (UV) vs Balmer's 6563 Å (red) — series decides the band."},
],
"3. Chemical Bonding & Molecular Structure": [
{type:"hard",q:"The shape of the NH₃ molecule is:",options:["tetrahedral","trigonal pyramidal","planar triangular","linear"],answer:1,steps:["N has 3 bond pairs + 1 lone pair → steric number 4.","Electron geometry tetrahedral; lone pair distorts it.","Molecular shape = trigonal pyramidal."],ans:"trigonal pyramidal (option B)",tip:"Count lone pairs: 1 lone pair on tetrahedral electron geometry always gives pyramidal shape (NH₃, H₃O⁺)."},
{type:"hard",q:"The hybridisation of carbon in CH₄ is:",options:["sp","sp²","sp³","dsp²"],answer:2,steps:["C forms 4 sigma bonds, zero lone pairs.","Steric number = 4.","sp³ hybridisation, tetrahedral, 109.5°."],ans:"sp³ (option C)",tip:"Steric number 4 → sp³, always. Bond pairs + lone pairs = 4 is the only check needed."},
{type:"hard",q:"The bond angle in H₂O is approximately:",options:["109.5°","104.5°","120°","180°"],answer:1,steps:["O has 2 bond pairs + 2 lone pairs → bent geometry.","Lone-pair repulsion compresses the tetrahedral angle.","104.5° (less than 109.5°)."],ans:"104.5° (option B)",tip:"Two lone pairs squeeze harder than one: H₂O 104.5° < NH₃ 107° < CH₄ 109.5°. Lone-pair count orders the angles."},
{type:"hard",q:"Which molecule has zero dipole moment?",options:["H₂O","NH₃","CO₂","SO₂"],answer:2,steps:["CO₂ is linear O=C=O; equal bond dipoles oppose exactly.","Net dipole = 0.","H₂O (bent), NH₃ (pyramidal), SO₂ (bent) all retain dipoles."],ans:"CO₂ (option C)",tip:"Linear symmetric molecules cancel bond dipoles; bent/pyramidal ones cannot. Shape decides polarity."},
{type:"hard",q:"The hybridisation of B in BF₃ is:",options:["sp³","sp²","sp","sp³d"],answer:1,steps:["B has 3 bond pairs, no lone pairs.","Steric number = 3.","sp², trigonal planar, 120°."],ans:"sp² (option B)",tip:"Three bonds, no lone pairs → sp² planar. Electron-deficient (6 e⁻) but geometry is still decided by steric number."},
{type:"hard",q:"The O–O bond order in ozone (O₃) is:",options:["1","2","1.5","2.5"],answer:2,steps:["O₃ resonates between two forms with one double + one single bond.","Total bond count 3 over 2 linkages.","Bond order = 3/2 = 1.5."],ans:"1.5 (option C)",tip:"Resonance averages bond orders: total bonds ÷ linkages = 3/2. Same logic gives 1.33 for carbonate (4/3)."},
{type:"hard",q:"The bond order of O₂⁺ is:",options:["2","2.5","1.5","3"],answer:1,steps:["O₂ has 12 valence electrons in MO order: (σ2s)²(σ*2s)²(σ2p)²(π2p)⁴(π*2p)².","Bond order = (10 − 6)/2 = 2.","Removing one antibonding electron: O₂⁺ → (10 − 5)/2 = 2.5."],ans:"2.5 (option B)",tip:"Removing an ANTIBONDING electron RAISES bond order (2 → 2.5); removing a bonding one would lower it. Check which level empties."},
{type:"hard",q:"Which species is paramagnetic?",options:["N₂","O₂","F₂","C₂"],answer:1,steps:["O₂ has two unpaired electrons in π*2p orbitals.","N₂, F₂ have all electrons paired.","C₂ (ground state) has all paired in simple MO counting."],ans:"O₂ (option B)",tip:"O₂'s paramagnetism is MOT's famous prediction — Lewis structures wrongly show all paired. Two π* singles decide it."},
{type:"hard",q:"The lattice energy is highest for:",options:["NaCl","MgO","CaO","KCl"],answer:1,steps:["Lattice energy ∝ (charge⁺ × charge⁻)/(r⁺ + r⁻).","MgO: 2×2 charges, smallest ions → maximum.","MgO > CaO > NaCl > KCl."],ans:"MgO (option B)",tip:"Charges dominate distance: 2+/2− salts dwarf 1+/1− salts. Among equals, smaller ions win — Mg²⁺ beats Ca²⁺."},
{type:"hard",q:"Hydrogen bonding is strongest in:",options:["HF","H₂O","NH₃","HCl"],answer:0,steps:["H-bond strength follows electronegativity: F > O > N.","HF has the most polar H–X bond.","Boiling points confirm: HF anomalously high for its mass."],ans:"HF (option A)",tip:"F > O > N >> Cl for H-bonding. Option D (HCl) barely H-bonds — size kills it despite Cl's electronegativity."},
],
"4. Chemical Thermodynamics": [
{type:"hard",q:"For the reaction 2SO₂ + O₂ ⇌ 2SO₃, ΔH = −198 kJ. The conditions favouring SO₃ are:",options:["high T, high P","low T, high P","low T, low P","high T, low P"],answer:1,steps:["Exothermic (ΔH < 0) → low T favours forward.","Δn = 2 − 3 = −1 → high P favours fewer moles.","Low T + high P."],ans:"low T, high P (option B)",tip:"Exothermic → cool it; fewer product moles → pressurise it. Option A heats an exothermic reaction — backwards."},
{type:"hard",q:"The entropy change is positive when:",options:["water freezes","gas condenses","CaCO₃(s) → CaO(s) + CO₂(g)","2H₂ + O₂ → 2H₂O(l)"],answer:2,steps:["Gas produced from solids → disorder rises sharply.","Other options reduce gas moles or order the system.","ΔS > 0 only for the decomposition."],ans:"CaCO₃(s) → CaO(s) + CO₂(g) (option C)",tip:"Count gas moles: more gas molecules out than in → ΔS > 0. Solids/liquids barely register."},
{type:"hard",q:"The standard enthalpy of formation of CO₂(g) is −393.5 kJ/mol. It represents ΔH for:",options:["C + O₂ → CO₂","CO + ½O₂ → CO₂","C + 2O → CO₂","CaCO₃ → CaO + CO₂"],answer:0,steps:["Formation = from constituent ELEMENTS in standard states.","C(graphite) + O₂(g) → CO₂(g).","ΔH = −393.5 kJ/mol."],ans:"C + O₂ → CO₂ (option A)",tip:"Formation always starts from elements (C + O₂), never from compounds like CO. Option B is a combustion, not a formation."},
{type:"hard",q:"For an ideal gas, Cp − Cv equals:",options:["R","2R","R/2","zero"],answer:0,steps:["Mayer's relation: Cp − Cv = R (per mole).","Follows from H = U + PV with PV = RT.","Universal for all ideal gases."],ans:"R (option A)",tip:"Cp − Cv = R per mole is Mayer's relation — the most quoted one-liner in thermodynamics. Cp/Cv = γ varies; the difference never does."},
{type:"hard",q:"The work done in an isothermal reversible expansion of 1 mol of ideal gas from 10 L to 20 L at 300 K is (R = 8.3):",options:["−1726 J","−1245 J","−2877 J","+1726 J"],answer:0,steps:["W = −2.303nRT log(V₂/V₁).","= −2.303 × 1 × 8.3 × 300 × log 2 = −2.303 × 2490 × 0.301.","= −1726 J."],ans:"−1726 J (option A)",tip:"W = −2.303nRT log(V₂/V₁) — log 2 = 0.301 is the memorised constant. Expansion → negative (work done BY gas)."},
{type:"hard",q:"For the reaction N₂ + 3H₂ → 2NH₃, ΔH = −92 kJ. The ΔU at 300 K is (R = 8.3 J/mol·K):",options:["−92 kJ","−87 kJ","−97 kJ","−46 kJ"],answer:1,steps:["ΔH = ΔU + Δn_gRT; Δn_g = 2 − 4 = −2.","ΔU = ΔH − Δn_gRT = −92000 + 2 × 8.3 × 300.","= −92000 + 4980 = −87020 J ≈ −87 kJ."],ans:"−87 kJ (option B)",tip:"ΔU = ΔH − ΔnRT: with Δn = −2 the correction ADDS ~5 kJ. Sign of Δn decides whether ΔU is above or below ΔH."},
/* @@C04D@@ */
/* @@C04E@@ */
],
"5. Solutions": [
{type:"hard",q:"The elevation in boiling point when 1 mol of a non-volatile solute is dissolved in 1 kg water (K_b = 0.52) is:",options:["0.52 K","1.04 K","0.26 K","100.52 K"],answer:0,steps:["ΔT_b = K_b × m.","m = 1 mol/1 kg = 1 m.","ΔT_b = 0.52 K."],ans:"0.52 K (option A)",tip:"ΔT = K × molality, one multiplication. Option D adds to 100 — elevation, not the new boiling point."},
{type:"hard",q:"The freezing point of a 0.5 m NaCl solution is approximately (K_f = 1.86, complete dissociation):",options:["−0.93 °C","−1.86 °C","−3.72 °C","0 °C"],answer:1,steps:["NaCl → Na⁺ + Cl⁻, so van't Hoff factor i = 2.","ΔT_f = iK_f m = 2 × 1.86 × 0.5 = 1.86.","T_f = 0 − 1.86 = −1.86 °C."],ans:"−1.86 °C (option B)",tip:"Multiply by i = 2 for NaCl: 2 × 1.86 × 0.5 = 1.86. Option A ignores dissociation (i = 1)."},
{type:"hard",q:"The osmotic pressure of a 0.1 M glucose solution at 300 K is (R = 0.083 L·bar/mol·K):",options:["2.49 bar","0.249 bar","24.9 bar","0.83 bar"],answer:0,steps:["π = iMRT with i = 1 (non-electrolyte).","= 1 × 0.1 × 0.083 × 300.","= 2.49 bar."],ans:"2.49 bar (option A)",tip:"π = MRT for non-electrolytes: 0.1 × 0.083 × 300 = 2.49. R in L·bar units avoids all conversions."},
{type:"hard",q:"A 5% (w/w) urea solution (M = 60) has molality approximately:",options:["0.877 m","0.833 m","5 m","0.05 m"],answer:0,steps:["5 g urea in 95 g water.","Moles = 5/60 = 0.0833.","m = 0.0833/0.095 = 0.877 m."],ans:"0.877 m (option A)",tip:"w/w % → grams per 100 g solution; solvent = 95 g, not 100. Dividing by 0.095 (not 0.1) is the precision step."},
{type:"hard",q:"The vapour pressure of pure water at 300 K is 25 mmHg. Adding 18 g glucose (M = 180) to 180 g water lowers it by:",options:["2.5 mmHg","0.25 mmHg","25 mmHg","1.25 mmHg"],answer:1,steps:["Moles solute = 18/180 = 0.1; moles water = 180/18 = 10.","Mole fraction solute = 0.1/10.1 ≈ 0.0099.","Δp = p° × x_solute = 25 × 0.0099 ≈ 0.25 mmHg."],ans:"0.25 mmHg (option B)",tip:"Δp = p°·x_solute: 0.1/10.1 ≈ 1% of 25 mmHg. Dilute solutions → x_solute ≈ n_solute/n_solvent."},
{type:"hard",q:"An ideal solution of A and B follows Raoult's law. Its total vapour pressure is:",options:["p_A°x_A + p_B°x_B","p_A° + p_B°","p_A°x_B + p_B°x_A","√(p_A°p_B°)"],answer:0,steps:["Partial pressures: p_A = p_A°x_A, p_B = p_B°x_B.","Total = p_A + p_B (Dalton).","= p_A°x_A + p_B°x_B."],ans:"p_A°x_A + p_B°x_B (option A)",tip:"Raoult × Dalton: each pure pressure weighted by its LIQUID mole fraction. Option C swaps the fractions."},
{type:"hard",q:"Henry's law constant K_H for a gas is 50 kbar. Its solubility (mole fraction) at 1 bar partial pressure is:",options:["0.02","50","0.5","0.002"],answer:0,steps:["p = K_H × x.","x = p/K_H = 1/50.","= 0.02."],ans:"0.02 (option A)",tip:"x = p/K_H: higher K_H → lower solubility. Units cancel (bar/bar) leaving pure mole fraction."},
{type:"hard",q:"A solution showing positive deviation from Raoult's law has:",options:["ΔH_mix < 0","ΔV_mix > 0","boiling point higher than ideal","vapour pressure lower than ideal"],answer:1,steps:["Positive deviation = weaker A–B than A–A/B–B.","Mixing absorbs heat (ΔH > 0) and expands (ΔV > 0).","Vapour pressure rises; boiling point drops."],ans:"ΔV_mix > 0 (option B)",tip:"Positive deviation: ΔH > 0, ΔV > 0, p higher, bp lower. Ethanol + water is the textbook example."},
{type:"hard",q:"The azeotrope of ethanol–water (positive deviation) boils at:",options:["above both pure liquids","below both pure liquids","between the two","at 100 °C exactly"],answer:1,steps:["Positive deviation → vapour pressure maximum.","Maximum vapour pressure → minimum boiling point.","Below both pure components."],ans:"below both pure liquids (option B)",tip:"Positive deviation = minimum-boiling azeotrope. Negative deviation (HNO₃–water) = maximum-boiling. Deviation sign flips the answer."},
{type:"hard",q:"Blood cells shrink in a solution that is:",options:["isotonic","hypotonic","hypertonic","saturated"],answer:2,steps:["Hypertonic = higher solute outside the cell.","Water leaves the cell by osmosis (crenation).","Hypotonic would swell/burst it."],ans:"hypertonic (option C)",tip:"Hyper = outside stronger → water exits → shrink. Hypo = outside weaker → water enters → burst. Direction follows water to salt."},
],
"6. Equilibrium": [
{type:"hard",q:"For the reaction H₂ + I₂ ⇌ 2HI, K_c = 50. The K_c for 2HI ⇌ H₂ + I₂ is:",options:["50","0.02","2500","√50"],answer:1,steps:["Reversing a reaction inverts K.","K_rev = 1/50.","= 0.02."],ans:"0.02 (option B)",tip:"Reverse → reciprocal; halve/doubling coefficients → square root/square. Option C squares instead of inverting."},
{type:"hard",q:"At equilibrium, the reaction quotient Q equals:",options:["zero","K","infinity","one"],answer:1,steps:["Equilibrium is defined by Q = K.","Q < K → forward shift; Q > K → backward.","Q = K means no net change."],ans:"K (option B)",tip:"Q vs K decides direction; equality IS equilibrium. Option D confuses K's value with the condition."},
{type:"hard",q:"For N₂ + 3H₂ ⇌ 2NH₃, if K_c = 4, then K_c for ½N₂ + ³/₂H₂ ⇌ NH₃ is:",options:["4","2","16","1"],answer:1,steps:["Halving coefficients → square root of K.","√4 = 2.","(Doubling would square it to 16.)"],ans:"2 (option B)",tip:"Scale coefficients by n → K becomes Kⁿ. Halving (n = 1/2) → √K. Option C doubles instead."},
{type:"hard",q:"Increasing pressure on N₂ + 3H₂ ⇌ 2NH₃ shifts equilibrium:",options:["toward reactants","toward products","no shift","decomposes N₂"],answer:1,steps:["Δn = 2 − 4 = −2 (fewer product moles).","Higher P favours the fewer-moles side.","Toward NH₃ (products)."],ans:"toward products (option B)",tip:"Pressure favours fewer gaseous moles: 4 → 2 here. Δn negative → products win under pressure."},
{type:"hard",q:"The pH of a 0.01 M HCl solution is:",options:["1","2","12","0.01"],answer:1,steps:["HCl → H⁺ fully: [H⁺] = 0.01 = 10⁻².","pH = −log(10⁻²).","= 2."],ans:"2 (option B)",tip:"Strong acid: [H⁺] = C directly, pH = −log C. Option A answers for 0.1 M — read the molarity."},
{type:"hard",q:"The pH of a 0.001 M NaOH solution is:",options:["3","11","13","1"],answer:1,steps:["[OH⁻] = 10⁻³ → pOH = 3.","pH = 14 − 3.","= 11."],ans:"11 (option B)",tip:"Strong base: pOH first (3), then pH = 14 − pOH. Option A reports pOH as pH — the classic swap."},
{type:"hard",q:"The K_sp of AgCl is 1.8 × 10⁻¹⁰. Its solubility in pure water is:",options:["1.34 × 10⁻⁵ M","1.8 × 10⁻¹⁰ M","3.6 × 10⁻¹⁰ M","1.8 × 10⁻⁵ M"],answer:0,steps:["AgCl → Ag⁺ + Cl⁻: s² = K_sp.","s = √(1.8 × 10⁻¹⁰) = 1.34 × 10⁻⁵.","M."],ans:"1.34 × 10⁻⁵ M (option A)",tip:"1:1 salt → s = √K_sp = √(18 × 10⁻¹¹) = 1.34 × 10⁻⁵. Option B reports K_sp itself as s."},
{type:"hard",q:"A buffer of 0.1 M CH₃COOH and 0.1 M CH₃COONa (pK_a = 4.74) has pH:",options:["7.0","4.74","2.87","9.26"],answer:1,steps:["Henderson: pH = pK_a + log(salt/acid).","log(0.1/0.1) = 0.","pH = 4.74."],ans:"4.74 (option B)",tip:"Equal concentrations → pH = pK_a exactly. Option C is the pure-acid pH — buffer vs acid confusion."},
{type:"hard",q:"The degree of dissociation of 0.01 M acetic acid (K_a = 1.8 × 10⁻⁵) is:",options:["0.042","0.42","0.0042","1.0"],answer:0,steps:["α = √(K_a/C) = √(1.8 × 10⁻⁵/0.01).","= √(1.8 × 10⁻³) = √18 × 10⁻².","= 4.24 × 10⁻² = 0.042."],ans:"0.042 (option A)",tip:"α = √(Ka/C): 1.8×10⁻³ → √18 × 10⁻² ≈ 4.24 × 10⁻². Option B misses one power of ten."},
{type:"hard",q:"Le Chatelier: adding an inert gas at constant VOLUME to N₂ + 3H₂ ⇌ 2NH₃:",options:["shifts right","shifts left","no effect","doubles K"],answer:2,steps:["Constant V → partial pressures unchanged.","Q unchanged → no shift.","(At constant P it would shift left.)"],ans:"no effect (option C)",tip:"Constant V: inert gas is invisible to Q. Constant P: it dilutes → shifts toward more moles. Volume decides."},
],
"7. Redox Reactions & Electrochemistry": [
{type:"hard",q:"The standard reduction potential of Zn²⁺/Zn is −0.76 V. For the reaction Zn + Cu²⁺ → Zn²⁺ + Cu (E°Cu = +0.34 V), E°cell is:",options:["−0.42 V","1.10 V","−1.10 V","0.42 V"],answer:1,steps:["E°cell = E°cathode − E°anode = 0.34 − (−0.76).","= 1.10 V.","Positive → spontaneous."],ans:"1.10 V (option B)",tip:"Cathode minus anode: 0.34 + 0.76 = 1.10. Option A subtracts the wrong way."},
{type:"hard",q:"In the electrolysis of aqueous NaCl, H₂ is liberated at the cathode because:",options:["Na⁺ discharges easily","H⁺/H₂O reduces more easily than Na⁺","Cl⁻ oxidises at cathode","Na melts"],answer:1,steps:["E°(Na⁺/Na) = −2.71 V vs E°(H₂O/H₂) = −0.83 V.","Water reduces far more easily.","So H₂ evolves; Na⁺ stays."],ans:"H⁺/H₂O reduces more easily than Na⁺ (option B)",tip:"Compare reduction potentials: less negative wins. Water (−0.83) beats Na⁺ (−2.71) always."},
{type:"hard",q:"During electrolysis, 9650 C deposits 3.175 g of Cu (Cu = 63.5). The current efficiency for Cu²⁺ + 2e⁻ is:",options:["100%","50%","200%","25%"],answer:0,steps:["Theoretical: 9650 C = 0.1 F → 0.05 mol Cu = 3.175 g.","Observed = 3.175 g.","Efficiency = 100%."],ans:"100% (option A)",tip:"0.1 F through Cu²⁺ gives exactly 0.05 mol = 3.175 g — the numbers are engineered: 9650 = F/10."},
{type:"hard",q:"The conductivity of a solution _____ with dilution while molar conductivity _____:",options:["decreases, increases","increases, decreases","both increase","both decrease"],answer:0,steps:["Fewer ions per mL → conductivity falls.","More dissociation + mobility → molar conductivity rises.","Opposite trends — the classic pair."],ans:"decreases, increases (option A)",tip:"κ falls (dilution) but Λm rises (dissociation) — opposite arrows. Kohlrausch plots confirm both."},
{type:"hard",q:"The E°cell for A + B⁺ → A⁺ + B is 0.5 V with n = 1. Its equilibrium constant at 298 K is:",options:["3 × 10⁸","0.5","2","5 × 10⁸"],answer:0,steps:["log K = nE°/0.059 = 0.5/0.059 = 8.47.","K = 10^8.47 ≈ 3 × 10⁸.","Large K — reaction goes to completion."],ans:"3 × 10⁸ (option A)",tip:"logK = nE°/0.059: 0.5/0.059 = 8.47 → K ≈ 3×10⁸. Option D rounds 10^0.47 as 5 — it is 3."},
{type:"hard",q:"A concentration cell Cu|Cu²⁺(0.01 M)||Cu²⁺(1.0 M)|Cu has emf:",options:["0.059 V","0.0295 V","0 V","0.118 V"],answer:0,steps:["E = (0.059/2)log(C₂/C₁) = 0.0295 × log(100).","= 0.0295 × 2.","= 0.059 V."],ans:"0.059 V (option A)",tip:"E = (0.059/n)log(high/low): 100-fold ratio with n = 2 gives exactly 0.059 V. Electrons flow from dilute to concentrated."},
{type:"hard",q:"The oxidation number of Cr in K₂Cr₂O₇ is:",options:["+6","+3","+7","+2"],answer:0,steps:["2K = +2, 7O = −14.","2x + 2 − 14 = 0.","x = +6."],ans:"+6 (option A)",tip:"Dichromate Cr is +6 (chromate too). Option B (+3) is the reduced green Cr³⁺ product."},
{type:"hard",q:"In the reaction Cu + 4HNO₃ → Cu(NO₃)₂ + 2NO₂ + 2H₂O, the oxidising agent is:",options:["Cu","HNO₃","Cu(NO₃)₂","NO₂"],answer:1,steps:["N goes from +5 (HNO₃) to +4 (NO₂) — reduced.","Reduced species oxidises another → HNO₃ is the oxidant.","Cu (0 → +2) is oxidised — the reductant."],ans:"HNO₃ (option B)",tip:"The species whose oxidation number FALLS is the oxidising agent. N: +5 → +4 falls; Cu: 0 → +2 rises."},
{type:"hard",q:"Zinc displaces copper from CuSO₄ because:",options:["Zn is more reactive (lower E°)","Cu is more reactive","both equal","temperature"],answer:0,steps:["E°(Zn²⁺/Zn) = −0.76 < E°(Cu²⁺/Cu) = +0.34.","Lower E° metal oxidises, displacing higher E° ions.","Zn → Zn²⁺ while Cu²⁺ → Cu."],ans:"Zn is more reactive (option A)",tip:"Lower reduction potential = stronger reductant = displaces higher ones. Order the E° values."},
{type:"hard",q:"The charge required to deposit 6.35 g Cu (Cu = 63.5, Cu²⁺ + 2e⁻) is:",options:["19300 C","9650 C","38600 C","96500 C"],answer:0,steps:["Moles Cu = 6.35/63.5 = 0.1 mol.","Electrons = 0.2 mol = 0.2 F.","Q = 0.2 × 96500 = 19300 C."],ans:"19300 C (option A)",tip:"0.1 mol Cu needs 0.2 F (n = 2): 0.2 × 96500 = 19300. Option B uses n = 1."},
],
"8. Chemical Kinetics": [
{type:"hard",q:"The rate constant of a first-order reaction is 0.0693 s⁻¹. Its half-life is:",options:["10 s","20 s","0.693 s","100 s"],answer:0,steps:["t½ = 0.693/k.","= 0.693/0.0693.","= 10 s."],ans:"10 s (option A)",tip:"t½ = ln2/k: 0.693/0.0693 = 10. The 0.0693 value is engineered — recognise ln2/10."},
{type:"hard",q:"For a zero-order reaction, the rate:",options:["depends on concentration","is constant","doubles when concentration doubles","is zero"],answer:1,steps:["Rate = k[A]⁰ = k.","Independent of concentration.","Units of k are mol·L⁻¹·s⁻¹."],ans:"is constant (option B)",tip:"Zero order → rate = k always. Option C describes first order; option D confuses order with rate value."},
{type:"hard",q:"The time to complete 75% of a first-order reaction is approximately (t½ given):",options:["t½","2t½","3t½","4t½"],answer:1,steps:["75% done = 2 half-lives (50% + 25%).","t = 2t½.","(87.5% = 3t½; 93.75% = 4t½.)"],ans:"2t½ (option B)",tip:"Halving ladder: 50→1, 75→2, 87.5→3 half-lives. 75% is exactly two halvings."},
{type:"hard",q:"Doubling [A] quadruples the rate; doubling [B] doubles it. The overall order is:",options:["2","3","1","4"],answer:1,steps:["Rate ∝ [A]² (quadruple on doubling).","Rate ∝ [B]¹.","Overall = 2 + 1 = 3."],ans:"3 (option B)",tip:"Doubling response reveals each exponent (×4 → 2, ×2 → 1); add them. Option A reports only A's order."},
{type:"hard",q:"Increasing temperature increases the rate because:",options:["more molecules exceed E_a","E_a decreases","ΔH changes","catalyst forms"],answer:0,steps:["Maxwell–Boltzmann tail beyond E_a grows exponentially.","k = Ae^(−Ea/RT) rises.","E_a itself is unchanged."],ans:"more molecules exceed E_a (option A)",tip:"Temperature feeds the high-energy tail, not the barrier. E_a is fixed; the fraction crossing it explodes."},
{type:"hard",q:"A catalyst increases the rate by:",options:["raising E_a","providing an alternate path with lower E_a","increasing temperature","shifting equilibrium"],answer:1,steps:["New mechanism, lower barrier.","More molecules cross per second.","Equilibrium (K) untouched."],ans:"providing an alternate path with lower E_a (option B)",tip:"Catalyst = lower E_a, same K. Option D is the classic confusion — catalysts never move equilibrium."},
{type:"hard",q:"For the reaction 2N₂O₅ → 4NO₂ + O₂ (first order), the rate law is:",options:["rate = k[N₂O₅]","rate = k[N₂O₅]²","rate = k[NO₂]⁴[O₂]","rate = k[N₂O₅][NO₂]"],answer:0,steps:["First order in N₂O₅ (experimental).","Rate = k[N₂O₅]¹.","Stoichiometric coefficients do NOT set the law."],ans:"rate = k[N₂O₅] (option A)",tip:"Order comes from experiment, never from balancing. Option B reads the coefficient 2 as the order."},
{type:"hard",q:"The half-life of a first-order reaction is 20 min. The fraction remaining after 60 min is:",options:["1/2","1/4","1/8","1/16"],answer:2,steps:["60 min = 3 half-lives.","Remaining = (1/2)³.","= 1/8."],ans:"1/8 (option C)",tip:"Count half-lives: 60/20 = 3 → (1/2)³ = 1/8. Option B stops at 2 half-lives."},
{type:"hard",q:"The unit of the rate constant for a second-order reaction is:",options:["s⁻¹","L mol⁻¹ s⁻¹","mol L⁻¹ s⁻¹","dimensionless"],answer:1,steps:["Rate (mol L⁻¹ s⁻¹) = k[A]².","k = rate/[A]² → (mol L⁻¹ s⁻¹)/(mol² L⁻²).","= L mol⁻¹ s⁻¹."],ans:"L mol⁻¹ s⁻¹ (option B)",tip:"Units of k reveal the order: s⁻¹ → 1st, L/mol·s → 2nd, (L/mol)²·s → 3rd. Read units backwards to order."},
{type:"hard",q:"If E_a = 0, the rate constant:",options:["equals A","equals zero","is infinite","decreases with T"],answer:0,steps:["k = Ae^(−0/RT) = A × 1.","= A.","Temperature-independent."],ans:"equals A (option A)",tip:"Zero barrier → every collision works: k = A, flat with T. Free-radical recombinations approach this."},
],
"9. Classification of Elements & Periodicity": [
{type:"hard",q:"The most electronegative element is:",options:["F","O","Cl","Cs"],answer:0,steps:["Electronegativity rises across a period, falls down a group.","Top-right corner (excluding noble gases) is maximum.","F = 4.0 on the Pauling scale."],ans:"F (option A)",tip:"Fluorine tops every electronegativity question: top-right of the table, 4.0. Option D (Cs) is the minimum instead."},
{type:"hard",q:"The correct order of atomic radii is:",options:["Na > Mg > Al","Al > Mg > Na","Mg > Na > Al","Na > Al > Mg"],answer:0,steps:["Across a period, nuclear charge shrinks the atom.","Na (Z=11) > Mg (12) > Al (13).","Left-to-right shrink, no exceptions here."],ans:"Na > Mg > Al (option A)",tip:"Period trend: size falls left→right as Z rises. Option B reverses it — the most common periodicity error."},
{type:"hard",q:"The first ionisation energy is highest for:",options:["B","Be","Li","C"],answer:1,steps:["Be (1s²2s²) has a stable filled s-subshell.","Removing from filled 2s costs extra.","Be > B despite higher Z of B — the filled-shell exception."],ans:"Be (option B)",tip:"Filled/half-filled shells spike IE: Be > B, N > O, Mg > Al. Option A ignores the 2s² stability."},
{type:"hard",q:"The correct order of ionic radii is:",options:["Na⁺ > Mg²⁺ > Al³⁺","Al³⁺ > Mg²⁺ > Na⁺","Mg²⁺ > Na⁺ > Al³⁺","Na⁺ > Al³⁺ > Mg²⁺"],answer:0,steps:["Isoelectronic series (10 e⁻ each): more protons → smaller.","Na⁺ (11p) > Mg²⁺ (12p) > Al³⁺ (13p).","Charge up → size down within isoelectronic sets."],ans:"Na⁺ > Mg²⁺ > Al³⁺ (option A)",tip:"Isoelectronic → sort by proton count descending size. More positive charge squeezes harder."},
{type:"hard",q:"Oxygen is paramagnetic in the gaseous state but the reason asked most is: O₂ has:",options:["10 bonding electrons","2 unpaired electrons","a double bond","16 electrons"],answer:1,steps:["MO configuration ends (π*2p)² with parallel spins.","Two unpaired electrons.","Measured μ ≈ 2.83 BM confirms."],ans:"2 unpaired electrons (option B)",tip:"O₂: 2 π* singles → paramagnetic. Option C (double bond) is the Lewis picture that predicts the WRONG magnetism."},
{type:"hard",q:"The diagonal relationship exists between:",options:["Li and Mg","Na and Mg","Be and Al","both Li–Mg and Be–Al"],answer:3,steps:["Similar charge density: Li⁺≈Mg²⁺, Be²⁺≈Al³⁺.","Similar properties diagonally.","Both pairs show it."],ans:"both Li–Mg and Be–Al (option D)",tip:"Diagonal pairs: Li–Mg and Be–Al are THE two. Option A and C each name one — D collects both."},
{type:"hard",q:"The electron affinity is highest for:",options:["F","Cl","Br","I"],answer:1,steps:["Cl (349 kJ/mol) > F (328 kJ/mol).","Small F⁻ suffers inter-electronic repulsion.","Size wins over nuclear charge here — the famous exception."],ans:"Cl (option B)",tip:"Cl > F for electron affinity — the exception to the F-tops-everything rule. Small fluoride ion repels the incoming electron."},
{type:"hard",q:"Noble gases have _____ electron affinity:",options:["very high","zero or negative","equal to halogens","equal to alkali metals"],answer:1,steps:["Filled shells accept no electron willingly.","EA ≈ 0 (He, Ne) or negative.","No stable anion forms."],ans:"zero or negative (option B)",tip:"Full shell → no room: EA ~ 0. Option A confuses EA with ionisation energy (which IS huge for noble gases)."},
{type:"hard",q:"Boron shows a maximum covalence of 4 because:",options:["it has d-orbitals","it has only s and p orbitals (no d)","it is small","it is a metal"],answer:1,steps:["2nd-period elements: n = 2 shell only (2s, 2p).","Maximum 4 orbitals → 4 bonds ([BF₄]⁻).","No d-orbitals → no expansion beyond 4."],ans:"it has only s and p orbitals (option B)",tip:"2nd period caps at 4 bonds (octet); 3rd period+ expands via d (SF₆, PCl₅). Period decides covalence."},
{type:"hard",q:"Aluminium chloride in aqueous solution is acidic due to:",options:["Cl⁻ hydrolysis","cation hydrolysis (Al³⁺)","it is a base","neutral salt"],answer:1,steps:["Al³⁺ + H₂O ⇌ [Al(OH)]²⁺ + H⁺.","Small highly-charged cation polarises water.","Releases H⁺ → acidic."],ans:"cation hydrolysis (option B)",tip:"Small 3+ cations hydrolyse (release H⁺); small 1−/2− anions of weak acids hydrolyse (release OH⁻). Charge density decides."},
],
"10. p-Block Elements": [
{type:"hard",q:"Borax (Na₂B₄O₇·10H₂O) on heating gives:",options:["B₂O₃","H₃BO₃","NaBO₂ + B₂O₃","Na₂O"],answer:2,steps:["Borax first loses water, then forms sodium metaborate + boric anhydride.","Na₂B₄O₇ → 2NaBO₂ + B₂O₃.","The glassy B₂O₃ bead is used in borax-bead tests."],ans:"NaBO₂ + B₂O₃ (option C)",tip:"Borax → metaborate + B₂O₃ glass. Option A names only the glassy half — the bead-test product."},
{type:"hard",q:"Aluminium is extracted from alumina by:",options:["reduction with carbon","electrolysis (Hall–Heroult)","reduction with H₂","self-reduction"],answer:1,steps:["Al³⁺ is too stable for carbon reduction.","Fused Al₂O₃ + cryolite electrolysed with carbon anodes.","Hall–Heroult process."],ans:"electrolysis (option B)",tip:"Highly electropositive metals (Al, Mg, Na) need electrolysis; carbon works only below them. Cryolite lowers the melting point."},
{type:"hard",q:"Graphite is a good conductor of electricity because it has:",options:["free ions","delocalised π-electrons","metallic bonds","free protons"],answer:1,steps:["Each C in graphite bonds to 3 neighbours (sp²).","The 4th electron sits in a delocalised π-cloud.","Mobile π-electrons conduct along layers."],ans:"delocalised π-electrons (option B)",tip:"sp² leaves one p-electron free per carbon — mobile π-cloud conducts. Diamond (sp³, all locked) insulates."},
{type:"hard",q:"CO is a good reducing agent at high temperature because:",options:["it is oxidised to CO₂","it is reduced","it decomposes","it is inert"],answer:0,steps:["C in CO is +2; in CO₂ it is +4.","Oxidation of CO releases energy (Ellingham: CO line slopes down).","Blast furnace uses CO to reduce Fe₂O₃."],ans:"it is oxidised to CO₂ (option A)",tip:"CO → CO₂ (+2 → +4) donates oxygen-removal power. Ellingham: falling CO line crosses metal-oxide lines at high T."},
{type:"hard",q:"Silicon doped with phosphorus is:",options:["p-type","n-type","intrinsic","insulator"],answer:1,steps:["P (group 15) has 5 valence electrons vs Si's 4.","Extra electron → free negative carrier.","n-type semiconductor."],ans:"n-type (option B)",tip:"Group 15 dopant → n-type (electrons); group 13 → p-type (holes). Dopant group decides."},
{type:"hard",q:"The geometry of SiO₂ (quartz) network is based on:",options:["SiO₄ tetrahedra","SiO₆ octahedra","linear SiO₂ molecules","planar SiO₃ units"],answer:0,steps:["Each Si bonds 4 O in tetrahedral arrangement.","Corner-sharing SiO₄ network.","No discrete SiO₂ molecules exist."],ans:"SiO₄ tetrahedra (option A)",tip:"Silica = corner-shared tetrahedra network. Option C treats it as CO₂-like molecules — false for solids."},
{type:"hard",q:"Lead pipes are not used for drinking water because lead:",options:["is costly","forms toxic soluble compounds","is soft","is heavy"],answer:1,steps:["Pb dissolves slightly, forming toxic Pb²⁺.","Cumulative poison (plumbism).","Modern pipes use copper/PVC."],ans:"forms toxic soluble compounds (option B)",tip:"Lead poisoning (plumbism) is cumulative — solubility, not cost, bans lead pipes."},
{type:"hard",q:"The +1 oxidation state is most stable for:",options:["B","Al","Ga","Tl"],answer:3,steps:["Inert-pair effect grows down group 13.","Tl⁺ (6s² retained) beats Tl³⁺.","Stability of +1: Tl > In > Ga > Al > B."],ans:"Tl (option D)",tip:"Inert pair: heavier p-block elements keep ns² — Tl⁺ is the textbook case. Option A (B) never shows +1."},
/* @@C10E@@ */
],
"11. d- and f-Block Elements": [
/* @@C11A@@ */
/* @@C11B@@ */
/* @@C11C@@ */
/* @@C11D@@ */
/* @@C11E@@ */
],
"12. Coordination Compounds": [
/* @@C12A@@ */
/* @@C12B@@ */
/* @@C12C@@ */
/* @@C12D@@ */
/* @@C12E@@ */
],
"13. Purification & Characterisation of Organic Compounds": [
/* @@C13A@@ */
/* @@C13B@@ */
/* @@C13C@@ */
/* @@C13D@@ */
/* @@C13E@@ */
],
"14. Some Basic Principles of Organic Chemistry (GOC)": [
/* @@C14A@@ */
/* @@C14B@@ */
/* @@C14C@@ */
/* @@C14D@@ */
/* @@C14E@@ */
],
"15. Hydrocarbons": [
/* @@C15A@@ */
/* @@C15B@@ */
/* @@C15C@@ */
/* @@C15D@@ */
/* @@C15E@@ */
],
"16. Organic Compounds Containing Halogens": [
/* @@C16A@@ */
/* @@C16B@@ */
/* @@C16C@@ */
/* @@C16D@@ */
/* @@C16E@@ */
],
"17. Organic Compounds Containing Oxygen": [
/* @@C17A@@ */
/* @@C17B@@ */
/* @@C17C@@ */
/* @@C17D@@ */
/* @@C17E@@ */
],
"18. Organic Compounds Containing Nitrogen": [
/* @@C18A@@ */
/* @@C18B@@ */
/* @@C18C@@ */
/* @@C18D@@ */
/* @@C18E@@ */
],
"19. Biomolecules": [
/* @@C19A@@ */
/* @@C19B@@ */
/* @@C19C@@ */
/* @@C19D@@ */
/* @@C19E@@ */
],
"20. Principles Related to Practical Chemistry": [
/* @@C20A@@ */
/* @@C20B@@ */
/* @@C20C@@ */
/* @@C20D@@ */
/* @@C20E@@ */
],
};
