/* ===== PYQ-50 BANK — 50 important & hard JEE Main PYQ-pattern MCQs (5 × 10 high-weightage chapters) ===== */
/* Schema matches app.js: {type:"hard", q, options[4], answer(index 0-3), steps[], ans, tip}
   "hard" renders as the TOUGH · MCQ badge. Merged by chapter name inside app.js.
   NOTE: no existing questions are modified — this bank only ADDS questions. */
const PYQ50_PHYSICS = {
"12. Current Electricity": [
{type:"hard",q:"A uniform wire of resistance 12 Ω is bent in the form of a circle. The effective resistance between two points on the circle that subtend a 90° angle at the centre is:",options:["3 Ω","4 Ω","2.25 Ω","6 Ω"],answer:2,steps:["The two points split the wire into arcs of 90° and 270° → arc resistances of 3 Ω (12 × 90/360) and 9 Ω.","The arcs are in parallel between the two points: 1/R = 1/3 + 1/9 = 4/9.","R = 9/4 = 2.25 Ω."],ans:"2.25 Ω (option C)",tip:"Arc resistance is proportional to the angle: diametrically opposite points give R/4, quarter points give 3R/16. Always parallel-combine the two arcs."},
{type:"hard",q:"The free-electron number density of copper is 8.5 × 10²⁸ m⁻³. A current of 1.6 A flows through a copper wire of cross-sectional area 2 × 10⁻⁶ m². The drift speed of the electrons is:",options:["5.9 × 10⁻³ m/s","1.6 × 10⁻³ m/s","4.7 × 10⁻⁵ m/s","5.9 × 10⁻⁵ m/s"],answer:3,steps:["v_d = I/(neA).","Denominator = 8.5 × 10²⁸ × 1.6 × 10⁻¹⁹ × 2 × 10⁻⁶ = 2.72 × 10⁴.","v_d = 1.6 / 2.72 × 10⁴ = 5.9 × 10⁻⁵ m/s ≈ 0.06 mm/s."],ans:"5.9 × 10⁻⁵ m/s (option D)",tip:"Drift speed is TINY (fraction of a mm/s) — any option above 10⁻³ m/s is an instant elimination. Powers of ten decide this question."},
{type:"hard",q:"A battery of emf 10 V and internal resistance 3 Ω is connected to a variable resistance R. The maximum power that can be delivered to R is:",options:["33.3 W","8.33 W","16.7 W","4.17 W"],answer:1,steps:["Maximum power transfer: R = r = 3 Ω.","Then total resistance = 6 Ω and current = 10/6 A.","P_max = I²R = (100/36) × 3 = 100/12 = 8.33 W.","Shortcut: P_max = E²/4r."],ans:"8.33 W (option B)",tip:"Memorise P_max = E²/4r and the condition R = r. Option A (E²/r = 33.3) is the classic trap of forgetting the factor of 4."},
{type:"hard",q:"A potentiometer wire of length 10 m and resistance 10 Ω is connected in series with a battery of emf 2 V (negligible internal resistance) and a resistor of 490 Ω. The potential gradient along the wire is:",options:["4 mV/m","2 mV/m","0.4 mV/m","40 mV/m"],answer:0,steps:["Current in the circuit = 2/(490 + 10) = 0.004 A.","Potential drop across the wire = 0.004 × 10 = 0.04 V.","Potential gradient = 0.04/10 = 0.004 V/m = 4 mV/m."],ans:"4 mV/m (option A)",tip:"Current = E/(total resistance including the series resistor) FIRST, then take the drop across the wire only. Using 2/10 instead of 2/500 gives the absurd 40 mV/m trap option."},
{type:"hard",q:"A storage battery of emf 12 V and internal resistance 2 Ω is being CHARGED by a steady current of 3 A. Its terminal voltage is:",options:["12 V","6 V","18 V","16 V"],answer:2,steps:["While charging, current is pushed INTO the battery, so V = E + Ir.","V = 12 + 3 × 2 = 18 V.","(While discharging it would be V = E − Ir = 6 V.)"],ans:"18 V (option C)",tip:"Charging: terminal voltage EXCEEDS emf (V = E + Ir). Discharging: V = E − Ir. Spot the word 'charged' — it flips the sign and the whole answer."}
],
"13. Magnetic Effects of Current & Magnetism": [
{type:"hard",q:"Two long straight parallel wires carrying currents I and 4I in the same direction are a distance d apart. The distance from the wire carrying current I at which the magnetic field is zero is:",options:["d/2","d/3","2d/3","d/4"],answer:1,steps:["Equate fields at distance x from wire 1: μ₀I/2πx = μ₀(4I)/2π(d − x).","1/x = 4/(d − x) → d − x = 4x → x = d/3.","The null point lies between the wires, closer to the WEAKER current."],ans:"d/3 from the wire carrying I (option B)",tip:"Null point: x = d/(1 + √(I₂/I₁)). Here √4 = 2, so x = d/3. Same template as the gravitation null-point question — learn it once, use it twice."},
{type:"hard",q:"A circular coil of radius 10 cm having 100 turns carries a current of 1 A. The magnetic field at its centre is:",options:["6.28 × 10⁻⁴ T","3.14 × 10⁻⁴ T","1.26 × 10⁻³ T","6.28 × 10⁻⁵ T"],answer:0,steps:["B = μ₀NI/2R.","= (4π × 10⁻⁷ × 100 × 1)/(2 × 0.1).","= 2π × 10⁻⁴ = 6.28 × 10⁻⁴ T."],ans:"6.28 × 10⁻⁴ T (option A)",tip:"2R = 0.2 goes in the denominator. Forgetting the factor 2 (using μ₀NI/R) doubles the answer — that is exactly option C here. N turns simply multiply B by N."},
{type:"hard",q:"A proton moving with speed 4 × 10⁶ m/s enters a magnetic field of 0.3 T perpendicular to it. The radius of its circular path is (m_p = 1.67 × 10⁻²⁷ kg):",options:["28 cm","7 cm","14 cm","1.4 m"],answer:2,steps:["r = mv/qB.","= (1.67 × 10⁻²⁷ × 4 × 10⁶)/(1.6 × 10⁻¹⁹ × 0.3).","= 6.68 × 10⁻²¹ / 4.8 × 10⁻²⁰ = 0.139 m ≈ 14 cm."],ans:"14 cm (option C)",tip:"Keep every quantity in SI and count the powers of ten: 10⁻²¹/10⁻²⁰ ≈ 0.1. MeV-scale protons in laboratory fields always trace centimetre-radius circles."},
{type:"hard",q:"A long solenoid has 1000 turns wound over a length of 1 m and carries a current of 5 A. The magnetic field inside (well away from the ends) is:",options:["3.14 × 10⁻³ T","1.26 × 10⁻² T","6.28 × 10⁻⁴ T","6.28 × 10⁻³ T"],answer:3,steps:["Inside an ideal solenoid B = μ₀nI, with n = turns per LENGTH.","n = 1000/1 = 1000 m⁻¹.","B = 4π × 10⁻⁷ × 1000 × 5 = 2π × 10⁻³ = 6.28 × 10⁻³ T."],ans:"6.28 × 10⁻³ T (option D)",tip:"n is turns per metre, never the total turns. For a 1 m winding they coincide — the moment the length changes, the careless options activate."},
{type:"hard",q:"A rectangular coil of 100 turns, each of size 4 cm × 5 cm, carrying a current of 2 A is placed in a magnetic field of 0.1 T. The maximum torque on the coil is:",options:["0.02 N·m","0.04 N·m","0.4 N·m","0.004 N·m"],answer:1,steps:["τ_max = NIAB (when the plane of the coil is parallel to B).","A = 0.04 × 0.05 = 2 × 10⁻³ m².","τ = 100 × 2 × 2 × 10⁻³ × 0.1 = 0.04 N·m."],ans:"0.04 N·m (option B)",tip:"τ = NIAB sinθ where θ is between B and the NORMAL. Maximum torque when the plane is parallel to B. Converting cm² to m² is where most marks die."}
],
"14. EMI & Alternating Currents": [
{type:"hard",q:"A conducting rod of length 0.5 m slides with velocity 10 m/s perpendicular to a uniform magnetic field of 0.2 T. If the circuit resistance is 2 Ω, the power dissipated is:",options:["0.25 W","0.5 W","1 W","2 W"],answer:1,steps:["Motional emf = BLv = 0.2 × 0.5 × 10 = 1 V.","Current = 1/2 = 0.5 A.","Power = ε²/R = 1²/2 = 0.5 W (equivalently B²L²v²/R)."],ans:"0.5 W (option B)",tip:"P = B²L²v²/R in ONE step — no need to find emf or current separately. The mechanical power you push in with equals this electrical power (energy conservation)."},
{type:"hard",q:"An oscillating LC circuit has L = 1 mH and C = 10 μF. Its frequency of oscillation is approximately:",options:["16 kHz","0.8 kHz","1.6 kHz","3.2 kHz"],answer:2,steps:["f = 1/(2π√(LC)).","√(LC) = √(10⁻³ × 10⁻⁵) = √10⁻⁸ = 10⁻⁴ s.","f = 1/(2π × 10⁻⁴) = 10⁴/6.28 ≈ 1592 Hz ≈ 1.6 kHz."],ans:"1.6 kHz (option C)",tip:"First compute √(LC) in seconds, then one division. ω = 1/√(LC) is the analogue of √(k/m) for a spring — same SHM mathematics, different symbols."},
{type:"hard",q:"An ideal-type transformer has 220 V primary and 22 V secondary. Its efficiency is 90% and the secondary draws a current of 2 A. The current in the primary is:",options:["0.222 A","0.2 A","0.25 A","0.18 A"],answer:0,steps:["Output power = 22 × 2 = 44 W.","Input power = 44/0.9 = 48.9 W.","Primary current = 48.9/220 = 0.222 A."],ans:"0.222 A (option A)",tip:"For a 10:1 step-down with 90% efficiency, I_p = I_s/10 ÷ 0.9 = 2/(10 × 0.9). Efficiency DIVIDES the secondary current — forgetting it gives the 0.2 A trap."},
{type:"hard",q:"In a series LCR circuit R = 30 Ω, X_L = 60 Ω and X_C = 20 Ω. The power factor of the circuit is:",options:["0.8","0.6","0.75","1.0"],answer:1,steps:["Net reactance X = X_L − X_C = 60 − 20 = 40 Ω.","Impedance Z = √(R² + X²) = √(900 + 1600) = 50 Ω.","Power factor cos φ = R/Z = 30/50 = 0.6."],ans:"0.6 (option B)",tip:"X_L − X_C FIRST, then the 30-40-50 Pythagorean triple. Any series LCR question with R = 30 and net X = 40 has cos φ = 0.6 instantly."},
{type:"hard",q:"In an LR circuit L = 2 H, R = 10 Ω and E = 20 V. The current in the circuit one time constant (t = L/R = 0.2 s) after closing the switch is approximately:",options:["2.0 A","0.63 A","1.0 A","1.26 A"],answer:3,steps:["Final (steady) current = E/R = 20/10 = 2 A.","Growth law: i = (E/R)(1 − e^(−t/τ)) with τ = L/R = 0.2 s.","At t = τ: i = 2(1 − e⁻¹) = 2 × 0.632 = 1.26 A."],ans:"1.26 A (option D)",tip:"After one time constant the current is 63% of its final value (after one τ of decay, 37% remains). e⁻¹ ≈ 0.37 kills every LR/RC growth-decay MCQ."}
],
"16. Optics": [
{type:"hard",q:"In a Young's double-slit experiment the fringe width is 1.2 mm in air. If the entire apparatus is immersed in water (refractive index 4/3), the new fringe width is:",options:["1.6 mm","0.9 mm","0.6 mm","1.2 mm"],answer:1,steps:["Fringe width β = λD/d — wavelength is the only thing that changes in a medium.","λ_medium = λ_air/n = λ × 3/4.","β_new = 1.2 × 3/4 = 0.9 mm."],ans:"0.9 mm (option B)",tip:"Fringe width scales as 1/n of the medium. D and d do not change, so only one multiplication: β × (λ_medium/λ_air). Answer must be SMALLER in water."},
{type:"hard",q:"A ray of light passes through a prism of angle 60° symmetrically (i = e) and the minimum deviation is 30°. The refractive index of the prism material is:",options:["1.5","1.33","1.41","1.62"],answer:2,steps:["At minimum deviation: n = sin((A + δ_m)/2)/sin(A/2).","= sin(45°)/sin(30°) = (0.707)/(0.5).","n = 1.41 = √2."],ans:"1.41 (option C)",tip:"For symmetric passage i = e = (A + δ_m)/2. Recognising δ_m = 30° with A = 60° gives sin45/sin30 = √2 without any computation."},
{type:"hard",q:"Two thin lenses of focal lengths +20 cm and −10 cm are placed in contact. The combination behaves as:",options:["a convex lens of focal length +20 cm","a concave lens of focal length −20 cm","a concave lens of focal length −10 cm","a convex lens of focal length +30 cm"],answer:1,steps:["1/f = 1/f₁ + 1/f₂ = 1/20 − 1/10 = −1/20.","f = −20 cm.","Net power P = +5 D − 10 D = −5 D (negative → diverging)."],ans:"a concave lens of focal length −20 cm (option B)",tip:"Add POWERS in dioptres (P = 100/f cm), not focal lengths. A stronger concave always wins over a weaker convex — the combination diverges."},
{type:"hard",q:"An astronomical telescope has an objective of focal length 100 cm and an eyepiece of focal length 5 cm. For normal adjustment (relaxed eye), its magnifying power and tube length are:",options:["95 and 105 cm","20 and 100 cm","20 and 500 cm","20 and 105 cm"],answer:3,steps:["Magnifying power M = f_o/f_e = 100/5 = 20.","Tube length = f_o + f_e (image of objective at the eyepiece focus).","L = 100 + 5 = 105 cm."],ans:"20 and 105 cm (option D)",tip:"Normal adjustment: M = −f_o/f_e and L = f_o + f_e. Final image at near point (least distance): M = 1 + f_o/f_e and L = f_o + u_e — know which mode the question asks."},
{type:"hard",q:"The Brewster angle for a glass surface of refractive index 1.5 is:",options:["33.7°","45°","56.3°","48.6°"],answer:2,steps:["Brewster's law: tan θ_B = n = 1.5.","tan 56.3° ≈ 1.5.","θ_B = 56.3°, and the reflected light is completely plane-polarised."],ans:"56.3° (option C)",tip:"θ_B + refraction angle = 90°, so 33.7° (the complement) is the built-in trap. For glass n = 1.5, remember 56.3°."}
],
"17. Dual Nature of Matter & Radiation": [
{type:"hard",q:"Light of wavelength 400 nm ejects photoelectrons with maximum kinetic energy 1.0 eV from a metal surface. The threshold wavelength of the metal is:",options:["400 nm","590 nm","310 nm","620 nm"],answer:1,steps:["Photon energy E = 1240/λ(nm) = 1240/400 = 3.1 eV.","Work function φ = E − KE_max = 3.1 − 1.0 = 2.1 eV.","λ₀ = 1240/φ = 1240/2.1 ≈ 590 nm."],ans:"590 nm (option B)",tip:"The 1240/λ(nm) eV shortcut is the whole chapter. Chain: photon energy → subtract KE → threshold. λ₀ must be LONGER than the incident 400 nm — that alone eliminates A and C."},
{type:"hard",q:"An electron is accelerated from rest through a potential difference of 100 V. Its de Broglie wavelength is approximately:",options:["1.23 nm","0.0123 nm","0.123 nm","12.3 nm"],answer:2,steps:["λ = 1.227/√V nm for an electron.","√100 = 10.","λ = 1.227/10 = 0.1227 ≈ 0.123 nm."],ans:"0.123 nm (option C)",tip:"Memorise λ_electron = 1.227/√V nm (or 12.27/√V Å). Doubling V only divides λ by √2, never by 2 — exponent traps live in the options."},
{type:"hard",q:"An electron and a proton have the SAME de Broglie wavelength. Which particle has more kinetic energy?",options:["the proton","both have equal KE","cannot be decided","the electron"],answer:3,steps:["λ = h/√(2mK) → K = h²/(2mλ²).","Same λ means K is inversely proportional to mass.","m_e << m_p → the electron has the larger kinetic energy."],ans:"the electron (option D)",tip:"Same λ: KE ∝ 1/m (lighter wins). Same KE: λ ∝ 1/√(mK) so proton has the longer λ. Same momentum: KE ∝ 1/m again — pair these three variants together."},
{type:"hard",q:"In the graph of stopping potential V₀ versus frequency ν of incident light for a photocell, the slope of the straight line equals:",options:["e/h","hc/λ","h/e","the work function φ"],answer:2,steps:["Einstein's equation: eV₀ = hν − φ.","Rearranged: V₀ = (h/e)ν − φ/e.","Slope = h/e, intercept on the ν-axis = φ/h, intercept on the V₀-axis = −φ/e."],ans:"h/e (option C)",tip:"Slope h/e is universal for ALL metals — only the threshold intercept changes with the metal. If angular frequency ω (rad/s) is used on the x-axis instead of ν, the slope becomes h/2πe. Always check what the axis actually plots."},
{type:"hard",q:"The momentum of a photon of wavelength 6200 Å is approximately:",options:["3.3 × 10⁻³⁰ kg·m/s","1.07 × 10⁻²⁷ kg·m/s","1.07 × 10⁻³³ kg·m/s","6.2 × 10⁻²⁷ kg·m/s"],answer:1,steps:["Photon momentum p = h/λ.","λ = 6200 Å = 6.2 × 10⁻⁷ m.","p = 6.63 × 10⁻³⁴/6.2 × 10⁻⁷ = 1.07 × 10⁻²⁷ kg·m/s."],ans:"1.07 × 10⁻²⁷ kg·m/s (option B)",tip:"p = h/λ = E/c. Ångström → metres is ×10⁻¹⁰, and the exponent of the answer follows directly: 10⁻³⁴/10⁻⁷ = 10⁻²⁷. Get the power of ten right and the option picks itself."}
]
};

const PYQ50_CHEMISTRY = {
"6. Equilibrium": [
{type:"hard",q:"For the equilibrium N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the relation between Kp and Kc is:",options:["Kp = Kc(RT)²","Kp = Kc","Kp = Kc(RT)⁻¹","Kp = Kc(RT)⁻²"],answer:3,steps:["Kp = Kc(RT)^Δn where Δn = (moles of gaseous products) − (moles of gaseous reactants).","Δn = 2 − (1 + 3) = −2.","Kp = Kc(RT)⁻²."],ans:"Kp = Kc(RT)⁻² (option D)",tip:"Δn counts GASES only — solids/liquids never enter. Δn negative → Kp < Kc. The sign of the exponent is the entire question."},
{type:"hard",q:"The pH of a 0.1 M acetic acid solution (Ka = 1.8 × 10⁻⁵) is approximately:",options:["4.74","3.37","2.87","1.00"],answer:2,steps:["For a weak acid: [H⁺] = √(Ka·C) = √(1.8 × 10⁻⁵ × 0.1) = √(1.8 × 10⁻⁶).","[H⁺] = 1.34 × 10⁻³ M.","pH = −log(1.34 × 10⁻³) = 3 − log 1.34 ≈ 3 − 0.13 = 2.87."],ans:"2.87 (option C)",tip:"Shortcut: pH = ½(pKa − log C) = ½(4.74 + 1) = 2.87. Option A (4.74) is pKa itself — that belongs to an equal-concentration BUFFER, not a pure acid."},
{type:"hard",q:"An inert gas is added to the equilibrium N₂(g) + 3H₂(g) ⇌ 2NH₃(g) at CONSTANT VOLUME. The equilibrium:",options:["shifts forward","is unaffected (no shift)","shifts backward","Kc increases"],answer:1,steps:["At constant volume, partial pressures of ALL reacting gases stay unchanged after adding an inert gas.","Q stays equal to K → no shift.","At constant PRESSURE instead, total P is constant so reactant partial pressures fall → equilibrium shifts toward MORE moles (backward for NH₃)."],ans:"No shift — equilibrium is unaffected (option B)",tip:"Constant V: inert gas does nothing. Constant P: inert gas shifts toward the side with more gaseous moles. This pair of variants appears almost every year."},
{type:"hard",q:"Ksp of AgCl = 1.8 × 10⁻¹⁰. The solubility of AgCl in a 0.1 M NaCl solution is:",options:["1.34 × 10⁻⁵ M","1.8 × 10⁻¹⁰ M","1.34 × 10⁻¹⁰ M","1.8 × 10⁻⁹ M"],answer:3,steps:["Common ion: [Ag⁺] = s, [Cl⁻] ≈ 0.1 M (from NaCl, suppressing AgCl's own contribution).","Ksp = s × 0.1 = 1.8 × 10⁻¹⁰.","s = 1.8 × 10⁻⁹ M."],ans:"1.8 × 10⁻⁹ M (option D)",tip:"Option A (1.34 × 10⁻⁵) is the solubility in PURE water (√Ksp) — the standard trap. In a common-ion solution, divide Ksp by the existing ion concentration."},
{type:"hard",q:"A buffer contains 0.1 M CH₃COOH (pKa = 4.74) and 1.0 M CH₃COONa. Its pH is:",options:["4.74","5.74","3.74","6.74"],answer:1,steps:["Henderson–Hasselbalch: pH = pKa + log([salt]/[acid]).","= 4.74 + log(1.0/0.1) = 4.74 + 1.","pH = 5.74."],ans:"5.74 (option B)",tip:"pH = pKa when [salt] = [acid]; every factor of 10 in the salt/acid ratio shifts pH by exactly 1. Salt-rich buffer → pH above pKa. Never recalculate from Ka."}
],
"7. Redox Reactions & Electrochemistry": [
{type:"hard",q:"The reduction potential of the Zn²⁺(0.1 M)/Zn electrode at 298 K is (E° = −0.76 V):",options:["−0.76 V","−0.82 V","−0.79 V","−0.73 V"],answer:2,steps:["Nernst (reduction): E = E° − (0.059/n)log(1/[Mⁿ⁺]).","E = −0.76 − (0.059/2)log(1/0.1) = −0.76 − 0.0295 × 1.","E ≈ −0.79 V."],ans:"−0.79 V (option C)",tip:"Diluting a metal electrode makes its reduction potential MORE negative (0.03 V shift for n = 2 per ten-fold dilution). E° appears only at unit concentration."},
{type:"hard",q:"A current of 2 A is passed for 1 hour through CuSO₄ solution. The mass of copper deposited at the cathode is (atomic mass of Cu = 63.5, F = 96500 C/mol):",options:["1.18 g","2.37 g","4.74 g","0.59 g"],answer:1,steps:["Charge Q = It = 2 × 3600 = 7200 C.","Cu²⁺ + 2e⁻ → Cu, so moles of Cu = 7200/(2 × 96500).","m = (63.5 × 7200)/(193000) ≈ 2.37 g."],ans:"2.37 g (option B)",tip:"m = (atomic mass × I × t)/(nF) — the n here is the ELECTRONS per ion (2 for Cu²⁺, 3 for Al³⁺). Halving n wrongly doubles the mass; check the valency first."},
{type:"hard",q:"For the Daniell cell Zn|Zn²⁺||Cu²⁺|Cu with E°cell = 1.10 V (n = 2), the standard Gibbs energy change ΔG° is (F = 96500 C/mol):",options:["+212.3 kJ","−106.15 kJ","−424.6 kJ","−212.3 kJ"],answer:3,steps:["ΔG° = −nFE°cell.","= −2 × 96500 × 1.10 = −212300 J.","ΔG° ≈ −212.3 kJ (negative → spontaneous)."],ans:"−212.3 kJ (option D)",tip:"ΔG° = −nFE° always. A galvanic cell has negative ΔG° and positive E°; the −106 option forgets n = 2 and the + option mixes up spontaneity signs."},
{type:"hard",q:"The average oxidation state of sulphur in the tetrathionate ion S₄O₆²⁻ is:",options:["+6","+2","+2.5","+4"],answer:2,steps:["Total charge: 4x + 6(−2) = −2.","4x = +10.","x = +2.5 (an average — the ion actually has two S at +5 and two S at 0)."],ans:"+2.5 (option C)",tip:"Oxidation states can be fractional because they are averages. In S₄O₆²⁻ the two terminal S are +5 and the two central S are 0 — a favourite JEE twist on +2.5."},
{type:"hard",q:"The molar conductivity of a 0.01 M acetic acid solution is 39.05 S cm² mol⁻¹ and its limiting molar conductivity Λ°m is 390.5 S cm² mol⁻¹. The degree of dissociation α is:",options:["1.0","0.01","0.5","0.1"],answer:3,steps:["α = Λm/Λ°m.","= 39.05/390.5 = 0.1.","So the acid is 10% dissociated at 0.01 M."],ans:"0.1 (option D)",tip:"α = Λm/Λ°m — pure ratio, so units must match and the leading digits must align (39.05/390.5 is exactly one-tenth). Then Ka = Cα²/(1−α) if asked next."}
],
"12. Coordination Compounds": [
{type:"hard",q:"The IUPAC name of the complex [Co(NH₃)₅Cl]Cl₂ is:",options:["pentaamminechlorocobalt(II) chloride","pentaamminechloridocobalt(III) chloride","chloropentaamminecobalt(III) dichloride","pentaamminechloridocobaltate(III) chloride"],answer:1,steps:["Ligands first (alphabetical): ammine (NH₃) before chlorido (Cl⁻).","Charge balance: x + 5(0) + (−1) = +2 → Co is +3, written as cobalt(III).","Two Cl⁻ outside the sphere = chloride (not dichloride, since 'chloride' is the anion name)."],ans:"pentaamminechloridocobalt(III) chloride (option B)",tip:"Charge counting fixes the oxidation number instantly. 'Cobaltate' is reserved for an ANIONIC complex — a neutral complex keeps the plain metal name. 'Dichloride' is never used in IUPAC."},
{type:"hard",q:"The number of unpaired electrons in [Fe(CN)₆]³⁻ is:",options:["5","3","1","4"],answer:2,steps:["Fe³⁺ is d⁵. CN⁻ is a strong-field ligand → low-spin octahedral.","t₂g⁵ e_g⁰ configuration.","Unpaired electrons = 1 (in the t₂g level)."],ans:"1 (option C)",tip:"Strong field (CN⁻, CO) pairs electrons; weak field (F⁻, H₂O with 3d metals) leaves them unpaired. [FeF₆]³⁻ with the SAME Fe³⁺ d⁵ has 5 unpaired electrons — same metal, opposite spin state."},
{type:"hard",q:"Which statement about [NiCl₄]²⁻ and [Ni(CN)₄]²⁻ is CORRECT?",options:["both are tetrahedral","[NiCl₄]²⁻ is tetrahedral and paramagnetic, while [Ni(CN)₄]²⁻ is square planar and diamagnetic","both are square planar","[NiCl₄]²⁻ is square planar and [Ni(CN)₄]²⁻ is tetrahedral"],answer:1,steps:["Ni²⁺ is d⁸.","Cl⁻ (weak field): no pairing, sp³ hybridisation → tetrahedral, 2 unpaired → paramagnetic.","CN⁻ (strong field): electrons pair, dsp² hybridisation → square planar, all paired → diamagnetic."],ans:"[NiCl₄]²⁻ tetrahedral/paramagnetic and [Ni(CN)₄]²⁻ square planar/diamagnetic (option B)",tip:"The d⁸ Ni²⁺ pair is THE classic JEE question: weak field → tetrahedral + paramagnetic, strong field → square planar + diamagnetic. One sentence, full marks."},
{type:"hard",q:"The number of geometrical isomers of the complex ion [Co(NH₃)₄Cl₂]⁺ is:",options:["3","4","1","2"],answer:3,steps:["Octahedral MA₄B₂ type.","The two Cl⁻ can be adjacent (cis) or opposite (trans).","Only 2 geometrical isomers exist (the cis one is additionally optically active)."],ans:"2 — cis and trans (option D)",tip:"MA₄B₂ octahedral → 2 isomers (cis/trans). MA₃B₃ → 2 (fac/mer). M(AB)₃ type → 2 + optical. Memorise these three patterns and all isomer-count MCQs collapse."},
{type:"hard",q:"The effective atomic number (EAN) of iron in [Fe(CN)₆]⁴⁻ is (Z of Fe = 26):",options:["34","36","38","26"],answer:1,steps:["Oxidation state: x + 6(−1) = −4 → x = +2.","EAN = Z − oxidation state + 2 × (coordination number).","EAN = 26 − 2 + 12 = 36 (krypton configuration)."],ans:"36 (option B)",tip:"EAN = Z − OS + 2(CN). Complexes obeying the EAN rule hit a noble-gas number (36 = Kr here, 54 = Xe for many 5d complexes). The −4 charge of the complex, not CN⁻ alone, sets the oxidation state."}
]
};

const PYQ50_MATHS = {
"5. Binomial Theorem": [
{type:"hard",q:"The term independent of x in the expansion of (x + 1/x²)⁹ is:",options:["36","126","84","1"],answer:2,steps:["General term: T(r+1) = C(9,r) · x^(9−r) · (x⁻²)^r = C(9,r) · x^(9−3r).","Independent of x → 9 − 3r = 0 → r = 3.","T₄ = C(9,3) = 84."],ans:"84 (option C)",tip:"Write the power of x as one expression (9 − 3r here), set it to zero, then just evaluate C(n,r). Never expand the whole binomial."},
{type:"hard",q:"The sum of all the coefficients in the expansion of (1 + x)ⁿ is 4096. The greatest coefficient in the expansion is:",options:["792","495","1024","924"],answer:3,steps:["Sum of coefficients = 2ⁿ = 4096 = 2¹² → n = 12.","Greatest coefficient is the central one: C(12,6).","C(12,6) = 924."],ans:"924 (option D)",tip:"Sum of coefficients → put x = 1, never expand. n = 12 is even so the greatest coefficient is unique and central: C(12,6) = 924 (for odd n it is the tie C(n,(n−1)/2) = C(n,(n+1)/2))."},
{type:"hard",q:"The remainder when 2⁶⁰ is divided by 7 is:",options:["2","1","4","0"],answer:1,steps:["2⁶⁰ = (2³)²⁰ = 8²⁰ = (7 + 1)²⁰.","Every term of the binomial expansion contains a factor of 7 except the last: C(20,20)·1²⁰ = 1.","Remainder = 1."],ans:"1 (option B)",tip:"Push the base to one more than the divisor: (divisor + 1)ⁿ always leaves remainder 1. Same trick for (a + 1)ⁿ mod a. Binomial is the fastest remainder machine in JEE."},
{type:"hard",q:"If the ratio of C(n,4) to C(n,6) is 1 : 3, then n equals:",options:["12","16","14","10"],answer:2,steps:["C(n,4)/C(n,6) = 1/3 → C(n,6) = 3C(n,4).","C(n,6)/C(n,4) = (n−4)(n−5)/(5 × 6) = 3.","n² − 9n + 20 = 90 → n² − 9n − 70 = 0 → n = 14 (rejecting n = −5)."],ans:"14 (option C)",tip:"Use the telescoping product form C(n,r)/C(n,r−1) = (n−r+1)/r. Chain it from r = 5 to 6 instead of expanding factorials blindly — the quadratic in n factorises fast."},
{type:"hard",q:"The value of Σ (r = 1 to 10) r · C(10,r) is:",options:["2560","5120","10240","1024"],answer:1,steps:["Differentiate (1 + x)ⁿ = Σ C(n,r)xʳ w.r.t. x: n(1 + x)^(n−1) = Σ r·C(n,r)x^(r−1).","Put x = 1: Σ r·C(n,r) = n·2^(n−1).","= 10 × 2⁹ = 5120."],ans:"5120 (option B)",tip:"Memorise Σ r·C(n,r) = n·2^(n−1) and Σ r²·C(n,r) = n(n+1)·2^(n−2). They are one-liners straight from differentiation — no term-by-term addition ever needed."}
],
"6. Sequences & Series": [
{type:"hard",q:"The sum of the series 1·2 + 2·3 + 3·4 + … up to 10 terms is:",options:["220","550","440","385"],answer:2,steps:["nth term = n(n + 1); Σ n(n+1) = n(n+1)(n+2)/3.","= 10 × 11 × 12/3.","= 440."],ans:"440 (option C)",tip:"Σ n(n+1)(n+2) = n(n+1)(n+2)(n+3)/4 — the pattern continues one factor beyond the last. For n(n+1) with n = 10: 10·11·12/3 = 440 in one line."},
{type:"hard",q:"The sum of an infinite GP is 15 and the sum of the squares of its terms is 45. The first term and common ratio are:",options:["a = 3, r = 4/5","a = 5, r = 1/3","a = 10, r = 1/3","a = 5, r = 2/3"],answer:3,steps:["S = a/(1 − r) = 15 and sum of squares = a²/(1 − r²) = 45.","Divide: a/(1 + r) = 3 → a = 3(1 + r).","Substituting: 3(1 + r) = 15(1 − r) → 1 + r = 5 − 5r → r = 2/3, a = 5."],ans:"a = 5, r = 2/3 (option D)",tip:"Divide the two equations instead of solving them separately: a/(1−r) ÷ a²/(1−r²) = (1+r)/a. One division collapses the system to two linear equations."},
{type:"hard",q:"The arithmetic mean of two positive numbers is 6 and their geometric mean is 4.8. The numbers are:",options:["8 and 4","9.6 and 2.4","7.2 and 4.8","10.8 and 1.2"],answer:1,steps:["AM = 6 → a + b = 12; GM² = ab = 4.8² = 23.04.","a and b are roots of x² − 12x + 23.04 = 0 → x = 6 ± √(36 − 23.04).","√12.96 = 3.6 → the numbers are 9.6 and 2.4."],ans:"9.6 and 2.4 (option B)",tip:"Numbers = AM ± √(AM² − GM²) — derive it from the quadratic rather than memorising. Also note AM ≥ GM: 6 ≥ 4.8 ✓, so the data is consistent."},
{type:"hard",q:"The sum of the series 1/(1+2) + 1/(1+2+3) + 1/(1+2+3+4) + … up to 99 terms is:",options:["0.99","2.00","1.98","1.00"],answer:2,steps:["1/(1+2+…+n) = 2/(n(n+1)) = 2(1/n − 1/(n+1)).","Sum telescopes: 2(1 − 1/(n+1)) = 2n/(n+1).","For n = 99: 2 × 99/100 = 1.98."],ans:"1.98 (option C)",tip:"Denominators of running sums scream 1/n − 1/(n+1) telescoping. The limit as n → ∞ is 2, so 1.98 (approaching 2 from below) is the only sensible option."},
{type:"hard",q:"The arithmetic mean of two positive numbers is 25 and their geometric mean is 15. Their harmonic mean is:",options:["12","6.5","15","9"],answer:3,steps:["AM × HM = GM² (the fundamental relation between the three means).","HM = GM²/AM = 225/25.","HM = 9."],ans:"9 (option D)",tip:"GM² = AM × HM for two numbers — one division and done. Also check G² = ab directly: 15² = 225 = ab ✓. Option D also verifies via HM = 2ab/(a+b)."}
]
};
