/* ===== BULK BANK M — 50 hard JEE Main PYQ-pattern MCQs per chapter ===== */
const BULK_MA = {
"1. Sets, Relations & Functions": [
{type:"hard",q:"If A = {1, 2, 3} then the number of relations from A to A is:",options:["9","27","512","2¹⁸"],answer:2,steps:["A × A has 3 × 3 = 9 ordered pairs.","A relation is any SUBSET of A × A.","Number of subsets of a 9-element set = 2⁹ = 512."],ans:"512 (option C)",tip:"Relations from A to B = 2^(mn); the answer is always a power of 2 — 2⁹ = 512, never 9 or 27."},
{type:"hard",q:"The domain of f(x) = 1/√(x² − 4) is:",options:["(−2, 2)","(−∞, −2) ∪ (2, ∞)","R − {−2, 2}","[2, ∞)"],answer:1,steps:["Denominator ≠ 0 and inside root > 0: x² − 4 > 0.","(x − 2)(x + 2) > 0.","Holds outside the roots: x < −2 or x > 2."],ans:"(−∞, −2) ∪ (2, ∞) (option B)",tip:"Square-root denominator → radicand STRICTLY positive. Factor, draw the wavy curve, take the positive humps."},
{type:"hard",q:"If f(x) = 2x + 3 and g(x) = x², then (g∘f)(2) equals:",options:["49","7","11","13"],answer:0,steps:["g∘f means apply f first, then g: g(f(x)).","f(2) = 2 × 2 + 3 = 7.","g(7) = 7² = 49."],ans:"49 (option A)",tip:"Compose right-to-left: innermost function (f) first. Confusing g∘f with f∘g gives 2 × 4 + 3 = 11 (option C)."},
{type:"hard",q:"The function f(x) = x³ is:",options:["neither one-one nor onto","one-one but not onto","onto but not one-one","both one-one and onto (bijective)"],answer:3,steps:["x³ is strictly increasing on R → distinct x give distinct values → one-one.","For every y ∈ R there is x = ∛y → onto.","Hence bijective on R → R."],ans:"both one-one and onto (option D)",tip:"Odd-degree polynomials with positive leading coefficient are strictly increasing → bijective. Even powers fail both."},
{type:"hard",q:"Let R = {(x, x²) : x ∈ N}. Which property does R satisfy?",options:["reflexive and symmetric","transitive only","reflexive, symmetric and transitive","none of reflexive, symmetric or transitive"],answer:3,steps:["Reflexive? (2,2) ∉ R since 2 ≠ 2² — fails.","Symmetric? (2,4) ∈ R but (4,2) ∉ R — fails.","Transitive? (2,4) and (4,16) ∈ R but (2,16) ∉ R — fails."],ans:"none of reflexive, symmetric or transitive (option D)",tip:"One counterexample kills each property; (2,4) is the universal breaker here. Squaring relations on N almost never form equivalence relations."},
{type:"hard",q:"If f : R → R, f(x) = 3x − 5, then f⁻¹(x) is:",options:["(x + 5)/3","(x − 5)/3","3x + 5","x/3 − 5"],answer:0,steps:["Set y = 3x − 5.","Solve: 3x = y + 5 → x = (y + 5)/3.","Swap roles: f⁻¹(x) = (x + 5)/3."],ans:"(x + 5)/3 (option A)",tip:"Solve y = f(x) for x, then rename. The sign on the constant FLIPS (option B's error); slope 3 becomes ÷3."},
{type:"hard",q:"The range of f(x) = sin²x + cos²x − 1 for x ∈ R is:",options:["{0}","{1}","[0, 1]","R"],answer:0,steps:["sin²x + cos²x = 1 for all x.","f(x) = 1 − 1 = 0.","Range = {0}."],ans:"{0} (option A)",tip:"Collapse identities BEFORE doing range machinery — the function is constant 0, so range is a singleton."},
{type:"hard",q:"The number of one-one functions from {1, 2, 3} to {a, b, c, d} is:",options:["12","24","64","4³"],answer:1,steps:["Choose distinct images: P(4,3) = 4 × 3 × 2.","= 24.","(General formula: P(n,r) = n!/(n−r)!.)"],ans:"24 (option B)",tip:"One-one from m to n elements = P(n,m) — permutations, not powers. Option D (4³) counts ALL functions."},
{type:"hard",q:"If f(x) = |x − 2|, then f is:",options:["differentiable at x = 2","continuous but not differentiable at x = 2","discontinuous at x = 2","constant"],answer:1,steps:["|x − 2| → 0 as x → 2 from both sides, and f(2) = 0 → continuous.","Left derivative = −1, right derivative = +1 at x = 2.","Unequal one-sided derivatives → sharp corner, not differentiable."],ans:"continuous but not differentiable at x = 2 (option B)",tip:"Modulus functions always corner at their zero (x = 2 here). Continuous? Yes. Differentiable at the corner? Never."},
{type:"hard",q:"The period of f(x) = |sin x| is:",options:["2π","π","π/2","not periodic"],answer:1,steps:["|sin(x + π)| = |−sin x| = |sin x|.","So shifting by π reproduces the function.","2π also works, but π is the SMALLEST such period."],ans:"π (option B)",tip:"Modulus halves the period of sin/cos (2π → π); |sin x| shows twice the humps per 2π interval."},
{type:"hard",q:"The number of functions from a set with m elements to a set with n elements is:",options:["mⁿ","nᵐ","m × n","m + n"],answer:1,steps:["Each of the m domain elements has n independent image choices.","Total = n × n × … (m times).","= nᵐ."],ans:"nᵐ (option B)",tip:"n choices per domain element, m elements → nᵐ. Option A swaps domain and codomain — read which set is the domain."},
{type:"hard",q:"Let f(x) = [x] (greatest integer function). Then f(3.7) + f(−2.3) equals:",options:["1","2","0","−1"],answer:2,steps:["[3.7] = 3.","[−2.3] = −3 (the GIF rounds DOWN toward −∞, never toward zero).","Sum = 3 + (−3) = 0."],ans:"0 (option C)",tip:"Negative GIF values are the trap: [−2.3] = −3, not −2. Positive side is trivial; always double-audit the negative side."},
{type:"hard",q:"If f(x) = x² − 3x + 2, then the minimum value of f on R is:",options:["−1/4","1/4","−1","2"],answer:0,steps:["Complete the square: f = (x − 3/2)² − 9/4 + 2.","= (x − 3/2)² − 1/4.","Minimum = −1/4 at x = 3/2."],ans:"−1/4 (option A)",tip:"Vertex form in one line: minimum = c − b²/4a = 2 − 9/4 = −1/4. Upward parabola → minimum at the vertex."},
{type:"hard",q:"The function f(x) = x² on R is:",options:["one-one and onto","neither one-one nor onto","one-one but not onto","onto but not one-one"],answer:1,steps:["f(−2) = f(2) = 4 → not one-one.","Negative numbers have no pre-image → not onto.","Both fail on R."],ans:"neither one-one nor onto (option B)",tip:"Even powers on R fail one-one (symmetric values) and onto (no negatives). Restrict domain/codomain to fix either."},
{type:"hard",q:"If f(x) = x/(x − 1), x ≠ 1, then f(f(x)) equals:",options:["x/(2x − 1)","x","1/x","(x − 1)/x"],answer:1,steps:["f(f(x)) = f(x)/(f(x) − 1).","= [x/(x−1)] / [x/(x−1) − 1] = [x/(x−1)] / [1/(x−1)].","= x."],ans:"x (option B)",tip:"Self-inverse functions (f(f(x)) = x) simplify instantly; x/(x−1) is a classic involution — substitute and watch it collapse."},
{type:"hard",q:"The smallest positive period of f(x) = sin 3x + cos 5x is:",options:["2π","2π/15","2π/3","π"],answer:0,steps:["Period of sin 3x = 2π/3; period of cos 5x = 2π/5.","Combined period = LCM(2π/3, 2π/5).","LCM of denominators 3,5 over GCD of numerators: 2π/(1/15)… compute: LCM = 2π × LCM(1/3,1/5) = 2π × 1 = 2π."],ans:"2π (option A)",tip:"Period of a sum = LCM of periods; for 2π/3 and 2π/5 the LCM is 2π. Options C and D are single-term periods."},
{type:"hard",q:"f(x) = (x² + 2)/3 for x ∈ R. The range of f is:",options:["[2/3, ∞)","[0, ∞)","(2/3, ∞)","[2, ∞)"],answer:0,steps:["x² ≥ 0 → x² + 2 ≥ 2.","Divide by 3: f(x) ≥ 2/3.","Minimum attained at x = 0 → range [2/3, ∞)."],ans:"[2/3, ∞) (option A)",tip:"Bound x² below by 0, then propagate the inequality through the expression. Inclusions (≥) at the endpoint matter."},
{type:"hard",q:"The domain of f(x) = √(9 − x²) + 1/(x − 1) is:",options:["[−3, 3]","(−∞, 1) ∪ (1, ∞)","[−3, 3] − {1}","[−3, 1) ∪ (1, 3]"],answer:3,steps:["Root needs 9 − x² ≥ 0 → x ∈ [−3, 3].","Fraction needs x ≠ 1.","Intersect: [−3, 3] excluding 1."],ans:"[−3, 1) ∪ (1, 3] (option D)",tip:"Apply each piece's condition, then INTERSECT. The hole at x = 1 splits the interval — option C writes the same set unclearly."},
{type:"hard",q:"If R is an equivalence relation on a set of n elements, the minimum possible number of ordered pairs in R is:",options:["n","2n","n²","0"],answer:0,steps:["Equivalence requires reflexivity at minimum.","Reflexivity forces all n diagonal pairs (a,a).","Minimum = n (the identity relation, which is an equivalence)."],ans:"n (option A)",tip:"Reflexivity alone forces n pairs; the identity relation shows n is attainable, so no smaller equivalence exists."},
{type:"hard",q:"The inverse of the function f(x) = eˣ exists on:",options:["R → R⁺ with f⁻¹(x) = ln x","R → R with f⁻¹(x) = ln x","R⁺ → R only","nowhere"],answer:0,steps:["eˣ is strictly increasing → one-one; its range is (0, ∞).","So f: R → R⁺ is bijective.","Inverse = ln x defined on R⁺."],ans:"R → R⁺ with f⁻¹(x) = ln x (option A)",tip:"Exponential and log are mirror bijections only when the codomain is restricted to positives; option B's onto-R fails."},
{type:"hard",q:"Let A = {a, b}. The number of equivalence relations on A is:",options:["1","2","3","4"],answer:1,steps:["Possible partitions of {a,b}: {{a},{b}} and {{a,b}}.","Each partition gives one equivalence relation.","Total = 2 (Bell number B₂)."],ans:"2 (option B)",tip:"Equivalence relations = set partitions (Bell numbers): B₂ = 2, B₃ = 5, B₄ = 15. Memorise the sequence."},
{type:"hard",q:"If f(x) = log(x² + 1), then f is:",options:["even","odd","neither","both"],answer:0,steps:["f(−x) = log((−x)² + 1) = log(x² + 1).","= f(x) for all x.","Hence even."],ans:"even (option A)",tip:"Even powers inside any function force f(−x) = f(x). Option B would need a sign flip — impossible with x²."},
{type:"hard",q:"The range of f(x) = 2ˣ for x ∈ R is:",options:["R","(0, ∞)","[1, ∞)","[0, ∞)"],answer:1,steps:["2ˣ > 0 for every real x.","As x → −∞, 2ˣ → 0⁺ (never reaching 0).","As x → ∞, 2ˣ → ∞. Range = (0, ∞)."],ans:"(0, ∞) (option B)",tip:"Exponentials are always positive but never zero — 0 is the excluded endpoint. Brackets decide between B and D."},
{type:"hard",q:"If f(x) = x³ − x, then f(−x) equals:",options:["f(x)","−f(x)","1/f(x)","x − x³"],answer:1,steps:["f(−x) = (−x)³ − (−x) = −x³ + x.","= −(x³ − x).","= −f(x) → odd function."],ans:"−f(x) (option B)",tip:"All-odd powers → odd function; option D is the same expression but hides the sign. −f(x) is the clean form."},
{type:"hard",q:"The number of onto functions from {1, 2, 3} to {a, b} is:",options:["8","6","4","2"],answer:1,steps:["Total functions = 2³ = 8.","Subtract the 2 constant (non-onto) functions.","Onto = 8 − 2 = 6."],ans:"6 (option B)",tip:"Small onto counts: total minus constant maps. For 3→2: 8 − 2 = 6. Inclusion–exclusion generalises it."},
{type:"hard",q:"f(x) = √(x − 3). The domain of f is:",options:["[3, ∞)","(3, ∞)","R","(−∞, 3]"],answer:0,steps:["Radicand ≥ 0: x − 3 ≥ 0.","x ≥ 3.","Endpoint included → [3, ∞)."],ans:"[3, ∞) (option A)",tip:"Even root → radicand non-negative; endpoint x = 3 gives 0, which is allowed. Square brackets include it."},
{type:"hard",q:"If g(x) = 2x and f(x) = x + 5, then (f∘g)(x) − (g∘f)(x) equals:",options:["5","−5","0","10"],answer:1,steps:["f∘g = 2x + 5.","g∘f = 2(x + 5) = 2x + 10.","Difference = (2x + 5) − (2x + 10) = −5."],ans:"−5 (option B)",tip:"Composition order flips the constant's fate: ×2 first vs +5 first differ by exactly 5. Expand both, subtract."},
{type:"hard",q:"The function f(x) = c (constant) on R is:",options:["one-one","onto R","neither","bijective"],answer:2,steps:["All x map to c → not one-one.","Only c is hit; other reals have no pre-image → not onto.","Both fail."],ans:"neither (option C)",tip:"Constant maps collapse everything to one value — the extreme failure of both properties. Onto {c} alone it would pass onto."},
{type:"hard",q:"If f(x) = (2x − 1)/(x + 1), x ≠ −1, then f⁻¹(x) is:",options:["(x + 1)/(2 − x)","(x − 1)/(x + 2)","(2x + 1)/(x − 1)","(x + 1)/(x − 2)"],answer:0,steps:["y = (2x − 1)/(x + 1) → yx + y = 2x − 1.","x(y − 2) = −1 − y → x = (y + 1)/(2 − y).","f⁻¹(x) = (x + 1)/(2 − x)."],ans:"(x + 1)/(2 − x) (option A)",tip:"Cross-multiply, collect x-terms, divide. For (ax+b)/(cx+d) the inverse is (−dx+b)/(cx−a) — verify with this result."},
{type:"hard",q:"The graph of y = |x| + 1 is obtained from y = |x| by:",options:["shifting up by 1","shifting right by 1","shifting left by 1","reflecting in the x-axis"],answer:0,steps:["+1 sits OUTSIDE the modulus, acting on y.","Every y-value rises by 1.","So the V-shape shifts vertically up by 1."],ans:"shifting up by 1 (option A)",tip:"Outside changes move vertically (+1 → up); inside changes move horizontally (|x−1| → right). Position decides direction."},
{type:"hard",q:"The number of bijective functions from {1, 2, 3} to {a, b, c} is:",options:["9","27","6","3"],answer:2,steps:["Bijection needs distinct images for distinct elements: 3! arrangements.","= 3 × 2 × 1 = 6.","(General: n! bijections between two n-element sets.)"],ans:"6 (option C)",tip:"Bijections = permutations = n!. Option B (27) counts all functions; bijections are far fewer."},
{type:"hard",q:"If f(x) = x² and g(x) = √x (principal root, x ≥ 0), then (f∘g)(4) equals:",options:["2","4","16","±2"],answer:1,steps:["g(4) = √4 = 2 (principal, non-negative).","f(2) = 2² = 4.","(f∘g)(4) = 4."],ans:"4 (option B)",tip:"Principal root is non-negative — ±2 never enters. Compose inside-out: root first, square after."},
{type:"hard",q:"The range of f(x) = 1/(x² + 1) for x ∈ R is:",options:["(0, 1]","(0, ∞)","[1, ∞)","R"],answer:0,steps:["x² + 1 ≥ 1 → 1/(x²+1) ≤ 1.","As x → ±∞, value → 0⁺.","Range = (0, 1]."],ans:"(0, 1] (option A)",tip:"Denominator bounded below by 1 → function capped above by 1, approaching 0. Endpoints: 1 included, 0 excluded."},
{type:"hard",q:"If A = {1, 2} and B = {x, y, z}, the number of one-one functions from A to B is:",options:["6","9","8","3"],answer:0,steps:["P(3,2) = 3 × 2 = 6.","(First element: 3 choices; second: 2 remaining.)","Option B counts all 3² functions."],ans:"6 (option A)",tip:"One-one = permutations P(n,r). All functions = n^r = 9 — the classic pair to confuse."},
{type:"hard",q:"The function f(x) = sin x on [−π/2, π/2] is:",options:["not invertible","bijective onto [−1, 1]","one-one but not onto [−1, 1]","onto but not one-one"],answer:1,steps:["sin x is strictly increasing on [−π/2, π/2] → one-one.","Its values cover [−1, 1] fully → onto [−1, 1].","Hence bijective — this is why arcsin is defined here."],ans:"bijective onto [−1, 1] (option B)",tip:"The principal branch [−π/2, π/2] is chosen exactly because sin is bijective there. Monotonic + full range = invertible."},
{type:"hard",q:"If f(x) = 5x − 2, then f⁻¹(8) equals:",options:["2","34/5","38/5","3"],answer:0,steps:["Solve 5x − 2 = 8 → 5x = 10.","x = 2.","So f⁻¹(8) = 2."],ans:"2 (option A)",tip:"For inverse VALUES, solve f(x) = target directly — no need to find the full inverse formula first."},
{type:"hard",q:"The domain of f(x) = log(x² − 5x + 6) is:",options:["(2, 3)","(−∞, 2) ∪ (3, ∞)","R − {2, 3}","[2, 3]"],answer:1,steps:["Log needs positive argument: x² − 5x + 6 > 0.","Roots 2, 3; upward parabola → positive outside.","x < 2 or x > 3."],ans:"(−∞, 2) ∪ (3, ∞) (option B)",tip:"Log → strictly positive argument. Factor, wavy curve, take the outer humps for upward parabolas."},
{type:"hard",q:"How many relations on {1, 2, 3} are reflexive AND have exactly 4 elements?",options:["6","3","9","12"],answer:0,steps:["Reflexive needs all 3 diagonal pairs present.","The 4th element is chosen freely from the 6 non-diagonal pairs.","C(6,1) = 6."],ans:"6 (option A)",tip:"Fix the 3 mandatory diagonals first, then count free choices: C(6,1) = 6 relations. A reflexive relation must contain the diagonals, so 4 total is possible."},
{type:"hard",q:"f(x) = x³ + 2x is:",options:["even","odd","neither","both"],answer:1,steps:["f(−x) = (−x)³ + 2(−x) = −x³ − 2x.","= −(x³ + 2x) = −f(x).","Odd function."],ans:"odd (option B)",tip:"All terms odd-powered → odd function. Derivatives of even functions are odd — same pattern."},
{type:"hard",q:"If f : N → N and f(n) = n + 1, then f is:",options:["bijective","one-one but not onto","onto but not one-one","neither"],answer:1,steps:["n₁ + 1 = n₂ + 1 → n₁ = n₂: one-one.","1 ∈ N has no pre-image (n + 1 ≥ 2) → not onto.","One-one but not onto."],ans:"one-one but not onto (option B)",tip:"Successor function on N: shifting misses the first element. On Z the same formula IS bijective — the set matters."},
{type:"hard",q:"If f(x) = x² − 1 and g(x) = 2x + 1, then (f∘g)(1) equals:",options:["8","3","10","2"],answer:0,steps:["g(1) = 2 × 1 + 1 = 3.","f(3) = 9 − 1 = 8.","(f∘g)(1) = 8."],ans:"8 (option A)",tip:"Work inside-out numerically: g(1) = 3, then f(3) = 8. Never expand the composition symbolically for a point value."},
{type:"hard",q:"The function f(x) = 1/x on R − {0} is:",options:["one-one and onto R − {0}","neither","onto but not one-one","one-one but not onto"],answer:0,steps:["1/x₁ = 1/x₂ → x₁ = x₂: one-one.","For any y ≠ 0, x = 1/y maps to y: onto R − {0}.","Bijective on its natural domain."],ans:"one-one and onto R − {0} (option A)",tip:"1/x is its own inverse — self-inverse functions on their natural domain are always bijective there."},
{type:"hard",q:"If A × B has 12 elements and A has 3 elements, then B has:",options:["4 elements","9 elements","15 elements","36 elements"],answer:0,steps:["|A × B| = |A| × |B|.","12 = 3 × |B|.","|B| = 4."],ans:"4 elements (option A)",tip:"Cartesian size multiplies: divide the product size by the known set. Option D multiplies instead — the reverse trap."},
{type:"hard",q:"Let f(x) = x + 1/x for x > 0. The minimum value of f is:",options:["1","2","0","−2"],answer:1,steps:["By AM ≥ GM: (x + 1/x)/2 ≥ √(x · 1/x) = 1.","So f ≥ 2.","Equality at x = 1 → minimum 2."],ans:"2 (option B)",tip:"x + 1/x ≥ 2 for x > 0 by AM–GM — the single most-used inequality in functions. Equality at x = 1."},
],
"2. Complex Numbers & Quadratic Equations": [
{type:"hard",q:"The modulus of (1 + i)/(1 − i) is:",options:["1","√2","2","0"],answer:0,steps:["(1+i)/(1−i) = (1+i)²/2 = 2i/2 = i.","|i| = 1.","(Faster: |num|/|den| = √2/√2 = 1.)"],ans:"1 (option A)",tip:"Modulus of a quotient = quotient of moduli: √2/√2 = 1, no rationalisation needed."},
{type:"hard",q:"If α, β are roots of x² − 5x + 6 = 0, then α² + β² equals:",options:["13","25","12","36"],answer:0,steps:["α + β = 5, αβ = 6.","α² + β² = (α+β)² − 2αβ.","= 25 − 12 = 13."],ans:"13 (option A)",tip:"Symmetric sums via (α+β) and αβ — never solve for the roots individually."},
{type:"hard",q:"The conjugate of (2 + 3i)/(1 − i) is:",options:["(−1 + 5i)/2","(−1 − 5i)/2","(5 + i)/2","(5 − i)/2"],answer:1,steps:["(2+3i)(1+i)/2 = (2 + 5i + 3i²)/2 = (−1 + 5i)/2.","Conjugate flips the imaginary sign.","= (−1 − 5i)/2."],ans:"(−1 − 5i)/2 (option B)",tip:"Simplify first, conjugate last. Conjugation distributes — but flipping before simplifying invites sign errors."},
{type:"hard",q:"If z = 1 + i, then z⁴ equals:",options:["4i","−4","4","−4i"],answer:1,steps:["z² = (1+i)² = 2i.","z⁴ = (2i)² = −4.","(Polar: √2·e^(iπ/4), raise to 4th → 4·e^(iπ) = −4.)"],ans:"−4 (option B)",tip:"Square twice: (1+i)² = 2i, then square again. Option A stops at z² — always count the squarings."},
{type:"hard",q:"The value of (1 + i)⁶ is:",options:["8i","−8i","8","−8"],answer:1,steps:["(1+i)² = 2i.","(1+i)⁴ = (2i)² = −4.","(1+i)⁶ = (1+i)⁴(1+i)² = (−4)(2i) = −8i."],ans:"−8i (option B)",tip:"Build powers from (1+i)² = 2i: square for 4th power, multiply 4th × 2nd for 6th. Never expand binomially."},
{type:"hard",q:"If |z| = 3 and arg(z) = π/3, then z equals:",options:["3/2 + (3√3/2)i","3 + 3i","√3 + 3i","3/2 − (3√3/2)i"],answer:0,steps:["z = r(cosθ + i sinθ).","= 3(1/2 + i√3/2).","= 3/2 + (3√3/2)i."],ans:"3/2 + (3√3/2)i (option A)",tip:"Polar → rectangular: r cosθ, r sinθ. cos π/3 = 1/2, sin π/3 = √3/2 — the standard triangle."},
{type:"hard",q:"If ω is a complex cube root of unity (ω ≠ 1), then 1 + ω + ω² equals:",options:["0","1","3","−1"],answer:0,steps:["ω³ = 1 with ω ≠ 1.","x³ − 1 = (x − 1)(x² + x + 1) = 0.","ω satisfies x² + x + 1 = 0 → sum = 0."],ans:"0 (option A)",tip:"1 + ω + ω² = 0 is THE cube-root identity — it annihilates half of all ω questions."},
{type:"hard",q:"The equation x² + x + 1 = 0 has roots in complex numbers. Their product is:",options:["1","−1","0","2"],answer:0,steps:["Product = c/a = 1/1.","= 1.","(They are ω, ω² with |ω| = 1.)"],ans:"1 (option A)",tip:"Product = c/a always. For x²+x+1 the roots are the primitive cube roots — product 1, sum −1."},
{type:"hard",q:"If z₁ = 2 + i and z₂ = 1 − i, then z₁z₂ equals:",options:["3 + i","3 − i","1 + 3i","2 − i"],answer:1,steps:["(2+i)(1−i) = 2 − 2i + i − i².","= 2 − i + 1 = 3 − i.","i² = −1 flips the last sign."],ans:"3 − i (option B)",tip:"FOIL with i² = −1: real parts 2+1 = 3, imaginary −2+1 = −1. Track the i² sign."},
{type:"hard",q:"The argument of −1 + i is:",options:["3π/4","π/4","−π/4","−3π/4"],answer:0,steps:["Point (−1, 1) lies in quadrant II.","Reference angle = tan⁻¹(1/1) = π/4.","arg = π − π/4 = 3π/4."],ans:"3π/4 (option A)",tip:"Quadrant II → π minus reference angle. Option B ignores the negative real part."},
],
"3. Matrices & Determinants": [
{type:"hard",q:"If A = [[1, 2], [3, 4]], then det(A) equals:",options:["−2","2","10","−10"],answer:0,steps:["det = ad − bc = 1 × 4 − 2 × 3.","= 4 − 6.","= −2."],ans:"−2 (option A)",tip:"ad − bc with the minus — 4 − 6 = −2. Option B adds (4 + 6 = 10 is |A| with wrong sign chain)."},
{type:"hard",q:"If A is a 3×3 matrix with det(A) = 2, then det(2A) equals:",options:["4","8","16","6"],answer:2,steps:["det(kA) = kⁿdet(A) for an n × n matrix.","n = 3 → det(2A) = 2³ × 2.","= 8 × 2 = 16."],ans:"16 (option C)",tip:"Every row scales by k, so kⁿ multiplies the determinant. For 3×3: ×8, not ×2 — option B scales once."},
{type:"hard",q:"If A = [[2, 0], [0, 3]], then A⁻¹ equals:",options:["[[1/2, 0], [0, 1/3]]","[[3, 0], [0, 2]]","[[1/3, 0], [0, 1/2]]","[[−2, 0], [0, −3]]"],answer:0,steps:["Diagonal matrix: inverse = reciprocal of each diagonal entry.","1/2 and 1/3.","Off-diagonals stay 0."],ans:"[[1/2, 0], [0, 1/3]] (option A)",tip:"Diagonal matrices invert entry-wise; option C swaps the reciprocals — match positions."},
{type:"hard",q:"The system x + y = 2, 2x + 2y = 5 has:",options:["a unique solution","infinitely many solutions","no solution","two solutions"],answer:2,steps:["Second equation is 2 × (x + y) = 5 → x + y = 2.5.","Contradicts x + y = 2 from the first.","Parallel lines → no solution."],ans:"no solution (option C)",tip:"Proportional coefficients (1:2 = 1:2) but different constants (2 vs 2.5) → inconsistent. Ratios decide: a₁/a₂ = b₁/b₂ ≠ c₁/c₂."},
{type:"hard",q:"If A and B are 2×2 matrices with det(A) = 3 and det(B) = 4, then det(AB) equals:",options:["7","12","24","1"],answer:1,steps:["det(AB) = det(A)·det(B).","= 3 × 4.","= 12."],ans:"12 (option B)",tip:"Determinants multiply across products; they ADD only across scalar multiples via kⁿ. Option A adds — wrong operation."},
{type:"hard",q:"A square matrix A satisfies A² = I. Then det(A) can be:",options:["only 1","only −1","1 or −1","0"],answer:2,steps:["det(A²) = (det A)² = det(I) = 1.","So (det A)² = 1.","det A = ±1."],ans:"1 or −1 (option C)",tip:"Take determinants of both sides: (detA)² = 1. Involutory matrices (reflections) show both signs occur."},
{type:"hard",q:"The rank of the matrix [[1, 2, 3], [2, 4, 6], [1, 1, 1]] is:",options:["3","2","1","0"],answer:1,steps:["Row 2 = 2 × Row 1 → dependent.","Rows 1 and 3 are independent.","Rank = 2."],ans:"2 (option B)",tip:"Spot proportional rows first — R₂ = 2R₁ kills full rank instantly. Non-zero determinant needs rank 3."},
{type:"hard",q:"If A = [[1, 1], [1, 1]], then A¹⁰ equals:",options:["2⁹A","2¹⁰A","10A","A"],answer:0,steps:["A² = [[2,2],[2,2]] = 2A.","So Aⁿ = 2ⁿ⁻¹A.","A¹⁰ = 2⁹A."],ans:"2⁹A (option A)",tip:"Idempotent-type pattern: compute A² = 2A once, then Aⁿ = 2ⁿ⁻¹A. Option B is off by one power."},
{type:"hard",q:"If the system 2x + 3y = 7 and 4x + 6y = 14 is considered, it has:",options:["no solution","a unique solution","infinitely many solutions","exactly two solutions"],answer:2,steps:["Second equation = 2 × first (4x+6y = 14 = 2×7).","Dependent equations → same line.","Infinitely many solutions."],ans:"infinitely many solutions (option C)",tip:"Fully proportional (a₁/a₂ = b₁/b₂ = c₁/c₂) → coincident lines → infinite solutions. One mismatch in constants → zero."},
{type:"hard",q:"The adjoint of [[a, b], [c, d]] is:",options:["[[d, −b], [−c, a]]","[[a, c], [b, d]]","[[d, b], [c, a]]","[[−d, b], [c, −a]]"],answer:0,steps:["Swap the diagonal, negate the off-diagonals.","[[d, −b], [−c, a]].","Then A⁻¹ = adj(A)/det(A)."],ans:"[[d, −b], [−c, a]] (option A)",tip:"Swap–negate: diagonals swap places, off-diagonals flip sign. Option B is the transpose, not the adjoint."},
],
"4. Permutations & Combinations": [
{type:"hard",q:"The number of ways to arrange 5 distinct books on a shelf is:",options:["25","120","60","32"],answer:1,steps:["5 distinct objects in a row: 5!.","= 5 × 4 × 3 × 2 × 1.","= 120."],ans:"120 (option B)",tip:"Distinct arrangements = n!. Option A (5²) and D (2⁵) are wrong-operation traps."},
{type:"hard",q:"The number of ways to choose 2 students from 6 is:",options:["12","15","30","36"],answer:1,steps:["C(6,2) = 6 × 5/2.","= 15.","Order does not matter → combinations, not permutations (30)."],ans:"15 (option B)",tip:"Choose = C(n,r) = 6×5/2 = 15. Option C (P(6,2) = 30) counts ordered pairs — read choose vs arrange."},
{type:"hard",q:"5 people sit around a round table. The number of arrangements is:",options:["120","24","60","12"],answer:1,steps:["Circular arrangements = (n−1)!.","= 4!.","= 24."],ans:"24 (option B)",tip:"Round table → fix one person, arrange the rest: (n−1)!. Option A forgets the circular symmetry."},
{type:"hard",q:"The number of diagonals of a hexagon is:",options:["6","9","12","15"],answer:1,steps:["Diagonals = C(n,2) − n.","= 15 − 6.","= 9."],ans:"9 (option B)",tip:"All pairs minus sides: n(n−3)/2 = 6×3/2 = 9. Option D counts all pairs including sides."},
{type:"hard",q:"The number of 4-letter words from MATHEMATICS (letters, repetition as available) is:",options:["2454","11P4","11⁴","11C4"],answer:0,steps:["Letters available: M×2, A×2, T×2, H,E,I,C,S single.","Cases: all distinct (P(8,4) = 1680), one pair + 2 distinct (C(3,1)×C(7,2)×12 = 756), two pairs (C(3,2)×6 = 18).","Total = 1680 + 756 + 18 = 2454."],ans:"2454 (option A)",tip:"Repetition-limited words need case-splitting by pattern (4 distinct / pair+2 / two pairs). Options B–D ignore the repeat limits."},
{type:"hard",q:"The number of ways to divide 6 distinct objects into groups of 4 and 2 is:",options:["15","30","90","45"],answer:0,steps:["C(6,4) = 15 (rest automatically forms the group of 2).","Unequal groups → no further division.","15."],ans:"15 (option A)",tip:"Unequal groups: C(n,r) once. Equal groups need ÷2! extra — option B forgets which case applies."},
/* @@M04D@@ */
/* @@M04E@@ */
],
"5. Binomial Theorem": [
{type:"hard",q:"The number of terms in the expansion of (x + y + z)⁵ is:",options:["21","15","25","6"],answer:0,steps:["Terms = C(n + r − 1, r − 1) with n = 5, r = 3.","= C(7, 2) = 21.","Stars-and-bars on exponents summing to 5."],ans:"21 (option A)",tip:"Multinomial term count = C(n+r−1, r−1) = C(7,2) = 21. Option B is C(6,2) — off-by-one on stars-and-bars."},
{type:"hard",q:"The coefficient of x³ in (1 + x)⁷ is:",options:["35","21","7","70"],answer:0,steps:["T₄ = C(7,3)x³.","C(7,3) = 35.","35."],ans:"35 (option A)",tip:"Coefficient of x^r in (1+x)ⁿ = C(n,r) directly. C(7,3) = 35 — Pascal's row 1-7-21-35-35-21-7-1."},
{type:"hard",q:"The term independent of x in (x + 2/x)⁶ is:",options:["160","60","120","240"],answer:0,steps:["T(r+1) = C(6,r) x^(6−r) (2/x)^r = C(6,r) 2^r x^(6−2r).","6 − 2r = 0 → r = 3.","C(6,3) × 8 = 20 × 8 = 160."],ans:"160 (option A)",tip:"Set the x-exponent to zero for r, then multiply C(n,r) by the constant's power. Option C drops the 2³ = 8."},
{type:"hard",q:"If the 4th term in (x + a)ⁿ is 56x³, then n and a satisfy:",options:["C(n,3)a³ = 56","C(n,4)a⁴ = 56x³","C(n,3)aⁿ⁻³ = 56","C(n,3) = 56"],answer:0,steps:["T₄ = C(n,3) x^(n−3) a³.","Given T₄ = 56x³ → powers of x match (n = 6).","Coefficients: C(n,3)a³ = 56."],ans:"C(n,3)a³ = 56 (option A)",tip:"T(r+1) ↔ C(n,r): 4th term uses r = 3, not 4. The x-power fixes n; the coefficient fixes a."},
{type:"hard",q:"The middle term in the expansion of (x + 1/x)⁸ is:",options:["70","56","128","35"],answer:0,steps:["8 + 1 = 9 terms → middle is T₅ (r = 4).","T₅ = C(8,4) x^(8−2×4) = C(8,4).","= 70."],ans:"70 (option A)",tip:"Even n → single middle term T(n/2+1); r = n/2 kills the x-power. C(8,4) = 70."},
{type:"hard",q:"The sum of the coefficients in (2x − 3y)⁴ is:",options:["1","−1","625","81"],answer:0,steps:["Put x = y = 1.","(2 − 3)⁴ = (−1)⁴.","= 1."],ans:"1 (option A)",tip:"Sum of coefficients = value at all-variables = 1: (2−3)⁴ = 1. Option C is (2+3)⁴ — sign matters."},
{type:"hard",q:"The greatest coefficient in (1 + x)¹⁰ is:",options:["252","210","120","1024"],answer:0,steps:["n = 10 even → central coefficient C(10,5).","= 252.","(Row 10 of Pascal: …210, 252, 210…)"],ans:"252 (option A)",tip:"Even n → C(n, n/2) is the unique maximum: C(10,5) = 252. Option D is the row SUM 2¹⁰."},
{type:"hard",q:"If (1 + x)ⁿ = C₀ + C₁x + … and C₀ + C₁ + … = 512, then n equals:",options:["9","8","10","7"],answer:0,steps:["Sum = 2ⁿ = 512.","2⁹ = 512.","n = 9."],ans:"9 (option A)",tip:"Sum of binomial coefficients = 2ⁿ. 512 = 2⁹ — powers of 2 to 1024 must be instant recall."},
{type:"hard",q:"The remainder when 7¹⁰³ is divided by 8 is:",options:["7","1","0","3"],answer:0,steps:["7 ≡ −1 (mod 8).","7¹⁰³ ≡ (−1)¹⁰³ = −1 ≡ 7.","Odd power preserves the −1."],ans:"7 (option A)",tip:"7 ≡ −1 mod 8: odd exponent → −1 ≡ 7. Even exponent would give 1 — parity decides."},
{type:"hard",q:"The last digit of 7¹⁰⁰ is:",options:["1","7","9","3"],answer:0,steps:["Powers of 7 cycle: 7, 9, 3, 1 (period 4).","100 mod 4 = 0 → 4th in cycle.","= 1."],ans:"1 (option A)",tip:"7ⁿ units digits cycle 7-9-3-1 every 4. Exponent mod 4 = 0 lands on 1."},
],
"6. Sequences & Series": [
{type:"hard",q:"The 10th term of the AP 3, 7, 11, … is:",options:["39","43","47","35"],answer:0,steps:["a = 3, d = 4.","T₁₀ = a + 9d = 3 + 36.","= 39."],ans:"39 (option A)",tip:"Tₙ = a + (n−1)d: 3 + 9×4 = 39. Option B uses 10d instead of 9d."},
{type:"hard",q:"The sum of the first 20 natural numbers is:",options:["190","210","200","220"],answer:1,steps:["S = n(n+1)/2.","= 20 × 21/2.","= 210."],ans:"210 (option B)",tip:"n(n+1)/2 with n = 20: 20×21/2 = 210. Option A is the sum to 19."},
{type:"hard",q:"The 5th term of the GP 2, 6, 18, … is:",options:["162","54","486","108"],answer:0,steps:["a = 2, r = 3.","T₅ = ar⁴ = 2 × 81.","= 162."],ans:"162 (option A)",tip:"Tₙ = ar^(n−1): 2 × 3⁴ = 162. Option B is T₄ — count the exponent (n−1)."},
{type:"hard",q:"The sum of the infinite GP 1 + 1/2 + 1/4 + … is:",options:["2","1","1.5","infinity"],answer:0,steps:["S∞ = a/(1 − r) = 1/(1 − 1/2).","= 1/(1/2).","= 2."],ans:"2 (option A)",tip:"a/(1−r) with a = 1, r = 1/2: 1/(1/2) = 2. Converges only because |r| < 1."},
{type:"hard",q:"If the AM of two numbers is 10 and GM is 8, the numbers are:",options:["16 and 4","12 and 8","20 and 0","14 and 6"],answer:0,steps:["Sum = 20, product = 64.","Roots of t² − 20t + 64 = 0.","t = 16, 4."],ans:"16 and 4 (option A)",tip:"Numbers are roots of t² − (2AM)t + GM² = 0: t² − 20t + 64 = 0 → 16, 4."},
{type:"hard",q:"The HM of 4 and 6 is:",options:["5","4.8","5.2","24"],answer:1,steps:["HM = 2ab/(a+b) = 2 × 24/10.","= 48/10.","= 4.8."],ans:"4.8 (option B)",tip:"HM = 2ab/(a+b) = 48/10 = 4.8. It sits below GM (√24 ≈ 4.9) — AM ≥ GM ≥ HM always."},
{type:"hard",q:"The sum of the series 1 + 3 + 5 + … up to 10 terms is:",options:["100","110","90","200"],answer:0,steps:["Sum of first n odd numbers = n².","n = 10 → 100.","100."],ans:"100 (option A)",tip:"Odd-sum = n² is exact: 10² = 100. Option B adds an extra 10."},
{type:"hard",q:"The 8th term of the HP with AP 2, 5, 8, … in the denominator is:",options:["1/23","1/20","23","1/26"],answer:0,steps:["AP: a = 2, d = 3; T₈ = 2 + 7 × 3 = 23.","HP term = reciprocal.","1/23."],ans:"1/23 (option A)",tip:"HP via AP: find the AP term (23), then reciprocate. Option C forgets the reciprocal."},
{type:"hard",q:"The sum 2 + 4 + 6 + … + 100 equals:",options:["2550","2500","5050","2600"],answer:0,steps:["= 2(1 + 2 + … + 50).","= 2 × 50 × 51/2.","= 2550."],ans:"2550 (option A)",tip:"Factor 2 out, then n(n+1)/2 with n = 50: 2 × 1275 = 2550. Option C is the sum to 100."},
{type:"hard",q:"Three numbers in GP have sum 13 and product 27. The numbers are:",options:["1, 3, 9","3, 3, 7","9, 3, 1 only","1, 3, 9 or 9, 3, 1"],answer:3,steps:["Let a/r, a, ar: product = a³ = 27 → a = 3.","Sum: 3/r + 3 + 3r = 13 → 1/r + r = 10/3.","r = 3 or 1/3 → (1,3,9) or (9,3,1)."],ans:"1, 3, 9 or 9, 3, 1 (option D)",tip:"GP triplets: product gives middle term (a = 3), sum gives r + 1/r. Both orders valid — option A lists one."},
{type:"hard",q:"The sum of the first n terms of 1² + 2² + … is:",options:["n(n+1)(2n+1)/6","n²(n+1)²/4","n(n+1)/2","n³/3"],answer:0,steps:["Standard formula: sum of squares = n(n+1)(2n+1)/6.","Option B is the sum of CUBES.","Option C is the sum of first n naturals."],ans:"n(n+1)(2n+1)/6 (option A)",tip:"Squares: n(n+1)(2n+1)/6; cubes: [n(n+1)/2]². Option B is the cubes formula — pair them to never confuse."},
{type:"hard",q:"If a, b, c are in AP, then a², b², c² are in:",options:["AP","GP","HP","none necessarily"],answer:3,steps:["Test 1, 2, 3 (AP): squares 1, 4, 9.","Differences 3, 5 — not AP; ratios differ — not GP.","Counterexample kills all three progressions at once."],ans:"none necessarily (option D)",tip:"One counterexample (1,2,3 → 1,4,9) disproves AP/GP/HP at once. Never assume structure survives squaring."},
],
"7. Limit, Continuity & Differentiability": [
{type:"hard",q:"The sum 1·2 + 2·3 + … + 10·11 equals:",options:["440","330","550","220"],answer:0,steps:["Σk(k+1) = Σk² + Σk.","= 10×11×21/6 + 10×11/2 = 385 + 55.","= 440."],ans:"440 (option A)",tip:"Split k(k+1) = k² + k, sum each: 385 + 55 = 440. Option D is Σk² alone."},
{type:"hard",q:"If the sum of n terms of 1 + 4 + 7 + … is 715, then n equals:",options:["20","22","25","19"],answer:1,steps:["a = 1, d = 3: S = n/2(2 + 3(n−1)).","n(3n − 1)/2 = 715 → 3n² − n − 1430 = 0.","n = 22 (positive root: (1 + √17161)/6 = 132/6)."],ans:"22 (option B)",tip:"S = n/2(2a + (n−1)d) → quadratic 3n² − n − 1430 = 0. √17161 = 131 → n = 22. Reject the negative root."},
{type:"hard",q:"lim(x→0) sin(5x)/x equals:",options:["5","1","0","1/5"],answer:0,steps:["sin(5x)/(5x) → 1.","So sin(5x)/x = 5 × sin(5x)/(5x).","= 5."],ans:"5 (option A)",tip:"Match the argument: sin(5x)/x = 5·sin(5x)/(5x) → 5. The coefficient jumps out front."},
{type:"hard",q:"lim(x→0) (eˣ − 1)/x equals:",options:["1","0","e","infinity"],answer:0,steps:["Standard limit = 1.","(First principle of d(eˣ)/dx at 0.)","Also follows from eˣ ≈ 1 + x."],ans:"1 (option A)",tip:"(eˣ−1)/x → 1 and ln(1+x)/x → 1 are the twin standard limits. Option C confuses the function with its limit."},
{type:"hard",q:"lim(x→0) (1 − cos x)/x² equals:",options:["1/2","1","0","2"],answer:0,steps:["1 − cos x = 2sin²(x/2).","Ratio = 2sin²(x/2)/x² = (1/2)[sin(x/2)/(x/2)]².","→ 1/2."],ans:"1/2 (option A)",tip:"Half-angle first: 1−cosx = 2sin²(x/2), then standard limit gives 1/2. Option B forgets the half."},
{type:"hard",q:"f(x) = |x| is continuous at x = 0 but:",options:["differentiable with f'(0) = 0","not differentiable at 0","discontinuous at 0","differentiable with f'(0) = 1"],answer:1,steps:["Continuous: limit 0 = f(0).","Left derivative −1, right derivative +1.","Corner → not differentiable."],ans:"not differentiable at 0 (option B)",tip:"Modulus corners are never differentiable at the join. Continuity holds; differentiability fails — the standard split."},
{type:"hard",q:"The derivative of x³ at x = 2 is:",options:["12","8","6","9"],answer:0,steps:["d/dx(x³) = 3x².","At x = 2: 3 × 4.","= 12."],ans:"12 (option A)",tip:"3x² at x = 2: 3 × 4 = 12. Option B evaluates x³ instead of its derivative."},
{type:"hard",q:"If y = sin(2x), then dy/dx equals:",options:["2cos(2x)","cos(2x)","−2sin(2x)","cos x"],answer:0,steps:["Chain rule: cos(2x) × d(2x)/dx.","= cos(2x) × 2.","= 2cos(2x)."],ans:"2cos(2x) (option A)",tip:"Chain rule multiplies by the inner derivative 2. Option B drops it — the universal chain-rule trap."},
{type:"hard",q:"The function f(x) = x² is decreasing on:",options:["(0, ∞)","(−∞, 0)","R","never"],answer:1,steps:["f'(x) = 2x < 0 → x < 0.","Decreasing on (−∞, 0).","Increasing on (0, ∞)."],ans:"(−∞, 0) (option B)",tip:"Sign of f' decides: 2x < 0 left of origin. Option A is the increasing interval — the mirror trap."},
{type:"hard",q:"The maximum value of f(x) = −x² + 4x + 1 is:",options:["5","1","4","−3"],answer:0,steps:["Vertex at x = −b/2a = 2.","f(2) = −4 + 8 + 1 = 5.","Downward parabola → maximum 5."],ans:"5 (option A)",tip:"−b/2a = 2, then f(2) = 5. Completing the square gives −(x−2)² + 5 directly."},
],
"8. Integral Calculus": [
{type:"hard",q:"∫ 2x dx equals:",options:["x² + C","2x² + C","x + C","2 + C"],answer:0,steps:["∫2x dx = 2 × x²/2.","= x² + C.","(+C mandatory for indefinite integrals.)"],ans:"x² + C (option A)",tip:"Power rule reversed: x^(1+1)/(1+1) × 2 = x². Option B forgets to divide by the new exponent."},
{type:"hard",q:"∫₀¹ x² dx equals:",options:["1/3","1/2","1","2"],answer:0,steps:["Antiderivative x³/3.","At 1: 1/3; at 0: 0.","= 1/3."],ans:"1/3 (option A)",tip:"x³/3 from 0 to 1 = 1/3. Option B integrates x instead of x²."},
{type:"hard",q:"∫ sin x dx equals:",options:["−cos x + C","cos x + C","−sin x + C","tan x + C"],answer:0,steps:["d(cos x)/dx = −sin x.","So ∫sin x dx = −cos x + C.","Differentiate back to confirm."],ans:"−cos x + C (option A)",tip:"Sine integrates to MINUS cosine. Option B forgets the sign — differentiate to self-audit."},
{type:"hard",q:"∫ e²ˣ dx equals:",options:["e²ˣ/2 + C","e²ˣ + C","2e²ˣ + C","eˣ + C"],answer:0,steps:["Substitute u = 2x: ∫e^u du/2.","= e^u/2.","= e²ˣ/2 + C."],ans:"e²ˣ/2 + C (option A)",tip:"Divide by the inner derivative 2. Option B integrates e²ˣ as plain eˣ — chain rule in reverse."},
{type:"hard",q:"∫ x eˣ dx equals:",options:["eˣ(x − 1) + C","xeˣ + C","eˣ + C","x²eˣ/2 + C"],answer:0,steps:["By parts: u = x, dv = eˣdx.","= xeˣ − ∫eˣdx.","= eˣ(x − 1) + C."],ans:"eˣ(x − 1) + C (option A)",tip:"LIATE: x first, eˣ second. Memorise ∫xeˣ = eˣ(x−1) — it recurs in area problems."},
{type:"hard",q:"∫₀^(π/2) cos x dx equals:",options:["1","0","−1","π/2"],answer:0,steps:["Antiderivative sin x.","sin(π/2) − sin 0.","= 1 − 0 = 1."],ans:"1 (option A)",tip:"Cosine over a quarter period integrates to exactly 1. Option B integrates over a half period."},
{type:"hard",q:"The area under y = x from 0 to 2 is:",options:["2","4","1","2.5"],answer:0,steps:["∫₀² x dx = [x²/2]₀².","= 4/2 = 2.","(Triangle: ½ × 2 × 2 = 2.)"],ans:"2 (option A)",tip:"Integrate or use the triangle area — both give 2. Option B forgets the ½."},
{type:"hard",q:"∫ dx/(1 + x²) equals:",options:["tan⁻¹x + C","sin⁻¹x + C","ln(1+x²) + C","cot⁻¹x + C"],answer:0,steps:["Standard form ∫dx/(1+x²) = tan⁻¹x.","+ C.","Differentiate tan⁻¹x to confirm: 1/(1+x²)."],ans:"tan⁻¹x + C (option A)",tip:"1/(1+x²) → arctan is a memorised pair. Option B pairs with 1/√(1−x²) — keep the families apart."},
{type:"hard",q:"∫₀^π sin x dx equals:",options:["2","0","1","−2"],answer:0,steps:["Antiderivative −cos x.","(−cos π) − (−cos 0) = 1 + 1.","= 2."],ans:"2 (option A)",tip:"Sine over a half period: 2. Full period gives 0 — the interval decides, memorise both."},
{type:"hard",q:"If d/dx F(x) = x², then ∫₁² x² dx equals:",options:["7/3","8/3","1/3","3"],answer:0,steps:["F(x) = x³/3.","F(2) − F(1) = 8/3 − 1/3.","= 7/3."],ans:"7/3 (option A)",tip:"Evaluate and subtract: 8/3 − 1/3 = 7/3. Option B forgets the lower limit."},
],
"9. Differential Equations": [
{type:"hard",q:"The differential equation of the family y = mx + 2/m (m is the parameter) has order and degree:",options:["1, 1","1, 3","2, 1","1, 2"],answer:3,steps:["Differentiate: dy/dx = m; call it p.","Substitute: y = px + 2/p → multiply by p: yp = p²x + 2.","Highest power of p is 2 → order 1, degree 2."],ans:"order 1, degree 2 (option D)",tip:"Eliminate the parameter via p = dy/dx, then read the highest power of p. yp = p²x + 2 shows degree 2 at once."},
{type:"hard",q:"The solution of dy/dx = 2x with y(0) = 1 is:",options:["y = x² + 1","y = x²","y = 2x + 1","y = x² − 1"],answer:0,steps:["Integrate: y = x² + C.","y(0) = 1 → C = 1.","y = x² + 1."],ans:"y = x² + 1 (option A)",tip:"Integrate, then use the initial condition for C: 0 + C = 1. Option B skips the condition."},
{type:"hard",q:"The order of d²y/dx² + (dy/dx)³ = 0 is:",options:["1","2","3","5"],answer:1,steps:["Highest derivative present: d²y/dx².","Order = 2.","(Its power is 1, so degree = 1.)"],ans:"2 (option B)",tip:"Order = highest derivative (2 here); the cubed FIRST derivative does not raise the order. Read derivatives, not powers."},
{type:"hard",q:"The general solution of dy/dx = y/x is:",options:["y = Cx","y = x + C","y = Cx²","y = eˣ + C"],answer:0,steps:["Separable: dy/y = dx/x.","ln y = ln x + C'.","y = Cx."],ans:"y = Cx (option A)",tip:"dy/y = dx/x → ln y = ln x + C → straight lines through origin. Option B adds instead of multiplying."},
{type:"hard",q:"The integrating factor of dy/dx + 2y = 4 is:",options:["e²ˣ","eˣ","x²","2x"],answer:0,steps:["IF = e^∫Pdx with P = 2.","= e^∫2dx.","= e²ˣ."],ans:"e²ˣ (option A)",tip:"IF = e^∫Pdx: integrate the y-coefficient (2 → 2x), then exponentiate. No constant needed in IF."},
{type:"hard",q:"The solution of dy/dx + y = e⁻ˣ with y(0) = 0 is:",options:["y = xe⁻ˣ","y = e⁻ˣ","y = eˣ","y = x + 1"],answer:0,steps:["IF = eˣ; d(y·eˣ)/dx = 1.","y·eˣ = x + C; y(0) = 0 → C = 0.","y = xe⁻ˣ."],ans:"y = xe⁻ˣ (option A)",tip:"IF = eˣ turns LHS into d(y·eˣ)/dx = 1 — integrate once, apply y(0) = 0. Resonance form x·e⁻ˣ emerges."},
{type:"hard",q:"The equation (dy/dx)² + y = x is of order and degree:",options:["1, 2","2, 1","1, 1","2, 2"],answer:0,steps:["Highest derivative: dy/dx → order 1.","Its power is 2 → degree 2.","Order 1, degree 2."],ans:"1, 2 (option A)",tip:"Order from the highest derivative; degree from ITS power. First derivative squared → (1, 2). Option B swaps them."},
{type:"hard",q:"The solution of dy/dx = eˣ⁺ʸ with y(0) = 0 is:",options:["eʸ + eˣ = 0","e⁻ʸ + eˣ = 2","y = x","eʸ = eˣ"],answer:1,steps:["Separate: e⁻ʸdy = eˣdx.","Integrate: −e⁻ʸ = eˣ + C.","y(0) = 0 → −1 = 1 + C → C = −2, so e⁻ʸ + eˣ = 2."],ans:"e⁻ʸ + eˣ = 2 (option B)",tip:"Split eˣ⁺ʸ = eˣeʸ, separate, integrate: −e⁻ʸ = eˣ + C. Initial condition fixes C = −2."},
],
"10. Coordinate Geometry": [
{type:"hard",q:"The slope of the tangent to y = x² at (1, 1) is:",options:["2","1","0","1/2"],answer:0,steps:["dy/dx = 2x.","At x = 1: 2.","Slope = 2."],ans:"2 (option A)",tip:"Differentiate and substitute: 2×1 = 2. Option B reports the point's y-value — irrelevant."},
{type:"hard",q:"The equation of the tangent to y = x² at (1, 1) is:",options:["y = 2x − 1","y = x + 1","y = 2x + 1","y = x − 1"],answer:0,steps:["Slope m = 2 at (1,1).","y − 1 = 2(x − 1).","y = 2x − 1."],ans:"y = 2x − 1 (option A)",tip:"Point-slope with m = 2: y − 1 = 2(x−1). Option C flips the intercept sign."},
{type:"hard",q:"The centre of the circle x² + y² − 4x + 6y = 0 is:",options:["(2, −3)","(−2, 3)","(4, −6)","(0, 0)"],answer:0,steps:["Centre = (−g, −f) = (4/2, −6/2).","= (2, −3).","Radius = √(4 + 9) = √13."],ans:"(2, −3) (option A)",tip:"Centre = (−g, −f): halve coefficients and flip signs. Option B forgets the flips."},
{type:"hard",q:"The radius of x² + y² = 25 is:",options:["25","5","10","√5"],answer:1,steps:["Standard form: r² = 25.","r = 5.","(Centre at origin.)"],ans:"5 (option B)",tip:"r² = constant → r = √constant = 5. Option A reports r² as r."},
{type:"hard",q:"The equation of the circle with centre (1, −2) and radius 3 is:",options:["(x−1)² + (y+2)² = 9","(x+1)² + (y−2)² = 9","x² + y² = 9","(x−1)² + (y+2)² = 3"],answer:0,steps:["(x − h)² + (y − k)² = r².","(x − 1)² + (y + 2)² = 9.","r² = 9, not 3."],ans:"(x−1)² + (y+2)² = 9 (option A)",tip:"Plug (h,k,r) = (1,−2,3): signs flip inside brackets, radius SQUARED. Option D forgets the square."},
{type:"hard",q:"The focus of the parabola y² = 8x is:",options:["(2, 0)","(0, 2)","(−2, 0)","(4, 0)"],answer:0,steps:["y² = 4ax → 4a = 8 → a = 2.","Focus = (a, 0).","= (2, 0)."],ans:"(2, 0) (option A)",tip:"4a = coefficient of x: a = 2, focus (a,0). Option D doubles a."},
/* @@M10D@@ */
/* @@M10E@@ */
],
"11. 3D Geometry": [
/* @@M11A@@ */
/* @@M11B@@ */
/* @@M11C@@ */
/* @@M11D@@ */
/* @@M11E@@ */
],
"12. Vector Algebra": [
/* @@M12A@@ */
/* @@M12B@@ */
/* @@M12C@@ */
/* @@M12D@@ */
/* @@M12E@@ */
],
"13. Statistics & Probability": [
/* @@M13A@@ */
/* @@M13B@@ */
/* @@M13C@@ */
/* @@M13D@@ */
/* @@M13E@@ */
],
"14. Trigonometry": [
/* @@M14A@@ */
/* @@M14B@@ */
/* @@M14C@@ */
/* @@M14D@@ */
/* @@M14E@@ */
],
};
