/* ===== PHYSICS QUESTION BANK — PYQs + Important, full solutions ===== */
const PHYSICS_TOPICS = [
{
  name: "1. Physics & Measurement",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"The density of a material in SI units is 128 kg/m³. In certain units where the unit of length is 25 cm and the unit of mass is 50 g, the numerical value of density is:",
   options:["20","40","640","10"], answer:1,
   steps:["Convert to CGS first: 128 kg/m³ = 128 × 1000 g / 10⁶ cm³ = 0.128 g/cm³.",
    "New unit of density = (unit of mass)/(unit of length)³ = 50 g / (25 cm)³ = 50/15625 = 0.0032 g/cm³ per unit.",
    "Numerical value = 0.128 / 0.0032 = 40.",
    "Check via N₁U₁ = N₂U₂: the ratio old-unit/new-unit always converts in one step."],
   ans:"40 (option B)", tip:"Numerical value × unit = constant. Convert everything to one system (CGS here), then divide by the size of the new unit. Done in 2 lines."},
  {type:"imp", q:"If force (F), length (L) and time (T) are chosen as base quantities, the dimensional formula of MASS is:",
   options:["F L⁻¹ T²","F L T⁻²","F L⁻¹ T⁻²","F L T²"], answer:0,
   steps:["From F = ma → F = m L T⁻².",
    "Solve for m: m = F / (L T⁻²) = F L⁻¹ T².",
    "Verify: F L⁻¹ T² × L T⁻² = F ✓",
    "Build a mini-table: energy = F L, momentum = F T, pressure = F L⁻² — these cover most 'alternate-system' PYQs."],
   ans:"[F L⁻¹ T²] (option A)", tip:"Just rewrite F = ma and solve for the wanted quantity. Never memorise — derive in 5 seconds."}
  ]
},
{
  name: "2. Kinematics",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"The position of a particle is given by x(t) = t³ − 6t² + 9t (m). At what time(s) is the velocity of the particle zero?",
   options:["t = 1 s and 3 s","t = 0 s and 2 s","only t = 2 s","t = 3 s and 4 s"], answer:0,
   steps:["Velocity = dx/dt = 3t² − 12t + 9.",
    "Set v = 0: t² − 4t + 3 = 0.",
    "Factor: (t − 1)(t − 3) = 0 → t = 1 s, 3 s.",
    "Meaning: the particle momentarily stops and turns around at both instants."],
   ans:"t = 1 s and t = 3 s (option A)", tip:"Divide the quadratic by its coefficient of t² first — it collapses instantly to (t−1)(t−3)."},
  {type:"imp", q:"A ball is projected from the ground at 45° with speed 20 m/s (g = 10 m/s²). The ratio of maximum height H to horizontal range R is:",
   options:["1/2","1/4","1/8","1/16"], answer:1,
   steps:["H = u²sin²θ/2g = (400 × ½)/20 = 10 m.",
    "R = u²sin2θ/g = 400 × 1 / 10 = 40 m.",
    "H : R = 10 : 40 = 1 : 4.",
    "This is the identity tanθ = 4H/R; for θ = 45°, H/R = 1/4 automatically."],
   ans:"1/4 (option B)", tip:"Memorise tanθ = 4H/R. For 45°, H = R/4 instantly — zero calculation."},
  {type:"imp", q:"A 150 m long train moving at 30 m/s overtakes another train moving at 20 m/s in the same direction. Time taken to cross it (assume negligible length of the slower train) ≈",
   options:["10 s","15 s","7.5 s","30 s"], answer:1,
   steps:["Relative velocity (same direction) = 30 − 20 = 10 m/s.",
    "Distance to cover = length of the faster train = 150 m.",
    "Time = 150/10 = 15 s."],
   ans:"15 s (option B)", tip:"Same direction → subtract speeds; opposite → add. Relative velocity turns a two-body problem into a one-body problem."}
  ]
}
,
{
  name: "3. Laws of Motion",
  qs: [
  {type:"pyq", year:"JEE Main 2019", q:"A block of mass 10 kg rests on a horizontal floor (μₖ = 0.5). A horizontal force of 60 N is applied. Take g = 10 m/s². The acceleration of the block is:",
   options:["1 m/s²","6 m/s²","0.5 m/s²","zero"], answer:0,
   steps:["Normal reaction N = mg = 100 N.",
    "Friction = μN = 0.5 × 100 = 50 N.",
    "Net force = 60 − 50 = 10 N (> 0, so the block does move).",
    "a = 10/10 = 1 m/s²."],
   ans:"1 m/s² (option A)", tip:"First compare F with μmg — if F ≤ μmg the answer is instantly 0. Here 60 > 50, so it slides."},
  {type:"imp", q:"A car takes a turn on a banked road (θ = 45°) of radius 40 m. Ignoring friction, the maximum safe speed is (g = 10 m/s²):",
   options:["20 m/s","10 m/s","40 m/s","14.1 m/s"], answer:0,
   steps:["For a frictionless banked road: v² = r g tanθ.",
    "v² = 40 × 10 × tan45° = 400.",
    "v = 20 m/s.",
    "With friction the safe range is √[rg(μ + tanθ)/(1 − μtanθ)] — use only when μ is given."],
   ans:"20 m/s (option A)", tip:"Frictionless banking → v = √(rg tanθ). tan45° = 1 collapses it to v = √(rg)."},
  {type:"imp", q:"Two blocks of masses 2 kg and 3 kg are connected by a light string over a frictionless pulley (Atwood machine). The acceleration is (g = 10 m/s²):",
   options:["2 m/s²","3 m/s²","5 m/s²","1 m/s²"], answer:0,
   steps:["a = (m₂ − m₁)g/(m₁ + m₂) = (1)(10)/5 = 2 m/s².",
    "Tension: T = 2m₁m₂g/(m₁+m₂) = 2·2·3·10/5 = 24 N.",
    "Check: for 3 kg block, mg − T = 30 − 24 = 6 = 3a ✓"],
   ans:"2 m/s² (option A)", tip:"Atwood: a = Δm·g/(Σm), T = 2m₁m₂g/(m₁+m₂). Two formulas solve every pulley pair."}
  ]
},
{
  name: "4. Work, Energy & Power",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"A body of mass 2 kg moving at 10 m/s is brought to rest by a constant retarding force over a distance of 5 m. The magnitude of the force is:",
   options:["20 N","10 N","40 N","100 N"], answer:0,
   steps:["Work–energy theorem: W = ΔKE.",
    "−F × 5 = 0 − ½ × 2 × 10².",
    "−5F = −100 → F = 20 N.",
    "Equivalently F = KE/d = 100/5 = 20 N."],
   ans:"20 N (option A)", tip:"F·d = ½mv² → F = ½mv²/d. One line, no kinematics needed."},
  {type:"imp", q:"In an elastic head-on collision between two identical balls, ball A (speed v) hits stationary ball B. After the collision:",
   options:["A stops, B moves with speed v","both move with v/2","A rebounds with v","B moves with 2v"], answer:0,
   steps:["Elastic + equal masses → the velocities are exchanged.",
    "A: v → 0;  B: 0 → v.",
    "This satisfies momentum (mv) and KE (½mv²) conservation simultaneously.",
    "General elastic result: v₁' = (m₁−m₂)v/(m₁+m₂); for m₁ = m₂ → v₁' = 0."],
   ans:"A stops, B moves off with speed v (option A)", tip:"Equal-mass elastic = velocity exchange. Heavy hits light → heavy continues; light hits a wall → light rebounds with same speed."},
  {type:"imp", q:"A spring of constant k = 200 N/m is compressed by 10 cm. The energy stored is:",
   options:["1 J","2 J","0.5 J","20 J"], answer:0,
   steps:["U = ½kx².",
    "x = 0.1 m → U = ½ × 200 × (0.1)² = ½ × 200 × 0.01.",
    "U = 1 J."],
   ans:"1 J (option A)", tip:"Always convert cm → m BEFORE squaring. Half the errors in spring PYQs come from forgetting this."}
  ]
},
{
  name: "5. Rotational Motion",
  qs: [
  {type:"pyq", year:"JEE Main 2019", q:"A solid sphere rolls without slipping. The ratio of its rotational KE to its total KE is:",
   options:["2/7","5/7","2/5","1/2"], answer:0,
   steps:["Rolling: v = ωR. Total KE = ½mv² + ½Iω².",
    "Sphere: I = (2/5)mR² → Rot KE = ½ × (2/5)mR² × v²/R² = (1/5)mv².",
    "Total = (1/2 + 1/5)mv² = (7/10)mv².",
    "Ratio = (1/5)/(7/10) = 2/7."],
   ans:"2/7 (option A)", tip:"Memorise (Rot KE / Total) = ring 1/2, disc 1/4, sphere 2/7. Three ratios cover every rolling PYQ."},
  {type:"imp", q:"A uniform rod of mass M and length L rotates about an axis through one end, perpendicular to the rod. Its moment of inertia is:",
   options:["ML²/12","ML²/3","ML²/2","ML²"], answer:1,
   steps:["About the centre (⊥ axis): I_cm = ML²/12.",
    "Parallel-axis theorem: I = I_cm + Md², with d = L/2.",
    "I = ML²/12 + ML²/4 = ML²/3.",
    "About the centre it is ML²/12 — examiners love testing both."],
   ans:"ML²/3 (option B)", tip:"I(end) = I(centre) + M(L/2)². The parallel-axis theorem converts almost every rod problem into one line."},
  {type:"imp", q:"A disc rotating at 10 rad/s has moment of inertia 0.2 kg·m². If no external torque acts and I becomes 0.1 kg·m² (mass pulled inward), the new angular speed is:",
   options:["20 rad/s","5 rad/s","10 rad/s","40 rad/s"], answer:0,
   steps:["No external torque → L = Iω is conserved.",
    "I₁ω₁ = I₂ω₂ → 0.2 × 10 = 0.1 × ω₂.",
    "ω₂ = 20 rad/s.",
    "KE doubled (like a spinning skater pulling arms in) — extra energy came from the muscles doing work."],
   ans:"20 rad/s (option A)", tip:"Angular momentum conserved whenever torque = 0 — but rotational KE is NOT automatically conserved. Classic trap."}
  ]
}
,
{
  name: "6. Gravitation",
  qs: [
  {type:"pyq", year:"JEE Main 2022", q:"The escape velocity from Earth's surface is vₑ. The orbital velocity of a satellite orbiting very close to Earth's surface is:",
   options:["vₑ/2","vₑ/√2","√2·vₑ","vₑ"], answer:1,
   steps:["Escape velocity: vₑ = √(2GM/R).",
    "Close-orbit speed: v₀ = √(GM/R).",
    "Ratio: vₑ/v₀ = √2 → v₀ = vₑ/√2.",
    "Numerically: vₑ = 11.2 km/s → v₀ ≈ 7.9 km/s."],
   ans:"vₑ/√2 (option B)", tip:"Escape needs extra energy to 'unhook' from gravity → √2 × orbital speed. One ratio reused in dozens of PYQs."},
  {type:"imp", q:"The value of g at a depth d = R/2 (R = Earth's radius) below the surface is (g₀ = surface value):",
   options:["g₀/2","g₀/4","g₀/√2","2g₀"], answer:0,
   steps:["Inside Earth (uniform density): g(depth) = g₀(1 − d/R).",
    "d = R/2 → g = g₀(1 − ½) = g₀/2.",
    "Contrast with height: for h << R, g(h) ≈ g₀(1 − 2h/R).",
    "Depth effect is linear; height effect doubles the fractional change (factor 2h vs d)."],
   ans:"g₀/2 (option A)", tip:"Depth → (1 − d/R), linear. Height → (1 − 2h/R) for small h. At the centre of Earth g = 0 — a favourite statement question."},
  {type:"imp", q:"Two planets move in circular orbits around the same star with orbital radii r and 4r. The ratio of their time periods T₁ : T₂ is:",
   options:["1:8","1:4","1:2","1:16"], answer:0,
   steps:["Kepler's third law: T² ∝ r³.",
    "T₂/T₁ = (r₂/r₁)^(3/2) = 4^(3/2) = 8.",
    "So T₁ : T₂ = 1 : 8.",
    "Same law gives orbital speeds: v ∝ 1/√r — outer planets move slower."],
   ans:"1 : 8 (option A)", tip:"T ∝ r^(3/2). Any 'radius doubles → period?' question is (2)^(3/2) = 2√2. Practice powers of 2 and 4."}
  ]
},
{
  name: "7. Properties of Solids & Liquids",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"A wire of length 1 m and cross-sectional area 2 × 10⁻⁶ m² stretches by 1 mm under a 200 N load. Young's modulus of the material is:",
   options:["1 × 10¹¹ N/m²","2 × 10¹¹ N/m²","4 × 10¹¹ N/m²","0.5 × 10¹¹ N/m²"], answer:0,
   steps:["Y = stress/strain = (F/A)/(ΔL/L).",
    "Stress = 200 / (2 × 10⁻⁶) = 10⁸ N/m².",
    "Strain = 10⁻³ / 1 = 10⁻³.",
    "Y = 10⁸ / 10⁻³ = 1 × 10¹¹ N/m²."],
   ans:"1 × 10¹¹ N/m² (option A)", tip:"Y = FL/(AΔL). One line. Sanity check: metals have Y ~ 10¹¹ N/m²."},
  {type:"imp", q:"Two raindrops of radii r and 2r fall through the same air. The ratio of their terminal velocities is:",
   options:["1:2","1:4","1:8","4:1"], answer:1,
   steps:["Terminal velocity: v_t = 2r²(ρ−σ)g / 9η.",
    "With η, ρ, σ the same → v_t ∝ r².",
    "Ratio = r² : (2r)² = 1 : 4.",
    "That's why big drops fall much faster than drizzle."],
   ans:"1 : 4 (option B)", tip:"Terminal velocity ∝ r², capillary rise ∝ 1/r. These two r-powers cover most fluid PYQs."},
  {type:"imp", q:"Water rises to height h in a capillary tube. If the tube is replaced by one of half the radius, the new rise is:",
   options:["2h","h/2","4h","h/4"], answer:0,
   steps:["Jurin's law: h = 2S cosθ / (ρ g r).",
    "h ∝ 1/r → halving r doubles h.",
    "New height = 2h."],
   ans:"2h (option A)", tip:"Capillary rise h ∝ 1/r. Combine with cosθ: if the liquid doesn't wet (θ > 90°), h is negative → depression."}
  ]
},
{
  name: "8. Thermodynamics",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"A Carnot engine operates between 500 K and 300 K. Its efficiency is:",
   options:["40%","60%","50%","20%"], answer:0,
   steps:["η = 1 − T_cold/T_hot.",
    "η = 1 − 300/500 = 1 − 0.6 = 0.4.",
    "η = 40%.",
    "Carnot is the MAXIMUM possible efficiency for these two temperatures."],
   ans:"40% (option A)", tip:"Always use absolute (Kelvin) temperatures. If T_cold → 0, η → 1 — that's why 100% is impossible."},
  {type:"imp", q:"A gas absorbs 400 J of heat and does 150 J of work. The change in its internal energy is:",
   options:["250 J","550 J","−250 J","400 J"], answer:0,
   steps:["First law: ΔU = Q − W.",
    "ΔU = 400 − 150 = 250 J.",
    "Sign convention: Q in is +, work BY the gas is +.",
    "If the same gas were compressed with the same numbers, signs flip — read carefully."],
   ans:"250 J (option A)", tip:"ΔU = Q − W with W = work done BY gas. Isothermal (ΔU=0 → Q=W) and adiabatic (Q=0 → ΔU=−W) are the two special cases most asked."},
  {type:"imp", q:"n moles of an ideal gas expand isothermally and reversibly from V to 2V at temperature T. Work done BY the gas is:",
   options:["nRT ln2","nRT ln(1/2)","2nRT","zero"], answer:0,
   steps:["Isothermal reversible work: W = nRT ln(V₂/V₁).",
    "W = nRT ln(2V/V) = nRT ln2.",
    "Since ln(1/2) < 0, compression gives negative work — direction matters.",
    "For adiabatic instead: W = nR(T₁−T₂)/(γ−1)."],
   ans:"nRT ln2 (option A)", tip:"Isothermal W = nRT·ln(ratio). Ratio > 1 → expansion, positive. Memory aid: 'ln2 = 0.693' — appear often in numericals."}
  ]
}
,
{
  name: "9. Kinetic Theory of Gases",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"At the same temperature, the ratio of rms speed of H₂ molecules to that of O₂ molecules is:",
   options:["4:1","1:4","16:1","1:16"], answer:0,
   steps:["v_rms = √(3RT/M) → at same T, v_rms ∝ 1/√M.",
    "M(H₂) = 2, M(O₂) = 32.",
    "Ratio = √(32/2) = √16 = 4.",
    "v(H₂) : v(O₂) = 4 : 1."],
   ans:"4 : 1 (option A)", tip:"Lighter gas → faster molecules. For ratio questions: v ∝ 1/√M, and M-ratio 16 → speed-ratio 4."},
  {type:"imp", q:"Total internal energy of n moles of a diatomic gas (rigid) at temperature T is:",
   options:["(5/2)nRT","(3/2)nRT","(7/2)nRT","3nRT"], answer:0,
   steps:["Diatomic rigid → degrees of freedom f = 5 (3 translational + 2 rotational).",
    "Equipartition: energy per mole = (f/2)RT.",
    "U = (5/2)nRT.",
    "If vibrational modes are active, f = 7 → U = (7/2)nRT."],
   ans:"(5/2)nRT (option A)", tip:"Monoatomic 3/2, diatomic 5/2, triatomic 6/2 nRT — remember γ too: 5/3, 7/5, 4/3."},
  {type:"imp", q:"The mean free path of gas molecules increases when:",
   options:["pressure decreases","pressure increases","temperature decreases (V const)","molecular size increases"], answer:0,
   steps:["λ = kT/(√2·π d²·P).",
    "λ ∝ T/P → lower pressure or higher temperature → longer mean free path.",
    "Larger molecular diameter d → shorter λ.",
    "So answer: pressure decreases."],
   ans:"Pressure decreases (option A)", tip:"λ = kT/(√2πd²P). Fewer obstacles (low P) → longer free runs."}
  ]
},
{
  name: "10. Oscillations & Waves",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"A simple pendulum has time period T on Earth. On the Moon (g/6), its time period becomes:",
   options:["T√6","T/√6","6T","T/6"], answer:0,
   steps:["T = 2π√(L/g) → T ∝ 1/√g.",
    "g' = g/6 → T' = T·√(g/g') = T√6.",
    "Weaker gravity → slower swing."],
   ans:"T√6 (option A)", tip:"T ∝ 1/√g. Any 'pendulum on Moon/planet/lift' question is a ratio problem in disguise."},
  {type:"imp", q:"Two tuning forks of frequencies 256 Hz and 260 Hz are sounded together. The number of beats heard per second is:",
   options:["4","2","260","512"], answer:0,
   steps:["Beat frequency = |f₁ − f₂|.",
    "= |260 − 256| = 4 beats/s.",
    "Beats are used to tune instruments: adjust one until beats vanish."],
   ans:"4 beats/s (option A)", tip:"Beats = frequency difference. It can never exceed ~10/s for the human ear — use this to eliminate absurd options."},
  {type:"imp", q:"A string fixed at both ends vibrates in its 3rd harmonic at frequency f. Its fundamental frequency is:",
   options:["f/3","f/2","3f","f/9"], answer:0,
   steps:["Fixed-fixed string: harmonics are f, 2f, 3f, … (nth harmonic = n × fundamental).",
    "3rd harmonic = 3f₀ → f₀ = f/3.",
    "Standing wave condition: L = nλ/2 for fixed-fixed; L = (2n−1)λ/4 for fixed-free."],
   ans:"f/3 (option A)", tip:"Harmonic number × fundamental. Fixed-free strings only have odd harmonics — a favourite trick question."}
  ]
},
{
  name: "11. Electrostatics",
  qs: [
  {type:"pyq", year:"JEE Main 2019", q:"Two point charges exert force F on each other. If the distance between them is doubled, the new force is:",
   options:["F/4","F/2","2F","F/8"], answer:0,
   steps:["Coulomb's law: F = kq₁q₂/r².",
    "F ∝ 1/r² → doubling r divides F by 4.",
    "New force = F/4.",
    "If one charge is also halved: F/8."],
   ans:"F/4 (option A)", tip:"Inverse-square law: distance ×2 → force ÷4; distance ×3 → force ÷9. Instant answers."},
  {type:"imp", q:"Capacitors 2 µF and 3 µF are connected in SERIES across a battery. The equivalent capacitance is:",
   options:["1.2 µF","5 µF","2.5 µF","6 µF"], answer:0,
   steps:["Series: 1/C = 1/2 + 1/3 = 5/6.",
    "C = 6/5 = 1.2 µF.",
    "Series C is smaller than the smallest (2 µF) ✓; parallel would be 5 µF."],
   ans:"1.2 µF (option A)", tip:"Quick checks: series < smallest, parallel > largest. For two capacitors, series = product/sum = 6/5."},
  {type:"imp", q:"A dipole of moment p is placed in a uniform field E, at angle θ to the field. The torque on it is:",
   options:["pE sinθ","pE cosθ","pE tanθ","pE"], answer:0,
   steps:["τ = pE sinθ (tends to align the dipole with the field).",
    "Maximum at θ = 90° → τ_max = pE; zero when aligned (θ = 0).",
    "Potential energy U = −pE cosθ — minimum (stable) when aligned."],
   ans:"pE sinθ (option A)", tip:"Dipole trio: τ = pE sinθ, U = −pE cosθ; field on axis = 2kp/r³, equatorial = kp/r³."}
  ]
}
,
{
  name: "12. Current Electricity",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"A cell of emf 12 V and internal resistance 2 Ω is connected to an external resistance 4 Ω. The current in the circuit is:",
   options:["2 A","3 A","6 A","1.5 A"], answer:0,
   steps:["I = emf/(R + r).",
    "I = 12/(4 + 2) = 2 A.",
    "Terminal voltage V = emf − Ir = 12 − 2×2 = 8 V.",
    "Check: V = IR = 2×4 = 8 V ✓"],
   ans:"2 A (option A)", tip:"Treat internal resistance as just another series resistor. Terminal voltage = emf − Ir while discharging."},
  {type:"imp", q:"Two resistors 3 Ω and 6 Ω are in parallel across a 12 V battery. Total power dissipated is:",
   options:["72 W","24 W","36 W","108 W"], answer:0,
   steps:["Parallel R = (3×6)/(3+6) = 2 Ω.",
    "P = V²/R = 144/2 = 72 W.",
    "Check individually: P₃ = 144/3 = 48 W, P₆ = 144/6 = 24 W; total 72 W ✓"],
   ans:"72 W (option A)", tip:"P = V²/R for parallel (same V), P = I²R for series (same I). Choosing the right form halves the work."},
  {type:"imp", q:"In a balanced Wheatstone bridge (P/Q = R/S), if all four resistances are doubled, the balance condition:",
   options:["still holds","fails","holds only if P=R","cannot say"], answer:0,
   steps:["Balance needs P/Q = R/S.",
    "Doubling all: (2P)/(2Q) = P/Q and (2R)/(2S) = R/S → ratios unchanged.",
    "Bridge stays balanced; galvanometer current remains zero."],
   ans:"Still holds (option A)", tip:"Balanced bridge → no current through the galvanometer → you can DELETE that branch and redraw. Powerful simplification."}
  ]
},
{
  name: "13. Magnetic Effects of Current & Magnetism",
  qs: [
  {type:"pyq", year:"JEE Main 2019", q:"A charged particle moves parallel to a uniform magnetic field B. The force on it is:",
   options:["zero","qvB","maximum","qvB/2"], answer:0,
   steps:["Magnetic force: F = qvB sinθ.",
    "Parallel motion → θ = 0 → sinθ = 0 → F = 0.",
    "Force is maximum (qvB) when velocity is ⊥ to B.",
    "Magnetic force never does work — it only changes direction."],
   ans:"Zero (option A)", tip:"F = qvB sinθ. Parallel → 0, perpendicular → max. Magnetic force can bend a path but never speed it up."},
  {type:"imp", q:"A circular coil of radius R carries current i. The magnetic field at its centre is:",
   options:["μ₀i/2R","μ₀i/4πR","μ₀i/2πR","μ₀iR/2"], answer:0,
   steps:["Biot–Savart for a full loop: B = μ₀i/2R (centre).",
    "For an arc of angle θ (in radians): B = μ₀iθ/4πR.",
    "On the axis at distance x: B = μ₀iR²/2(R²+x²)^(3/2).",
    "Long straight wire at distance d: B = μ₀i/2πd."],
   ans:"μ₀i/2R (option A)", tip:"Learn three formulas only: straight wire μ₀i/2πd, full loop μ₀i/2R, solenoid μ₀ni. Arcs come from the loop by fraction θ/2π."},
  {type:"imp", q:"A galvanometer of resistance G, full-scale current i_g is converted to an ammeter (range I) by connecting a shunt S. S equals:",
   options:["i_g G/(I − i_g)","(I − i_g)G/i_g","I G/i_g","i_g I/G"], answer:0,
   steps:["Shunt carries I − i_g; galvanometer carries i_g; same potential difference.",
    "i_g·G = (I − i_g)·S.",
    "S = i_g G/(I − i_g).",
    "For a voltmeter, instead connect a HIGH resistance R = V/i_g − G in series."],
   ans:"i_g G/(I − i_g) (option A)", tip:"Ammeter → tiny shunt in PARALLEL. Voltmeter → big resistor in SERIES. Same 'equal voltage' idea both times."}
  ]
},
{
  name: "14. EMI & Alternating Currents",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"A rod of length 1 m moves with velocity 5 m/s perpendicular to a magnetic field of 0.4 T. The motional emf developed is:",
   options:["2 V","0.5 V","20 V","0.2 V"], answer:0,
   steps:["Motional emf: ε = B·l·v.",
    "ε = 0.4 × 1 × 5 = 2 V.",
    "Direction from F = qvB on positive charges (one end becomes +).",
    "If the rod were parallel to B, ε = 0."],
   ans:"2 V (option A)", tip:"ε = Blv with B, l, v mutually ⊥. If angle θ: ε = Blv sinθ."},
  {type:"imp", q:"A series LCR circuit has L = 1 H, C = 1 µF. The resonance angular frequency ω₀ is:",
   options:["1000 rad/s","√2 × 1000 rad/s","100 rad/s","500 rad/s"], answer:0,
   steps:["Resonance: ω₀ = 1/√(LC).",
    "LC = 1 × 10⁻⁶ → √(LC) = 10⁻³.",
    "ω₀ = 1/10⁻³ = 1000 rad/s.",
    "At resonance X_L = X_C, impedance = R (minimum), current maximum, power factor = 1."],
   ans:"1000 rad/s (option A)", tip:"ω₀ = 1/√(LC). At resonance: Z = R, cosφ = 1, V_L = V_C (they cancel)."},
  {type:"imp", q:"An ideal transformer steps 220 V down to 22 V. If the primary has 1000 turns, the secondary has:",
   options:["100 turns","10000 turns","50 turns","500 turns"], answer:0,
   steps:["Vₛ/Vₚ = Nₛ/Nₚ.",
    "22/220 = Nₛ/1000 → Nₛ = 100 turns.",
    "Current ratio is inverse: Iₛ/Iₚ = Vₚ/Vₛ (power conserved in ideal transformer)."],
   ans:"100 turns (option A)", tip:"Voltage ∝ turns. Step-down → fewer secondary turns AND more secondary current. Faraday + Lenz explain the whole device."}
  ]
}
,
{
  name: "15. Electromagnetic Waves",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"In an EM wave, E₀ = 60 V/m. The amplitude of the magnetic field (c = 3 × 10⁸ m/s) is:",
   options:["2 × 10⁻⁷ T","1.8 × 10⁻⁷ T","5 × 10⁻⁷ T","2 × 10⁻⁶ T"], answer:0,
   steps:["B₀ = E₀/c.",
    "B₀ = 60/(3 × 10⁸) = 2 × 10⁻⁷ T.",
    "E and B oscillate in phase, mutually ⊥, and ⊥ to propagation (transverse).",
    "Energy splits equally: u_E = u_B."],
   ans:"2 × 10⁻⁷ T (option A)", tip:"B₀ = E₀/c — magnetic fields of light are TINY because c is huge. Direction: E × B points along propagation."},
  {type:"imp", q:"Which of the following EM radiations is arranged in CORRECT order of increasing frequency?",
   options:["Radio < Microwave < IR < Visible < UV","UV < Visible < IR < Microwave","Visible < Radio < UV < Microwave","IR < Radio < Visible < UV"], answer:0,
   steps:["Frequency order: Radio < Microwave < IR < Visible < UV < X-rays < γ-rays.",
    "Wavelength order is exactly the reverse.",
    "Visible: red (low f) → violet (high f)."],
   ans:"Radio < Microwave < IR < Visible < UV (option A)", tip:"Memory line: 'Rabbits Mating In Very Unusual eXpensive Gardens' (Radio→γ). Frequency rises left to right."},
  {type:"imp", q:"Displacement current in a capacitor circuit exists because of the changing:",
   options:["electric flux between the plates","magnetic field in the wire","resistance of the wire","charge on the wire"], answer:0,
   steps:["Maxwell: i_d = ε₀ dΦ_E/dt.",
    "Between capacitor plates no conduction current flows, but the electric field (flux) changes as charge builds up.",
    "Displacement current keeps Ampere's law consistent there.",
    "It produces a magnetic field exactly like a real current."],
   ans:"Changing electric flux between the plates (option A)", tip:"No charge crosses the gap — only the E-field changes. That 'virtual current' completes the circuit in Ampere–Maxwell law."}
  ]
},
{
  name: "16. Optics",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"In Young's double-slit experiment, λ = 600 nm, d = 0.3 mm, D = 1.5 m. The fringe width is:",
   options:["3 mm","0.3 mm","1.5 mm","6 mm"], answer:0,
   steps:["β = λD/d.",
    "= (600 × 10⁻⁹ × 1.5)/(0.3 × 10⁻³).",
    "= 9 × 10⁻⁷ / 3 × 10⁻⁴ = 3 × 10⁻³ m = 3 mm.",
    "Fringe width is independent of order n — all bright fringes are equally spaced."],
   ans:"3 mm (option A)", tip:"β = λD/d. Immersing in water → β shrinks by n; covering one slit → pattern vanishes (uniform light)."},
  {type:"imp", q:"An object is placed 20 cm from a convex lens of focal length 15 cm. The image distance and nature are:",
   options:["60 cm, real & inverted","12 cm, virtual & erect","60 cm, virtual & erect","7.5 cm, real & inverted"], answer:0,
   steps:["Lens formula: 1/v − 1/u = 1/f with u = −20, f = +15.",
    "1/v = 1/15 + (−1/20)·(−1)… carefully: 1/v = 1/f + 1/u = 1/15 − 1/20 = 1/60.",
    "v = +60 cm → real image, on the opposite side.",
    "m = v/|u| = 60/20 = 3 → magnified, inverted."],
   ans:"60 cm, real, inverted, magnified 3× (option A)", tip:"1/v = 1/f + 1/u (new-cartesian). f>0 convex. Real image ↔ v positive ↔ inverted."},
  {type:"imp", q:"Critical angle for a medium w.r.t. air is 45°. The refractive index of the medium is:",
   options:["√2","1/√2","2","1.5"], answer:0,
   steps:["sin C = 1/n (denser to air).",
    "n = 1/sin45° = 1/(1/√2) = √2 ≈ 1.41.",
    "TIR happens only going denser → rarer, beyond the critical angle."],
   ans:"√2 (option A)", tip:"n = 1/sinC. For water C ≈ 49°, glass ≈ 42°, diamond ≈ 24° — diamond's tiny C is why it sparkles."}
  ]
},
{
  name: "17. Dual Nature of Matter & Radiation",
  qs: [
  {type:"pyq", year:"JEE Main 2022", q:"Light of energy 5 eV falls on a metal of work function 2 eV. The maximum kinetic energy of photoelectrons is:",
   options:["3 eV","7 eV","2 eV","5 eV"], answer:0,
   steps:["Einstein's photoelectric equation: KE_max = hν − φ.",
    "KE_max = 5 − 2 = 3 eV.",
    "Stopping potential V₀ = KE_max/e = 3 V.",
    "Below threshold (hν < φ), NO emission however intense the light."],
   ans:"3 eV (option A)", tip:"One law runs everything: KE_max = hν − φ. Intensity changes the NUMBER of electrons, frequency changes their ENERGY."},
  {type:"imp", q:"An electron is accelerated through a potential difference of 100 V. Its de Broglie wavelength is approximately:",
   options:["1.227 Å","0.1227 Å","12.27 Å","3.14 Å"], answer:0,
   steps:["λ = 12.27/√V Å for electrons (h²/2meV form).",
    "λ = 12.27/√100 = 12.27/10 = 1.227 Å.",
    "This matches atomic spacings → why electrons diffract in crystals (Davisson–Germer, 1927).",
    "Heavier particles at the same V → much smaller λ."],
   ans:"≈ 1.227 Å (option A)", tip:"λ = 12.27/√V Å. At 50 V → 1.736 Å; quadruple the V → halve the λ (√ relation)."}
  ]
}
,
{
  name: "18. Atoms & Nuclei",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"In Bohr's model, the energy of an electron in the nth orbit of hydrogen is E_n = −13.6/n² eV. The energy required to ionise hydrogen from the ground state is:",
   options:["13.6 eV","3.4 eV","10.2 eV","27.2 eV"], answer:0,
   steps:["Ground state energy E₁ = −13.6 eV.",
    "Ionisation → take electron to E = 0 (n = ∞).",
    "Energy needed = 0 − (−13.6) = 13.6 eV.",
    "For n = 2 (first excited), ionisation needs only 13.6/4 = 3.4 eV."],
   ans:"13.6 eV (option A)", tip:"E ∝ −1/n². Energy to jump 1→2 is 10.2 eV (Lyman-α); to jump 2→∞ just 3.4 eV. Fractions of 13.6 cover most questions."},
  {type:"imp", q:"The half-life of a radioactive sample is 10 days. The fraction remaining after 30 days is:",
   options:["1/8","1/3","1/9","1/16"], answer:0,
   steps:["30 days = 3 half-lives.",
    "Fraction left = (1/2)³ = 1/8.",
    "General: N = N₀(1/2)^(t/T).",
    "Activity decays the same way — it's proportional to the number of nuclei."],
   ans:"1/8 (option A)", tip:"Count half-lives, halve that many times. 2 → ¼, 3 → ⅛, 4 → 1/16. 20-second answer."},
  {type:"imp", q:"In the reaction ¹H + ¹H → ²He + energy, the mass of products is LESS than the mass of reactants. The missing mass appears as:",
   options:["energy (binding energy released)","momentum only","charge","nothing"], answer:0,
   steps:["Mass defect Δm = (mass of reactants) − (mass of products).",
    "E = Δm·c² — released as energy (that's fusion's power).",
    "Binding energy per nucleon peaks near Fe-56 → fusion before Fe, fission after.",
    "Charge and nucleon number are conserved separately."],
   ans:"Energy, via E = Δmc² (option A)", tip:"Mass defect ↔ binding energy: BE = Δm × 931.5 MeV per u. Sun runs on this; reactors on fission."}
  ]
},
{
  name: "19. Electronic Devices",
  qs: [
  {type:"pyq", year:"JEE Main 2020", q:"A full-wave rectifier is fed with 50 Hz AC. The fundamental frequency of the output ripple is:",
   options:["100 Hz","50 Hz","25 Hz","zero"], answer:0,
   steps:["Half-wave rectifier → output frequency = input f = 50 Hz.",
    "Full-wave → both halves used → ripple frequency = 2f = 100 Hz.",
    "Zener diode instead works in REVERSE breakdown as a voltage regulator.",
    "LED & photodiode are forward/reverse biased respectively."],
   ans:"100 Hz (option A)", tip:"Ripple frequency = 2×input for full-wave, = input for half-wave. One-line answer, appears repeatedly."},
  {type:"imp", q:"A p-n junction diode is forward biased when:",
   options:["p-side to +ve terminal (barrier height reduces)","p-side to −ve terminal","either way","never"], answer:0,
   steps:["Forward bias: p → positive, n → negative of battery.",
    "Depletion layer narrows, barrier lowers, current flows easily.",
    "Reverse bias widens depletion layer — only tiny leakage (minority carriers) flows."],
   ans:"p-side to the positive terminal (option A)", tip:"'p plus' = forward. Doping: n-type has electrons (pentavalent P, As), p-type has holes (trivalent B, Al)."},
  {type:"imp", q:"A Zener diode used as a voltage regulator operates in:",
   options:["reverse breakdown region","forward bias","cut-off","saturation"], answer:0,
   steps:["In reverse breakdown, voltage across the Zener stays nearly constant (= V_Z) for a wide current range.",
    "Series resistor R absorbs the excess voltage; load sees constant V_Z.",
    "That's why it's the standard shunt regulator."],
   ans:"Reverse breakdown (option A)", tip:"Breakdown is not damage — Zener is DESIGNED for it. Compare: LED forward, solar cell & photodiode reverse-biased."}
  ]
},
{
  name: "20. Experimental Skills",
  qs: [
  {type:"pyq", year:"JEE Main 2021", q:"A screw gauge has pitch 0.5 mm and 50 divisions on the circular scale. Its least count is:",
   options:["0.01 mm","0.5 mm","0.001 mm","0.05 mm"], answer:0,
   steps:["Least count = pitch / number of circular-scale divisions.",
    "= 0.5/50 = 0.01 mm = 10 µm.",
    "Vernier callipers LC = (smallest main-scale division)/(number of vernier divisions), typically 0.1 mm.",
    "Zero error must be corrected with sign (+ if scales overlap at closed jaws)."],
   ans:"0.01 mm (option A)", tip:"LC(screw gauge) = pitch/N. Typical reading = main + (circular × LC) − zero error. Memorise 0.01 mm & 0.1 mm."},
  {type:"imp", q:"While finding focal length of a convex lens by u-v method, the experiment uses the relation:",
   options:["1/f = 1/v − 1/u","f = uv","f = (u+v)/2","f = v/u"], answer:0,
   steps:["Lens formula with sign convention: 1/f = 1/v − 1/u.",
    "Practical shortcut (when |u| = |v|, image same size): f = |u|/2 = distance/2.",
    "Graph of 1/v vs 1/u is a straight line with intercepts 1/f on both axes.",
    "For a concave mirror (focal length by u-v): same lens formula but mirror form 1/f = 1/v + 1/u."],
   ans:"1/f = 1/v − 1/u (option A)", tip:"Symmetry trick: when the object-image distance is minimum (4f), u = v = 2f. Great for checking experimental values."},
  {type:"imp", q:"In a meter bridge experiment, the balance point is at 40 cm from the left end. If the left gap resistance is 4 Ω, the right gap resistance is:",
   options:["6 Ω","4 Ω","2.67 Ω","10 Ω"], answer:0,
   steps:["Meter bridge (Wheatstone): R/S = l/(100 − l).",
    "R/S = 40/60 = 2/3.",
    "S = R × 3/2 = 4 × 1.5 = 6 Ω.",
    "Best accuracy is near l = 50 cm — shift the range using known resistances."],
   ans:"6 Ω (option A)", tip:"Meter bridge is just a Wheatstone bridge drawn on a wire: R/S = l/(100−l). 40/60 splits are extremely common."}
  ]
}
];






